// 1999_SOFT_LOAN__3CB4.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 3CB4:0008: define fn3CB4_0008
// Called from:
//      main
//      fn2BC7_0236
define fn3CB4_0008
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	D = false;
	es_di = ss->*((word16) bp + 0x0A);
	ax = ax ^ ax;
	es->*di = ax;
	di = &di.u7->u1.t0002.u0;
	ax.u0 = 19094;
	es->*di = ax;
	bx = ax;
	ax.u0 = 0x4D8E;
	ax -= bx;
	SCZO = cond(ax);
	di = ss->*sp;
	sp = &sp.u7->u1.t0002.u0;
	si = ss->*sp;
	sp = &sp.u7->u1.t0002.u0;
	bp = ss->*sp;
	sp = &sp.u7->u1.t0002.u0;
}

