// 1999_SOFT_LOAN__207F.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 207F:0006: define fn207F_0006
// Called from:
//      fn2644_45CA
//      fn2EB3_0B54
define fn207F_0006
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	while (true)
	{
		ds->w10CC = 0x00;
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		ax.u0 = 0x01;
		dx_ax = (int32) ax;
		sp -= 2;
		ss->*sp = dx;
		sp -= 2;
		ss->*sp = ax;
		ax.u0 = 0xCA00;
		dx.u0 = 15258;
		sp -= 2;
		ss->*sp = dx;
		sp -= 2;
		ss->*sp = ax;
		v11 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v11;
		fn208F_0147();
		sp = (word16) sp + 0x0C;
		ax |= ax;
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(NE,Z))
			break;
		SCZO = cond(ds->w10CC - 0x00);
		if (Test(NE,Z))
		{
			ax -= ax;
			SCZO = cond(ax);
			bp = ss->*sp;
			sp = (word16) sp + 2;
			return;
		}
		fn21DC_0D60();
	}
	ax.u0 = 0x01;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 207F:0048: define fn207F_0048
// Called from:
//      fn2644_1F12
//      fn2644_45CA
//      fn2EB3_0BB4
define fn207F_0048
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	ax.u0 = 0x01;
	sp -= 2;
	ss->*sp = ax;
	dx_ax = (int32) ax;
	sp -= 2;
	ss->*sp = dx;
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0xCA00;
	dx.u0 = 15258;
	sp -= 2;
	ss->*sp = dx;
	sp -= 2;
	ss->*sp = ax;
	v9 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v9;
	fn208F_0147();
	sp = (word16) sp + 0x0C;
	SCZO = cond(sp);
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 207F:0088: define fn207F_0088
// Called from:
//      fn2644_44C4
define fn207F_0088
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_49864 Eq_49871::*) bp;
	bp = sp;
	ax = &Eq_49871::t0001;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_49864 Eq_49871::*) ax;
	ax = &Eq_49871::tCA00;
	dx = &Eq_49871::t3B9A;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_49864 Eq_49871::*) dx;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_49864 Eq_49871::*) ax;
	ax = &Eq_49871::tCA01;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_49864 Eq_49871::*) dx;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_49864 Eq_49871::*) ax;
	v8 = (struct Eq_49864 Eq_49871::*) (ss->*bp).ptr0006;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_49864 Eq_49871::*) v8;
	fn208F_0147();
	sp = (struct Eq_49864 Eq_49871::*) &sp->ptr0006;
	SCZO = cond(sp);
	bp = (struct Eq_49864 Eq_49871::*) (ss->*sp).ptr0000;
	sp = (struct Eq_49864 Eq_49871::*) &sp->ptr0000;
}

// 207F:00D2: define fn207F_00D2
// Called from:
//      fn2644_44C4
define fn207F_00D2
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	ax.u0 = 0x01;
	sp -= 2;
	ss->*sp = ax;
	dx_ax = (int32) ax;
	sp -= 2;
	ss->*sp = dx;
	sp -= 2;
	ss->*sp = ax;
	ax = ss->*((word16) bp + 8);
	dx = ss->*((word16) bp + 0x0A);
	ax = (word16) ax.u0 + 0x0000CA00;
	SCZO = cond(ax);
	dx = (bool) C + ((word16) dx + 15258);
	SCZO = cond(dx);
	sp -= 2;
	ss->*sp = dx;
	sp -= 2;
	ss->*sp = ax;
	v11 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v11;
	fn208F_0147();
	sp = (word16) sp + 0x0C;
	SCZO = cond(sp);
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

