// 1999_SOFT_LOAN__4827.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 3CEE:B417: define fn3CEE_B417
// Called from:
//      fn3CEE_1472
define fn3CEE_B417
{
	sp = fp;
	Top = 0;
	v7 = (byte) ((word16) (ds->*((word16) si - 113)) + ah);
	ds->*((word16) si - 113) = v7;
	v12 = Mem0[ss:bp + 0x1E + si:word16] + bx;
	ss->*((word16) si + ((word16) bp + 30)) = v12;
	v13 = sp;
	sp -= 2;
	ss->*sp = v13;
	ax = ss->*sp;
	sp = &sp.u7->u1.t0002.u0;
	SCZO = cond(al - Mem0[ds:bx + si:byte]);
	v16 = cx;
	cx = ax;
	ax = v16;
	v19 = (word16) ((word80) (ds->*((word16) bx + 0x00003901)) + dx);
	ds->*((word16) bx + 0x00003901) = v19;
	v21 = (byte) ((word80) (ds->*((word16) bx + 11777)) + dl);
	ds->*((word16) bx + 11777) = v21;
	v23 = (byte) ((word16) (ss->*((word16) si + ((word16) bp + 30))) + bl);
	ss->*((word16) si + ((word16) bp + 30)) = v23;
	al |= ds->*((word16) si + ((word16) bx + 0x0000AA6F));
	v27 = di;
	di = ax;
	ax = v27;
	v29 = (word16) bp + ds->w8600;
	ds->w8600 = v29;
	FPUF.u0 = cond(*Top - ds->*di);
	Top = (real64 *) ((char *) Top + 1);
	v33 = (word80) (ds->*((word16) di + ((word16) bx + 37476))) + cl;
	ds->*((word16) di + ((word16) bx + 37476)) = v33;
	v34 = Mem0[ss:bp + 0x1D:word16] + bx;
	ss->*((word16) bp + 29) = v34;
	v35 = di;
	di = ax;
	ax = v35;
	v36 = Mem0[ds:bx + di:word16] + di;
	Mem0[ds:bx + di:word16] = v36;
	v37 = (byte) ((word16) (ss->*((word16) si + ((word16) bp + 30))) + bl);
	ss->*((word16) si + ((word16) bp + 30)) = v37;
	SCZO = cond(v37);
	Z = __arpl(ss->*((word16) si + ((word16) bp + 29)), bx, &(ss->*((word16) si + ((word16) bp + 29))));
	Z = __arpl(ds->*((word16) bx - 86), bx, &(ds->*((word16) bx - 86)));
	v39 = al;
	al = bl;
	bl = v39;
	ax = ax - 0x8900 - C;
	v40 = sp;
	sp = ax;
	ax = v40;
	v41 = Mem0[ds:bx + 19 + di:word16] + bx;
	ds->*((word16) di + ((word16) bx + 19)) = v41;
	v42 = (byte) ((word16) (ds->*((word16) si - 0x006A)) + ah);
	ds->*((word16) si - 0x006A) = v42;
	v43 = (word16) ((word80) (ds->*((word16) bx + 0x00003901)) + dx);
	ds->*((word16) bx + 0x00003901) = v43;
	v44 = (byte) ((word16) (ss->*((word16) si + ((word16) bp + 30))) + bl);
	ss->*((word16) si + ((word16) bp + 30)) = v44;
	Z = __arpl(ss->*((word16) si + ((word16) bp + 0x00001DD8)), bx, &(ss->*((word16) si + ((word16) bp + 0x00001DD8))));
	v45 = (word80) (ds->*((word16) di + ((word16) bx + 0x00009864))) + cl;
	ds->*((word16) di + ((word16) bx + 0x00009864)) = v45;
	v46 = Mem0[ds:si + -0x0066:word16] + sp;
	ds->*((word16) si - 0x0066) = v46;
	v47 = Mem0[ds:bx + 0x0D + di:word16] + bx;
	ds->*((word16) di + ((word16) bx + 0x0D)) = v47;
	v48 = (byte) ((word16) (ds->*((word16) si - 100)) + ah);
	ds->*((word16) si - 100) = v48;
	v49 = (word80) (ds->*bx) + dx;
	ds->*bx = v49;
	FPUF.u0 = cond(*Top - ds->*di);
	Top = (real64 *) ((char *) Top + 1);
	v50 = (word80) (ds->*((word16) di + ((word16) bx + 40548))) + cl;
	ds->*((word16) di + ((word16) bx + 40548)) = v50;
	v51 = Mem0[ds:si + -96:word16] + sp;
	ds->*((word16) si - 96) = v51;
	v52 = Mem0[ss:bp + 0x1D:word16] + bx;
	ss->*((word16) bp + 29) = v52;
	al = 0x59;
	ax += Mem0[ds:bx + si:word16];
	SZP = cond(al & 0x01);
	al = al ^ 0x55;
	bp = sp;
	bx = bx ^ bx;
	SZ = cond(bx);
	O = false;
	C.u0 = false;
	ax.u0 = 0x00;
	sp -= 2;
	ss->*sp = ax;
	sp -= 2;
	ss->*sp = bx;
	ax.u0 = 0x4CB2;
	sp -= 2;
	ss->*sp = ax;
	sp -= 2;
	ss->*sp = bx;
	ax.u0 = 0x1D;
	sp -= 2;
	ss->*sp = cs;
	sp -= 2;
	ss->*sp = ax;
	fn3BC2_0000();
	sp = bp;
	bp = ss->*sp;
	sp = &sp.u7->u1.t0002.u0;
}

