// 1999_SOFT_LOAN__3BC2.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 3BC2:0000: define fn3BC2_0000
// Called from:
//      fn3CB7_0000
//      fn3CEE_B417
//      fn3CEE_C213
//      fn3CEE_C583
//      fn3CEE_CE21
//      fn3CEE_D021
define fn3BC2_0000
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	sp -= 0x02;
	SCZO = cond(sp);
	di = ss->*((word16) bp + 0x0A);
	while (true)
	{
l3BC2_000B:
		do
		{
			dx -= dx;
			es = (struct Eq_119870 *) (ss->*((word16) bp + 0x0C));
			cx = dx;
			cl = (bu8) (es->*di);
			cx <<= 0x01;
			si = cx;
			cx <<= 0x01;
			si += cx;
			si <<= 0x01;
			SCZO = cond(si);
			bx = dx;
			bl = (byte) (ds->*((word16) si + 9531));
			ax = ds->*((word16) bx + 9382);
			bx = dx;
			bl = (byte) (ds->*((word16) si + 9530));
			bx = ds->*((word16) bx + 9432);
			(seg3BC2->*ax)();
		} while (Test(UGE,C));
		do
		{
			SCZO = cond(ds->w10D2 - 101);
			if (Test(EQ,Z))
			{
				sp -= 2;
				ss->*sp = bp;
				fn20B2_1192();
				sp = (word16) sp + 2;
				ax |= ax;
				SZ = cond(ax);
				O = false;
				C = false;
				if (Test(EQ,Z))
				{
					sp = (word16) sp + 2;
					SCZO = cond(sp);
					di = ss->*sp;
					sp = (word16) sp + 2;
					si = ss->*sp;
					sp = (word16) sp + 2;
					bp = ss->*sp;
					sp = (word16) sp + 2;
					return;
				}
				else
				{
					di = ax;
					ds->w10D2 = 0x00;
					goto l3BC2_000B;
				}
			}
			es = (struct Eq_119870 *) (ss->*((word16) bp + 0x0C));
			ax -= ax;
			al = (bu8) (es->*di);
			cx.u0 = 0x0C;
			ax = cl *16 al;
			si = ax;
			SZP = cond(ds->*((word16) si + 9531) & ~0x00);
			O = false;
			C = false;
			if (Test(NE,Z))
				fn3BC2_0ED9();
			ax -= ax;
			SCZO = cond(ax);
			al = (bu8) (es->*di);
			sp -= 2;
			ss->*sp = ax;
			fn20B2_0BDC();
			sp = (word16) sp + 2;
			SZP = cond(ds->w10D2 & ~0x00);
			O = false;
			C = false;
		} while (Test(NE,Z));
		ax |= ax;
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
			di = (word16) di + 1;
			SZP = cond(ds->*((word16) si + 9530) & ~0x00);
			O = false;
			C = false;
			if (Test(NE,Z))
			{
				di = (word16) di + 2;
				SCZO = cond(di);
			}
		}
	}
}

// 3BC2:009D: define fn3BC2_009D
// Called from:
//      fn31FF_1B66
define fn3BC2_009D
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	di = ss->*((word16) bp + 0x0A);
	while (true)
	{
l3BC2_00A5:
		do
		{
			dx -= dx;
			es = (struct Eq_120064 *) (ss->*((word16) bp + 0x0C));
			cx = dx;
			cl = (bu8) (es->*di);
			cx <<= 0x01;
			si = cx;
			cx <<= 0x01;
			si += cx;
			si <<= 0x01;
			SCZO = cond(si);
			bx = dx;
			bl = (byte) (ds->*((word16) si + 9531));
			ax = ds->*((word16) bx + 9382);
			bx = dx;
			bl = (byte) (ds->*((word16) si + 9530));
			bx = ds->*((word16) bx + 9450);
			(seg3BC2->*ax)();
		} while (Test(UGE,C));
		do
		{
			SCZO = cond(ds->w10D2 - 101);
			if (Test(EQ,Z))
			{
				sp -= 2;
				ss->*sp = bp;
				fn20B2_1192();
				sp = (word16) sp + 2;
				ax |= ax;
				SZ = cond(ax);
				O = false;
				C = false;
				if (Test(EQ,Z))
				{
					di = ss->*sp;
					sp = (word16) sp + 2;
					si = ss->*sp;
					sp = (word16) sp + 2;
					bp = ss->*sp;
					sp = (word16) sp + 2;
					return;
				}
				else
				{
					di = ax;
					ds->w10D2 = 0x00;
					goto l3BC2_00A5;
				}
			}
			es = (struct Eq_120064 *) (ss->*((word16) bp + 0x0C));
			ax -= ax;
			al = (bu8) (es->*di);
			cx.u0 = 0x0C;
			ax = cl *16 al;
			si = ax;
			SZP = cond(ds->*((word16) si + 9531) & ~0x00);
			O = false;
			C = false;
			if (Test(NE,Z))
				fn3BC2_0ED9();
			ax -= ax;
			SCZO = cond(ax);
			al = (bu8) (es->*di);
			sp -= 2;
			ss->*sp = ax;
			fn20B2_0BDC();
			sp = (word16) sp + 2;
			SZP = cond(ds->w10D2 & ~0x00);
			O = false;
			C = false;
		} while (Test(NE,Z));
		ax |= ax;
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
			di = (word16) di + 1;
			SZP = cond(ds->*((word16) si + 9530) & ~0x00);
			O = false;
			C = false;
			if (Test(NE,Z))
			{
				di = (word16) di + 2;
				SZP = cond(ds->*((word16) si + 9530) & 0x0E);
				O = false;
				C = false;
				if (Test(NE,Z))
				{
					di = (word16) di + 2;
					SCZO = cond(di);
				}
			}
		}
	}
}

// 3BC2:013E: define fn3BC2_013E
// Called from:
//      fn31FF_207C
define fn3BC2_013E
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	di = ss->*((word16) bp + 0x0A);
	dx -= dx;
	es = (struct Eq_120265 *) (ss->*((word16) bp + 0x0C));
	cx = dx;
	cl = (bu8) (es->*di);
	cx <<= 0x01;
	si = cx;
	cx <<= 0x01;
	si += cx;
	si <<= 0x01;
	SCZO = cond(si);
	bx = dx;
	bl = (byte) (ds->*((word16) si + 9531));
	ax = ds->*((word16) bx + 9382);
	bx = dx;
	bl = (byte) (ds->*((word16) si + 9530));
	bx = ds->*((word16) bx + 9450);
	(seg3BC2->*ax)();
	if (Test(UGE,C))
	{
		di -= ss->*((word16) bp + 0x0A);
		SCZO = cond(di);
		ax = di;
	}
	else
	{
		es = (struct Eq_120265 *) (ss->*((word16) bp + 0x0C));
		ax -= ax;
		al = (bu8) (es->*di);
		cx.u0 = 0x0C;
		ax = cl *16 al;
		si = ax;
		SZP = cond(ds->*((word16) si + 9531) & ~0x00);
		O = false;
		C = false;
		if (Test(NE,Z))
			fn3BC2_0ED9();
		ax -= ax;
		SCZO = cond(ax);
	}
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 3BC2:0ED9: define fn3BC2_0ED9
// Called from:
//      fn3BC2_0000
//      fn3BC2_009D
//      fn3BC2_013E
define fn3BC2_0ED9
{
	word16 si;
	selector ds;
	bool P;
	Top_3 = 0;
	cx_14 = 0x00;
	switch ((ds->*si).b253B)
	{
	case 0x22:
		cx_37 = 0x03;
		break;
	case 0x24:
		cx_36 = 0x03;
		break;
	default:
		if ((ds->*si).w253E != 0x00)
			cx_24 = 0x01;
		cx_33 = ϕ(cx_14, cx_24);
		SZP_29 = cond((ds->*si).w2540);
		P_78 = SLICE(SZP_29, bool, 5);
		if ((ds->*si).w2540 != 0x00)
			cx_34 = cx_33 + 0x01;
		break;
	}
	P_76 = ϕ(P, P, P_78, P_78);
	cx_38 = ϕ(cx_37, cx_36, cx_33, cx_34);
	cx_39 = cx_38 << 0x01;
	es_di_45 = ds->t1296;
	v13_48 = (word32) ds->t1296 + (cx_39 << 0x03);
	ds->t1296 = v13_48;
	SCZO_50 = cond(v13_48);
	C_74 = SLICE(SCZO_50, bool, 1);
	O_75 = SLICE(SCZO_50, bool, 4);
	S_79 = (bool) SCZO_50;
	Z_82 = SLICE(SCZO_50, bool, 2);
	size_52 = (uint32) (cx_39 << 0x03);
	memcpy((word32) es_di_45 + 16, *((char *) &ds->t1296 + 20), size_52);
	cx_54 = 0x00;
}

