// 1999_SOFT_LOAN__49C4.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 3CEE:CE21: define fn3CEE_CE21
// Called from:
//      fn3CEE_1472
define fn3CEE_CE21
{
	sp = fp;
	Top = 0;
	if (Test(EQ,Z))
	{
l3CEE_CE88:
		v47 = Mem0[ds:bx + si:byte] + al;
		Mem0[ds:bx + si:byte] = v47;
		v48 = Mem0[ds:bx + si:byte] + al;
		Mem0[ds:bx + si:byte] = v48;
		v49 = Mem0[ds:bx + si:byte] + al;
		Mem0[ds:bx + si:byte] = v49;
		v50 = Mem0[ds:bx + si:byte] + al;
		Mem0[ds:bx + si:byte] = v50;
		sp -= 2;
		ss->*sp = bp;
		bp = sp;
		bx = bx ^ bx;
		SZ = cond(bx);
		O = false;
		C.u0 = false;
		ax.u0 = 0x00;
		goto l3CEE_CE98;
	}
	else
	{
		if (Test(UGE,C))
		{
			v9 = ds->*((word16) bx + 0x0066) & ch;
			ds->*((word16) bx + 0x0066) = v9;
			SZ = cond(ds->*((word16) bx + 0x0066));
			v14 = ds->*((word16) si + 101) & ah;
			ds->*((word16) si + 101) = v14;
			SZ = cond(ds->*((word16) si + 101));
			O = false;
			C.u0 = false;
			if (Test(ULT,C))
			{
				if (Test(UGE,C))
				{
					v17 = fs->*((word16) bp + 97) & ch;
					fs->*((word16) bp + 97) = v17;
					SZ = cond(fs->*((word16) bp + 97));
					ax = __in<word16>(dx);
					di = &di.u7->u1.t0002.u0;
					SCZO = cond(ah - Mem0[gs:bx + si:byte]);
					v24 = (byte) ((word80) (ds->*((word16) bx - 79)) + bh);
					ds->*((word16) bx - 79) = v24;
					--dx;
					v26 = di;
					di = ax;
					ax = v26;
					al += 0x40;
					ax = ds->*((word16) si + ((word16) bx + 33)) *s 0x00;
					SCZO = cond(ax);
					FPUF.u0 = cond(*Top - ds->*di);
					Top = (real64 *) ((char *) Top + 1);
					--ax;
					Mem0[ds:50715:byte] = al;
					v30 = Mem0[ds:bx + si:byte] - al - C;
					Mem0[ds:bx + si:byte] = v30;
					bp = ss->*sp;
					sp = &sp.u7->u1.t0002.u0;
					cl += cl;
					v33 = Mem0[ds:bx + si:word16] + ax;
					Mem0[ds:bx + si:word16] = v33;
					FPUF.u0 = cond(*Top - ds->*si);
					Top = Top;
					v34 = (byte) ((word80) (ss->*((word16) bp - 40)) + al);
					ss->*((word16) bp - 40) = v34;
					bp = ss->*sp;
					v35 = (word80) (ds->*((word16) di + ((word16) bx + 0x0000D8DD))) + cl;
					ds->*((word16) di + ((word16) bx + 0x0000D8DD)) = v35;
					SCZO = cond(v35);
					Z = __arpl(Mem0[ds:bx + si:word16], bx, &Mem0[ds:bx + si:word16]);
					ds->*((word16) di + ((word16) bx + 23)) = bx;
					__out<word16>(dx, ax);
					dx_ax = (int32) ax;
					v37 = Mem0[ds:bx + si:byte] - al - C;
					Mem0[ds:bx + si:byte] = v37;
					dx_ax = (int32) ax;
					--di;
					v39 = (byte) ((word80) (ss->*((word16) bp + 0x0068)) + bl);
					ss->*((word16) bp + 0x0068) = v39;
					sp = bp;
					bp = ss->*sp;
					sp = &sp.u7->u1.t0002.u0;
					ax = (byte) ax.u0 + 0x0000D800;
					ds = ss->*sp;
					sp = &sp.u7->u1.t0002.u0;
					v40 = (byte) ((word80) (ss->*((word16) bp - 121)) + al);
					ss->*((word16) bp - 121) = v40;
					ax = Mem0[ds:bx + si:word16] *s ~0x6645;
					ax |= 0x1200;
					bx = ss->*sp;
					sp = &sp.u7->u1.t0002.u0;
					sp -= 2;
					ss->*sp = cs;
					cx = ss->*sp;
					sp = &sp.u7->u1.t0002.u0;
					v43 = Mem0[ds:bx + si:byte] + al;
					Mem0[ds:bx + si:byte] = v43;
					al = al ^ 0x00;
					v44 = Mem0[ds:bx + si:byte] + al;
					Mem0[ds:bx + si:byte] = v44;
					v45 = Mem0[ds:bx + si:byte] + al;
					Mem0[ds:bx + si:byte] = v45;
					v46 = Mem0[ds:bx + si:byte] + al;
					Mem0[ds:bx + si:byte] = v46;
					SCZO = cond(v46);
					goto l3CEE_CE88;
				}
				Mem0[ds:bx + 0x00 + si:real80] = CONVERT(ST[Top + 0x00:real64], real64, real80);
				Top = (real64 *) ((char *) Top + 1);
			}
			else
			{
				v51 = Mem0[ds:bx + si:byte] + al;
				Mem0[ds:bx + si:byte] = v51;
				SCZO = cond(v51);
			}
		}
l3CEE_CE98:
		sp -= 2;
		ss->*sp = ax;
		sp -= 2;
		ss->*sp = bx;
		ax.u0 = 19696;
		sp -= 2;
		ss->*sp = ax;
		sp -= 2;
		ss->*sp = bx;
		ax.u0 = 0x1D;
		sp -= 2;
		ss->*sp = cs;
		sp -= 2;
		ss->*sp = ax;
		fn3BC2_0000();
		sp = bp;
		bp = ss->*sp;
		sp = &sp.u7->u1.t0002.u0;
	}
}

