// 1999_SOFT_LOAN__2017.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

struct seg2017_t * g_ptr20170 = &g_t21CD; // 00020170
// 2017:000F: define fn2017_000F
// Called from:
//      fn2068_00A8
//      fn2C27_0002
define fn2017_000F
{
	byte al;
	word16 wArg04;
	Top_3 = 0;
	C_19 = msdos_allocate_memory_block(wArg04);
	ax_38 = SEQ(0x48, al);
	if (!C_19 && wArg04 == wArg04)
	{
		SZ_30 = cond(0x00);
		S_67 = (bool) SZ_30;
		Z_72 = SLICE(SZ_30, bool, 2);
	}
	else
	{
		ax_24 = 0x00;
		SZ_25 = cond(0x00);
		S_68 = (bool) SZ_25;
		Z_73 = SLICE(SZ_25, bool, 2);
	}
	Z_71 = ϕ(Z_72, Z_73);
	S_66 = ϕ(S_67, S_68);
	O_65 = false;
	C_64 = false;
	bx_42 = 0x00;
	ax_36 = ϕ(ax_38, ax_24);
	ax_43 = 0x00;
	dx_44 = ax_36;
}

// 2017:0033: define fn2017_0033
// Called from:
//      fn2068_00A8
//      fn2C27_0112
define fn2017_0033
{
	segptr32 ptrArg04;
	bool O;
	bool S;
	bool Z;
	Top_3 = 0;
	es_17 = SLICE(ptrArg04, selector, 16);
	C_18 = msdos_free_memory_block(es_17);
	if (!C_18)
		ax_23 = 0x01;
	else
	{
		ax_19 = 0x00;
		SZ_20 = cond(0x00);
		S_47 = (bool) SZ_20;
		Z_51 = SLICE(SZ_20, bool, 2);
		O_21 = false;
		C_22 = false;
	}
	Z_49 = ϕ(Z, Z_51);
	S_45 = ϕ(S, S_47);
	O_43 = ϕ(O, O_21);
	C_41 = ϕ(C_18, C_22);
	ax_40 = ϕ(ax_23, ax_19);
}

// 2017:004C: define fn2017_004C
// Called from:
//      fn21DC_0EC2
define fn2017_004C
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46901 Eq_46908::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46901 Eq_46908::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46901 Eq_46908::*) di;
	bp = sp;
	al = 0x67;
	ah = 0x35;
	es_bx = msdos_get_interrupt_vector(al);
	SCZO = cond(es->b000A - 0x45);
	if (Test(EQ,Z))
	{
		SCZO = cond(es->w000B - 0x4D4D);
		if (Test(EQ,Z))
		{
			ah = ems_get_number_of_pages(out bx, out dx);
			ah |= ah;
			SZ = cond(ah);
			O = false;
			C = false;
			if (Test(EQ,Z))
			{
l2017_0072:
				al = 0x10;
				ax = bl *16 al;
				SCZO = cond(ax);
				di = (struct Eq_46901 Eq_46908::*) (ss->*sp).ptr0000;
				sp = (struct Eq_46901 Eq_46908::*) &sp->ptr0000;
				si = (struct Eq_46901 Eq_46908::*) (ss->*sp).ptr0000;
				sp = (struct Eq_46901 Eq_46908::*) &sp->ptr0000;
				bp = (struct Eq_46901 Eq_46908::*) (ss->*sp).ptr0000;
				sp = (struct Eq_46901 Eq_46908::*) &sp->ptr0000;
				return;
			}
		}
	}
	bl = 0x00;
	goto l2017_0072;
}

// 2017:007A: define fn2017_007A
// Called from:
//      fn2C27_0032
define fn2017_007A
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46994 Eq_47001::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46994 Eq_47001::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46994 Eq_47001::*) di;
	bp = sp;
	ah = ems_get_page_frame_segment(out bx);
	es_di.u1 = (ss->*bp).t000A.u1;
	(es->*di).ptr0000 = (struct Eq_46994 Eq_47001::*) &Eq_47001::t0000;
	(es->*di).w0002 = bx;
	al = al ^ al;
	SZ = cond(al);
	O = false;
	C = false;
	v16 = ah;
	ah = al;
	al = v16;
	di = (struct Eq_46994 Eq_47001::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46994 Eq_47001::*) &sp->w0002;
	si = (struct Eq_46994 Eq_47001::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46994 Eq_47001::*) &sp->w0002;
	bp = (struct Eq_46994 Eq_47001::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46994 Eq_47001::*) &sp->w0002;
}

// 2017:0097: define fn2017_0097
// Called from:
//      fn2C27_0032
define fn2017_0097
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_47069 Eq_47076::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_47069 Eq_47076::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_47069 Eq_47076::*) di;
	bp = sp;
	bx = (ss->*bp).w000A;
	ah = ems_get_handle_and_allocate_memory(bx, out dx);
	es_di.u1 = (ss->*bp).t000C.u1;
	(es->*di).ptr0000 = (struct Eq_47069 Eq_47076::*) dx;
	al = al ^ al;
	SZ = cond(al);
	O = false;
	C = false;
	v17 = ah;
	ah = al;
	al = v17;
	di = (struct Eq_47069 Eq_47076::*) (ss->*sp).ptr0000;
	sp = (struct Eq_47069 Eq_47076::*) &sp->ptr0000;
	si = (struct Eq_47069 Eq_47076::*) (ss->*sp).ptr0000;
	sp = (struct Eq_47069 Eq_47076::*) &sp->ptr0000;
	bp = (struct Eq_47069 Eq_47076::*) (ss->*sp).ptr0000;
	sp = (struct Eq_47069 Eq_47076::*) &sp->ptr0000;
}

// 2017:00B1: define fn2017_00B1
// Called from:
//      fn2C27_0440
define fn2017_00B1
{
	word16 wArg04;
	word16 wArg06;
	word16 wArg08;
	Top_3 = 0;
	dx_15 = wArg04;
	bx_16 = wArg06;
	al_18 = (byte) wArg08;
	ah_19 = ems_map_memory(al_18, wArg06, wArg04);
	SZ_21 = cond(0x00);
	S_40 = (bool) SZ_21;
	Z_41 = SLICE(SZ_21, bool, 2);
	O_22 = false;
	C_23 = false;
	ax_39 = (uint16) ah_19;
}

// 2017:00CB: define fn2017_00CB
// Called from:
//      main
//      fn2C27_01AC
define fn2017_00CB
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_47174 Eq_47181::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_47174 Eq_47181::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_47174 Eq_47181::*) di;
	bp = sp;
	dx = (ss->*bp).w000A;
	ah = ems_release_memory(dx);
	al = al ^ al;
	SZ = cond(al);
	O = false;
	C = false;
	v14 = ah;
	ah = al;
	al = v14;
	di = (struct Eq_47174 Eq_47181::*) (ss->*sp).ptr0000;
	sp = (struct Eq_47174 Eq_47181::*) &sp->ptr0000;
	si = (struct Eq_47174 Eq_47181::*) (ss->*sp).ptr0000;
	sp = (struct Eq_47174 Eq_47181::*) &sp->ptr0000;
	bp = (struct Eq_47174 Eq_47181::*) (ss->*sp).ptr0000;
	sp = (struct Eq_47174 Eq_47181::*) &sp->ptr0000;
}

// 2017:00DF: define fn2017_00DF
// Called from:
//      fn2BC7_0236
//      fn2C27_0440
define fn2017_00DF
{
	segptr32 ptrArg04;
	ui32 dwArg08;
	Top_3 = 0;
	es_16 = SLICE(ptrArg04, selector, 16);
	di_23 = (word16) ptrArg04;
	ax_bx_53 = SEQ(es_16 >> 0x0C, es_16 << 0x04);
	ax_bx_54 = ax_bx_53 + (uint32) di_23;
	ax_bx_56 = ax_bx_54 + dwArg08;
	bx_28 = (word16) ax_bx_56;
	ax_31 = SLICE(ax_bx_56, word16, 16);
	bx_33 = bx_28 & 0x0F;
	cl_36 = 0x0C;
	ax_38 = ax_31 << 0x0C | bx_28 >> 0x04;
	SZ_39 = cond(ax_38);
	S_63 = (bool) SZ_39;
	Z_64 = SLICE(SZ_39, bool, 2);
	O_40 = false;
	C_41 = false;
	ax_44 = bx_28 & 0x0F;
	dx_45 = ax_38;
}

// 2017:0132: define fn2017_0132
// Called from:
//      fn2BC7_0312
define fn2017_0132
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_47284 Eq_47291::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_47284 Eq_47291::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_47284 Eq_47291::*) di;
	bp = sp;
	cl = 0x04;
	ax = (ss->*bp).w000C;
	bx = (ss->*bp).w000A;
	bx >>= cl;
	ax += bx;
	bx = (ss->*bp).w0010;
	dx = (ss->*bp).w000E;
	dx >>= cl;
	bx += dx;
	SCZO = cond(ax - bx);
	if (Test(EQ,Z))
	{
		ax = (ss->*bp).w000A;
		ax &= 0x0F;
		bx = (ss->*bp).w000E;
		bx &= 0x0F;
		SCZO = cond(ax - bx);
	}
	ax = ~0x00;
	if (Test(UGE,C))
	{
		if (Test(NE,Z))
		{
			++ax;
			SZO = cond(ax);
		}
		++ax;
		SZO = cond(ax);
	}
	di = (struct Eq_47284 Eq_47291::*) (ss->*sp).ptr0000;
	sp = (struct Eq_47284 Eq_47291::*) &sp->ptr0000;
	si = (struct Eq_47284 Eq_47291::*) (ss->*sp).ptr0000;
	sp = (struct Eq_47284 Eq_47291::*) &sp->ptr0000;
	bp = (struct Eq_47284 Eq_47291::*) (ss->*sp).ptr0000;
	sp = (struct Eq_47284 Eq_47291::*) &sp->ptr0000;
}

// 2017:016C: define fn2017_016C
// Called from:
//      fn3CEE_8634
define fn2017_016C
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	sp -= 2;
	ss->*sp = ds;
	ds_dx = (char *) (ss->*((word16) bp + 0x0E));
	msdos_set_DTA(ds_dx);
	cx = (word16) (ss->*((word16) bp + 18));
	ds_dx = (char *) (ss->*((word16) bp + 0x0A));
	ah = 0x4E;
	C = msdos_find_first_file(cx, ds_dx);
	ax = 0x01;
	if (Test(ULT,C))
	{
		ax = ax ^ ax;
		SZ = cond(ax);
		O = false;
		C = false;
	}
	ds = ss->*sp;
	sp = (word16) sp + 2;
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2017:018F: define fn2017_018F
// Called from:
//      fn3CEE_8634
define fn2017_018F
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	sp -= 2;
	ss->*sp = ds;
	ds_dx = ss->*((word16) bp + 0x0A);
	ah = 0x4F;
	C = msdos_find_next_file();
	ax = 0x01;
	if (Test(ULT,C))
	{
		ax = ax ^ ax;
		SZ = cond(ax);
		O = false;
		C = false;
	}
	ds = ss->*sp;
	sp = (word16) sp + 2;
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2017:01A8: define fn2017_01A8
// Called from:
//      fn21DC_0EC2
//      fn2C27_0002
define fn2017_01A8
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bx = ~0x00;
	ah = 0x48;
	C = msdos_allocate_memory_block(bx);
	ax = bx;
	di = ss->*sp;
	++sp;
	si = ss->*sp;
	++sp;
	bp = ss->*sp;
	++sp;
}

// 2017:01BA: define fn2017_01BA
// Called from:
//      fn1825_139A
//      fn1825_1D40
//      fn1825_2CF2
//      fn1825_3BCE
//      fn1825_3EE6
//      fn1825_4BFA
//      fn1825_5E5C
//      fn1825_6168
//      fn1825_63F8
//      fn2BC7_03C2
//      fn3431_0E74
//      fn38D6_0DFE
define fn2017_01BA
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	sp -= 2;
	ss->*sp = ds;
	D = false;
	es_di = ss->*((word16) bp + 0x0A);
	bx = di;
	ds_si = ss->*((word16) bp + 0x0E);
	do
	{
		al = ds->*si;
		si = (word16) si + 1;
		es->*di = al;
		di = (word16) di + 1;
		al |= al;
		SZ = cond(al);
		O = false;
		C = false;
	} while (Test(NE,Z));
	ax = es;
	ds = ss->*sp;
	sp = (word16) sp + 2;
	sp -= 2;
	ss->*sp = ax;
	ax = bx;
	dx = ss->*sp;
	sp = (word16) sp + 2;
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2017:01DA: define fn2017_01DA
// Called from:
//      fn38D6_0DFE
define fn2017_01DA
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	sp -= 2;
	ss->*sp = ds;
	D = false;
	es_di = ss->*((word16) bp + 0x0A);
	ds_si = ss->*((word16) bp + 0x0E);
	cx = (word16) (ss->*((word16) bp + 18));
	if (cx != 0x00)
	{
		do
		{
			al = ds->*si;
			si = (word16) si + 1;
			es->*di = al;
			di = (word16) di + 1;
			al |= al;
			SZ = cond(al);
			O = false;
			C = false;
			--cx;
		} while (Test(NE,Z) && cx != 0x00);
		(es->*((word16) di - 1)).u0 = 0x00;
	}
	ax = (word16) (ss->*((word16) bp + 18));
	ax -= cx;
	SCZO = cond(ax);
	ds = ss->*sp;
	sp = (word16) sp + 2;
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2017:0228: define fn2017_0228
// Called from:
//      fn1825_3766
//      fn1825_54D4
//      fn2368_0002
//      fn2644_000E
//      fn2644_0D70
//      fn2644_22BE
//      fn2B41_00B4
//      fn2B41_01FA
//      fn2D1A_0008
//      fn2D1A_0A76
//      fn2E37_02A4
//      fn2E37_0740
//      fn31FF_0008
//      fn31FF_19EA
//      fn31FF_1B66
//      fn31FF_207C
//      fn3431_000A
//      fn3431_0E74
//      fn38D6_06FA
//      fn38D6_0DFE
//      fn3CEE_3E50
//      fn3CEE_3E8B
//      fn3CEE_3F4C
//      fn3CEE_4188
//      fn3CEE_4490
//      fn3CEE_661D
//      fn3CEE_6620
//      fn3CEE_6E24
//      fn3CEE_6F82
define fn2017_0228
{
	word16 wArg06;
	word16 wArg04;
	byte bArg08;
	word16 wArg0A;
	Top_3 = 0;
	D_15 = false;
	bx_22 = wArg04 >> 0x04;
	ax_23 = wArg06 + (wArg04 >> 0x04);
	di_24 = wArg04 & 0x0F;
	es_25 = ax_23;
	cx_29 = wArg0A >> 0x01;
	SCZO_30 = cond(wArg0A >> 0x01);
	C_55 = SLICE(SCZO_30, bool, 1);
	O_81 = SLICE(SCZO_30, bool, 4);
	S_84 = (bool) SCZO_30;
	Z_89 = SLICE(SCZO_30, bool, 2);
	while (true)
	{
		di_35 = ϕ(di_24, di_53);
		cx_31 = ϕ(cx_29, cx_54);
		ax_51 = SEQ(bArg08, bArg08);
		if (cx_31 == 0x00)
			break;
		ax_23->*di_35 = ax_51;
		di_53 = (word16) di_35 + 2;
		cx_54 = cx_31 - 0x01;
	}
	ax_70 = SEQ(bArg08, bArg08);
	if (wArg0A >> 0x01 < 0x00)
	{
		ax_23->*di_35 = bArg08;
		ax_71 = SEQ(bArg08, bArg08);
	}
	ax_69 = ϕ(ax_70, ax_71);
}

// 2017:0258: define fn2017_0258
// Called from:
//      fn2644_20AA
//      fn2BC7_011C
//      fn2D1A_03E4
//      fn2D1A_064E
//      fn2EB3_1206
//      fn3431_0E74
//      fn3CEE_3F4C
//      fn3CEE_4188
//      fn3CEE_4490
//      fn3CEE_4EAC
//      fn3CEE_6980
//      fn3CEE_6A6A
//      fn3CEE_70B0
define fn2017_0258
{
	word16 wArg0A;
	word16 wArg08;
	word16 wArg06;
	word16 wArg04;
	word16 wArg0C;
	Top_3 = 0;
	ax_26 = wArg0A + (wArg08 >> 0x04);
	bx_35 = wArg04 >> 0x04;
	dx_36 = wArg06 + (wArg04 >> 0x04);
	es_38 = dx_36;
	if (ax_26 <= dx_36)
	{
		if (ax_26 >= dx_36)
		{
			if ((wArg08 & 0x0F) > (wArg04 & 0x0F))
				goto l2017_02E0;
			bx_63 = wArg0C + (wArg08 & 0x0F);
			bx_64 = bx_63 - 0x01;
			if (bx_63 - 0x01 >= (wArg04 & 0x0F))
			{
l2017_02C6:
				bx_170 = ϕ(bx_64, bx_50, bx_57);
				if (wArg0C >= 0x02)
				{
					si_92 = (wArg08 & 0x0F) + wArg0C;
					si_94 = si_92 - 0x02;
					di_95 = (wArg04 & 0x0F) + wArg0C;
					di_97 = di_95 - 0x02;
					cx_98 = wArg0C >> 0x01;
					SCZO_99 = cond(wArg0C >> 0x01);
					C_138 = SLICE(SCZO_99, bool, 1);
					O_185 = SLICE(SCZO_99, bool, 4);
					S_190 = (bool) SCZO_99;
					Z_199 = SLICE(SCZO_99, bool, 2);
					while (true)
					{
						Mem110 = ϕ(Mem17, Mem134);
						di_106 = ϕ(di_97, di_136);
						si_104 = ϕ(si_94, si_135);
						cx_101 = ϕ(cx_98, cx_137);
						if (cx_101 == 0x00)
							break;
						v23_133 = ax_26->*si_104;
						dx_36->*di_106 = v23_133;
						si_135 = si_104 - 2;
						di_136 = di_106 - 2;
						cx_137 = cx_101 - 0x01;
					}
					if (wArg0C >> 0x01 < 0x00)
					{
						si_105 = (word16) si_104 + 1;
						di_107 = (word16) di_106 + 1;
						SZO_108 = cond(di_107);
						O_186 = SLICE(SZO_108, bool, 4);
						S_191 = (bool) SZO_108;
						Z_200 = SLICE(SZO_108, bool, 2);
						v24_111.u0 = (ax_26->*si_105).u0;
						(dx_36->*di_107).u0 = (byte) v24_111;
					}
l2017_02E7:
					Z_196 = ϕ(Z_197, Z_197, Z_199, Z_200);
					S_187 = ϕ(S_188, S_188, S_190, S_191);
					O_182 = ϕ(O_183, O_183, O_185, O_186);
					D_174 = false;
					cx_173 = ϕ(cx_82, cx_82, cx_101, cx_101);
					C_172 = ϕ(C_85, C_85, C_138, C_138);
					bx_168 = ϕ(bx_169, bx_169, bx_170, bx_170);
					return;
				}
				goto l2017_02E0;
			}
		}
		else
		{
			bx_44 = wArg0C + (wArg08 & 0x0F);
			bx_46 = bx_44 - 0x01 >> 0x01;
			bx_50 = ax_26 + (bx_46 >> 0x03);
			if (bx_50 < dx_36)
				goto l2017_02E0;
			if (bx_50 > dx_36)
				goto l2017_02C6;
			bx_55 = wArg0C + (wArg08 & 0x0F);
			bx_57 = bx_55 - 0x01 & 0x0F;
			if (bx_57 >= (wArg04 & 0x0F))
				goto l2017_02C6;
		}
	}
l2017_02E0:
	bx_169 = ϕ(bx_35, bx_35, bx_64, bx_170, bx_50, bx_57);
	SCZO_72 = cond(wArg0C >> 0x01);
	C_85 = SLICE(SCZO_72, bool, 1);
	O_183 = SLICE(SCZO_72, bool, 4);
	S_188 = (bool) SCZO_72;
	Z_197 = SLICE(SCZO_72, bool, 2);
	size_73 = (wArg0C >> 0x01) *32 0x02;
	memcpy(wArg04 & 0x0F, wArg08 & 0x0F, size_73);
	cx_82 = 0x00;
	si_83 = (wArg08 & 0x0F) + (word16) size_73;
	di_84 = (wArg04 & 0x0F) + (word16) size_73;
	if (wArg0C >> 0x01 < 0x00)
	{
		v22_88 = (byte) (ax_26->*si_83);
		dx_36->*di_84 = v22_88;
	}
	goto l2017_02E7;
}

// 2017:02EC: define fn2017_02EC
// Called from:
//      fn1825_2CF2
//      fn1825_3766
//      fn1825_4658
//      fn1825_48D2
//      fn1825_496A
//      fn1825_54D4
//      fn1825_6078
//      fn1825_6168
//      fn20B2_0176
//      fn20B2_01FC
//      fn20B2_0308
//      fn20B2_0474
//      fn20B2_0E9E
//      fn21DC_0368
//      fn21DC_03EE
//      fn2368_059E
//      fn2644_17C8
//      fn2EB3_0ED4
//      fn2EB3_1206
//      fn2EB3_1720
//      fn2EB3_17FE
//      fn2EB3_20FE
//      fn31FF_006A
//      fn31FF_0BA0
//      fn31FF_0C14
//      fn31FF_0C62
//      fn31FF_0DB8
//      fn31FF_0F20
//      fn31FF_17DA
//      fn31FF_19EA
//      fn31FF_1B66
//      fn31FF_207C
//      fn38D6_03DC
//      fn3B5D_04C8
//      fn3CEE_8634
define fn2017_02EC
{
	segptr32 ptrArg04;
	segptr32 ptrArg08;
	word16 wArg0C;
	Top_3 = 0;
	D_18 = false;
	es_25 = SLICE(ptrArg04, selector, 16);
	di_26 = (word16) ptrArg04;
	ds_27 = SLICE(ptrArg08, selector, 16);
	si_28 = (word16) ptrArg08;
	SCZO_23 = cond(wArg0C >> 0x01);
	C_32 = SLICE(SCZO_23, bool, 1);
	O_64 = SLICE(SCZO_23, bool, 4);
	S_66 = (bool) SCZO_23;
	Z_69 = SLICE(SCZO_23, bool, 2);
	size_24 = (wArg0C >> 0x01) *32 0x02;
	memcpy(ptrArg04, ptrArg08, size_24);
	cx_29 = 0x00;
	si_30 = si_28 + (word16) size_24;
	di_31 = di_26 + (word16) size_24;
	if (wArg0C >> 0x01 < 0x00)
	{
		v17_33 = ds_27->*si_30;
		es_25->*di_31 = v17_33;
	}
}

// 2017:0308: define fn2017_0308
// Called from:
//      fn2EB3_240A
//      fn2EB3_24C6
define fn2017_0308
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	sp -= 2;
	ss->*sp = ds;
	D = false;
	es_di = ss->*((word16) bp + 0x0A);
	ds_si = ss->*((word16) bp + 0x0E);
	cx = (uint16) (ss->*((word16) bp + 18));
	dx = (uint16) (ss->*((word16) bp + 20));
	SCZO = cond(cx - dx);
	if (Test(ULE,CZ))
	{
		size = cx *32 0x01;
		memcpy(di, si, size);
		cx = 0x00;
		si = (<unknown>*) ((char *) si + (word16) size);
		di = (<unknown>*) ((char *) di + (word16) size);
	}
	else
	{
		v18 = dx;
		dx = cx;
		cx = v18;
		dx -= cx;
		SCZO = cond(dx);
		size = cx *32 0x01;
		memcpy(di, si, size);
		si = (<unknown>*) ((char *) si + (word16) size);
		di = (<unknown>*) ((char *) di + (word16) size);
		al.u0 = 0x20;
		for (cx = dx; cx != 0x00; --cx)
		{
			es->*di = (<unknown>*) al;
			di = (<unknown>*) ((char *) di + 1);
		}
	}
	ds = ss->*sp;
	sp = (word16) sp + 2;
	di = (<unknown>*) (ss->*sp);
	sp = (word16) sp + 2;
	si = (<unknown>*) (ss->*sp);
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2017:0335: define fn2017_0335
// Called from:
//      fn1825_4814
define fn2017_0335
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	sp -= 2;
	ss->*sp = ds;
	D = false;
	ds_si = ss->*((word16) bp + 0x0A);
	es_di = ss->*((word16) bp + 0x0E);
	cx = (uint16) (ss->*((word16) bp + 18));
	ax = 0x00;
	if (cx != 0x00)
	{
		cmpResult = memcmp(si, di, cx *32 0x01);
		firstDifference = __find_first_difference__(si, di);
		cx -= firstDifference;
		si = (<unknown>*) ((char *) si + firstDifference);
		di = (<unknown>*) ((char *) di + firstDifference);
		SCZO = cond(cmpResult);
		if (Test(NE,Z))
		{
			ax = 0x01;
			if (Test(LE,SZO))
				ax = ~0x00;
		}
	}
	ds = ss->*sp;
	sp = (word16) sp + 2;
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2017:035B: define fn2017_035B
// Called from:
//      fn31FF_0216
//      fn31FF_17DA
//      fn3431_0DDE
//      fn3CEE_0EA8
define fn2017_035B
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	D = false;
	es_di = ss->*((word16) bp + 0x0A);
	cx = (word16) (ss->*((word16) bp + 0x0E));
	if (cx != 0x00)
	{
		bx = cx;
		al = (byte) (ss->*((word16) bp + 16));
		while (cx != 0x00)
		{
			SCZO = cond(al - es->*di);
			di = (word16) di + 1;
			--cx;
			if (Test(NE,Z))
				break;
		}
		if (Test(EQ,Z))
		{
			++cx;
			SZO = cond(cx);
		}
		v18 = cx;
		cx = bx;
		bx = v18;
		cx -= bx;
		SCZO = cond(cx);
	}
	ax = cx;
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2017:037D: define fn2017_037D
// Called from:
//      fn1825_2CF2
//      fn38D6_0DFE
define fn2017_037D
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	sp -= 2;
	ss->*sp = ds;
	D = false;
	es_di = ss->*((word16) bp + 0x0A);
	bx = di;
	ds_si = ss->*((word16) bp + 0x0E);
	ax = ax ^ ax;
	SZ = cond(ax);
	O = false;
	C = false;
	cx = ~0x00;
	while (cx != 0x00)
	{
		SCZO = cond(al - es->*di);
		di = (word16) di + 1;
		--cx;
		if (Test(NE,Z))
			break;
	}
	--di;
	SZO = cond(di);
	do
	{
		al = ds->*si;
		si = (word16) si + 1;
		es->*di = al;
		di = (word16) di + 1;
		al |= al;
		SZ = cond(al);
		O = false;
		C = false;
	} while (Test(NE,Z));
	ax = es;
	ds = ss->*sp;
	sp = (word16) sp + 2;
	sp -= 2;
	ss->*sp = ax;
	ax = bx;
	dx = ss->*sp;
	sp = (word16) sp + 2;
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2017:03D0: define fn2017_03D0
// Called from:
//      fn1825_2CF2
//      fn1825_63F8
//      fn2BC7_03C2
//      fn2BC7_0494
define fn2017_03D0
{
	segptr32 ptrArg04;
	Top_3 = 0;
	D_18 = false;
	ds_50 = SLICE(ptrArg04, selector, 16);
	si_51 = (word16) ptrArg04;
	do
	{
		do
		{
			si_21 = ϕ(si_51, si_24, si_24, si_24);
			al_23 = ds_50->*si_21;
			si_24 = si_21 + 1;
		} while (al_23 == 0x20 || al_23 == 0x09);
		SCZO_29 = cond(al_23 - 0x0A);
		C_62 = SLICE(SCZO_29, bool, 1);
	} while (al_23 == 0x0A);
	SZO_32 = cond(si_24 - 0x01);
	O_64 = SLICE(SZO_32, bool, 4);
	S_65 = (bool) SZO_32;
	Z_67 = SLICE(SZO_32, bool, 2);
	bx_34 = si_24 - 0x01;
	ax_41 = si_24 - 0x01;
	dx_42 = ds_50;
}

// 2017:03F5: define fn2017_03F5
// Called from:
//      fn1825_02F0
//      fn1825_037E
//      fn1825_05F2
//      fn1825_06E0
//      fn1825_0A00
//      fn1825_0E72
//      fn1825_139A
//      fn1825_18A6
//      fn1825_1D40
//      fn1825_2020
//      fn1825_2696
//      fn1825_26D6
//      fn1825_2C52
//      fn1825_2CF2
//      fn1825_3766
//      fn1825_39DE
//      fn1825_3BCE
//      fn1825_3EE6
//      fn1825_4658
//      fn1825_48D2
//      fn1825_496A
//      fn1825_4BFA
//      fn1825_4DA6
//      fn1825_54D4
//      fn1825_5730
//      fn1825_5850
//      fn1825_5E5C
//      fn1825_6042
//      fn1825_6168
//      fn1825_63F8
//      fn1825_648A
//      fn20B2_005C
//      fn20B2_0140
//      fn20B2_01FC
//      fn20B2_0308
//      fn20B2_0E9E
//      fn20B2_10AC
//      fn2368_022E
//      fn2644_17C8
//      fn2BC7_0312
//      fn31FF_006A
//      fn31FF_0AAE
//      fn3431_0E74
//      fn38D6_0DFE
//      fn3B5D_04C8
//      fn3CEE_3CE2
//      fn3CEE_4188
//      fn3CEE_4490
//      fn3CEE_5556
//      fn3CEE_8634
define fn2017_03F5
{
	segptr32 ptrArg04;
	Top_3 = 0;
	D_15 = false;
	es_46 = SLICE(ptrArg04, selector, 16);
	di_47 = (word16) ptrArg04;
	cx_17 = ~0x00;
	do
	{
		di_22 = ϕ(di_47, di_25);
		cx_19 = ϕ(cx_17, cx_26);
		if (cx_19 == 0x00)
			break;
		di_25 = di_22 + 1;
		cx_26 = cx_19 - 0x01;
	} while (es_46->*di_22 == 0x00);
	cx_28 = ϕ(cx_19, cx_26);
	C_30 = cx_28 != 0x00;
	ax_31 = -cx_28;
	ax_33 = ax_31 - 0x02;
	SZO_34 = cond(ax_31 - 0x02);
	O_61 = SLICE(SZO_34, bool, 4);
	S_62 = (bool) SZO_34;
	Z_65 = SLICE(SZO_34, bool, 2);
}

// 2017:040F: define fn2017_040F
// Called from:
//      fn3CEE_DA1B
define fn2017_040F
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_48711 Eq_48718::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_48711 Eq_48718::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_48711 Eq_48718::*) di;
	bp = sp;
	dx = (ss->*bp).w000A;
	es_di.u1 = (ss->*bp).t000C.u1;
	ah = 0x36;
	__syscall<byte>(33);
	(es->*di).ptr0000 = (struct Eq_48711 Eq_48718::*) bx;
	(es->*di).w0002 = ax;
	(es->*di).w0004 = dx;
	di = (struct Eq_48711 Eq_48718::*) (ss->*sp).ptr0000;
	sp = (struct Eq_48711 Eq_48718::*) &sp->w0002;
	si = (struct Eq_48711 Eq_48718::*) (ss->*sp).ptr0000;
	sp = (struct Eq_48711 Eq_48718::*) &sp->w0002;
	bp = (struct Eq_48711 Eq_48718::*) (ss->*sp).ptr0000;
	sp = (struct Eq_48711 Eq_48718::*) &sp->w0002;
}

// 2017:042D: define fn2017_042D
// Called from:
//      fn38D6_0304
define fn2017_042D
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	sp -= 2;
	ss->*sp = ds;
	D = false;
	ds_si = ss->*((word16) bp + 0x0A);
	cx.u0 = 0x06;
	do
	{
		ax = ds->*si;
		si = (word16) si + 2;
		sp -= 2;
		ss->*sp = ax;
		--cx;
	} while (cx != 0x00);
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	dx = ss->*sp;
	sp = (word16) sp + 2;
	cx = ss->*sp;
	sp = (word16) sp + 2;
	bx = ss->*sp;
	sp = (word16) sp + 2;
	ax = ss->*sp;
	sp = (word16) sp + 2;
	__syscall<byte>(33);
	sp -= 2;
	ss->*sp = SCZDOP;
	sp -= 2;
	ss->*sp = di;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = dx;
	sp -= 2;
	ss->*sp = cx;
	sp -= 2;
	ss->*sp = bx;
	sp -= 2;
	ss->*sp = ax;
	es_di = ss->*((word16) bp + 0x0A);
	cx.u0 = 0x06;
	do
	{
		ax = ss->*sp;
		sp = (word16) sp + 2;
		es->*di = ax;
		di = (word16) di + 2;
		--cx;
	} while (cx != 0x00);
	ax = ss->*sp;
	sp = (word16) sp + 2;
	ds = ss->*sp;
	sp = (word16) sp + 2;
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2017:0489: define fn2017_0489
// Called from:
//      fn2EB3_0BF0
define fn2017_0489
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	cx.u0 = 0x00;
	es_di = ss->*((word16) bp + 0x0A);
	bx = es->*di;
	while (true)
	{
		SCZO = cond(cx - bx);
		if (Test(UGE,C))
			break;
		dx = cx;
		dx += bx;
		dx >>= 0x01;
		sp -= 2;
		ss->*sp = bx;
		sp -= 2;
		ss->*sp = cx;
		sp -= 2;
		ss->*sp = dx;
		sp -= 2;
		ss->*sp = es;
		sp -= 2;
		ss->*sp = di;
		si = dx;
		si <<= 0x01;
		si += di;
		si = es->*((word16) si + 2);
		si = (word16) si + 8;
		si += di;
		SCZO = cond(si);
		v15 = ss->*((word16) bp + 18);
		sp -= 2;
		ss->*sp = v15;
		v16 = ss->*((word16) bp + 16);
		sp -= 2;
		ss->*sp = v16;
		v17 = ss->*((word16) bp + 0x0E);
		sp -= 2;
		ss->*sp = v17;
		sp -= 2;
		ss->*sp = es;
		sp -= 2;
		ss->*sp = si;
		fn38AD_00F2();
		sp = (word16) sp + 0x0A;
		di = ss->*sp;
		sp = (word16) sp + 2;
		es = ss->*sp;
		sp = (word16) sp + 2;
		dx = ss->*sp;
		sp = (word16) sp + 2;
		cx = ss->*sp;
		sp = (word16) sp + 2;
		bx = ss->*sp;
		sp = (word16) sp + 2;
		SCZO = cond(ax - 0x00);
		if (Test(GT,SZO))
			bx = dx;
		else
		{
			cx = dx;
			cx = (char *) cx.u0 + 1;
			SZO = cond(cx);
		}
	}
	ax = cx;
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2017:04E1: define fn2017_04E1
// Called from:
//      fn38D6_0DFE
define fn2017_04E1
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	sp -= 2;
	ss->*sp = ds;
	0x2017->ptr04E9 = ss;
	0x2017->t04EB = sp;
	ds_dx = ss->*((word16) bp + 0x0A);
	es_bx = ss->*((word16) bp + 0x0E);
	ax = 0x4B00;
	C = msdos_exec(al, ds_dx, es_bx);
	__cli();
	ss = 0x2017->ptr04E9;
	sp = 0x2017->t04EB;
	__sti();
	if (Test(UGE,C))
	{
		ax = ax ^ ax;
		SZ = cond(ax);
		O = false;
		C = false;
	}
	ds = ss->*sp;
	sp = (word16) sp + 2;
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

struct Eq_49183 * g_ptr04E9 = null; // 2017:04E9
Eq_49176 g_t04EB = // 2017:04EB
	{
		null
	};
