// 1999_SOFT_LOAN__20B2.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 20B2:000E: define fn20B2_000E
// Called from:
//      fn20B2_005C
define fn20B2_000E
{
	mp16 fp;
	selector ss;
	selector ds;
	word16 wArg04;
	Top_3 = 0;
	ptrLoc1E_89 = fp - 18;
	fn38D6_0D68();
	wLoc14_90.u0 = 0x00;
	do
	{
		wLoc14_91 = ϕ(wLoc14_90, wLoc14_92);
		Mem39 = ϕ(Mem36, Mem44);
		if (Mem39[ss:fp - 18 + wLoc14_91:byte] != 0x20)
			break;
		v11_43 = (word16) wLoc14_91.u0 + 1;
		wLoc14_92 = v11_43;
	} while (v11_43 < 0x10);
	wLoc14_93 = ϕ(wLoc14_91, wLoc14_92);
	ax_51 = 0x0F - wLoc14_93;
	ax_58 = fp - 18 + wLoc14_93;
	ptrLoc1C_97 = (segptr32) ax_58;
	fn1F38_049F();
	SCZO_77 = cond(fp - 22);
	C_102 = SLICE(SCZO_77, bool, 1);
	O_103 = SLICE(SCZO_77, bool, 4);
	S_104 = (bool) SCZO_77;
	Z_107 = SLICE(SCZO_77, bool, 2);
}

// 20B2:005C: define fn20B2_005C
// Called from:
//      fn20B2_0140
//      fn20B2_107C
//      fn20B2_10AC
define fn20B2_005C
{
	mp16 fp;
	selector ss;
	selector ds;
	Top_3 = 0;
	fn1F38_0517();
	ax_17 = ax_241;
	ds->w1144 = ax_17;
	fn1F38_04E7();
	ah_35 = SLICE(ax_25, byte, 8);
	fn1F38_08CB();
	if (ds->w128A != 0x00)
	{
		dx_ax_50 = ds->w128A *32 22;
		ax_52 = (word16) dx_ax_50;
		es_bx_55 = ds->t1282;
		es_56 = SLICE(es_bx_55, selector, 16);
		bx_57 = (word16) es_bx_55;
		v15_58 = (&(es_56->*((es_56->*bx_57).a0012 + 1)))[ax_52];
		v16_61 = (&(es_56->*(es_56->*bx_57).a0012))[ax_52];
		ptrLoc0C_204 = SEQ(v15_58, v16_61);
		fn2BC7_050A();
		wLoc06_205 = ax_64;
		wLoc04_206 = dx_66;
		dwLoc06_242 = SEQ(wLoc04_206, wLoc06_205);
	}
	else
	{
		wLoc06_200 = 23358;
		wLoc04_201 = ds;
		dwLoc06_243 = (segptr32) wLoc06_200;
	}
	dwLoc06_244 = ϕ(dwLoc06_242, dwLoc06_243);
	ptrLoc0E_210 = (segptr32) (&ds->w128A + 9311);
	fn1F38_049F();
	ptrLoc0C_215 = dwLoc06_244;
	fn2017_03F5();
	ptrLoc0E_219 = dwLoc06_244;
	fn1F38_049F();
	if (ds->w127A != 0x00)
	{
		ptrLoc0E_223 = (segptr32) (&ds->w128A + 0x00002462);
		fn1F38_049F();
		v22_153 = ds->w127A;
		fn20B2_000E();
	}
	ptrLoc0E_228 = (segptr32) (&ds->w128A + 0x00002466);
	fn1F38_049F();
	SCZO_190 = cond(fp - 0x08);
	C_233 = SLICE(SCZO_190, bool, 1);
	O_234 = SLICE(SCZO_190, bool, 4);
	S_237 = (bool) SCZO_190;
	Z_240 = SLICE(SCZO_190, bool, 2);
}

// 20B2:0118: define fn20B2_0118
// Called from:
//      fn20B2_1014
define fn20B2_0118
{
	mp16 fp;
	selector ds;
	Top_3 = 0;
	fn1F38_04E7();
	ah_22 = SLICE(ax_12, byte, 8);
	fn1F38_08CB();
	al_31 = ds->t1144;
	ax_34 = (uint16) al_31;
	ax_36 = ds->t1144;
	fn1F38_04E7();
	SCZO_51 = cond(fp);
	C_56 = SLICE(SCZO_51, bool, 1);
	O_57 = SLICE(SCZO_51, bool, 4);
	S_58 = (bool) SCZO_51;
	Z_59 = SLICE(SCZO_51, bool, 2);
}

// 20B2:0140: define fn20B2_0140
// Called from:
//      fn20B2_0176
//      fn20B2_01BA
//      fn20B2_0BDC
//      fn20B2_0E9E
//      fn20B2_0EF6
define fn20B2_0140
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_50636 Eq_50643::*) bp;
	bp = sp;
	SCZO = cond(ds->w1278 - 0x00);
	if (Test(EQ,Z))
	{
		fn20B2_005C();
		v9 = (struct Eq_50636 Eq_50643::*) (ss->*bp).ptr0008;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_50636 Eq_50643::*) v9;
		v10 = (struct Eq_50636 Eq_50643::*) (ss->*bp).ptr0006;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_50636 Eq_50643::*) v10;
		fn2017_03F5();
		sp = (struct Eq_50636 Eq_50643::*) &sp->ptr0000;
		SCZO = cond(sp);
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_50636 Eq_50643::*) ax;
		v12 = (struct Eq_50636 Eq_50643::*) (ss->*bp).ptr0008;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_50636 Eq_50643::*) v12;
		v13 = (struct Eq_50636 Eq_50643::*) (ss->*bp).ptr0006;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_50636 Eq_50643::*) v13;
		fn1F38_049F();
		sp = (struct Eq_50636 Eq_50643::*) &sp->ptr0006;
		SCZO = cond(sp);
		fn20B2_1014();
	}
	fn21DC_04BA();
	bp = (struct Eq_50636 Eq_50643::*) (ss->*sp).ptr0000;
	sp = (struct Eq_50636 Eq_50643::*) &sp->ptr0000;
}

// 20B2:0176: define fn20B2_0176
// Called from:
//      fn20B2_0BDC
//      fn20B2_1192
//      fn21DC_01C4
//      fn2C27_0112
//      fn2C27_0140
//      fn2C27_03B4
//      fn2C27_0440
//      fn2D1A_07F6
//      fn2D1A_0890
//      fn2D1A_0A76
//      fn2D1A_0BD2
//      fn2EB3_1206
//      fn2EB3_2340
//      fn2EB3_24C6
define fn20B2_0176
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x20;
	SCZO = cond(sp);
	ax.u0 = 0x0F;
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x5B5A;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	ax = bp - 32;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	fn2017_02EC();
	sp = (word16) sp + 0x0A;
	ax -= ax;
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x02;
	sp -= 2;
	ss->*sp = ax;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v9 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v9;
	ax = bp - 0x0011;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	fn3CEE_0EFC();
	sp = (word16) sp + 0x0C;
	SCZO = cond(sp);
	ax = bp - 32;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	fn20B2_0140();
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:01BA: define fn20B2_01BA
// Called from:
//      fn20B2_0474
//      fn20B2_0612
//      fn20B2_0776
//      fn20B2_0898
//      fn20B2_099A
//      fn20B2_0AC6
//      fn20B2_0EF6
define fn20B2_01BA
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_50856 Eq_50863::*) bp;
	bp = sp;
	sp -= 0x04;
	SCZO = cond(sp);
	v7 = (struct Eq_50856 Eq_50863::*) (ss->*bp).ptr0008;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_50856 Eq_50863::*) v7;
	v8 = (struct Eq_50856 Eq_50863::*) (ss->*bp).ptr0006;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_50856 Eq_50863::*) v8;
	fn2BC7_0494();
	sp = (struct Eq_50856 Eq_50863::*) &sp->ptr0000;
	(ss->*bp).tFFFFFFFC.u0 = (cui16) ax;
	(ss->*bp).wFFFFFFFE = dx;
	ax |= dx;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		es_bx.u2 = (ss->*bp).tFFFFFFFC.u2;
		ax.u0 = (es->*bx).t000E.u0;
		ax |= (es->*bx).w0010;
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
l20B2_01F2:
			ax.u0 = (ss->*bp).tFFFFFFFC.u0;
			dx = (ss->*bp).wFFFFFFFE;
			sp = bp;
			bp = (struct Eq_50856 Eq_50863::*) (ss->*sp).ptr0000;
			sp = (struct Eq_50856 Eq_50863::*) &sp->ptr0000;
			return;
		}
	}
	v18 = (struct Eq_50856 Eq_50863::*) (ss->*bp).ptr000C;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_50856 Eq_50863::*) v18;
	v19 = (struct Eq_50856 Eq_50863::*) (ss->*bp).ptr000A;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_50856 Eq_50863::*) v19;
	fn20B2_0140();
	sp = (struct Eq_50856 Eq_50863::*) &sp->ptr0000;
	SCZO = cond(sp);
	goto l20B2_01F2;
}

// 20B2:01FC: define fn20B2_01FC
// Called from:
//      fn20B2_099A
define fn20B2_01FC
{
	mp16 fp;
	selector ds;
	Top_3 = 0;
	es_bx_14 = ds->ptr1296;
	ax_17 = es_bx_14->w000C;
	bLoc04_220 = (byte) ax_17;
	wLoc0A_213 = 0x00;
	if (ax_17 == 0x00)
	{
l20B2_02C7:
		wLoc0A_256 = ϕ(wLoc0A_213, wLoc0A_244);
		Mem145 = ϕ(Mem19, Mem143);
		es_bx_146 = ds->ptr1296;
		v19_149 = es_bx_146->w000A;
		v20_156 = es_bx_146->w0008;
		ptrLoc14_247 = SEQ(v19_149, v20_156);
		fn2BC7_050A();
		dx_161 = SLICE(dx_ax_277, word16, 16);
		ptrLoc14_252 = dx_ax_277;
		fn2017_03F5();
		ax_191 = wLoc0A_256 + 4322;
		wLoc1A_258 = wLoc0A_256 + 4322;
		ptrLoc1A_259 = (segptr32) wLoc1A_258;
		ptrLoc16_260 = dx_ax_277;
		fn2017_02EC();
		SCZO_205 = cond(fp - 0x10);
		C_269 = SLICE(SCZO_205, bool, 1);
		O_270 = SLICE(SCZO_205, bool, 4);
		S_271 = (bool) SCZO_205;
		Z_276 = SLICE(SCZO_205, bool, 2);
		return;
	}
	if (ax_17 == ~0x00)
	{
		wLoc0A_241 = &Eq_50988::t0001;
		ds->b10E2 = 77;
		goto l20B2_02B1;
	}
	if (ax_17 != ~0x01)
	{
		es_si_32 = ds->t130A;
		es_33 = SLICE(es_si_32, selector, 16);
		si_34 = (word16) es_si_32;
		ax_35 = si_34[ax_17].w0000;
		dx_36 = (Eq_51094) si_34[((word16) (ax_17 << 0x02) + 2) /16 4].w0000;
		ax_39 = ax_35 | dx_36;
		ptrLoc0E_216 = SEQ(dx_36, ax_35);
		if (ax_39 != 0x00)
		{
			ax_47 = ptrLoc0E_216->w003E;
			ax_48 = ax_47 | ptrLoc0E_216->w0040;
			if (ax_48 != 0x00)
			{
				v31_64 = ptrLoc0E_216->w0040;
				v32_67 = ptrLoc0E_216->w003E;
				ptrLoc14_227 = SEQ(v31_64, v32_67);
l20B2_023C:
				ptrLoc14_225 = ϕ(ptrLoc14_226, ptrLoc14_227);
				fn2BC7_050A();
				ptrLoc14_232 = dx_ax_278;
				fn2017_03F5();
				wLoc0A_233 = ax_92;
				ptrLoc1A_239 = (segptr32) &ds->b10E2;
				ptrLoc16_240 = dx_ax_278;
				fn2017_02EC();
l20B2_02B1:
				wLoc0A_242 = ϕ(wLoc0A_241, wLoc0A_233, wLoc0A_218);
				v24_135 = (struct Eq_51061 Eq_50988::*) ((char *) wLoc0A_242 + 1);
				(ds->*wLoc0A_242).b10E2 = 0x2D;
				wLoc0A_244 = (char *) v24_135 + 1;
				(ds->*v24_135).b10E2 = 0x3E;
				goto l20B2_02C7;
			}
		}
		wLoc0A_218 = &Eq_50988::t0001;
		ds->b10E2 = bLoc04_220 + 0x40;
		goto l20B2_02B1;
	}
	else
	{
		v26_70 = ds->w10E0;
		v27_73 = ds->w10DE;
		ptrLoc14_226 = SEQ(v26_70, v27_73);
		goto l20B2_023C;
	}
}

// 20B2:0308: define fn20B2_0308
// Called from:
//      fn20B2_0474
//      fn20B2_0612
//      fn20B2_0776
//      fn20B2_0898
//      fn20B2_099A
//      fn20B2_0AC6
define fn20B2_0308
{
	word32 dwLoc06;
	word32 dwArg04;
	mp16 fp;
	selector ds;
	word16 wArg08;
	bool P;
	Top_3 = 0;
	ptrLoc0C_295 = dwArg04;
	fn2017_03F5();
	ax_38 = 0x1104;
	ptrLoc12_302 = &ds->t1104;
	ptrLoc0E_303 = dwArg04;
	fn2017_02EC();
	SCZO_52 = cond(wArg08 - 0x00);
	Z_53 = SLICE(SCZO_52, bool, 2);
	C_388 = SLICE(SCZO_52, bool, 1);
	O_394 = SLICE(SCZO_52, bool, 4);
	S_408 = (bool) SCZO_52;
	if (wArg08 != 0x00)
	{
		ptrLoc12_310 = (segptr32) (ax_17 + 0x1104);
		ptrLoc0E_311 = (segptr32) ((char *) &ds->t1104 + 0x00004A66);
		fn2017_02EC();
		wLoc08_312 = ax_17 + 0x05;
		dwLoc06_425 = dwLoc06;
		while (true)
		{
			dwLoc06_426 = ϕ(dwLoc06_425, dwLoc06_424, dwLoc06_424);
			P_398 = ϕ(P, P_399, P_399);
			wLoc08_317 = ϕ(wLoc08_312, wLoc08_362, wLoc08_380);
			wArg08_313 = ϕ(wArg08, wArg08_363, wArg08_363);
			bArg08_322 = (byte) wArg08_313;
			bArg09_364 = SLICE(wArg08_313, byte, 8);
			if (wArg08_313 == 0x00)
				break;
			SZP_111 = cond(bArg08_322 & 0x04);
			P_400 = SLICE(SZP_111, bool, 5);
			if ((bArg08_322 & 0x04) != 0x00)
			{
				wLoc06_341 = 0x5B70;
				wLoc04_342 = ds;
				wArg08_365 = SEQ(bArg09_364, bArg08_322 & ~0x04);
				dwLoc06_416 = (segptr32) wLoc06_341;
			}
			else
			{
				SZP_115 = cond(bArg08_322 & 0x08);
				P_401 = SLICE(SZP_115, bool, 5);
				if ((bArg08_322 & 0x08) != 0x00)
				{
					wLoc06_338 = 0x5B7A;
					wLoc04_339 = ds;
					wArg08_366 = SEQ(bArg09_364, bArg08_322 & ~0x08);
					dwLoc06_417 = (segptr32) wLoc06_338;
				}
				else
				{
					SZP_119 = cond(bArg08_322 & 0x20);
					P_402 = SLICE(SZP_119, bool, 5);
					if ((bArg08_322 & 0x20) != 0x00)
					{
						wLoc06_335 = 23426;
						wLoc04_336 = ds;
						wArg08_367 = SEQ(bArg09_364, bArg08_322 & 223);
						dwLoc06_418 = (segptr32) wLoc06_335;
					}
					else
					{
						SZP_123 = cond(bArg08_322 & 0x02);
						P_403 = SLICE(SZP_123, bool, 5);
						if ((bArg08_322 & 0x02) != 0x00)
						{
							wLoc06_332 = 23432;
							wLoc04_333 = ds;
							wArg08_368 = SEQ(bArg09_364, bArg08_322 & ~0x02);
							dwLoc06_419 = (segptr32) wLoc06_332;
						}
						else
						{
							SZP_127 = cond(bArg08_322 & 0x80);
							P_404 = SLICE(SZP_127, bool, 5);
							if ((bArg08_322 & 0x80) != 0x00)
							{
								wLoc06_329 = 23442;
								wLoc04_330 = ds;
								wArg08_369 = SEQ(bArg09_364, bArg08_322 & 0x7F);
								dwLoc06_420 = (segptr32) wLoc06_329;
							}
							else
							{
								SZP_131 = cond(bArg08_322 & 0x40);
								P_405 = SLICE(SZP_131, bool, 5);
								if ((bArg08_322 & 0x40) != 0x00)
								{
									wLoc06_326 = 23448;
									wLoc04_327 = ds;
									wArg08_370 = SEQ(bArg09_364, bArg08_322 & 191);
									dwLoc06_421 = (segptr32) wLoc06_326;
								}
								else
								{
									SZP_135 = cond(bArg08_322 & 0x01);
									P_406 = SLICE(SZP_135, bool, 5);
									wArg08_371 = wArg08_313;
									dwLoc06_422 = dwLoc06_426;
									if ((bArg08_322 & 0x01) != 0x00)
									{
										wLoc06_323 = 23454;
										wLoc04_324 = ds;
										wArg08_372 = SEQ(bArg09_364, bArg08_322 & ~0x01);
										dwLoc06_423 = (segptr32) wLoc06_323;
									}
								}
							}
						}
					}
				}
			}
			dwLoc06_424 = ϕ(dwLoc06_416, dwLoc06_417, dwLoc06_418, dwLoc06_419, dwLoc06_420, dwLoc06_421, dwLoc06_422, dwLoc06_423);
			P_399 = ϕ(P_400, P_401, P_402, P_403, P_404, P_405, P_406, P_406);
			wArg08_363 = ϕ(wArg08_365, wArg08_366, wArg08_367, wArg08_368, wArg08_369, wArg08_370, wArg08_371, wArg08_372);
			ptrLoc0C_350 = dwLoc06_424;
			fn2017_03F5();
			wLoc12_356 = wLoc08_317 + 0x1104;
			ptrLoc12_357 = (segptr32) wLoc12_356;
			ptrLoc0E_358 = dwLoc06_424;
			fn2017_02EC();
			ptrLoc0C_361 = dwLoc06_424;
			fn2017_03F5();
			v28_254 = wLoc08_317 + ax_245;
			wLoc08_362 = v28_254;
			if (wArg08_363 != 0x00)
			{
				ptrLoc12_378 = (segptr32) (v28_254 + 0x1104);
				ptrLoc0E_379 = (segptr32) ((char *) &ds->t1104 + 0x00004AA0);
				fn2017_02EC();
				wLoc08_380 = v28_254 + 0x02;
			}
		}
		ax_96 = wLoc08_317 + 0x1104;
		wLoc12_319 = wLoc08_317 + 0x1104;
		ptrLoc12_320 = (segptr32) wLoc12_319;
		ptrLoc0E_321 = (segptr32) ((char *) &ds->t1104 + 0x00004AA4);
		fn2017_02EC();
		SCZO_110 = cond(fp - 0x08);
		C_389 = SLICE(SCZO_110, bool, 1);
		O_395 = SLICE(SCZO_110, bool, 4);
		S_409 = (bool) SCZO_110;
		Z_414 = SLICE(SCZO_110, bool, 2);
	}
	Z_413 = ϕ(Z_53, Z_414);
	S_407 = ϕ(S_408, S_409);
	P_396 = ϕ(P, P_398);
	O_393 = ϕ(O_394, O_395);
	es_392 = ϕ(es_45, es_103);
	D_391 = ϕ(D_49, D_107);
	cx_390 = ϕ(cx_44, cx_102);
	C_387 = ϕ(C_388, C_389);
	ax_386 = ϕ(ax_38, ax_96);
}

// 20B2:0474: define fn20B2_0474
// Called from:
//      fn20B2_0BDC
define fn20B2_0474
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x70;
	sp -= 2;
	ss->*sp = di;
	sp -= 2;
	ss->*sp = si;
	ax = ss->*((word16) bp + 6);
	cx = ax;
	ax <<= 0x01;
	ax += cx;
	ax <<= 0x01;
	ax <<= 0x01;
	si = ax;
	al = (byte) (ds->*((word16) si + 9532));
	ah -= ah;
	ss->*((word16) bp - 0x0A) = ax;
	ax = ds->*((word16) si + 0x00002544);
	ax = (word16) ax + 12410;
	SCZO = cond(ax);
	ss->*((word16) bp - 4) = ax;
	ss->*((word16) bp - 2) = ds;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	v14 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v14;
	v15 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v15;
	ax.u0 = 0x5BAA;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn20B2_01BA();
	sp = (word16) sp + 0x0C;
	SCZO = cond(sp);
	ss->*((word16) bp - 32) = ax;
	ss->*((word16) bp - 30) = dx;
	v17 = Mem0[ds:0x10D4:word16];
	sp -= 2;
	ss->*sp = v17;
	v18 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v18;
	v19 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v19;
	fn20B2_0308();
	sp = (word16) sp + 6;
	SCZO = cond(Mem0[ds:4746:word16] - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = 22;
		dx_ax = Mem0[ds:4746:word16] *u32 ax;
		SCZO = cond(dx_ax);
		di = ax;
		es_bx = Mem0[ds:0x1282:segptr32];
		v25 = es->*((word16) di + ((word16) bx + 20));
		sp -= 2;
		ss->*sp = v25;
		v26 = es->*((word16) di + ((word16) bx + 18));
		sp -= 2;
		ss->*sp = v26;
		fn2BC7_050A();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = dx;
	}
	else
	{
		ax.u0 = 0x5BB6;
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = ds;
	}
	SCZO = cond(ss->*((word16) bp - 0x0A) - 0x00);
	if (Test(NE,Z))
	{
		si = ss->*((word16) bp - 0x0A);
		cl = 0x04;
		si <<= cl;
		sp -= 2;
		ss->*sp = si;
		ax = Mem0[ds:0x1296:word16];
		dx = Mem0[ds:0x1298:word16];
		ax -= si;
		ax = (word32) ax.u0 + 16;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = dx;
		sp -= 2;
		ss->*sp = ax;
		ax = bp - 112;
		sp -= 2;
		ss->*sp = ss;
		sp -= 2;
		ss->*sp = ax;
		fn2017_02EC();
		sp = (word16) sp + 0x0A;
		SCZO = cond(sp);
	}
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v28 = ss->*((word16) bp - 6);
	sp -= 2;
	ss->*sp = v28;
	v29 = ss->*((word16) bp - 8);
	sp -= 2;
	ss->*sp = v29;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v30 = Mem0[ds:0x127A:word16];
	sp -= 2;
	ss->*sp = v30;
	fn2368_01E0();
	sp = (word16) sp + 2;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x1104;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2368_022E();
	sp = (word16) sp + 6;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v31 = ss->*((word16) bp - 2);
	sp -= 2;
	ss->*sp = v31;
	v32 = ss->*((word16) bp - 4);
	sp -= 2;
	ss->*sp = v32;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	(ss->*((word16) bp - 0x0C)).u0 = 0x00;
	while (true)
	{
		ax = ss->*((word16) bp - 0x0A);
		SCZO = cond(ss->*((word16) bp - 0x0C) - ax);
		if (Test(UGE,C))
			break;
		v38 = Mem0[ds:0x1296:word16] + 0x10;
		Mem0[ds:0x1296:word16] = v38;
		es_bx = Mem0[ds:0x1296:segptr32];
		si = ss->*((word16) bp - 0x0C);
		cl = 0x04;
		si <<= cl;
		di = bx;
		si = bp - 112 + si;
		cx.u0 = 0x08;
		size = cx *32 0x02;
		memcpy(di, si, size);
		cx.u0 = 0x00;
		si += SLICE(size, word16, 0);
		di += SLICE(size, word16, 0);
		SZP = cond(es->*bx & 0x0100);
		O = false;
		C = false;
		if (Test(NE,Z))
			es->*((word16) bx + 0x0C) = 0x00;
		v47 = (word32) (ss->*((word16) bp - 0x0C)) + 1;
		ss->*((word16) bp - 0x0C) = v47;
		SZO = cond(v47);
	}
	v34 = ss->*((word16) bp - 30);
	sp -= 2;
	ss->*sp = v34;
	v35 = ss->*((word16) bp - 32);
	sp -= 2;
	ss->*sp = v35;
	fn2368_030E();
	sp = (word16) sp + 4;
	ax = ss->*((word16) bp - 0x0A);
	ax = (word16) ax + 4;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	fn21DC_00A6();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	fn21DC_0368();
	SCZO = cond(Mem0[ds:0x10D2:word16] - 101);
	if (Test(NE,Z))
	{
		ax = Mem0[ds:0x1296:word16];
		dx = Mem0[ds:0x1298:word16];
		v36 = Mem0[ds:0x1296:word16] - 0x10;
		Mem0[ds:0x1296:word16] = v36;
		SCZO = cond(v36);
		di = (<unknown>*) (bp - 28);
		si = (<unknown>*) ax;
		sp -= 2;
		ss->*sp = ss;
		es = ss->*sp;
		sp = (word16) sp + 2;
		sp -= 2;
		ss->*sp = ds;
		ds = dx;
		cx.u0 = 0x08;
		size = cx *32 0x02;
		memcpy(di, si, size);
		cx.u0 = 0x00;
		si += SLICE(size, word16, 0);
		di += SLICE(size, word16, 0);
		ds = ss->*sp;
		sp = (word16) sp + 2;
		while (true)
		{
			ax = ss->*((word16) bp - 0x0A);
			v42 = ss->*((word16) bp - 0x0A) - 0x01;
			ss->*((word16) bp - 0x0A) = v42;
			ax |= ax;
			SZ = cond(ax);
			O = false;
			C = false;
			if (Test(EQ,Z))
				break;
			fn2368_033C();
		}
		v45 = Mem0[ds:0x1296:word16] + 0x10;
		Mem0[ds:0x1296:word16] = v45;
		SCZO = cond(v45);
		es_bx = Mem0[ds:0x1296:segptr32];
		di = (<unknown>*) bx;
		si = (<unknown>*) (bp - 28);
		cx.u0 = 0x08;
		size = cx *32 0x02;
		memcpy(di, si, size);
		cx.u0 = 0x00;
		si += SLICE(size, word16, 0);
		di += SLICE(size, word16, 0);
	}
	si = (<unknown>*) (ss->*sp);
	sp = (word16) sp + 2;
	di = (<unknown>*) (ss->*sp);
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:0612: define fn20B2_0612
// Called from:
//      fn20B2_0BDC
define fn20B2_0612
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x1C;
	sp -= 2;
	ss->*sp = di;
	sp -= 2;
	ss->*sp = si;
	bx = ss->*((word16) bp + 6);
	ax = bx;
	bx <<= 0x01;
	bx += ax;
	bx <<= 0x01;
	bx <<= 0x01;
	ax = ds->*((word16) bx + 0x00002544);
	ax = (word16) ax + 12410;
	SCZO = cond(ax);
	ss->*((word16) bp - 4) = ax;
	ss->*((word16) bp - 2) = ds;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	v12 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v12;
	v13 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v13;
	ax.u0 = 0x5BC0;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn20B2_01BA();
	sp = (word16) sp + 0x0C;
	SCZO = cond(sp);
	ss->*((word16) bp - 28) = ax;
	ss->*((word16) bp - 26) = dx;
	v15 = Mem0[ds:0x10D4:word16];
	sp -= 2;
	ss->*sp = v15;
	v16 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v16;
	v17 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v17;
	fn20B2_0308();
	sp = (word16) sp + 6;
	SCZO = cond(Mem0[ds:4746:word16] - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = 22;
		dx_ax = Mem0[ds:4746:word16] *u32 ax;
		SCZO = cond(dx_ax);
		si = ax;
		es_bx = Mem0[ds:0x1282:segptr32];
		v22 = es->*((word16) si + ((word16) bx + 20));
		sp -= 2;
		ss->*sp = v22;
		v23 = es->*((word16) si + ((word16) bx + 18));
		sp -= 2;
		ss->*sp = v23;
		fn2BC7_050A();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = dx;
	}
	else
	{
		ax.u0 = 0x5BCC;
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = ds;
	}
	ax = Mem0[ds:0x1296:word16];
	dx = Mem0[ds:0x1298:word16];
	di = bp - 24;
	si = ax;
	sp -= 2;
	ss->*sp = ss;
	es = ss->*sp;
	sp = (word16) sp + 2;
	sp -= 2;
	ss->*sp = ds;
	ds = dx;
	cx = 0x08;
	size = cx *32 0x02;
	memcpy(di, si, size);
	cx = 0x00;
	si += SLICE(size, word16, 0);
	di = (<unknown>*) ((char *) di + (word16) size);
	ds = ss->*sp;
	sp = (word16) sp + 2;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v26 = ss->*((word16) bp - 6);
	sp -= 2;
	ss->*sp = v26;
	v27 = ss->*((word16) bp - 8);
	sp -= 2;
	ss->*sp = v27;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v28 = Mem0[ds:0x127A:word16];
	sp -= 2;
	ss->*sp = v28;
	fn2368_01E0();
	sp = (word16) sp + 2;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x1104;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2368_022E();
	sp = (word16) sp + 6;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v29 = ss->*((word16) bp - 2);
	sp -= 2;
	ss->*sp = v29;
	v30 = ss->*((word16) bp - 4);
	sp -= 2;
	ss->*sp = v30;
	fn2368_022E();
	sp = (word16) sp + 6;
	v31 = Mem0[ds:0x1296:word16] + 0x10;
	Mem0[ds:0x1296:word16] = v31;
	es_bx = Mem0[ds:0x1296:segptr32];
	di = (<unknown>*) bx;
	si = (<unknown>*) (bp - 24);
	cx = 0x08;
	size = cx *32 0x02;
	memcpy(di, si, size);
	cx = 0x00;
	si += SLICE(size, word16, 0);
	di += SLICE(size, word16, 0);
	SZP = cond(es->*bx & 0x0100);
	O = false;
	C = false;
	if (Test(NE,Z))
		es->*((word16) bx + 0x0C) = 0x00;
	v36 = ss->*((word16) bp - 26);
	sp -= 2;
	ss->*sp = v36;
	v37 = ss->*((word16) bp - 28);
	sp -= 2;
	ss->*sp = v37;
	fn2368_030E();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ax.u0 = 0x05;
	sp -= 2;
	ss->*sp = ax;
	fn21DC_00A6();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	fn21DC_0368();
	SCZO = cond(Mem0[ds:0x10D2:word16] - 101);
	if (Test(EQ,Z))
	{
		ax -= ax;
		SCZO = cond(ax);
		si = (<unknown>*) (ss->*sp);
		sp = (word16) sp + 2;
		di = (<unknown>*) (ss->*sp);
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
	else
	{
		ax = Mem0[ds:0x1296:word16];
		dx = Mem0[ds:0x1298:word16];
		v38 = Mem0[ds:0x1296:word16] - 0x10;
		Mem0[ds:0x1296:word16] = v38;
		SCZO = cond(v38);
		di = (<unknown>*) (bp - 24);
		si = (<unknown>*) ax;
		sp -= 2;
		ss->*sp = ss;
		es = ss->*sp;
		sp = (word16) sp + 2;
		sp -= 2;
		ss->*sp = ds;
		ds = dx;
		cx = 0x08;
		size = cx *32 0x02;
		memcpy(di, si, size);
		cx = 0x00;
		si += SLICE(size, word16, 0);
		di += SLICE(size, word16, 0);
		ds = ss->*sp;
		sp = (word16) sp + 2;
		fn2368_033C();
		v40 = Mem0[ds:0x1296:word16] + 0x10;
		Mem0[ds:0x1296:word16] = v40;
		SCZO = cond(v40);
		es_bx = Mem0[ds:0x1296:segptr32];
		di = (<unknown>*) bx;
		si = (<unknown>*) (bp - 24);
		cx = 0x08;
		size = cx *32 0x02;
		memcpy(di, si, size);
		cx = 0x00;
		ax.u0 = 0x01;
		si = (<unknown>*) (ss->*sp);
		sp = (word16) sp + 2;
		di = (<unknown>*) (ss->*sp);
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 20B2:0776: define fn20B2_0776
// Called from:
//      fn20B2_0BDC
define fn20B2_0776
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x10;
	sp -= 2;
	ss->*sp = si;
	bx = ss->*((word16) bp + 6);
	ax = bx;
	bx <<= 0x01;
	bx += ax;
	bx <<= 0x01;
	bx <<= 0x01;
	ax = ds->*((word16) bx + 0x00002544);
	ax = (word16) ax + 12410;
	SCZO = cond(ax);
	ss->*((word16) bp - 4) = ax;
	ss->*((word16) bp - 2) = ds;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	v11 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v11;
	v12 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v12;
	ax.u0 = 0x5BD6;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn20B2_01BA();
	sp = (word16) sp + 0x0C;
	SCZO = cond(sp);
	ss->*((word16) bp - 16) = ax;
	ss->*((word16) bp - 0x0E) = dx;
	v14 = Mem0[ds:0x10D4:word16];
	sp -= 2;
	ss->*sp = v14;
	v15 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v15;
	v16 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v16;
	fn20B2_0308();
	sp = (word16) sp + 6;
	SCZO = cond(Mem0[ds:4746:word16] - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = 22;
		dx_ax = Mem0[ds:4746:word16] *u32 ax;
		SCZO = cond(dx_ax);
		si = ax;
		es_bx = Mem0[ds:0x1282:segptr32];
		v21 = es->*((word16) si + ((word16) bx + 20));
		sp -= 2;
		ss->*sp = v21;
		v22 = es->*((word16) si + ((word16) bx + 18));
		sp -= 2;
		ss->*sp = v22;
		fn2BC7_050A();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = dx;
	}
	else
	{
		ax.u0 = 23522;
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = ds;
	}
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v23 = ss->*((word16) bp - 6);
	sp -= 2;
	ss->*sp = v23;
	v24 = ss->*((word16) bp - 8);
	sp -= 2;
	ss->*sp = v24;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v25 = Mem0[ds:0x127A:word16];
	sp -= 2;
	ss->*sp = v25;
	fn2368_01E0();
	sp = (word16) sp + 2;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x1104;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2368_022E();
	sp = (word16) sp + 6;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v26 = ss->*((word16) bp - 2);
	sp -= 2;
	ss->*sp = v26;
	v27 = ss->*((word16) bp - 4);
	sp -= 2;
	ss->*sp = v27;
	fn2368_022E();
	sp = (word16) sp + 6;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 9118;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v28 = ss->*((word16) bp - 0x0E);
	sp -= 2;
	ss->*sp = v28;
	v29 = ss->*((word16) bp - 16);
	sp -= 2;
	ss->*sp = v29;
	fn2368_030E();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ax.u0 = 0x05;
	sp -= 2;
	ss->*sp = ax;
	fn21DC_00A6();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	fn21DC_0368();
	SCZO = cond(Mem0[ds:0x10D2:word16] - 101);
	if (Test(NE,Z))
	{
		es_bx = Mem0[ds:0x1296:segptr32];
		SZP = cond(es->*bx & 0x80);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			ax = es->*((word16) bx + 8);
			ss->*((word16) bp - 0x0A) = ax;
		}
		else
			(ss->*((word16) bp - 0x0A)).u0 = 0x01;
		fn2368_033C();
	}
	else
		(ss->*((word16) bp - 0x0A)).u0 = 0x00;
	ax = ss->*((word16) bp - 0x0A);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:0898: define fn20B2_0898
// Called from:
//      fn20B2_0BDC
define fn20B2_0898
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x10;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	ax.u0 = 23532;
	ss->*((word16) bp - 4) = ax;
	ss->*((word16) bp - 2) = ds;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	v10 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v10;
	v11 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v11;
	ax.u0 = 0x5BEE;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn20B2_01BA();
	sp = (word16) sp + 0x0C;
	SCZO = cond(sp);
	ss->*((word16) bp - 16) = ax;
	ss->*((word16) bp - 0x0E) = dx;
	v13 = Mem0[ds:0x10D4:word16];
	sp -= 2;
	ss->*sp = v13;
	v14 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v14;
	v15 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v15;
	fn20B2_0308();
	sp = (word16) sp + 6;
	SCZO = cond(Mem0[ds:4746:word16] - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = 22;
		dx_ax = Mem0[ds:4746:word16] *u32 ax;
		SCZO = cond(dx_ax);
		si = ax;
		es_bx = Mem0[ds:0x1282:segptr32];
		v21 = Mem0[es:bx + 20 + si:word16];
		sp -= 2;
		ss->*sp = v21;
		v22 = Mem0[es:bx + 18 + si:word16];
		sp -= 2;
		ss->*sp = v22;
		fn2BC7_050A();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = dx;
	}
	else
	{
		ax.u0 = 23544;
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = ds;
	}
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v23 = ss->*((word16) bp - 6);
	sp -= 2;
	ss->*sp = v23;
	v24 = ss->*((word16) bp - 8);
	sp -= 2;
	ss->*sp = v24;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v25 = Mem0[ds:0x127A:word16];
	sp -= 2;
	ss->*sp = v25;
	fn2368_01E0();
	sp = (word16) sp + 2;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x1104;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2368_022E();
	sp = (word16) sp + 6;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v26 = ss->*((word16) bp - 2);
	sp -= 2;
	ss->*sp = v26;
	v27 = ss->*((word16) bp - 4);
	sp -= 2;
	ss->*sp = v27;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v28 = ss->*((word16) bp - 0x0E);
	sp -= 2;
	ss->*sp = v28;
	v29 = ss->*((word16) bp - 16);
	sp -= 2;
	ss->*sp = v29;
	fn2368_030E();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ax.u0 = 0x04;
	sp -= 2;
	ss->*sp = ax;
	fn21DC_00A6();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	fn21DC_0368();
	SCZO = cond(Mem0[ds:0x10D2:word16] - 101);
	if (Test(NE,Z))
	{
		es_bx = Mem0[ds:0x1296:segptr32];
		SZP = cond((es->*bx).b0000 & 0x80);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			ax.u0 = (es->*bx).t0008.u0;
			ss->*((word16) bp - 0x0A) = ax;
		}
		else
			(ss->*((word16) bp - 0x0A)).u0 = 0x01;
		fn2368_033C();
	}
	else
		(ss->*((word16) bp - 0x0A)).u0 = 0x00;
	ax = ss->*((word16) bp - 0x0A);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:099A: define fn20B2_099A
// Called from:
//      fn20B2_0BDC
define fn20B2_099A
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 22;
	sp -= 2;
	ss->*sp = si;
	ax.u0 = 0x5C02;
	ss->*((word16) bp - 6) = ax;
	ss->*((word16) bp - 4) = ds;
	SCZO = cond(Mem0[ds:4322:byte] - 0x00);
	if (Test(EQ,Z))
		fn20B2_01FC();
	v11 = ss->*((word16) bp - 4);
	sp -= 2;
	ss->*sp = v11;
	v12 = ss->*((word16) bp - 6);
	sp -= 2;
	ss->*sp = v12;
	v13 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v13;
	v14 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v14;
	ax.u0 = 0x5C06;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn20B2_01BA();
	sp = (word16) sp + 0x0C;
	SCZO = cond(sp);
	ss->*((word16) bp - 22) = ax;
	ss->*((word16) bp - 20) = dx;
	v16 = Mem0[ds:0x10D4:word16];
	sp -= 2;
	ss->*sp = v16;
	v17 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v17;
	v18 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v18;
	fn20B2_0308();
	sp = (word16) sp + 6;
	SCZO = cond(Mem0[ds:4746:word16] - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = 22;
		dx_ax = Mem0[ds:4746:word16] *u32 ax;
		SCZO = cond(dx_ax);
		si = ax;
		es_bx = Mem0[ds:0x1282:segptr32];
		v23 = Mem0[es:bx + 20 + si:word16];
		sp -= 2;
		ss->*sp = v23;
		v24 = Mem0[es:bx + 18 + si:word16];
		sp -= 2;
		ss->*sp = v24;
		fn2BC7_050A();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		ss->*((word16) bp - 0x0A) = ax;
		ss->*((word16) bp - 8) = dx;
	}
	else
	{
		ax.u0 = 0x5C12;
		ss->*((word16) bp - 0x0A) = ax;
		ss->*((word16) bp - 8) = ds;
	}
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v25 = ss->*((word16) bp - 8);
	sp -= 2;
	ss->*sp = v25;
	v26 = ss->*((word16) bp - 0x0A);
	sp -= 2;
	ss->*sp = v26;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v27 = Mem0[ds:0x127A:word16];
	sp -= 2;
	ss->*sp = v27;
	fn2368_01E0();
	sp = (word16) sp + 2;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x1104;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2368_022E();
	sp = (word16) sp + 6;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v28 = ss->*((word16) bp - 4);
	sp -= 2;
	ss->*sp = v28;
	v29 = ss->*((word16) bp - 6);
	sp -= 2;
	ss->*sp = v29;
	fn2368_022E();
	sp = (word16) sp + 6;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 4322;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v30 = ss->*((word16) bp - 20);
	sp -= 2;
	ss->*sp = v30;
	v31 = ss->*((word16) bp - 22);
	sp -= 2;
	ss->*sp = v31;
	fn2368_030E();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ax.u0 = 0x05;
	sp -= 2;
	ss->*sp = ax;
	fn21DC_00A6();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	fn21DC_0368();
	SCZO = cond(Mem0[ds:0x10D2:word16] - 101);
	if (Test(NE,Z))
	{
		es_bx = Mem0[ds:0x1296:segptr32];
		SZP = cond((es->*bx).b0000 & 0x80);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			ax.u0 = (es->*bx).t0008.u0;
			ss->*((word16) bp - 0x0C) = ax;
		}
		else
			(ss->*((word16) bp - 0x0C)).u0 = 0x01;
		fn2368_033C();
		SCZO = cond(ss->*((word16) bp - 0x0C) - 0x00);
		if (Test(EQ,Z))
			fn21DC_04BA();
	}
	else
		(ss->*((word16) bp - 0x0C)).u0 = 0x00;
	ax = ss->*((word16) bp - 0x0C);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:0AC6: define fn20B2_0AC6
// Called from:
//      fn20B2_0BDC
define fn20B2_0AC6
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x0E;
	sp -= 2;
	ss->*sp = si;
	bx = ss->*((word16) bp + 6);
	ax = bx;
	bx <<= 0x01;
	bx += ax;
	bx <<= 0x01;
	bx <<= 0x01;
	ax = ds->*((word16) bx + 0x00002544);
	ax = (word16) ax + 12410;
	SCZO = cond(ax);
	ss->*((word16) bp - 4) = ax;
	ss->*((word16) bp - 2) = ds;
	ax.u0 = 0x5C1C;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	v11 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v11;
	v12 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v12;
	ax.u0 = 23582;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn20B2_01BA();
	sp = (word16) sp + 0x0C;
	SCZO = cond(sp);
	ss->*((word16) bp - 0x0E) = ax;
	ss->*((word16) bp - 0x0C) = dx;
	v14 = Mem0[ds:0x10D4:word16];
	sp -= 2;
	ss->*sp = v14;
	v15 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v15;
	v16 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v16;
	fn20B2_0308();
	sp = (word16) sp + 6;
	SCZO = cond(Mem0[ds:4746:word16] - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = 22;
		dx_ax = Mem0[ds:4746:word16] *u32 ax;
		SCZO = cond(dx_ax);
		si = ax;
		es_bx = Mem0[ds:0x1282:segptr32];
		v21 = es->*((word16) si + ((word16) bx + 20));
		sp -= 2;
		ss->*sp = v21;
		v22 = es->*((word16) si + ((word16) bx + 18));
		sp -= 2;
		ss->*sp = v22;
		fn2BC7_050A();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = dx;
	}
	else
	{
		ax.u0 = 0x5C2A;
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = ds;
	}
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v23 = ss->*((word16) bp - 6);
	sp -= 2;
	ss->*sp = v23;
	v24 = ss->*((word16) bp - 8);
	sp -= 2;
	ss->*sp = v24;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v25 = Mem0[ds:0x127A:word16];
	sp -= 2;
	ss->*sp = v25;
	fn2368_01E0();
	sp = (word16) sp + 2;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x1104;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2368_022E();
	sp = (word16) sp + 6;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v26 = ss->*((word16) bp - 2);
	sp -= 2;
	ss->*sp = v26;
	v27 = ss->*((word16) bp - 4);
	sp -= 2;
	ss->*sp = v27;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v28 = ss->*((word16) bp - 0x0C);
	sp -= 2;
	ss->*sp = v28;
	v29 = ss->*((word16) bp - 0x0E);
	sp -= 2;
	ss->*sp = v29;
	fn2368_030E();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ax.u0 = 0x04;
	sp -= 2;
	ss->*sp = ax;
	fn21DC_00A6();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	fn21DC_0368();
	SCZO = cond(Mem0[ds:0x10D2:word16] - 101);
	if (Test(NE,Z))
	{
		es_bx = Mem0[ds:0x1296:segptr32];
		SZP = cond(es->*bx & 0x80);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			ax = es->*((word16) bx + 8);
			ss->*((word16) bp - 0x0A) = ax;
		}
		else
			(ss->*((word16) bp - 0x0A)).u0 = 0x01;
		fn2368_033C();
	}
	else
		(ss->*((word16) bp - 0x0A)).u0 = 0x00;
	ax = ss->*((word16) bp - 0x0A);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:0BDC: define fn20B2_0BDC
// Called from:
//      fn3BC2_0000
//      fn3BC2_009D
define fn20B2_0BDC
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x12;
	SCZO = cond(Mem0[ds:0x1278:word16] - 0x00);
	if (Test(NE,Z))
		fn21DC_04BA();
	SCZO = cond(Mem0[ds:0x1102:word16] - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = 0x5C34;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		fn20B2_0140();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
	}
	(ss->*((word16) bp - 0x0A)).u0 = 0x00;
	ax = Mem0[ds:0x10D2:word16];
	Mem0[ds:0x1102:word16] = ax;
	Mem0[ds:0x10D2:word16] = 0x00;
	ax = Mem0[ds:0x21A2:word16];
	ss->*((word16) bp - 2) = ax;
	Mem0[ds:0x21A2:word16] = 0x00;
	ax = Mem0[ds:0x21A4:word16];
	ss->*((word16) bp - 4) = ax;
	Mem0[ds:0x21A4:word16] = 0x00;
	ax = Mem0[ds:0x10D4:word16];
	ss->*((word16) bp - 0x0E) = ax;
	ax = Mem0[ds:0x10D6:word16];
	v10 = Mem0[ds:0x10D4:word16] | ax;
	Mem0[ds:0x10D4:word16] = v10;
	SZ = cond(Mem0[ds:0x10D4:word16]);
	ss->*((word16) bp - 18) = 0x00;
	ss->*((word16) bp - 16) = 0x00;
	ax = Mem0[ds:0x1102:word16];
	--ax;
	v17 = ax;
	SCZO = cond(ax - 0x17);
	if (Test(UGT,CZ))
	{
l20B2_0E02:
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		fn20B2_0176();
l20B2_0CA3:
		sp = (word16) sp + 2;
		SCZO = cond(sp);
	}
	else
	{
		ax += ax;
		SCZO = cond(ax);
		v15 = bx;
		bx = ax;
		ax = v15;
		switch (v17)
		{
		case 0x00:
			ax.u0 = 0x5C70;
			ss->*((word16) bp - 8) = ax;
			ss->*((word16) bp - 6) = ds;
			bx = ss->*((word16) bp + 6);
			ax = bx;
			bx <<= 0x01;
			bx += ax;
			bx <<= 0x01;
			bx <<= 0x01;
			SCZO = cond(ds->*((word16) bx + 9533) - 0x01);
			if (Test(NE,Z))
				goto l20B2_0CC7;
			goto l20B2_0CF9;
		case 0x01:
			ax.u0 = 23720;
			goto l20B2_0D59;
		case 0x02:
			ax.u0 = 0x5CD4;
l20B2_0D59:
			ss->*((word16) bp - 8) = ax;
			ss->*((word16) bp - 6) = ds;
			sp -= 2;
			ss->*sp = ds;
			sp -= 2;
			ss->*sp = ax;
			v18 = ss->*((word16) bp + 6);
			sp -= 2;
			ss->*sp = v18;
			fn20B2_099A();
			goto l20B2_0C6A;
		case 0x03:
			ax.u0 = 23782;
			ss->*((word16) bp - 8) = ax;
			ss->*((word16) bp - 6) = ds;
			ss->*((word16) bp - 18) = 0x01;
			goto l20B2_0E3C;
		case 0x04:
			ax.u0 = 0x5C9C;
			ss->*((word16) bp - 8) = ax;
			ss->*((word16) bp - 6) = ds;
			sp -= 2;
			ss->*sp = ds;
			sp -= 2;
			ss->*sp = ax;
			v38 = ss->*((word16) bp + 6);
			sp -= 2;
			ss->*sp = v38;
			fn20B2_0776();
			sp = (word16) sp + 6;
			ss->*((word16) bp - 0x0A) = ax;
			ax |= ax;
			SZ = cond(ax);
			O = false;
			C = false;
			if (Test(EQ,Z))
			{
				bx = ss->*((word16) bp + 6);
				ax = bx;
				bx <<= 0x01;
				bx += ax;
				bx <<= 0x01;
				bx <<= 0x01;
				al = (byte) (ds->*((word16) bx + 9532));
				ah -= ah;
				SCZO = cond(ah);
				ss->*((word16) bp - 0x0C) = ax;
				while (true)
				{
					ax = ss->*((word16) bp - 0x0C);
					v41 = ss->*((word16) bp - 0x0C) - 0x01;
					ss->*((word16) bp - 0x0C) = v41;
					ax |= ax;
					SZ = cond(ax);
					O = false;
					C = false;
					if (Test(EQ,Z))
						break;
					fn2368_033C();
				}
			}
			goto l20B2_0E3C;
		case 0x05:
			ax.u0 = 0x5C7E;
			ss->*((word16) bp - 8) = ax;
			ss->*((word16) bp - 6) = ds;
			goto l20B2_0CF9;
		case 0x06:
			ax.u0 = 23742;
			ss->*((word16) bp - 8) = ax;
			ss->*((word16) bp - 6) = ds;
			v31 = Mem0[ds:0x10DC:word16];
			sp -= 2;
			ss->*sp = v31;
			v32 = Mem0[ds:4314:word16];
			sp -= 2;
			ss->*sp = v32;
			fn2368_030E();
			sp = (word16) sp + 4;
			SCZO = cond(sp);
			v33 = ss->*((word16) bp - 6);
			sp -= 2;
			ss->*sp = v33;
			v34 = ss->*((word16) bp - 8);
			sp -= 2;
			ss->*sp = v34;
			v35 = ss->*((word16) bp + 6);
			sp -= 2;
			ss->*sp = v35;
			fn20B2_099A();
			sp = (word16) sp + 6;
			ss->*((word16) bp - 0x0A) = ax;
			v36 = Mem0[ds:0x1296:word16] - 0x10;
			Mem0[ds:0x1296:word16] = v36;
			SCZO = cond(v36);
			goto l20B2_0E3C;
		case 0x07:
		case 0x0A:
		case 11:
			goto l20B2_0E02;
		case 0x08:
		case 0x09:
			ax.u0 = 0x5C8A;
			ss->*((word16) bp - 8) = ax;
			ss->*((word16) bp - 6) = ds;
			bx = ss->*((word16) bp + 6);
			ax = bx;
			bx <<= 0x01;
			bx += ax;
			bx <<= 0x01;
			bx <<= 0x01;
			SCZO = cond(ds->*((word16) bx + 9533) - 0x01);
			if (Test(NE,Z))
				goto l20B2_0CC7;
l20B2_0CF9:
			v19 = ss->*((word16) bp - 6);
			sp -= 2;
			ss->*sp = v19;
			v20 = ss->*((word16) bp - 8);
			sp -= 2;
			ss->*sp = v20;
			v21 = ss->*((word16) bp + 6);
			sp -= 2;
			ss->*sp = v21;
			fn20B2_0474();
			sp = (word16) sp + 6;
			SCZO = cond(sp);
			goto l20B2_0E3C;
		case 0x0C:
			ax.u0 = 0x5C44;
			goto l20B2_0C5B;
		case 0x0D:
			ax.u0 = 0x5C52;
l20B2_0C5B:
			ss->*((word16) bp - 8) = ax;
			ss->*((word16) bp - 6) = ds;
			sp -= 2;
			ss->*sp = ds;
			sp -= 2;
			ss->*sp = ax;
			v37 = ss->*((word16) bp + 6);
			sp -= 2;
			ss->*sp = v37;
			fn20B2_0612();
l20B2_0C6A:
			sp = (word16) sp + 6;
			SCZO = cond(sp);
			ss->*((word16) bp - 0x0A) = ax;
			goto l20B2_0E3C;
		case 0x0E:
			ax.u0 = 0x5C62;
			ss->*((word16) bp - 8) = ax;
			ss->*((word16) bp - 6) = ds;
			fn2368_033C();
			v25 = ss->*((word16) bp - 6);
			sp -= 2;
			ss->*sp = v25;
			v26 = ss->*((word16) bp - 8);
			sp -= 2;
			ss->*sp = v26;
			v27 = ss->*((word16) bp + 6);
			sp -= 2;
			ss->*sp = v27;
			fn20B2_099A();
			sp = (word16) sp + 6;
			ss->*((word16) bp - 0x0A) = ax;
			ax -= ax;
			SCZO = cond(ax);
			sp -= 2;
			ss->*sp = ax;
			fn2368_01E0();
			goto l20B2_0CA3;
		case 0x0F:
			ax.u0 = 0x5CF4;
			ss->*((word16) bp - 8) = ax;
			ss->*((word16) bp - 6) = ds;
l20B2_0CC7:
			ss->*((word16) bp - 16) = 0x01;
			goto l20B2_0E3C;
		case 0x10:
		case 0x13:
		case 0x14:
			ax.u0 = 0x5CFE;
			break;
		case 0x11:
		case 0x15:
			ax.u0 = 0x5D10;
			break;
		case 0x12:
			ax.u0 = 23838;
			break;
		case 22:
			ax.u0 = 23858;
			break;
		case 0x17:
			ax.u0 = 23882;
			break;
		}
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = ds;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		v22 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v22;
		fn20B2_0898();
		sp = (word16) sp + 6;
		ss->*((word16) bp - 0x0A) = ax;
		SCZO = cond(Mem0[ds:0x10D2:word16] - 101);
		if (Test(NE,Z))
			fn21DC_04BA();
	}
l20B2_0E3C:
	SCZO = cond(ss->*((word16) bp - 18) - 0x00);
	if (Test(NE,Z))
	{
		v23 = ss->*((word16) bp - 6);
		sp -= 2;
		ss->*sp = v23;
		v24 = ss->*((word16) bp - 8);
		sp -= 2;
		ss->*sp = v24;
		fn20B2_0140();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
	}
	else
	{
		SCZO = cond(ss->*((word16) bp - 16) - 0x00);
		if (Test(NE,Z))
		{
			v28 = ss->*((word16) bp - 6);
			sp -= 2;
			ss->*sp = v28;
			v29 = ss->*((word16) bp - 8);
			sp -= 2;
			ss->*sp = v29;
			v30 = ss->*((word16) bp + 6);
			sp -= 2;
			ss->*sp = v30;
			fn20B2_0AC6();
			sp = (word16) sp + 6;
			SCZO = cond(Mem0[ds:0x10D2:word16] - 101);
			if (Test(NE,Z))
				fn21DC_04BA();
		}
	}
	Mem0[ds:0x1102:word16] = 0x00;
	ax = ss->*((word16) bp - 0x0E);
	Mem0[ds:0x10D4:word16] = ax;
	Mem0[ds:0x10D6:word16] = 0x00;
	Mem0[ds:4322:byte] = 0x00;
	ax = ss->*((word16) bp - 2);
	Mem0[ds:0x21A2:word16] = ax;
	ax = ss->*((word16) bp - 4);
	Mem0[ds:0x21A4:word16] = ax;
	ax = ss->*((word16) bp - 0x0A);
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:0E9E: define fn20B2_0E9E
// Called from:
//      fn2068_0154
//      fn21DC_0588
//      fn21DC_05EA
//      fn2C27_0292
define fn20B2_0E9E
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x20;
	SCZO = cond(Mem0[ds:0x1278:word16] - 0x00);
	if (Test(NE,Z))
		fn21DC_04BA();
	ax.u0 = 0x0E;
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x5D60;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	ax = bp - 32;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	fn2017_02EC();
	sp = (word16) sp + 0x0A;
	SCZO = cond(sp);
	v10 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v10;
	v11 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v11;
	fn2017_03F5();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ax = (char *) ax.u0 + 1;
	SZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v13 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v13;
	v14 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v14;
	ax = bp - 18;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	fn2017_02EC();
	sp = (word16) sp + 0x0A;
	SCZO = cond(sp);
	ax = bp - 32;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	fn20B2_0140();
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:0EF6: define fn20B2_0EF6
// Called from:
//      fn3431_0214
define fn20B2_0EF6
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x0E;
	sp -= 2;
	ss->*sp = si;
	SCZO = cond(Mem0[ds:0x1278:word16] - 0x00);
	if (Test(NE,Z))
		fn21DC_04BA();
	SCZO = cond(Mem0[ds:0x1102:word16] - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = 0x5D70;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		fn20B2_0140();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
	}
	ax = Mem0[ds:0x10D2:word16];
	Mem0[ds:0x1102:word16] = ax;
	Mem0[ds:0x10D2:word16] = 0x00;
	ax = Mem0[ds:0x21A2:word16];
	ss->*((word16) bp - 2) = ax;
	Mem0[ds:0x21A2:word16] = 0x00;
	ax = Mem0[ds:0x21A4:word16];
	ss->*((word16) bp - 4) = ax;
	Mem0[ds:0x21A4:word16] = 0x00;
	ax.u0 = 0x5D80;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 23938;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x5D90;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn20B2_01BA();
	sp = (word16) sp + 0x0C;
	ss->*((word16) bp - 0x0E) = ax;
	ss->*((word16) bp - 0x0C) = dx;
	SCZO = cond(Mem0[ds:4746:word16] - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = 22;
		dx_ax = Mem0[ds:4746:word16] *u32 ax;
		SCZO = cond(dx_ax);
		si = ax;
		es_bx = Mem0[ds:0x1282:segptr32];
		v16 = Mem0[es:bx + 20 + si:word16];
		sp -= 2;
		ss->*sp = v16;
		v17 = Mem0[es:bx + 18 + si:word16];
		sp -= 2;
		ss->*sp = v17;
		fn2BC7_050A();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = dx;
	}
	else
	{
		ax.u0 = 0x5D9C;
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = ds;
	}
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v18 = ss->*((word16) bp - 6);
	sp -= 2;
	ss->*sp = v18;
	v19 = ss->*((word16) bp - 8);
	sp -= 2;
	ss->*sp = v19;
	fn2368_022E();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v20 = Mem0[ds:0x127A:word16];
	sp -= 2;
	ss->*sp = v20;
	fn2368_01E0();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	v21 = ss->*((word16) bp - 0x0C);
	sp -= 2;
	ss->*sp = v21;
	v22 = ss->*((word16) bp - 0x0E);
	sp -= 2;
	ss->*sp = v22;
	fn2368_030E();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ax.u0 = 0x02;
	sp -= 2;
	ss->*sp = ax;
	fn21DC_00A6();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	fn21DC_0368();
	SCZO = cond(Mem0[ds:0x10D2:word16] - 101);
	if (Test(NE,Z))
	{
		es_bx = Mem0[ds:0x1296:segptr32];
		SZP = cond((es->*bx).b0000 & 0x80);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			ax.u0 = (es->*bx).t0008.u0;
			ss->*((word16) bp - 0x0A) = ax;
		}
		else
			(ss->*((word16) bp - 0x0A)).u0 = 0x01;
		fn2368_033C();
	}
	else
		(ss->*((word16) bp - 0x0A)).u0 = 0x00;
	Mem0[ds:0x1102:word16] = 0x00;
	ax = ss->*((word16) bp - 2);
	Mem0[ds:0x21A2:word16] = ax;
	ax = ss->*((word16) bp - 4);
	Mem0[ds:0x21A4:word16] = ax;
	ax = ss->*((word16) bp - 0x0A);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:1014: define fn20B2_1014
// Called from:
//      fn20B2_0140
//      fn20B2_107C
//      fn20B2_10AC
define fn20B2_1014
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x02;
	ax.u0 = 0x3D;
	sp -= 2;
	ss->*sp = ax;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	fn1F38_04E7();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ax.u0 = 0x0C;
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x5DA6;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn1F38_049F();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	fn1F38_0CC5();
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x08;
	sp -= 2;
	ss->*sp = ax;
	fn3431_07B6();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ss->*((word16) bp - 2) = ax;
	fn20B2_0118();
	SCZO = cond(ss->*((word16) bp - 2) - 0x02);
	if (Test(EQ,Z))
	{
		al = Mem0[ds:3863:byte];
		ah -= ah;
		SCZO = cond(ah);
		sp -= 2;
		ss->*sp = ax;
		fn38AD_0040();
		sp = (word16) sp + 2;
		SZP = cond(al & 0x08);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			ax.u0 = 0x01;
			sp = bp;
			bp = ss->*sp;
			sp = (word16) sp + 2;
			return;
		}
	}
	ax -= ax;
	SCZO = cond(ax);
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:107C: define fn20B2_107C
// Called from:
//      fn21DC_0006
define fn20B2_107C
{
	sp = fp;
	Top = 0;
	SCZO = cond(ds->w1278 - 0x00);
	if (Test(NE,Z))
		fn21DC_04BA();
	fn20B2_005C();
	ax = 0x09;
	sp -= 2;
	ss->*sp = (struct Eq_55782 * Eq_55797::*) ax;
	ax = 23992;
	sp -= 2;
	ss->*sp = (struct Eq_55782 * Eq_55797::*) ds;
	sp -= 2;
	ss->*sp = (struct Eq_55782 * Eq_55797::*) ax;
	fn1F38_049F();
	sp = (struct Eq_55782 * Eq_55797::*) ((char *) sp + 6);
	SCZO = cond(sp);
	fn20B2_1014();
	ax |= ax;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(EQ,Z))
		fn21DC_04BA();
}

// 20B2:10AC: define fn20B2_10AC
// Called from:
//      fn2644_21CA
//      fn2B41_0052
//      fn2D1A_003C
//      fn2D1A_064E
define fn20B2_10AC
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	SCZO = cond(ds->w1278 - 0x00);
	if (Test(NE,Z))
		fn21DC_04BA();
	fn20B2_005C();
	v9 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v9;
	v10 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v10;
	fn2017_03F5();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = ax;
	v12 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v12;
	v13 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v13;
	fn1F38_049F();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	fn20B2_1014();
	ax |= ax;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(EQ,Z))
		fn21DC_04BA();
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 20B2:1176: define fn20B2_1176
// Called from:
//      fn20B2_1192
define fn20B2_1176
{
	selector ds;
	<unknown> Mem0;
	ax_6 = ds->t3CE4;
	ax_7 = ax_6 | ds->w3CE6;
	if (ax_7 != 0x00)
		ds->t3CE4();
	ax_18 = ds->t3E10;
	ax_19 = ax_18 | ds->w3E12;
	SZ_20 = cond(ax_19);
	Z_23 = SLICE(SZ_20, bool, 2);
	S_36 = (bool) SZ_20;
	O_21 = false;
	C_22 = false;
	if (ax_19 != 0x00)
	{
		ds->t3E10();
		C_32 = SLICE(SCZO_29, bool, 1);
		O_34 = SLICE(SCZO_29, bool, 4);
		S_37 = (bool) SCZO_29;
		Z_41 = SLICE(SCZO_29, bool, 2);
	}
	Z_40 = ϕ(Z_23, Z_41);
	Top_39 = 0;
	S_35 = ϕ(S_36, S_37);
	O_33 = ϕ(O_21, O_34);
	C_31 = ϕ(C_22, C_32);
	ax_30 = ϕ(ax_19, ax_27);
}

// 20B2:1192: define fn20B2_1192
// Called from:
//      fn3BC2_0000
//      fn3BC2_009D
define fn20B2_1192
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x14;
	sp -= 2;
	ss->*sp = di;
	sp -= 2;
	ss->*sp = si;
	ax.u0 = 0x12;
	dx_ax = ds->w1266 *32 ax;
	bx = ax;
	di = bp - 20;
	si = (word16) bx + 4422;
	sp -= 2;
	ss->*sp = ss;
	es = ss->*sp;
	sp = (word16) sp + 2;
	cx = 0x09;
	size = cx *32 0x02;
	memcpy(di, si, size);
	cx = 0x00;
	si = (<unknown>*) ((char *) si + (word16) size);
	di = (<unknown>*) ((char *) di + (word16) size);
	ax = ss->*((word16) bp + 6);
	SCZO = cond(ss->*((word16) bp - 20) - ax);
	if (Test(NE,Z))
	{
		ax = ss->*((word16) bp + 6);
		SCZO = cond(ss->*((word16) bp - 20) - ax);
		if (Test(ULT,C))
			fn21DC_04BA();
		(ss->*((word16) bp - 2)).u0 = 0x00;
	}
	else
	{
		ax = ds->t1296;
		dx = ds->w1298;
		SCZO = cond(ss->*((word16) bp - 16) - ax);
		if (Test(ULE,CZ))
		{
			while (true)
			{
				ax = ds->t1296;
				dx = ds->w1298;
				SCZO = cond(ss->*((word16) bp - 16) - ax);
				if (Test(UGE,C))
					break;
				fn2368_033C();
			}
		}
		else
		{
			ax.u0 = 0x0C;
			sp -= 2;
			ss->*sp = ax;
			fn20B2_0176();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
		}
		fn20B2_1176();
		ax.u0 = 0x12;
		dx_ax = ds->w1266 *32 ax;
		SCZO = cond(dx_ax);
		bx = ax;
		v20 = ds->*((word16) bx + 4438);
		sp -= 2;
		ss->*sp = v20;
		fn2D1A_11C0();
		sp = (word16) sp + 2;
		ax.u0 = 0x12;
		dx_ax = ds->w1266 *32 ax;
		SCZO = cond(dx_ax);
		bx = ax;
		v21 = ds->*((word16) bx + 4438);
		sp -= 2;
		ss->*sp = v21;
		fn2644_4A66();
		sp = (word16) sp + 2;
		ax = ss->*((word16) bp - 0x0C);
		ds->t10D4 = ax;
		ax.u0 = 0x12;
		dx_ax = ds->w1266 *32 ax;
		bx = ax;
		ax = ds->t21A6;
		SCZO = cond(ds->*((word16) bx + 4436) - ax);
		if (Test(NE,Z))
		{
			sp -= 2;
			ss->*sp = ax;
			fn208F_00AE();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
		}
		ax.u0 = 0x12;
		dx_ax = ds->w1266 *32 ax;
		SCZO = cond(dx_ax);
		si = (<unknown>*) ax;
		ax = ds->*((char *) si + 4432);
		ds->t21A2 = ax;
		ax = ds->*((char *) si + 4434);
		ds->t21A4 = ax;
		ax = ds->*((char *) si + 4436);
		ds->t21A6 = ax;
		ds->w10D6 = 0x00;
		ds->w10D2 = 0x00;
		ds->w1102 = 0x00;
		ax = ss->*((word16) bp - 18);
		ss->*((word16) bp - 2) = ax;
		v22 = ds->w1266 - 0x01;
		ds->w1266 = v22;
		SZO = cond(v22);
	}
	ax = ss->*((word16) bp - 2);
	si = (<unknown>*) (ss->*sp);
	sp = (word16) sp + 2;
	di = (<unknown>*) (ss->*sp);
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

