// 1999_SOFT_LOAN__31FF.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 31FF:0008: define fn31FF_0008
// Called from:
//      fn21DC_0EC2
define fn31FF_0008
{
	sp = fp;
	Top = 0;
	ds->w1A4A = 0x40;
	ds->ptr1A4C = 0x0200;
	ds->w1A28 = 0x00;
	ds->ptr1A26 = 0x0100;
	v5 = ds->ptr1A4C;
	sp -= 2;
	ss->*sp = (struct Eq_99099 * Eq_99121::*) v5;
	ax = 6726;
	sp -= 2;
	ss->*sp = (struct Eq_99099 * Eq_99121::*) ds;
	sp -= 2;
	ss->*sp = (struct Eq_99099 * Eq_99121::*) ax;
	fn21DC_06DC();
	sp = (struct Eq_99099 * Eq_99121::*) ((char *) sp + 6);
	ax |= ax;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		v13 = ds->ptr1A4C;
		sp -= 2;
		ss->*sp = (struct Eq_99099 * Eq_99121::*) v13;
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = (struct Eq_99099 * Eq_99121::*) ax;
		v14 = ds->ptr1A48;
		sp -= 2;
		ss->*sp = (struct Eq_99099 * Eq_99121::*) v14;
		v15 = ds->ptr1A46;
		sp -= 2;
		ss->*sp = (struct Eq_99099 * Eq_99121::*) v15;
		fn2017_0228();
		sp = (struct Eq_99099 * Eq_99121::*) ((char *) sp + 8);
		SCZO = cond(sp);
		v16 = ds->ptr1A26;
		sp -= 2;
		ss->*sp = (struct Eq_99099 * Eq_99121::*) v16;
		ax = 0x1A22;
		sp -= 2;
		ss->*sp = (struct Eq_99099 * Eq_99121::*) ds;
		sp -= 2;
		ss->*sp = (struct Eq_99099 * Eq_99121::*) ax;
		fn21DC_06DC();
		sp = (struct Eq_99099 * Eq_99121::*) ((char *) sp + 6);
		ax |= ax;
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			ax = 0x01;
			return;
		}
	}
	ax -= ax;
	SCZO = cond(ax);
}

// 31FF:006A: define fn31FF_006A
// Called from:
//      fn31FF_0F20
define fn31FF_006A
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x04;
	SCZO = cond(sp);
	(ss->*((word16) bp - 2)).u0 = 0x00;
	v7 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v7;
	v8 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v8;
	fn2017_03F5();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ss->*((word16) bp - 4) = ax;
	sp -= 2;
	ss->*sp = ax;
	v10 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v10;
	v11 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v11;
	ax.u0 = 4322;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2017_02EC();
	sp = (word16) sp + 0x0A;
	ax = ss->*((word16) bp - 4);
	v13 = Mem0[ss:bp + -2:word16] + ax;
	ss->*((word16) bp - 2) = v13;
	SCZO = cond(v13);
	v14 = ss->*((word16) bp + 0x0C);
	sp -= 2;
	ss->*sp = v14;
	v15 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v15;
	fn2017_03F5();
	sp = (word16) sp + 4;
	ss->*((word16) bp - 4) = ax;
	sp -= 2;
	ss->*sp = ax;
	v16 = ss->*((word16) bp + 0x0C);
	sp -= 2;
	ss->*sp = v16;
	v17 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v17;
	ax = ss->*((word16) bp - 2);
	ax = (char *) ax.u0 + 4322;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2017_02EC();
	sp = (word16) sp + 0x0A;
	ax = ss->*((word16) bp - 4);
	v18 = Mem0[ss:bp + -2:word16] + ax;
	ss->*((word16) bp - 2) = v18;
	SCZO = cond(v18);
	v19 = ss->*((word16) bp + 16);
	sp -= 2;
	ss->*sp = v19;
	v20 = ss->*((word16) bp + 0x0E);
	sp -= 2;
	ss->*sp = v20;
	fn2017_03F5();
	sp = (word16) sp + 4;
	ss->*((word16) bp - 4) = ax;
	sp -= 2;
	ss->*sp = ax;
	v21 = ss->*((word16) bp + 16);
	sp -= 2;
	ss->*sp = v21;
	v22 = ss->*((word16) bp + 0x0E);
	sp -= 2;
	ss->*sp = v22;
	ax = ss->*((word16) bp - 2);
	ax = (word16) ax + 4322;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2017_02EC();
	ax = ss->*((word16) bp - 4);
	v23 = Mem0[ss:bp + -2:word16] + ax;
	ss->*((word16) bp - 2) = v23;
	SCZO = cond(v23);
	bx = ss->*((word16) bp - 2);
	ds->*((word16) bx + 4322) = 0x00;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 31FF:0106: define fn31FF_0106
// Called from:
//      fn31FF_17DA
define fn31FF_0106
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x06;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = di;
	sp -= 2;
	ss->*sp = si;
	v9 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v9;
	v10 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v10;
	v11 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v11;
	fn38AD_0118();
	sp = (word16) sp + 6;
	ss->*((word16) bp - 2) = ax;
	ax = ss->*((word16) bp + 0x0A);
	SCZO = cond(ss->*((word16) bp - 2) - ax);
	if (Test(UGE,C))
	{
l31FF_0200:
		(ss->*((word16) bp - 2)).u0 = 0x00;
		goto l31FF_0205;
	}
	bx = ss->*((word16) bp - 2);
	es_si = ss->*((word16) bp + 6);
	al = Mem0[es:bx + si:byte];
	ss->*((word16) bp - 6) = al;
	ah -= ah;
	SCZO = cond(ah);
	sp -= 2;
	ss->*sp = ax;
	fn38AD_0040();
	sp = (word16) sp + 2;
	SZP = cond(al & 0x01);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
		SCZO = cond(ss->*((word16) bp - 6) - 0x5F);
		if (Test(NE,Z))
			goto l31FF_0200;
	}
	ss->*((word16) bp - 4) = 0x00;
	while (true)
	{
		ax = ss->*((word16) bp + 0x0A);
		SCZO = cond(ss->*((word16) bp - 2) - ax);
		if (Test(UGE,C))
			break;
		SCZO = cond(ss->*((word16) bp - 4) - 0x0A);
		if (Test(UGE,C))
			break;
		bx = ss->*((word16) bp - 2);
		es_di = ss->*((word16) bp + 6);
		al = Mem0[es:bx + di:byte];
		ss->*((word16) bp - 6) = al;
		ah -= ah;
		SCZO = cond(ah);
		si = ax;
		sp -= 2;
		ss->*sp = si;
		fn38AD_0040();
		sp = (word16) sp + 2;
		SZP = cond(al & 0x01);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
			SCZO = cond(ss->*((word16) bp - 6) - 0x5F);
			if (Test(NE,Z))
			{
				sp -= 2;
				ss->*sp = si;
				fn38AD_0040();
				sp = (word16) sp + 2;
				SZP = cond(al & 0x02);
				O = false;
				C = false;
				if (Test(EQ,Z))
					break;
			}
		}
		bx = ss->*((word16) bp - 2);
		es_si = ss->*((word16) bp + 6);
		al = Mem0[es:bx + si:byte];
		ah -= ah;
		SCZO = cond(ah);
		sp -= 2;
		ss->*sp = ax;
		fn38AD_001E();
		sp = (word16) sp + 2;
		SCZO = cond(sp);
		es_bx = ss->*((word16) bp + 0x0C);
		v26 = (word32) (ss->*((word16) bp + 0x0C)) + 1;
		ss->*((word16) bp + 0x0C) = v26;
		es->*bx = al;
		v27 = (word32) (ss->*((word16) bp - 2)) + 1;
		ss->*((word16) bp - 2) = v27;
		v28 = (word16) ((word32) (ss->*((word16) bp - 4)) + 1);
		ss->*((word16) bp - 4) = v28;
		SZO = cond(v28);
	}
l31FF_01B9:
	ax = ss->*((word16) bp + 0x0A);
	SCZO = cond(ss->*((word16) bp - 2) - ax);
	if (Test(UGE,C))
	{
l31FF_01E2:
		bx = ss->*((word16) bp - 2);
		es_si = ss->*((word16) bp + 6);
		al = Mem0[es:bx + si:byte];
		ah -= ah;
		SCZO = cond(ah);
		sp -= 2;
		ss->*sp = ax;
		fn38AD_0040();
		sp = (word16) sp + 2;
		SZP = cond(al & 0x02);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
l31FF_0205:
			es_bx = ss->*((word16) bp + 0x0C);
			es->*bx = 0x00;
			ax = ss->*((word16) bp - 2);
			si = ss->*sp;
			sp = (word16) sp + 2;
			di = ss->*sp;
			sp = bp;
			bp = ss->*sp;
			sp = (word16) sp + 2;
			return;
		}
		goto l31FF_01FA;
	}
	else
	{
		bx = ss->*((word16) bp - 2);
		es_si = ss->*((word16) bp + 6);
		al = Mem0[es:bx + si:byte];
		ss->*((word16) bp - 6) = al;
		ah -= ah;
		SCZO = cond(ah);
		sp -= 2;
		ss->*sp = ax;
		fn38AD_0040();
		sp = (word16) sp + 2;
		SZP = cond(al & 0x01);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
			SCZO = cond(ss->*((word16) bp - 6) - 0x5F);
			if (Test(NE,Z))
				goto l31FF_01E2;
		}
l31FF_01FA:
		v23 = (word32) (ss->*((word16) bp - 2)) + 1;
		ss->*((word16) bp - 2) = v23;
		SZO = cond(v23);
		goto l31FF_01B9;
	}
}

// 31FF:0216: define fn31FF_0216
// Called from:
//      fn31FF_026E
define fn31FF_0216
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_99946 Eq_99953::*) bp;
	bp = sp;
	ax = ds->ptr1A32;
	ds->ptr1A34 = ax;
	al = (ss->*bp).b0006;
	ah -= ah;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_99946 Eq_99953::*) ax;
	ax = ds->ptr1A30;
	ax -= ds->ptr1A32;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_99946 Eq_99953::*) ax;
	ax = ds->ptr1A32;
	ax += ds->w1A2C /16 7;
	SCZO = cond(ax);
	dx = ds->ptr1A2E;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_99946 Eq_99953::*) dx;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_99946 Eq_99953::*) ax;
	fn2017_035B();
	sp = &sp->b0006 + 2;
	v12 = Mem0[ds:6706:word16] + ax;
	ds->ptr1A32 = v12;
	ax = ds->ptr1A30;
	SCZO = cond(ds->ptr1A32 - ax);
	if (Test(NE,Z))
	{
		ax = ds->ptr1A32;
		ax -= ds->ptr1A34;
		SCZO = cond(ax);
		ds->ptr1A36 = ax;
		v14 = (struct Eq_99946 Eq_99953::*) &ds->ptr1A32->ptr0000;
		ds->ptr1A32 = v14;
		SZO = cond(v14);
		bp = (struct Eq_99946 Eq_99953::*) (ss->*sp).ptr0000;
		sp = (struct Eq_99946 Eq_99953::*) &sp->ptr0000;
	}
	else
	{
		ds->w1A2A = 100;
		ds->ptr1A36 = &Eq_99953::t0000;
		bp = (struct Eq_99946 Eq_99953::*) (ss->*sp).ptr0000;
		sp = (struct Eq_99946 Eq_99953::*) &sp->ptr0000;
	}
}

// 31FF:026E: define fn31FF_026E
// Called from:
//      fn31FF_0F20
define fn31FF_026E
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x04;
	sp -= 2;
	ss->*sp = si;
	ax = ds->t1A30;
	ax -= ds->t1A32;
	sp -= 2;
	ss->*sp = ax;
	ax = ds->t1A32;
	ax += Mem0[ds:6700:word16];
	SCZO = cond(ax);
	dx = ds->t1A2E;
	sp -= 2;
	ss->*sp = dx;
	sp -= 2;
	ss->*sp = ax;
	fn38AD_0118();
	sp = (word16) sp + 6;
	v11 = Mem0[ds:6706:word16] + ax;
	ds->t1A32 = v11;
	ax = ds->t1A30;
	SCZO = cond(ds->t1A32 - ax);
	if (Test(EQ,Z))
	{
		ds->w1A2A = 200;
		ax.u0 = 110;
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
		return;
	}
	bx = ds->t1A32;
	es_si = ds->t1A2C;
	al = Mem0[es:bx + si:byte];
	ah -= ah;
	SCZO = cond(ah);
	sp -= 2;
	ss->*sp = ax;
	fn38AD_0040();
	sp = (word16) sp + 2;
	SZP = cond(al & 0x01);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
		bx = ds->t1A32;
		es_si = ds->t1A2C;
		SCZO = cond(Mem0[es:bx + si:byte] - 0x5F);
		if (Test(NE,Z))
		{
			bx = ds->t1A32;
			es_si = ds->t1A2C;
			al = Mem0[es:bx + si:byte];
			ah -= ah;
			SCZO = cond(ah);
			sp -= 2;
			ss->*sp = ax;
			fn38AD_0040();
			sp = (word16) sp + 2;
			SZP = cond(al & 0x02);
			O = false;
			C = false;
			if (Test(EQ,Z))
			{
				bx = ds->t1A32;
				es_si = ds->t1A2C;
				SCZO = cond(Mem0[es:bx + si:byte] - 0x2E);
				if (Test(NE,Z))
				{
l31FF_0494:
					si.u0 = 6706;
					bx = ds->*si.u0;
					v21 = (word32) (ds->*si.u0) + 1;
					ds->*si.u0 = v21;
					es_si = ds->t1A2C;
					al = Mem0[es:bx + si:byte];
					ah -= ah;
					SCZO = cond(ax - 0x29);
					if (Test(EQ,Z))
					{
						(ss->*((word16) bp - 2)).u0 = 0x7C;
						goto l31FF_05E3;
					}
					if (Test(UGT,CZ))
					{
						SCZO = cond(ax - 0x2B);
						if (Test(EQ,Z))
						{
							(ss->*((word16) bp - 2)).u0 = 0x84;
							goto l31FF_05E3;
						}
						SCZO = cond(ax - 0x2D);
						if (Test(EQ,Z))
						{
							(ss->*((word16) bp - 2)).u0 = 133;
							goto l31FF_05E3;
						}
						SCZO = cond(ax - 0x2E);
						if (Test(EQ,Z))
						{
							(ss->*((word16) bp - 2)).u0 = 110;
							ax = ds->t1A30;
							SCZO = cond(ds->t1A32 - ax);
							if (Test(UGE,C))
								goto l31FF_05E3;
							si.u0 = 6706;
							bx = ds->*si.u0;
							v27 = (word32) (ds->*si.u0) + 1;
							ds->*si.u0 = v27;
							es_si = ds->t1A2C;
							al = Mem0[es:bx + si:byte];
							ah -= ah;
							SCZO = cond(ah);
							sp -= 2;
							ss->*sp = ax;
							fn38AD_001E();
							sp = (word16) sp + 2;
							ah -= ah;
							SCZO = cond(ax - 0x46);
							if (Test(NE,Z))
							{
								SCZO = cond(ax - 0x4E);
								if (Test(NE,Z))
								{
									SCZO = cond(ax - 0x54);
									if (Test(NE,Z))
									{
										SCZO = cond(ax - 0x59);
										if (Test(NE,Z))
											goto l31FF_05E3;
									}
									ax = ds->t1A30;
									SCZO = cond(ds->t1A32 - ax);
									if (Test(ULT,C))
									{
										bx = ds->t1A32;
										es_si = ds->t1A2C;
										SCZO = cond(Mem0[es:bx + si:byte] - 0x2E);
										if (Test(EQ,Z))
										{
											v29 = (word32) ds->t1A32 + 1;
											ds->t1A32 = v29;
											SZO = cond(v29);
											(ss->*((word16) bp - 2)).u0 = 121;
										}
									}
									goto l31FF_05E3;
								}
								ax = ds->t1A30;
								SCZO = cond(ds->t1A32 - ax);
								if (Test(ULT,C))
								{
									bx = ds->t1A32;
									es_si = ds->t1A2C;
									SCZO = cond(Mem0[es:bx + si:byte] - 0x2E);
									if (Test(EQ,Z))
										goto l31FF_0577;
								}
								ax = ds->t1A32;
								ax = (word16) ax.u0 + 2;
								SCZO = cond(ax - ds->t1A30);
								if (Test(UGE,C))
									goto l31FF_05E3;
								bx = ds->t1A32;
								es_si = ds->t1A2C;
								al = Mem0[es:bx + si:byte];
								ah -= ah;
								SCZO = cond(ah);
								sp -= 2;
								ss->*sp = ax;
								fn38AD_001E();
								sp = (word16) sp + 2;
								SCZO = cond(al - 0x4F);
								if (Test(EQ,Z))
								{
									si = ds->t1A32;
									es_bx = ds->t1A2C;
									al = es->*((word16) si.u0 + ((word16) bx + 1));
									ah -= ah;
									SCZO = cond(ah);
									sp -= 2;
									ss->*sp = ax;
									fn38AD_001E();
									sp = (word16) sp + 2;
									SCZO = cond(al - 0x54);
									if (Test(NE,Z))
										goto l31FF_05E3;
									si = ds->t1A32;
									es_bx = ds->t1A2C;
									SCZO = cond(es->*((word16) si.u0 + ((word16) bx + 2)) - 0x2E);
									if (Test(EQ,Z))
									{
										v31 = (word32) ds->t1A32 + 3;
										ds->t1A32 = v31;
										SCZO = cond(v31);
l31FF_05D7:
										(ss->*((word16) bp - 2)).u0 = 0x93;
										goto l31FF_05E3;
									}
								}
							}
							else
							{
								ax = ds->t1A30;
								SCZO = cond(ds->t1A32 - ax);
								if (Test(UGE,C))
									goto l31FF_05E3;
								bx = ds->t1A32;
								es_si = ds->t1A2C;
								SCZO = cond(Mem0[es:bx + si:byte] - 0x2E);
								if (Test(EQ,Z))
								{
l31FF_0577:
									v28 = (word32) ds->t1A32 + 1;
									ds->t1A32 = v28;
									SZO = cond(v28);
									(ss->*((word16) bp - 2)).u0 = 0x78;
									goto l31FF_05E3;
								}
							}
l31FF_05E3:
							SCZO = cond(ss->*((word16) bp - 2) - 110);
							if (Test(EQ,Z))
								ds->w1A2A = 300;
							ax = ss->*((word16) bp - 2);
							si = ss->*sp;
							sp = bp;
							bp = ss->*sp;
							sp = (word16) sp + 2;
							return;
						}
						SCZO = cond(ax - 0x40);
						if (Test(EQ,Z))
						{
							(ss->*((word16) bp - 2)).u0 = 0x82;
							goto l31FF_05E3;
						}
						SCZO = cond(ax - 0x5B);
						if (Test(EQ,Z))
						{
							ax.u0 = 0x5D;
							goto l31FF_0613;
						}
						SCZO = cond(ax - 0x60);
						if (Test(NE,Z))
							goto l31FF_0657;
					}
					else
					{
						SCZO = cond(ax - 33);
						if (Test(EQ,Z))
							goto l31FF_05D7;
						SCZO = cond(ax - 0x22);
						if (Test(EQ,Z))
						{
							ax.u0 = 0x22;
l31FF_0613:
							sp -= 2;
							ss->*sp = ax;
							fn31FF_0216();
							sp = (word16) sp + 2;
							SCZO = cond(sp);
							(ss->*((word16) bp - 2)).u0 = 118;
							goto l31FF_05E3;
						}
						SCZO = cond(ax - 0x27);
						if (Test(NE,Z))
						{
							SCZO = cond(ax - 0x28);
							if (Test(EQ,Z))
							{
								(ss->*((word16) bp - 2)).u0 = 0x7B;
								goto l31FF_05E3;
							}
l31FF_0657:
							(ss->*((word16) bp - 2)).u0 = 110;
							goto l31FF_05E3;
						}
					}
					ax.u0 = 0x27;
					goto l31FF_0613;
				}
				ax = ds->t1A30;
				SCZO = cond(bx - ax);
				if (Test(UGE,C))
					goto l31FF_0494;
				si = bx;
				bx = ds->t1A2C;
				al = es->*((word16) si.u0 + ((word16) bx + 1));
				ah -= ah;
				SCZO = cond(ah);
				sp -= 2;
				ss->*sp = ax;
				fn38AD_0040();
				sp = (word16) sp + 2;
				SZP = cond(al & 0x02);
				O = false;
				C = false;
				if (Test(EQ,Z))
					goto l31FF_0494;
			}
			ax = ds->t1A32;
			ds->t1A34 = ax;
			while (true)
			{
				ax = ds->t1A30;
				SCZO = cond(ds->t1A32 - ax);
				if (Test(UGE,C))
					break;
				bx = ds->t1A32;
				es_si = ds->t1A2C;
				al = Mem0[es:bx + si:byte];
				ah -= ah;
				SCZO = cond(ah);
				sp -= 2;
				ss->*sp = ax;
				fn38AD_0040();
				sp = (word16) sp + 2;
				SZP = cond(al & 0x02);
				O = false;
				C = false;
				if (Test(EQ,Z))
					break;
				v33 = (word32) ds->t1A32 + 1;
				ds->t1A32 = v33;
				SZO = cond(v33);
			}
			ax = ds->t1A32;
			ax = (word16) ax.u0 + 1;
			SCZO = cond(ax - ds->t1A30);
			if (Test(ULT,C))
			{
				bx = ds->t1A32;
				es_si = ds->t1A2C;
				SCZO = cond(Mem0[es:bx + si:byte] - 0x2E);
				if (Test(EQ,Z))
				{
					si = bx;
					bx = ds->t1A2C;
					al = es->*((word16) si.u0 + ((word16) bx + 1));
					while (true)
					{
						ah -= ah;
						SCZO = cond(ah);
						sp -= 2;
						ss->*sp = ax;
						fn38AD_0040();
						sp = (word16) sp + 2;
						SZP = cond(al & 0x02);
						O = false;
						C = false;
						if (Test(EQ,Z))
							break;
						v32 = (word32) ds->t1A32 + 1;
						ds->t1A32 = v32;
						ax = ds->t1A30;
						SCZO = cond(ds->t1A32 - ax);
						if (Test(UGE,C))
							break;
						bx = ds->t1A32;
						es_si = ds->t1A2C;
						al = Mem0[es:bx + si:byte];
					}
				}
			}
			ax = ds->t1A32;
			ax -= ds->t1A34;
			SCZO = cond(ax);
			ds->t1A36 = ax;
			(ss->*((word16) bp - 2)).u0 = 0x77;
			goto l31FF_05E3;
		}
	}
	ds->t1A38.u0 = 0x00;
	while (true)
	{
		ax = ds->t1A30;
		SCZO = cond(ds->t1A32 - ax);
		if (Test(UGE,C))
			break;
		SCZO = cond(ds->t1A38 - 0x0A);
		if (Test(UGE,C))
			break;
		bx = ds->t1A32;
		es_si = ds->t1A2C;
		al = Mem0[es:bx + si:byte];
		ah -= ah;
		SCZO = cond(ah);
		sp -= 2;
		ss->*sp = ax;
		fn38AD_0040();
		sp = (word16) sp + 2;
		SZP = cond(al & 0x01);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
			bx = ds->t1A32;
			es_si = ds->t1A2C;
			al = Mem0[es:bx + si:byte];
			ss->*((word16) bp - 4) = al;
			SCZO = cond(al - 0x5F);
			if (Test(NE,Z))
			{
				ah -= ah;
				SCZO = cond(ah);
				sp -= 2;
				ss->*sp = ax;
				fn38AD_0040();
				sp = (word16) sp + 2;
				SZP = cond(al & 0x02);
				O = false;
				C = false;
				if (Test(EQ,Z))
					break;
			}
		}
		bx = ds->t1A32;
		es_si = ds->t1A2C;
		al = Mem0[es:bx + si:byte];
		ah -= ah;
		SCZO = cond(ah);
		sp -= 2;
		ss->*sp = ax;
		fn38AD_001E();
		sp = (word16) sp + 2;
		SCZO = cond(sp);
		bx = ds->t1A38;
		ds->*((word16) bx + 0x00001A3A) = al;
		v25 = (word32) ds->t1A32 + 1;
		ds->t1A32 = v25;
		v26 = (word32) ds->t1A38 + 1;
		ds->t1A38 = v26;
		SZO = cond(v26);
	}
	bx = ds->t1A38;
	(ds->*((word16) bx + 0x00001A3A)).u1 = 0x00;
	SCZO = cond(bx - 0x0A);
	if (Test(EQ,Z))
	{
		while (true)
		{
			ax = ds->t1A30;
			SCZO = cond(ds->t1A32 - ax);
			if (Test(UGE,C))
				break;
			bx = ds->t1A32;
			es_si = ds->t1A2C;
			al = Mem0[es:bx + si:byte];
			ah -= ah;
			SCZO = cond(ah);
			sp -= 2;
			ss->*sp = ax;
			fn38AD_0040();
			sp = (word16) sp + 2;
			SZP = cond(al & 0x01);
			O = false;
			C = false;
			if (Test(EQ,Z))
			{
				bx = ds->t1A32;
				es_si = ds->t1A2C;
				al = Mem0[es:bx + si:byte];
				ss->*((word16) bp - 4) = al;
				SCZO = cond(al - 0x5F);
				if (Test(NE,Z))
				{
					ah -= ah;
					SCZO = cond(ah);
					sp -= 2;
					ss->*sp = ax;
					fn38AD_0040();
					sp = (word16) sp + 2;
					SZP = cond(al & 0x02);
					O = false;
					C = false;
					if (Test(EQ,Z))
						break;
				}
			}
			v23 = (word32) ds->t1A32 + 1;
			ds->t1A32 = v23;
			SZO = cond(v23);
		}
	}
	(ss->*((word16) bp - 2)).u0 = 122;
	goto l31FF_05E3;
}

// 31FF:065E: define fn31FF_065E
// Called from:
//      fn31FF_0F20
define fn31FF_065E
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x04;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	while (true)
	{
		ax = ds->t1A30;
		SCZO = cond(ds->t1A32 - ax);
		if (Test(UGE,C))
			break;
		bx = ds->t1A32;
		es_si = ds->t1A2C;
		al = Mem0[es:bx + si:byte];
		ss->*((word16) bp - 4) = al;
		SCZO = cond(al - 0x20);
		if (Test(NE,Z))
		{
			SCZO = cond(al - 0x09);
			if (Test(NE,Z))
				break;
		}
		v16 = (word16) ds->t1A32 + 1;
		ds->t1A32 = v16;
		SZO = cond(v16);
	}
	ax = ds->t1A30;
	SCZO = cond(ds->t1A32 - ax);
	if (Test(EQ,Z))
	{
		ax.u0 = 110;
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
		return;
	}
	si.u0 = 6706;
	bx = ds->*si.u0;
	v18 = (word16) (ds->*si.u0) + 1;
	ds->*si.u0 = v18;
	es_si = ds->t1A2C;
	al = Mem0[es:bx + si:byte];
	ah -= ah;
	SCZO = cond(ax - 44);
	if (Test(EQ,Z))
	{
		SCZO = cond(ss->*((word16) bp + 6) - 0x00);
		if (Test(NE,Z))
		{
			(ss->*((word16) bp - 2)).u0 = 114;
			goto l31FF_07BE;
		}
		ds->w1A2A = 900;
l31FF_0920:
		(ss->*((word16) bp - 2)).u0 = 110;
		goto l31FF_07BE;
	}
	if (Test(UGT,CZ))
	{
		SCZO = cond(ax - 0x3C);
		if (Test(EQ,Z))
		{
			ax = ds->t1A30;
			SCZO = cond(ds->t1A32 - ax);
			if (Test(ULT,C))
			{
				bx = ds->t1A32;
				es_si = ds->t1A2C;
				SCZO = cond(Mem0[es:bx + si:byte] - 0x3D);
				if (Test(EQ,Z))
				{
					(ss->*((word16) bp - 2)).u0 = 0x91;
					goto l31FF_0896;
				}
			}
			ax = ds->t1A30;
			SCZO = cond(ds->t1A32 - ax);
			if (Test(ULT,C))
			{
				bx = ds->t1A32;
				es_si = ds->t1A2C;
				SCZO = cond(Mem0[es:bx + si:byte] - 0x3E);
				if (Test(EQ,Z))
				{
l31FF_0891:
					(ss->*((word16) bp - 2)).u0 = 0x92;
					goto l31FF_0896;
				}
			}
			(ss->*((word16) bp - 2)).u0 = 0x8F;
			goto l31FF_07BE;
		}
		if (Test(ULE,CZ))
		{
			SCZO = cond(ax - 0x2D);
			if (Test(EQ,Z))
			{
				ax = ds->t1A30;
				SCZO = cond(ds->t1A32 - ax);
				if (Test(ULT,C))
				{
					bx = ds->t1A32;
					es_si = ds->t1A2C;
					SCZO = cond(Mem0[es:bx + si:byte] - 0x3E);
					if (Test(EQ,Z))
					{
						(ss->*((word16) bp - 2)).u0 = 0x7E;
						goto l31FF_0896;
					}
				}
				(ss->*((word16) bp - 2)).u0 = 0x87;
				goto l31FF_07BE;
			}
			SCZO = cond(ax - 0x2E);
			if (Test(EQ,Z))
			{
				(ss->*((word16) bp - 2)).u0 = 110;
				ax = ds->t1A30;
				SCZO = cond(ds->t1A32 - ax);
				if (Test(UGE,C))
				{
					ds->w1A2A = 700;
					goto l31FF_07BE;
				}
				si.u0 = 6706;
				bx = ds->*si.u0;
				v22 = (word16) (ds->*si.u0) + 1;
				ds->*si.u0 = v22;
				es_si = ds->t1A2C;
				al = Mem0[es:bx + si:byte];
				ah -= ah;
				SCZO = cond(ah);
				sp -= 2;
				ss->*sp = ax;
				fn38AD_001E();
				sp = (word16) sp + 2;
				ah -= ah;
				SCZO = cond(ax - 0x41);
				if (Test(NE,Z))
				{
					SCZO = cond(ax - 0x4F);
					if (Test(NE,Z))
					{
						ds->w1A2A = 600;
						goto l31FF_07BE;
					}
					ax = ds->t1A32;
					ax = (word16) ax + 1;
					SCZO = cond(ax - ds->t1A30);
					if (Test(ULT,C))
					{
						bx = ds->t1A32;
						es_si = ds->t1A2C;
						al = Mem0[es:bx + si:byte];
						ah -= ah;
						SCZO = cond(ah);
						sp -= 2;
						ss->*sp = ax;
						fn38AD_001E();
						sp = (word16) sp + 2;
						SCZO = cond(al - 0x52);
						if (Test(EQ,Z))
						{
							si = ds->t1A32;
							es_bx = ds->t1A2C;
							SCZO = cond(es->*((word16) si.u0 + ((word16) bx + 1)) - 0x2E);
							if (Test(EQ,Z))
							{
								v24 = (word16) ds->t1A32 + 2;
								ds->t1A32 = v24;
								SCZO = cond(v24);
								(ss->*((word16) bp - 2)).u0 = 0x95;
								goto l31FF_07BE;
							}
						}
					}
					ds->w1A2A = 500;
					goto l31FF_07BE;
				}
				ax = ds->t1A32;
				ax = (word16) ax.u0 + 2;
				SCZO = cond(ax - ds->t1A30);
				if (Test(ULT,C))
				{
					bx = ds->t1A32;
					es_si = ds->t1A2C;
					al = Mem0[es:bx + si:byte];
					ah -= ah;
					SCZO = cond(ah);
					sp -= 2;
					ss->*sp = ax;
					fn38AD_001E();
					sp = (word16) sp + 2;
					SCZO = cond(al - 0x4E);
					if (Test(EQ,Z))
					{
						si = ds->t1A32;
						es_bx = ds->t1A2C;
						al = (byte) (es->*((word16) si.u0 + ((word16) bx + 1)));
						ah -= ah;
						SCZO = cond(ah);
						sp -= 2;
						ss->*sp = ax;
						fn38AD_001E();
						sp = (word16) sp + 2;
						SCZO = cond(al - 0x44);
						if (Test(EQ,Z))
						{
							si = ds->t1A32;
							es_bx = ds->t1A2C;
							SCZO = cond(es->*((word16) si.u0 + ((word16) bx + 2)) - 0x2E);
							if (Test(EQ,Z))
							{
								v25 = (word16) ds->t1A32 + 3;
								ds->t1A32 = v25;
								SCZO = cond(v25);
								(ss->*((word16) bp - 2)).u0 = 0x94;
								goto l31FF_07BE;
							}
						}
					}
				}
				ds->w1A2A = 400;
				goto l31FF_07BE;
			}
			SCZO = cond(ax - 0x2F);
			if (Test(EQ,Z))
			{
				(ss->*((word16) bp - 2)).u0 = 0x89;
				goto l31FF_07BE;
			}
l31FF_0970:
			ds->w1A2A = 1000;
			goto l31FF_0920;
		}
		SCZO = cond(ax - 0x3D);
		if (Test(EQ,Z))
		{
			ax = ds->t1A30;
			SCZO = cond(ds->t1A32 - ax);
			if (Test(ULT,C))
			{
				bx = ds->t1A32;
				es_si = ds->t1A2C;
				SCZO = cond(Mem0[es:bx + si:byte] - 0x3D);
				if (Test(EQ,Z))
				{
					(ss->*((word16) bp - 2)).u0 = 0x8C;
					goto l31FF_0896;
				}
			}
			(ss->*((word16) bp - 2)).u0 = 141;
		}
		else
		{
			SCZO = cond(ax - 0x3E);
			if (Test(EQ,Z))
			{
				ax = ds->t1A30;
				SCZO = cond(ds->t1A32 - ax);
				if (Test(ULT,C))
				{
					bx = ds->t1A32;
					es_si = ds->t1A2C;
					SCZO = cond(Mem0[es:bx + si:byte] - 0x3D);
					if (Test(EQ,Z))
					{
						(ss->*((word16) bp - 2)).u0 = 0x90;
l31FF_0896:
						v21 = (word16) ds->t1A32 + 1;
						ds->t1A32 = v21;
						SZO = cond(v21);
						goto l31FF_07BE;
					}
				}
				(ss->*((word16) bp - 2)).u0 = 0x8E;
			}
			else
			{
				SCZO = cond(ax - 0x5B);
				if (Test(NE,Z))
				{
					SCZO = cond(ax - 0x5D);
					if (Test(NE,Z))
					{
						SCZO = cond(ax - 0x5E);
						if (Test(NE,Z))
							goto l31FF_0970;
						(ss->*((word16) bp - 2)).u0 = 0x8B;
					}
					else
						(ss->*((word16) bp - 2)).u0 = 0x81;
				}
				else
					(ss->*((word16) bp - 2)).u0 = 0x80;
			}
		}
	}
	else
	{
		ax -= 33;
		v27 = ax;
		SCZO = cond(ax - 0x0A);
		if (Test(UGT,CZ))
			goto l31FF_0970;
		ax += ax;
		SCZO = cond(ax);
		v26 = bx;
		bx = ax;
		ax = v26;
		switch (v27)
		{
		case 0x00:
			ax = ds->t1A30;
			SCZO = cond(ds->t1A32 - ax);
			if (Test(ULT,C))
			{
				bx = ds->t1A32;
				es_si = ds->t1A2C;
				SCZO = cond(Mem0[es:bx + si:byte] - 0x3D);
				if (Test(EQ,Z))
					goto l31FF_0891;
			}
			ds->w1A2A = 800;
			break;
		case 0x01:
		case 0x05:
		case 0x06:
			goto l31FF_0970;
		case 0x02:
			(ss->*((word16) bp - 2)).u0 = 0x92;
			break;
		case 0x03:
			(ss->*((word16) bp - 2)).u0 = 0x96;
			break;
		case 0x04:
			(ss->*((word16) bp - 2)).u0 = 0x8A;
			break;
		case 0x07:
			(ss->*((word16) bp - 2)).u0 = 0x7B;
			break;
		case 0x08:
			(ss->*((word16) bp - 2)).u0 = 0x7C;
			break;
		case 0x09:
			ax = ds->t1A30;
			SCZO = cond(ds->t1A32 - ax);
			if (Test(ULT,C))
			{
				bx = ds->t1A32;
				es_si = ds->t1A2C;
				SCZO = cond(Mem0[es:bx + si:byte] - 0x2A);
				if (Test(EQ,Z))
				{
					(ss->*((word16) bp - 2)).u0 = 0x8B;
					goto l31FF_0896;
				}
			}
			(ss->*((word16) bp - 2)).u0 = 0x88;
			break;
		case 0x0A:
			(ss->*((word16) bp - 2)).u0 = 0x86;
			break;
		}
	}
l31FF_07BE:
	ax = ss->*((word16) bp - 2);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 31FF:099C: define fn31FF_099C
// Called from:
//      fn31FF_0F20
define fn31FF_099C
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_101754 Eq_101761::*) bp;
	bp = sp;
	sp -= 0x02;
	ax = (ss->*bp).w0006;
	SCZO = cond(ax - 0x8A);
	if (Test(ULE,CZ))
	{
		SCZO = cond(ax - 0x88);
		if (Test(UGE,C))
		{
			(ss->*bp).wFFFFFFFE = 0x06;
			goto l31FF_0A4A;
		}
		SCZO = cond(ax - 0x7E);
		if (Test(EQ,Z))
		{
			(ss->*bp).wFFFFFFFE = 0x09;
			goto l31FF_0A4A;
		}
		if (Test(ULE,CZ))
		{
			SCZO = cond(ax - 0x04);
			if (Test(EQ,Z))
			{
				(ss->*bp).wFFFFFFFE = 0x0A;
				goto l31FF_0A4A;
			}
			goto l31FF_0A1B;
		}
		SCZO = cond(ax - 133);
		if (Test(NE,Z))
		{
			SCZO = cond(ax - 0x86);
			if (Test(ULT,C))
			{
l31FF_0A1B:
				(ss->*bp).wFFFFFFFE = 0x00;
				goto l31FF_0A4A;
			}
			SCZO = cond(ax - 0x87);
			if (Test(UGT,CZ))
				goto l31FF_0A1B;
			(ss->*bp).wFFFFFFFE = 0x05;
		}
		else
			(ss->*bp).wFFFFFFFE = 0x08;
	}
	else
	{
		ax -= 0x8B;
		v13 = ax;
		SCZO = cond(ax - 11);
		if (Test(UGT,CZ))
			goto l31FF_0A1B;
		ax += ax;
		SCZO = cond(ax);
		v11 = bx;
		bx = ax;
		ax = v11;
		switch (v13)
		{
		case 0x00:
			(ss->*bp).wFFFFFFFE = 0x07;
			break;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 11:
			(ss->*bp).wFFFFFFFE = 0x04;
			break;
		case 0x08:
			(ss->*bp).wFFFFFFFE = 0x03;
			break;
		case 0x09:
			(ss->*bp).wFFFFFFFE = 0x02;
			break;
		case 0x0A:
			(ss->*bp).wFFFFFFFE = 0x01;
			break;
		}
	}
l31FF_0A4A:
	ax = (ss->*bp).wFFFFFFFE;
	sp = bp;
	bp = (struct Eq_101754 Eq_101761::*) (ss->*sp).ptr0000;
	sp = (struct Eq_101754 Eq_101761::*) &sp->ptr0000;
}

// 31FF:0A52: define fn31FF_0A52
// Called from:
//      fn31FF_0AAE
define fn31FF_0A52
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x04;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	ss->*((word16) bp - 2) = Eq_101920::a0000;
	while (true)
	{
		bx = (byte Eq_101920::*) (ss->*((word16) bp - 2));
		es_si = ss->*((word16) bp + 6);
		al = Mem0[es:bx + si:byte];
		ss->*((word16) bp - 4) = al;
		al |= al;
		SZ = cond(al);
		O = false;
		C = false;
		if (Test(EQ,Z))
			break;
		bx = (byte Eq_101920::*) (ss->*((word16) bp - 2));
		es_si = ss->*((word16) bp + 0x0A);
		al = (byte) (ss->*((word16) bp - 4));
		SCZO = cond(Mem0[es:bx + si:byte] - al);
		if (Test(NE,Z))
			break;
		v18 = (word16) (ss->*((word16) bp - 2)) + 1;
		ss->*((word16) bp - 2) = v18;
		SZO = cond(v18);
	}
	es_si = ss->*((word16) bp + 0x0A);
	al = Mem0[es:bx + si:byte];
	es_si = ss->*((word16) bp + 6);
	SCZO = cond(Mem0[es:bx + si:byte] - al);
	if (Test(EQ,Z))
	{
l31FF_0A9D:
		ax = 0x01;
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
	else
	{
		es_si = ss->*((word16) bp + 0x0A);
		SCZO = cond(Mem0[es:bx + si:byte] - 0x00);
		if (Test(EQ,Z))
		{
			SCZO = cond(bx - 0x04);
			if (Test(GE,SO))
				goto l31FF_0A9D;
		}
		ax -= ax;
		SCZO = cond(ax);
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 31FF:0AAE: define fn31FF_0AAE
// Called from:
//      fn31FF_0F20
define fn31FF_0AAE
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x06;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	(ss->*((word16) bp - 4)).u0 = 0x01;
	(ss->*((word16) bp - 2)).u0 = 0x48;
	while (true)
	{
		ax = ss->*((word16) bp - 2);
		SCZO = cond(ss->*((word16) bp - 4) - ax);
		if (Test(GE,SO))
			break;
		ax = ss->*((word16) bp - 4);
		ax += Mem0[ss:bp + -2:word16];
		dx_ax = (int32) ax;
		ax -= dx;
		ax >>= 0x01;
		SCZ = cond(ax);
		O = false;
		ss->*((word16) bp - 6) = ax;
		v23 = ss->*((word16) bp + 8);
		sp -= 2;
		ss->*sp = v23;
		v24 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v24;
		fn2017_03F5();
		sp = (word16) sp + 4;
		ax = (word16) ax + 1;
		sp -= 2;
		ss->*sp = ax;
		ax.u0 = 22;
		dx_ax = ss->*((word16) bp - 6) *s32 ax;
		ax = (char *) ax.u0 + 6734;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		v26 = ss->*((word16) bp + 8);
		sp -= 2;
		ss->*sp = v26;
		v27 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v27;
		fn38AD_00F2();
		sp = (word16) sp + 0x0A;
		ax |= ax;
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(GT,SZO))
		{
			ax = ss->*((word16) bp - 6);
			ax = (word16) ax + 1;
			SZO = cond(ax);
			ss->*((word16) bp - 4) = ax;
		}
		else
		{
			ax = ss->*((word16) bp - 6);
			ss->*((word16) bp - 2) = ax;
		}
	}
	ax = ss->*((word16) bp - 4);
	ax += Mem0[ss:bp + -2:word16];
	dx_ax = (int32) ax;
	ax -= dx;
	ax >>= 0x01;
	ss->*((word16) bp - 6) = ax;
	ax.u0 = 22;
	dx_ax = ss->*((word16) bp - 6) *s32 ax;
	si = ax;
	v14 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v14;
	v15 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v15;
	ax = (char *) ax.u0 + 6734;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn31FF_0A52();
	sp = (word16) sp + 8;
	ax |= ax;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
		es_bx = ss->*((word16) bp + 0x0A);
		(es->*bx).u0 = ~0x00;
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
	else
	{
		es_bx = ss->*((word16) bp + 0x0A);
		ax = ds->*((word16) si + 6750);
		(es->*bx).u0 = (struct Eq_238074 *) ax;
		es_bx = ss->*((word16) bp + 0x0E);
		ax = ds->*((word16) si + 6752);
		(es->*bx).u0 = (struct Eq_238074 *) ax;
		es_bx = ss->*((word16) bp + 18);
		ax = ds->*((word16) si + 6754);
		(es->*bx).u0 = (struct Eq_238074 *) ax;
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 31FF:0B72: define fn31FF_0B72
// Called from:
//      fn31FF_0BA0
//      fn31FF_0C62
//      fn31FF_0E18
//      fn31FF_0F20
define fn31FF_0B72
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 2;
	ss->*sp = si;
	ax = ds->ptr1A28;
	ax = (<unknown> Eq_102403::*) ((char *) ax + 1);
	SCZO = cond(ax - ds->w1A26);
	if (Test(UGE,C))
	{
		ds->w1A2A = 0x03;
		si = ss->*sp;
		sp = (word16) sp + 2;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
	else
	{
		bx = ds->ptr1A28;
		es_si = ds->t1A22;
		al = (byte) (ss->*((word16) bp + 6));
		Mem0[es:bx + si:byte] = al;
		v16 = (<unknown> Eq_102403::*) ((char *) ds->ptr1A28 + 1);
		ds->ptr1A28 = v16;
		SZO = cond(v16);
		si = ss->*sp;
		sp = (word16) sp + 2;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 31FF:0BA0: define fn31FF_0BA0
// Called from:
//      fn31FF_0F20
define fn31FF_0BA0
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 2;
	ss->*sp = si;
	SCZO = cond(ss->*((word16) bp + 0x0A) - 0x00);
	if (Test(NE,Z))
	{
		ax = ss->*((word16) bp + 0x0A);
		ax += Mem0[ds:6696:word16];
		ax = (word16) ax + 2;
		SCZO = cond(ax - ds->w1A26);
		if (Test(UGE,C))
		{
			ds->w1A2A = 0x03;
			si = ss->*sp;
			sp = (word16) sp + 2;
			bp = ss->*sp;
			sp = (word16) sp + 2;
		}
		else
		{
			bx = ds->t1A28;
			es_si = ds->t1A22;
			Mem0[es:bx + si:byte] = 151;
			v15 = (word16) ds->t1A28 + 1;
			ds->t1A28 = v15;
			bx = ds->t1A28;
			al = ss->*((word16) bp + 0x0A);
			Mem0[es:bx + si:byte] = al;
			v18 = (word16) ds->t1A28 + 1;
			ds->t1A28 = v18;
			v19 = ss->*((word16) bp + 0x0A);
			sp -= 2;
			ss->*sp = v19;
			v20 = ss->*((word16) bp + 8);
			sp -= 2;
			ss->*sp = v20;
			v21 = ss->*((word16) bp + 6);
			sp -= 2;
			ss->*sp = v21;
			ax = ds->t1A28;
			ax += si;
			SCZO = cond(ax);
			dx = es;
			sp -= 2;
			ss->*sp = dx;
			sp -= 2;
			ss->*sp = ax;
			fn2017_02EC();
			sp = (word16) sp + 0x0A;
			ax = ss->*((word16) bp + 0x0A);
			v23 = Mem0[ds:6696:word16] + ax;
			ds->t1A28 = v23;
			SCZO = cond(v23);
			si = ss->*sp;
			sp = (word16) sp + 2;
			bp = ss->*sp;
			sp = (word16) sp + 2;
		}
	}
	else
	{
		ax.u0 = 0x7F;
		sp -= 2;
		ss->*sp = ax;
		fn31FF_0B72();
		sp = (word16) sp + 2;
		SCZO = cond(sp);
		si = ss->*sp;
		sp = (word16) sp + 2;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 31FF:0C14: define fn31FF_0C14
// Called from:
//      fn31FF_0C62
//      fn31FF_0E18
//      fn31FF_0F20
define fn31FF_0C14
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 2;
	ss->*sp = si;
	ax = ds->t1A28;
	ax = (word16) ax + 3;
	SCZO = cond(ax - ds->w1A26);
	if (Test(UGE,C))
	{
		ds->w1A2A = 0x03;
		si = ss->*sp;
		sp = (word16) sp + 2;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
	else
	{
		bx = ds->t1A28;
		es_si = ds->t1A22;
		al = (byte) (ss->*((word16) bp + 6));
		Mem0[es:bx + si:byte] = al;
		v15 = (word16) ds->t1A28 + 1;
		ds->t1A28 = v15;
		ax.u0 = 0x02;
		sp -= 2;
		ss->*sp = ax;
		ax = (word16) bp + 8;
		sp -= 2;
		ss->*sp = ss;
		sp -= 2;
		ss->*sp = ax;
		ax = ds->t1A28;
		ax += si;
		SCZO = cond(ax);
		dx = es;
		sp -= 2;
		ss->*sp = dx;
		sp -= 2;
		ss->*sp = ax;
		fn2017_02EC();
		sp = (word16) sp + 0x0A;
		v18 = (word16) ds->t1A28 + 2;
		ds->t1A28 = v18;
		SCZO = cond(v18);
		si = ss->*sp;
		sp = (word16) sp + 2;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 31FF:0C62: define fn31FF_0C62
// Called from:
//      fn31FF_0F20
define fn31FF_0C62
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x12;
	sp -= 2;
	ss->*sp = si;
	SCZO = cond(ss->*((word16) bp + 0x0A) - 0x01);
	if (Test(EQ,Z))
	{
		es_bx = ss->*((word16) bp + 6);
		SCZO = cond(es->*bx - 0x30);
		if (Test(EQ,Z))
		{
			ax.u0 = 0xEF;
			goto l31FF_0C87;
		}
		SCZO = cond(es->*bx - 0x31);
		if (Test(EQ,Z))
		{
			ax.u0 = 0x80;
l31FF_0C87:
			sp -= 2;
			ss->*sp = ax;
			fn31FF_0B72();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
			si = ss->*sp;
			sp = bp;
			bp = ss->*sp;
			sp = (word16) sp + 2;
			return;
		}
		es_bx = ss->*((word16) bp + 6);
		al = es->*bx;
		ah -= ah;
		ax -= 0x30;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
	}
	else
	{
		(ss->*((word16) bp - 2)).u0 = 0x00;
		(ss->*((word16) bp - 4)).u0 = 0x00;
		while (true)
		{
			ax = ss->*((word16) bp + 0x0A);
			SCZO = cond(ss->*((word16) bp - 2) - ax);
			if (Test(UGE,C))
				break;
			bx = ss->*((word16) bp - 2);
			es_si = ss->*((word16) bp + 6);
			al = Mem0[es:bx + si:byte];
			ss->*((word16) bp - 18) = al;
			SCZO = cond(al - 0x2E);
			if (Test(EQ,Z))
				break;
			SCZO = cond(ss->*((word16) bp - 4) - 0x0CCB);
			if (Test(GE,SO))
				break;
			ax.u0 = 0x0A;
			dx_ax = ss->*((word16) bp - 4) *s32 ax;
			ss->*((word16) bp - 4) = ax;
			al = ss->*((word16) bp - 18);
			ah -= ah;
			ax -= 0x30;
			v20 = Mem0[ss:bp + -4:word16] + ax;
			ss->*((word16) bp - 4) = v20;
			SCZO = cond(v20);
			v21 = (word32) (ss->*((word16) bp - 2)) + 1;
			ss->*((word16) bp - 2) = v21;
			SZO = cond(v21);
		}
		ax = ss->*((word16) bp + 0x0A);
		SCZO = cond(ss->*((word16) bp - 2) - ax);
		if (Test(NE,Z))
		{
			ax = ds->t1A28;
			ax.u0 = (byte) ax.u0 + 11;
			SCZO = cond(ax - ds->w1A26);
			if (Test(ULT,C))
			{
				ax = bp - 6;
				sp -= 2;
				ss->*sp = ss;
				sp -= 2;
				ss->*sp = ax;
				ax = bp - 16;
				sp -= 2;
				ss->*sp = ss;
				sp -= 2;
				ss->*sp = ax;
				ax = bp - 0x0E;
				sp -= 2;
				ss->*sp = ss;
				sp -= 2;
				ss->*sp = ax;
				v24 = ss->*((word16) bp + 0x0A);
				sp -= 2;
				ss->*sp = v24;
				v25 = ss->*((word16) bp + 8);
				sp -= 2;
				ss->*sp = v25;
				v26 = ss->*((word16) bp + 6);
				sp -= 2;
				ss->*sp = v26;
				fn3CEE_0EA8();
				sp = (word16) sp + 18;
				SCZO = cond(ss->*((word16) bp - 6) - 0x00);
				if (Test(NE,Z))
				{
					ax = ss->*((word16) bp - 6);
					ax.u0 = (byte) ax.u0 + 11;
					ax -= ss->*((word16) bp - 16);
					SCZO = cond(ax);
					cx = cx - cx - C;
					cx = ~cx;
					ax &= cx;
					ax += Mem0[ss:bp + -16:word16];
					SCZO = cond(ax);
				}
				else
				{
					ax = ss->*((word16) bp + 0x0A);
					ax -= 0x0A;
					SCZO = cond(ax);
					cx = cx - cx - C;
					cx = ~cx;
					ax &= cx;
					ax.u0 = (byte) ax.u0 + 0x0A;
					SCZO = cond(ax);
				}
				ss->*((word16) bp - 16) = ax;
				bx = ds->t1A28;
				es_si = ds->t1A22;
				Mem0[es:bx + si:byte] = 155;
				v30 = (word32) ds->t1A28 + 1;
				ds->t1A28 = v30;
				bx = ds->t1A28;
				al = ss->*((word16) bp - 16);
				Mem0[es:bx + si:byte] = al;
				v31 = (word32) ds->t1A28 + 1;
				ds->t1A28 = v31;
				bx = ds->t1A28;
				al = ss->*((word16) bp - 6);
				Mem0[es:bx + si:byte] = al;
				v32 = (word32) ds->t1A28 + 1;
				ds->t1A28 = v32;
				ax.u0 = 0x08;
				sp -= 2;
				ss->*sp = ax;
				ax = bp - 0x0E;
				sp -= 2;
				ss->*sp = ss;
				sp -= 2;
				ss->*sp = ax;
				ax = ds->t1A28;
				ax += si;
				SCZO = cond(ax);
				dx = es;
				sp -= 2;
				ss->*sp = dx;
				sp -= 2;
				ss->*sp = ax;
				fn2017_02EC();
				sp = (word16) sp + 0x0A;
				v34 = (word32) ds->t1A28 + 8;
				ds->t1A28 = v34;
				SCZO = cond(v34);
				si = ss->*sp;
				sp = bp;
				bp = ss->*sp;
				sp = (word16) sp + 2;
				return;
			}
			else
			{
				ds->w1A2A = 0x03;
				si = ss->*sp;
				sp = bp;
				bp = ss->*sp;
				sp = (word16) sp + 2;
				return;
			}
		}
		v14 = ss->*((word16) bp - 4);
		sp -= 2;
		ss->*sp = v14;
	}
	ax.u0 = 0x99;
	sp -= 2;
	ss->*sp = ax;
	fn31FF_0C14();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 31FF:0DB8: define fn31FF_0DB8
// Called from:
//      fn31FF_0F20
define fn31FF_0DB8
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 2;
	ss->*sp = si;
	ax = ss->*((word16) bp + 8);
	ax |= ss->*((word16) bp + 0x0A);
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		ax = ds->t1A28;
		ax = (word16) ax + 5;
		SCZO = cond(ax - ds->w1A26);
		if (Test(UGE,C))
		{
			ds->w1A2A = 0x03;
			si = ss->*sp;
			sp = (word16) sp + 2;
			bp = ss->*sp;
			sp = (word16) sp + 2;
		}
		else
		{
			bx = ds->t1A28;
			es_si = ds->t1A22;
			al = (byte) (ss->*((word16) bp + 6));
			Mem0[es:bx + si:byte] = al;
			v18 = (word16) ds->t1A28 + 1;
			ds->t1A28 = v18;
			ax.u0 = 0x04;
			sp -= 2;
			ss->*sp = ax;
			ax = (word16) bp + 8;
			sp -= 2;
			ss->*sp = ss;
			sp -= 2;
			ss->*sp = ax;
			ax = ds->t1A28;
			ax += si;
			SCZO = cond(ax);
			dx = es;
			sp -= 2;
			ss->*sp = dx;
			sp -= 2;
			ss->*sp = ax;
			fn2017_02EC();
			sp = (word16) sp + 0x0A;
			v21 = (word16) ds->t1A28 + 4;
			ds->t1A28 = v21;
			SCZO = cond(v21);
			si = ss->*sp;
			sp = (word16) sp + 2;
			bp = ss->*sp;
			sp = (word16) sp + 2;
		}
	}
	else
	{
		ds->w1A2A = 0x02;
		si = ss->*sp;
		sp = (word16) sp + 2;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 31FF:0E18: define fn31FF_0E18
// Called from:
//      fn31FF_0F20
define fn31FF_0E18
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_103446 Eq_103453::*) bp;
	bp = sp;
	ax = (struct Eq_103446 Eq_103453::*) (ss->*bp).ptr0006;
	SCZO = cond(ax - 0x8C);
	if (Test(NE,Z))
	{
		if (Test(GT,SZO))
		{
			ax -= 141;
			v13 = ax;
			SCZO = cond(ax - 0x09);
			if (Test(UGT,CZ))
			{
				bp = (struct Eq_103446 Eq_103453::*) (ss->*sp).ptr0000;
				sp = (struct Eq_103446 Eq_103453::*) &sp->ptr0000;
				return;
			}
			ax += ax;
			SCZO = cond(ax);
			v11 = bx;
			bx = ax;
			ax = v11;
			switch (v13)
			{
			case 0x00:
				ax = &Eq_103453::t0038;
				break;
			case 0x01:
				ax = &Eq_103453::t004F;
				break;
			case 0x02:
				ax = &Eq_103453::t0069;
				break;
			case 0x03:
				ax = &Eq_103453::t0047;
				break;
			case 0x04:
				ax = &Eq_103453::t0062;
				break;
			case 0x05:
				ax = &Eq_103453::t0075;
				break;
			case 0x06:
				ax = &Eq_103453::t0079;
				break;
			case 0x07:
				ax = &Eq_103453::t0005;
				break;
			case 0x08:
				ax = &Eq_103453::t0081;
				break;
			case 0x09:
				ax = &Eq_103453::t0054;
				break;
			}
		}
		else
		{
			SCZO = cond(ax - 0x86);
			if (Test(NE,Z))
			{
				if (Test(GT,SZO))
				{
					SCZO = cond(ax - 0x87);
					if (Test(NE,Z))
					{
						SCZO = cond(ax - 0x88);
						if (Test(NE,Z))
						{
							SCZO = cond(ax - 0x89);
							if (Test(NE,Z))
							{
								SCZO = cond(ax - 0x8A);
								if (Test(NE,Z))
								{
									SCZO = cond(ax - 0x8B);
									if (Test(NE,Z))
									{
										bp = (struct Eq_103446 Eq_103453::*) (ss->*sp).ptr0000;
										sp = (struct Eq_103446 Eq_103453::*) &sp->ptr0000;
										return;
									}
									ax = &Eq_103453::t003B;
								}
								else
									ax = &Eq_103453::t0070;
							}
							else
								ax = &Eq_103453::t002B;
						}
						else
							ax = &Eq_103453::t0072;
					}
					else
						ax = &Eq_103453::t006F;
				}
				else
				{
					SCZO = cond(ax - 0x04);
					if (Test(EQ,Z))
					{
						ax = &Eq_103453::t0065;
						sp -= 2;
						(ss->*sp).ptr0000 = (struct Eq_103446 Eq_103453::*) ax;
						ax = &Eq_103453::t0026;
						sp -= 2;
						(ss->*sp).ptr0000 = (struct Eq_103446 Eq_103453::*) ax;
						fn31FF_0C14();
						sp = (struct Eq_103446 Eq_103453::*) &sp->ptr0000;
						SCZO = cond(sp);
						bp = (struct Eq_103446 Eq_103453::*) (ss->*sp).ptr0000;
						sp = (struct Eq_103446 Eq_103453::*) &sp->ptr0000;
						return;
					}
					SCZO = cond(ax - 0x7E);
					if (Test(NE,Z))
					{
						SCZO = cond(ax - 133);
						if (Test(NE,Z))
						{
							bp = (struct Eq_103446 Eq_103453::*) (ss->*sp).ptr0000;
							sp = (struct Eq_103446 Eq_103453::*) &sp->ptr0000;
							return;
						}
						ax = &Eq_103453::t0076;
					}
					else
					{
						ax = &Eq_103453::t0008;
						sp -= 2;
						(ss->*sp).ptr0000 = (struct Eq_103446 Eq_103453::*) ax;
						fn31FF_0B72();
						sp = (struct Eq_103446 Eq_103453::*) &sp->ptr0000;
						SCZO = cond(sp);
						ax = &Eq_103453::t009D;
					}
				}
			}
			else
				ax = &Eq_103453::t0086;
		}
	}
	else
		ax = &Eq_103453::t0031;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_103446 Eq_103453::*) ax;
	fn31FF_0B72();
	sp = (struct Eq_103446 Eq_103453::*) &sp->ptr0000;
	SCZO = cond(sp);
	bp = (struct Eq_103446 Eq_103453::*) (ss->*sp).ptr0000;
	sp = (struct Eq_103446 Eq_103453::*) &sp->ptr0000;
}

// 31FF:0F20: define fn31FF_0F20
// Called from:
//      fn31FF_1B0A
//      fn31FF_207C
define fn31FF_0F20
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x0108;
	sp -= 2;
	ss->*sp = si;
	(ss->*((word16) bp - 6)).u0 = 0x00;
	ss->*((word16) bp - 40) = 0x00;
	(ss->*((word16) bp - 2)).u0 = 0x00;
	ss->*((word16) bp - 54) = 0x00;
	Mem0[ds:0x1A2A:word16] = 0x00;
	Mem0[ds:6696:word16] = 0x00;
	ax = ss->*((word16) bp + 6);
	dx = ss->*((word16) bp + 8);
	Mem0[ds:6700:word16] = ax;
	Mem0[ds:0x1A2E:word16] = dx;
	ax = ss->*((word16) bp + 0x0A);
	Mem0[ds:0x1A30:word16] = ax;
	Mem0[ds:6706:word16] = 0x00;
	SCZO = cond(ss->*((word16) bp + 0x0C) - 0x03);
	if (Test(EQ,Z))
	{
		(ss->*((word16) bp + 0x0C)).u0 = 0x00;
		v12 = (word32) (ss->*((word16) bp - 6)) + 1;
		ss->*((word16) bp - 6) = v12;
		si = ss->*((word16) bp - 6);
		si <<= 0x01;
		SCZO = cond(si);
		Mem0[ss:bp - 40 + si:word16] = 0x81;
	}
	ax -= ax;
	SCZO = cond(ax);
	ss->*((word16) bp - 264) = ax;
	fn31FF_026E();
	ss->*((word16) bp - 4) = ax;
	while (true)
	{
		SCZO = cond(Mem0[ds:0x1A2A:word16] - 0x00);
		if (Test(NE,Z))
			break;
		SCZO = cond(ss->*((word16) bp - 6) - 0x00);
		if (Test(EQ,Z))
		{
			SCZO = cond(ss->*((word16) bp - 4) - 110);
			if (Test(EQ,Z))
				break;
		}
		ax = ss->*((word16) bp - 4);
		ax -= 110;
		v17 = ax;
		SCZO = cond(ax - 0x28);
		if (Test(ULE,CZ))
		{
			ax += ax;
			SCZO = cond(ax);
			v15 = bx;
			bx = ax;
			ax = v15;
			switch (v17)
			{
			case 0x00:
				SCZO = cond(ss->*((word16) bp - 264) - 0x00);
				if (Test(NE,Z))
				{
					si = ss->*((word16) bp - 6);
					si <<= 0x01;
					ax = Mem0[ss:bp - 40 + si:word16];
					SCZO = cond(ax - 0x7B);
					if (Test(NE,Z))
					{
						if (Test(ULE,CZ))
						{
							ax |= ax;
							SZ = cond(ax);
							O = false;
							C = false;
							if (Test(NE,Z))
								goto l31FF_135F;
						}
						else
						{
							SCZO = cond(ax - 0x7D);
							if (Test(NE,Z))
							{
								SCZO = cond(ax - 0x80);
								if (Test(ULT,C))
									goto l31FF_135F;
								SCZO = cond(ax - 0x81);
								if (Test(UGT,CZ))
									goto l31FF_135F;
							}
						}
					}
					Mem0[ds:0x1A2A:word16] = 1100;
				}
				else
					Mem0[ds:0x1A2A:word16] = 0x04B0;
				break;
			case 0x01:
			case 0x02:
			case 0x03:
			case 0x05:
			case 0x06:
			case 0x07:
			case 0x0F:
			case 0x11:
			case 0x15:
				break;
			case 0x04:
				si = ss->*((word16) bp - 6);
				si <<= 0x01;
				SCZO = cond(Mem0[ss:bp - 40 + si:word16] - 0x7D);
				if (Test(EQ,Z))
				{
					si = ss->*((word16) bp - 6);
					ax = si;
					si <<= 0x01;
					si += ax;
					si <<= 0x01;
					si <<= 0x01;
					v49 = Mem0[ss:bp - 0xEC + si:word16] + 0x01;
					Mem0[ss:bp - 0xEC + si:word16] = v49;
					si = ss->*((word16) bp - 6);
					ax = si;
					si <<= 0x01;
					si += ax;
					si <<= 0x01;
					si <<= 0x01;
					SCZO = cond(Mem0[ss:bp - 242 + si:word16] - 0x50);
					if (Test(EQ,Z))
					{
						si = ax;
						si <<= 0x01;
						si += ax;
						si <<= 0x01;
						si <<= 0x01;
						SCZO = cond(Mem0[ss:bp - 0xEC + si:word16] - 0x01);
						if (Test(EQ,Z))
						{
							ax -= ax;
							SCZO = cond(ax);
							sp -= 2;
							ss->*sp = ax;
							ax.u0 = 88;
							sp -= 2;
							ss->*sp = ax;
							fn31FF_0C14();
							sp = (word16) sp + 4;
							si = ss->*((word16) bp - 6);
							ax = si;
							si <<= 0x01;
							si += ax;
							si <<= 0x01;
							si <<= 0x01;
							SCZO = cond(si);
							ax = Mem0[ds:6696:word16];
							Mem0[ss:bp - 0xF0 + si:word16] = ax;
						}
						else
						{
							si = ss->*((word16) bp - 6);
							ax = si;
							si <<= 0x01;
							si += ax;
							si <<= 0x01;
							si <<= 0x01;
							SCZO = cond(Mem0[ss:bp - 0xEC + si:word16] - 0x02);
							if (Test(EQ,Z))
							{
								ax -= ax;
								SCZO = cond(ax);
								sp -= 2;
								ss->*sp = ax;
								ax.u0 = 0x59;
								sp -= 2;
								ss->*sp = ax;
								fn31FF_0C14();
								sp = (word16) sp + 4;
								si = ss->*((word16) bp - 6);
								ax = si;
								si <<= 0x01;
								si += ax;
								si <<= 0x01;
								si <<= 0x01;
								ax = Mem0[ds:6696:word16];
								Mem0[ss:bp - 0xEE + si:word16] = ax;
								si = ss->*((word16) bp - 6);
								ax = si;
								si <<= 0x01;
								si += ax;
								si <<= 0x01;
								si <<= 0x01;
								ax = Mem0[ss:bp - 0xF0 + si:word16];
								ss->*((word16) bp - 48) = ax;
								ax += Mem0[ds:0x1A22:word16];
								dx = Mem0[ds:6692:word16];
								ax -= 0x02;
								ss->*((word16) bp - 46) = ax;
								ss->*((word16) bp - 44) = dx;
								es_bx = ss->*((word16) bp - 46);
								ax = Mem0[ds:6696:word16];
								ax -= ss->*((word16) bp - 48);
								SCZO = cond(ax);
								es->*bx = ax;
							}
						}
					}
					goto l31FF_1331;
				}
				si = ss->*((word16) bp - 6);
				si <<= 0x01;
				SCZO = cond(Mem0[ss:bp - 40 + si:word16] - 0x7B);
				if (Test(EQ,Z))
					Mem0[ds:0x1A2A:word16] = 1300;
				else
				{
					SCZO = cond(ss->*((word16) bp - 6) - 0x00);
					if (Test(NE,Z))
						goto l31FF_135F;
				}
				break;
			case 0x08:
				v43 = Mem0[ds:0x1A36:word16];
				sp -= 2;
				ss->*sp = v43;
				ax = Mem0[ds:0x1A34:word16];
				ax += Mem0[ds:6700:word16];
				SCZO = cond(ax);
				dx = Mem0[ds:0x1A2E:word16];
				sp -= 2;
				ss->*sp = dx;
				sp -= 2;
				ss->*sp = ax;
				fn31FF_0BA0();
				goto l31FF_100B;
			case 0x09:
				v42 = Mem0[ds:0x1A36:word16];
				sp -= 2;
				ss->*sp = v42;
				ax = Mem0[ds:0x1A34:word16];
				ax += Mem0[ds:6700:word16];
				SCZO = cond(ax);
				dx = Mem0[ds:0x1A2E:word16];
				sp -= 2;
				ss->*sp = dx;
				sp -= 2;
				ss->*sp = ax;
				fn31FF_0C62();
l31FF_100B:
				sp = (word16) sp + 6;
				SCZO = cond(sp);
				goto l31FF_148B;
			case 0x0A:
				ax.u0 = 0x3E;
				goto l31FF_102D;
			case 11:
				ax.u0 = 0xDD;
l31FF_102D:
				sp -= 2;
				ss->*sp = ax;
				fn31FF_0B72();
				sp = (word16) sp + 2;
				SCZO = cond(sp);
				goto l31FF_148B;
			case 0x0C:
				si = ss->*((word16) bp - 6);
				si <<= 0x01;
				SCZO = cond(Mem0[ss:bp - 40 + si:word16] - 0x7E);
				if (Test(EQ,Z))
				{
					ax.u0 = 0x1A3A;
					sp -= 2;
					ss->*sp = ds;
					sp -= 2;
					ss->*sp = ax;
					fn2BC7_0494();
					sp = (word16) sp + 4;
					SCZO = cond(sp);
					sp -= 2;
					ss->*sp = dx;
					sp -= 2;
					ss->*sp = ax;
					ax.u0 = 0xD8;
					sp -= 2;
					ss->*sp = ax;
					fn31FF_0DB8();
					sp = (word16) sp + 6;
					SCZO = cond(Mem0[ds:0x1A2A:word16] - 0x02);
					if (Test(EQ,Z))
					{
						Mem0[ds:0x1A2A:word16] = 0x04;
						ax.u0 = 0x1A3A;
						sp -= 2;
						ss->*sp = ds;
						sp -= 2;
						ss->*sp = ax;
						ax.u0 = 0x5EE8;
						sp -= 2;
						ss->*sp = ds;
						sp -= 2;
						ss->*sp = ax;
						ax = bp - 262;
						sp -= 2;
						ss->*sp = ss;
						sp -= 2;
						ss->*sp = ax;
						fn31FF_006A();
						sp = (word16) sp + 0x0C;
						SCZO = cond(sp);
					}
					goto l31FF_148B;
				}
				v40 = Mem0[ds:0x1A38:word16];
				sp -= 2;
				ss->*sp = v40;
				ax.u0 = 0x1A3A;
				sp -= 2;
				ss->*sp = ds;
				sp -= 2;
				ss->*sp = ax;
				ax = bp - 262;
				sp -= 2;
				ss->*sp = ss;
				sp -= 2;
				ss->*sp = ax;
				fn2017_02EC();
				sp = (word16) sp + 0x0A;
				SCZO = cond(sp);
				si = Mem0[ds:0x1A38:word16];
				Mem0[ss:bp - 262 + si:byte] = 0x00;
				ax.u0 = 0x01;
				ss->*((word16) bp - 264) = ax;
				v41 = ss->*((word16) bp - 2);
				sp -= 2;
				ss->*sp = v41;
				fn31FF_065E();
				sp = (word16) sp + 2;
				ss->*((word16) bp - 4) = ax;
				SCZO = cond(ax - 110);
				if (Test(NE,Z))
				{
					SCZO = cond(ax - 114);
					if (Test(EQ,Z))
					{
l31FF_1224:
						SCZO = cond(ss->*((word16) bp - 54) - 0x00);
						if (Test(EQ,Z))
							goto l31FF_10EF;
						si = ss->*((word16) bp - 6);
						si <<= 0x01;
						SCZO = cond(Mem0[ss:bp - 40 + si:word16] - 0x7D);
						if (Test(NE,Z))
							goto l31FF_10EF;
						ax = bp - 262;
						sp -= 2;
						ss->*sp = ss;
						sp -= 2;
						ss->*sp = ax;
						fn2BC7_0494();
						sp = (word16) sp + 4;
						SCZO = cond(sp);
						sp -= 2;
						ss->*sp = dx;
						sp -= 2;
						ss->*sp = ax;
						ax.u0 = 0x9C;
						sp -= 2;
						ss->*sp = ax;
						fn31FF_0DB8();
						sp = (word16) sp + 6;
						SCZO = cond(sp);
						ss->*((word16) bp - 54) = 0x00;
					}
					else
					{
						SCZO = cond(ax - 0x7B);
						if (Test(EQ,Z))
						{
							SCZO = cond(ss->*((word16) bp - 6) - 0x08);
							if (Test(ULE,CZ))
							{
								v44 = (word32) (ss->*((word16) bp - 6)) + 1;
								ss->*((word16) bp - 6) = v44;
								si = ss->*((word16) bp - 6);
								si <<= 0x01;
								Mem0[ss:bp - 40 + si:word16] = 0x7D;
								si = ss->*((word16) bp - 6);
								ax = si;
								si <<= 0x01;
								si += ax;
								si <<= 0x01;
								si <<= 0x01;
								ax = bp - 0xEE + si;
								sp -= 2;
								ss->*sp = ss;
								sp -= 2;
								ss->*sp = ax;
								si = ss->*((word16) bp - 6);
								ax = si;
								si <<= 0x01;
								si += ax;
								si <<= 0x01;
								si <<= 0x01;
								ax = bp - 0xF0 + si;
								sp -= 2;
								ss->*sp = ss;
								sp -= 2;
								ss->*sp = ax;
								si = ss->*((word16) bp - 6);
								ax = si;
								si <<= 0x01;
								si += ax;
								si <<= 0x01;
								si <<= 0x01;
								SCZO = cond(si);
								ax = bp - 242 + si;
								sp -= 2;
								ss->*sp = ss;
								sp -= 2;
								ss->*sp = ax;
								ax = bp - 262;
								sp -= 2;
								ss->*sp = ss;
								sp -= 2;
								ss->*sp = ax;
								fn31FF_0AAE();
								sp = (word16) sp + 16;
								si = ss->*((word16) bp - 6);
								ax = si;
								si <<= 0x01;
								si += ax;
								si <<= 0x01;
								si <<= 0x01;
								SCZO = cond(Mem0[ss:bp - 242 + si:word16] - ~0x00);
								if (Test(EQ,Z))
								{
									ax = bp - 262;
									sp -= 2;
									ss->*sp = ss;
									sp -= 2;
									ss->*sp = ax;
									fn2BC7_03C2();
									sp = (word16) sp + 4;
									si = ss->*((word16) bp - 6);
									cx = si;
									si <<= 0x01;
									si += cx;
									si <<= 0x01;
									si <<= 0x01;
									SCZO = cond(si);
									Mem0[ss:bp - 0xF6 + si:word16] = ax;
									Mem0[ss:bp - 244 + si:word16] = dx;
								}
								si = ss->*((word16) bp - 6);
								ax = si;
								si <<= 0x01;
								si += ax;
								si <<= 0x01;
								si <<= 0x01;
								SCZO = cond(si);
								Mem0[ss:bp - 0xEC + si:word16] = 0x00;
								v45 = (word32) (ss->*((word16) bp - 2)) + 1;
								ss->*((word16) bp - 2) = v45;
								SZO = cond(v45);
								goto l31FF_1331;
							}
							Mem0[ds:0x1A2A:word16] = 0x03;
						}
						else
						{
							SCZO = cond(ax - 0x7C);
							if (Test(EQ,Z))
								goto l31FF_1224;
							SCZO = cond(ax - 0x7E);
							if (Test(NE,Z))
							{
								SCZO = cond(ax - 0x80);
								if (Test(EQ,Z))
								{
									ax = bp - 262;
									sp -= 2;
									ss->*sp = ss;
									sp -= 2;
									ss->*sp = ax;
									fn2BC7_0494();
									sp = (word16) sp + 4;
									SCZO = cond(sp);
									sp -= 2;
									ss->*sp = dx;
									sp -= 2;
									ss->*sp = ax;
									ax.u0 = 0xD8;
								}
								else
								{
l31FF_10EF:
									ax = bp - 262;
									sp -= 2;
									ss->*sp = ss;
									sp -= 2;
									ss->*sp = ax;
									fn2BC7_0494();
									sp = (word16) sp + 4;
									SCZO = cond(sp);
									sp -= 2;
									ss->*sp = dx;
									sp -= 2;
									ss->*sp = ax;
l31FF_114C:
									ax.u0 = 0x9E;
								}
l31FF_114F:
								sp -= 2;
								ss->*sp = ax;
								fn31FF_0DB8();
								sp = (word16) sp + 6;
								SCZO = cond(sp);
							}
						}
					}
				}
				else
				{
					ax = bp - 262;
					sp -= 2;
					ss->*sp = ss;
					sp -= 2;
					ss->*sp = ax;
					fn2BC7_0494();
					sp = (word16) sp + 4;
					ss->*((word16) bp - 52) = ax;
					ss->*((word16) bp - 50) = dx;
					SCZO = cond(ss->*((word16) bp - 6) - 0x00);
					if (Test(NE,Z))
					{
l31FF_1146:
						v50 = ss->*((word16) bp - 50);
						sp -= 2;
						ss->*sp = v50;
						v51 = ss->*((word16) bp - 52);
						sp -= 2;
						ss->*sp = v51;
						goto l31FF_114C;
					}
					ax = ss->*((word16) bp + 0x0C);
					ax |= ax;
					SZ = cond(ax);
					O = false;
					C = false;
					if (Test(EQ,Z))
						goto l31FF_1146;
					SCZO = cond(ax - 0x01);
					if (Test(EQ,Z))
					{
						v46 = ss->*((word16) bp - 50);
						sp -= 2;
						ss->*sp = v46;
						v47 = ss->*((word16) bp - 52);
						sp -= 2;
						ss->*sp = v47;
						ax.u0 = 0x96;
						goto l31FF_114F;
					}
					SCZO = cond(ax - 0x02);
					if (Test(EQ,Z))
					{
						sp -= 2;
						ss->*sp = dx;
						v48 = ss->*((word16) bp - 52);
						sp -= 2;
						ss->*sp = v48;
						ax.u0 = 0x9C;
						goto l31FF_114F;
					}
				}
				break;
			case 0x0D:
				SCZO = cond(ss->*((word16) bp - 264) - 0x00);
				if (Test(EQ,Z))
					goto l31FF_144B;
				Mem0[ds:0x1A2A:word16] = 1500;
				break;
			case 0x0E:
				si = ss->*((word16) bp - 6);
				si <<= 0x01;
				SCZO = cond(Mem0[ss:bp - 40 + si:word16] - 0x7B);
				if (Test(EQ,Z))
				{
					SCZO = cond(ss->*((word16) bp - 264) - 0x00);
					if (Test(NE,Z))
						goto l31FF_1488;
					Mem0[ds:0x1A2A:word16] = 1700;
				}
				else
				{
					si = ss->*((word16) bp - 6);
					si <<= 0x01;
					SCZO = cond(Mem0[ss:bp - 40 + si:word16] - 0x7D);
					if (Test(NE,Z))
					{
						SCZO = cond(ss->*((word16) bp - 6) - 0x00);
						if (Test(NE,Z))
						{
							SCZO = cond(ss->*((word16) bp - 264) - 0x00);
							if (Test(NE,Z))
								goto l31FF_135F;
							Mem0[ds:0x1A2A:word16] = 2000;
						}
						else
							Mem0[ds:0x1A2A:word16] = 2100;
					}
					else
					{
						SCZO = cond(ss->*((word16) bp - 264) - 0x00);
						if (Test(NE,Z))
						{
							si = ss->*((word16) bp - 6);
							ax = si;
							si <<= 0x01;
							si += ax;
							si <<= 0x01;
							si <<= 0x01;
							SCZO = cond(si);
							v30 = Mem0[ss:bp - 0xEC + si:word16] + 0x01;
							Mem0[ss:bp - 0xEC + si:word16] = v30;
							SZO = cond(v30);
							goto l31FF_14D0;
						}
						si = ss->*((word16) bp - 6);
						ax = si;
						si <<= 0x01;
						si += ax;
						si <<= 0x01;
						si <<= 0x01;
						SCZO = cond(Mem0[ss:bp - 0xEC + si:word16] - 0x00);
						if (Test(NE,Z))
							Mem0[ds:0x1A2A:word16] = 0x0708;
						else
						{
l31FF_14D0:
							si = ss->*((word16) bp - 6);
							ax = si;
							si <<= 0x01;
							si += ax;
							si <<= 0x01;
							si <<= 0x01;
							SCZO = cond(Mem0[ss:bp - 242 + si:word16] - 0x50);
							if (Test(EQ,Z))
							{
								si = ax;
								si <<= 0x01;
								si += ax;
								si <<= 0x01;
								si <<= 0x01;
								SCZO = cond(Mem0[ss:bp - 0xEC + si:word16] - 0x03);
								if (Test(EQ,Z))
								{
									si = ax;
									si <<= 0x01;
									si += ax;
									si <<= 0x01;
									si <<= 0x01;
									ax = Mem0[ss:bp - 0xEE + si:word16];
									ss->*((word16) bp - 48) = ax;
									ax += Mem0[ds:0x1A22:word16];
									dx = Mem0[ds:6692:word16];
									ax -= 0x02;
									ss->*((word16) bp - 46) = ax;
									ss->*((word16) bp - 44) = dx;
									es_bx = ss->*((word16) bp - 46);
									ax = Mem0[ds:6696:word16];
									ax -= ss->*((word16) bp - 48);
									SCZO = cond(ax);
									es->*bx = ax;
									goto l31FF_162D;
								}
								Mem0[ds:0x1A2A:word16] = 1900;
							}
							else
							{
								si = ss->*((word16) bp - 6);
								ax = si;
								si <<= 0x01;
								si += ax;
								si <<= 0x01;
								si <<= 0x01;
								SCZO = cond(Mem0[ss:bp - 242 + si:word16] - ~0x00);
								if (Test(EQ,Z))
								{
									si = ax;
									si <<= 0x01;
									si += ax;
									si <<= 0x01;
									si <<= 0x01;
									SCZO = cond(si);
									v34 = Mem0[ss:bp - 0xEC + si:word16];
									sp -= 2;
									ss->*sp = v34;
									ax.u0 = 0xC9;
									sp -= 2;
									ss->*sp = ax;
									fn31FF_0C14();
									sp = (word16) sp + 4;
									si = ss->*((word16) bp - 6);
									ax = si;
									si <<= 0x01;
									si += ax;
									si <<= 0x01;
									si <<= 0x01;
									SCZO = cond(si);
									v35 = Mem0[ss:bp - 244 + si:word16];
									sp -= 2;
									ss->*sp = v35;
									v36 = Mem0[ss:bp - 0xF6 + si:word16];
									sp -= 2;
									ss->*sp = v36;
									ax.u0 = 0xD8;
									sp -= 2;
									ss->*sp = ax;
									fn31FF_0DB8();
									sp = (word16) sp + 6;
									SCZO = cond(sp);
									ax.u0 = 0x46;
									goto l31FF_1625;
								}
								si = ss->*((word16) bp - 6);
								ax = si;
								si <<= 0x01;
								si += ax;
								si <<= 0x01;
								si <<= 0x01;
								ax = Mem0[ss:bp - 0xF0 + si:word16];
								si = ss->*((word16) bp - 6);
								cx = si;
								si <<= 0x01;
								si += cx;
								si <<= 0x01;
								si <<= 0x01;
								SCZO = cond(Mem0[ss:bp - 0xEC + si:word16] - ax);
								if (Test(GE,SO))
								{
									si = cx;
									ax = si;
									si <<= 0x01;
									si += ax;
									si <<= 0x01;
									si <<= 0x01;
									ax = Mem0[ss:bp - 0xEE + si:word16];
									si = cx;
									si <<= 0x01;
									si += cx;
									si <<= 0x01;
									si <<= 0x01;
									SCZO = cond(Mem0[ss:bp - 0xEC + si:word16] - ax);
									if (Test(GT,SZO))
										goto l31FF_15EC;
									ax.u0 = 0x01;
								}
								else
								{
l31FF_15EC:
									ax -= ax;
									SCZO = cond(ax);
								}
								ss->*((word16) bp - 8) = ax;
								ax |= ax;
								SZ = cond(ax);
								O = false;
								C = false;
								if (Test(NE,Z))
								{
									si = ss->*((word16) bp - 6);
									ax = si;
									si <<= 0x01;
									si += ax;
									si <<= 0x01;
									si <<= 0x01;
									ax = Mem0[ss:bp - 242 + si:word16];
									si = ss->*((word16) bp - 6);
									cx = si;
									si <<= 0x01;
									si += cx;
									si <<= 0x01;
									si <<= 0x01;
									ax += Mem0[ss:bp - 0xEC + si:word16];
									si = cx;
									si <<= 0x01;
									si += cx;
									si <<= 0x01;
									si <<= 0x01;
									ax -= Mem0[ss:bp - 0xF0 + si:word16];
									SCZO = cond(ax);
l31FF_1625:
									sp -= 2;
									ss->*sp = ax;
									fn31FF_0B72();
									sp = (word16) sp + 2;
									SCZO = cond(sp);
l31FF_162D:
									v33 = ss->*((word16) bp - 2) - 0x01;
									ss->*((word16) bp - 2) = v33;
									SZO = cond(v33);
									goto l31FF_1488;
								}
								Mem0[ds:0x1A2A:word16] = 0x0776;
							}
						}
					}
				}
				break;
			case 0x10:
				ax -= ax;
				SCZO = cond(ax);
				ss->*((word16) bp - 264) = ax;
				fn31FF_026E();
				ss->*((word16) bp - 4) = ax;
				SCZO = cond(ax - 122);
				if (Test(EQ,Z))
				{
					ax = bp - 262;
					sp -= 2;
					ss->*sp = ss;
					sp -= 2;
					ss->*sp = ax;
					fn2BC7_0494();
					sp = (word16) sp + 4;
					SCZO = cond(sp);
					sp -= 2;
					ss->*sp = dx;
					sp -= 2;
					ss->*sp = ax;
					ax.u0 = 0x96;
					sp -= 2;
					ss->*sp = ax;
					fn31FF_0DB8();
					sp = (word16) sp + 6;
					SCZO = cond(Mem0[ds:0x1A2A:word16] - 0x02);
					if (Test(EQ,Z))
					{
						Mem0[ds:0x1A2A:word16] = 0x04;
						ax.u0 = 0x1A3A;
						sp -= 2;
						ss->*sp = ds;
						sp -= 2;
						ss->*sp = ax;
						ax.u0 = 0x5EEC;
						sp -= 2;
						ss->*sp = ds;
						sp -= 2;
						ss->*sp = ax;
						ax = bp - 262;
						sp -= 2;
						ss->*sp = ss;
						sp -= 2;
						ss->*sp = ax;
						fn31FF_006A();
						sp = (word16) sp + 0x0C;
						SCZO = cond(sp);
					}
					v28 = (word32) (ss->*((word16) bp - 6)) + 1;
					ss->*((word16) bp - 6) = v28;
					si = ss->*((word16) bp - 6);
					si <<= 0x01;
					SCZO = cond(si);
					Mem0[ss:bp - 40 + si:word16] = 0x7E;
				}
				else
				{
					SCZO = cond(ss->*((word16) bp - 4) - 0x7B);
					if (Test(EQ,Z))
					{
						ax = bp - 262;
						sp -= 2;
						ss->*sp = ss;
						sp -= 2;
						ss->*sp = ax;
						fn2BC7_0494();
						sp = (word16) sp + 4;
						SCZO = cond(sp);
						sp -= 2;
						ss->*sp = dx;
						sp -= 2;
						ss->*sp = ax;
						ax.u0 = 0x96;
						sp -= 2;
						ss->*sp = ax;
						fn31FF_0DB8();
						sp = (word16) sp + 6;
						SCZO = cond(Mem0[ds:0x1A2A:word16] - 0x02);
						if (Test(EQ,Z))
						{
							Mem0[ds:0x1A2A:word16] = 0x04;
							ax.u0 = 0x5EF0;
							sp -= 2;
							ss->*sp = ds;
							sp -= 2;
							ss->*sp = ax;
							ax.u0 = 0x5EF2;
							sp -= 2;
							ss->*sp = ds;
							sp -= 2;
							ss->*sp = ax;
							ax = bp - 262;
							sp -= 2;
							ss->*sp = ss;
							sp -= 2;
							ss->*sp = ax;
							fn31FF_006A();
							sp = (word16) sp + 0x0C;
							SCZO = cond(sp);
						}
						ax.u0 = 100;
						sp -= 2;
						ss->*sp = ax;
						ax.u0 = 0x26;
						sp -= 2;
						ss->*sp = ax;
						fn31FF_0C14();
						sp = (word16) sp + 4;
						v29 = (word32) (ss->*((word16) bp - 6)) + 1;
						ss->*((word16) bp - 6) = v29;
						si = ss->*((word16) bp - 6);
						si <<= 0x01;
						SCZO = cond(si);
						Mem0[ss:bp - 40 + si:word16] = 0x04;
					}
					else
						Mem0[ds:0x1A2A:word16] = 1400;
				}
				break;
			case 0x12:
				SCZO = cond(ss->*((word16) bp - 264) - 0x00);
				if (Test(NE,Z))
					goto l31FF_144B;
				Mem0[ds:0x1A2A:word16] = 0x0640;
				break;
			case 0x13:
				si = ss->*((word16) bp - 6);
				si <<= 0x01;
				SCZO = cond(Mem0[ss:bp - 40 + si:word16] - 0x80);
				if (Test(EQ,Z))
				{
					SCZO = cond(ss->*((word16) bp - 264) - 0x00);
					if (Test(NE,Z))
					{
						ax.u0 = 0x07;
						sp -= 2;
						ss->*sp = ax;
						fn31FF_0B72();
						sp = (word16) sp + 2;
						SCZO = cond(sp);
						ax.u0 = 0x9D;
						sp -= 2;
						ss->*sp = ax;
						fn31FF_0B72();
						sp = (word16) sp + 2;
						SCZO = cond(sp);
l31FF_1488:
						v27 = ss->*((word16) bp - 6) - 0x01;
						ss->*((word16) bp - 6) = v27;
						SZO = cond(v27);
l31FF_148B:
						ax.u0 = 0x01;
						ss->*((word16) bp - 264) = ax;
						v26 = ss->*((word16) bp - 2);
						sp -= 2;
						ss->*sp = v26;
						fn31FF_065E();
						sp = (word16) sp + 2;
						SCZO = cond(sp);
						goto l31FF_133B;
					}
					Mem0[ds:0x1A2A:word16] = 2200;
				}
				else
				{
					si = ss->*((word16) bp - 6);
					si <<= 0x01;
					SCZO = cond(Mem0[ss:bp - 40 + si:word16] - 0x81);
					if (Test(EQ,Z))
					{
						v39 = ss->*((word16) bp - 6) - 0x01;
						ss->*((word16) bp - 6) = v39;
						SZO = cond(v39);
						(ss->*((word16) bp - 4)).u0 = 110;
					}
					else
					{
						SCZO = cond(ss->*((word16) bp - 6) - 0x00);
						if (Test(NE,Z))
						{
							SCZO = cond(ss->*((word16) bp - 264) - 0x00);
							if (Test(NE,Z))
								goto l31FF_135F;
							Mem0[ds:0x1A2A:word16] = 2300;
						}
						else
							Mem0[ds:0x1A2A:word16] = 0x0960;
					}
				}
				break;
			case 0x14:
				ax -= ax;
				SCZO = cond(ax);
				ss->*((word16) bp - 264) = ax;
				fn31FF_026E();
				ss->*((word16) bp - 4) = ax;
				SCZO = cond(ax - 122);
				if (Test(EQ,Z))
					ss->*((word16) bp - 54) = 0x01;
				else
					Mem0[ds:0x1A2A:word16] = 2500;
				break;
			case 22:
				goto l31FF_1331;
			case 0x17:
			case 0x25:
				goto l31FF_144B;
			case 0x18:
			case 0x19:
			case 0x1A:
			case 0x1B:
			case 0x1C:
			case 0x1D:
			case 0x1E:
			case 0x1F:
			case 0x20:
			case 33:
			case 0x22:
			case 0x23:
			case 0x24:
			case 0x26:
			case 0x27:
			case 0x28:
				v21 = ss->*((word16) bp - 4);
				sp -= 2;
				ss->*sp = v21;
				fn31FF_099C();
				sp = (word16) sp + 2;
				si = ss->*((word16) bp - 6);
				si <<= 0x01;
				SCZO = cond(si);
				v22 = Mem0[ss:bp - 40 + si:word16];
				sp -= 2;
				ss->*sp = v22;
				si = ax;
				fn31FF_099C();
				sp = (word16) sp + 2;
				SCZO = cond(ax - si);
				if (Test(UGE,C))
				{
l31FF_135F:
					si = ss->*((word16) bp - 6);
					v24 = ss->*((word16) bp - 6) - 0x01;
					ss->*((word16) bp - 6) = v24;
					si <<= 0x01;
					SCZO = cond(si);
					v25 = Mem0[ss:bp - 40 + si:word16];
					sp -= 2;
					ss->*sp = v25;
					fn31FF_0E18();
					sp = (word16) sp + 2;
					SCZO = cond(sp);
				}
				else
				{
l31FF_144B:
					v23 = (word32) (ss->*((word16) bp - 6)) + 1;
					ss->*((word16) bp - 6) = v23;
					si = ss->*((word16) bp - 6);
					si <<= 0x01;
					SCZO = cond(si);
					ax = ss->*((word16) bp - 4);
					Mem0[ss:bp - 40 + si:word16] = ax;
l31FF_1331:
					ax -= ax;
					SCZO = cond(ax);
					ss->*((word16) bp - 264) = ax;
					fn31FF_026E();
l31FF_133B:
					ss->*((word16) bp - 4) = ax;
				}
				break;
			}
		}
		SCZO = cond(ss->*((word16) bp - 6) - 0x0F);
		if (Test(UGE,C))
			Mem0[ds:0x1A2A:word16] = 0x03;
	}
	SCZO = cond(ss->*((word16) bp - 264) - 0x00);
	if (Test(EQ,Z))
	{
		SCZO = cond(Mem0[ds:0x1A2A:word16] - 0x00);
		if (Test(EQ,Z))
			Mem0[ds:0x1A2A:word16] = 2600;
	}
	SCZO = cond(Mem0[ds:0x1A2A:word16] - 0x02);
	if (Test(EQ,Z))
	{
		ax.u0 = 0x5EF6;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		ax.u0 = 24312;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		ax = bp - 262;
		sp -= 2;
		ss->*sp = ss;
		sp -= 2;
		ss->*sp = ax;
		fn31FF_006A();
		sp = (word16) sp + 0x0C;
		SCZO = cond(sp);
	}
	else
	{
		SCZO = cond(Mem0[ds:0x1A2A:word16] - 0x04);
		if (Test(EQ,Z))
			Mem0[ds:0x1A2A:word16] = 0x02;
	}
	ax.u0 = 0x34;
	sp -= 2;
	ss->*sp = ax;
	fn31FF_0B72();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	ax = Mem0[ds:0x1A2A:word16];
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 31FF:17DA: define fn31FF_17DA
// Called from:
//      fn31FF_1D44
//      fn31FF_207C
define fn31FF_17DA
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x2A;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	es_bx = ds->t1296;
	ax = es->*((word16) bx + 8);
	dx = es->*((word16) bx + 0x0A);
	ss->*((word16) bp - 18) = ax;
	ss->*((word16) bp - 16) = dx;
	ax = es->*((word16) bx + 0x0C);
	ss->*((word16) bp - 20) = ax;
	ax = es->*((word16) bx + 2);
	ss->*((word16) bp - 40) = ax;
	ax.u0 = 0x26;
	sp -= 2;
	ss->*sp = ax;
	v14 = ss->*((word16) bp - 40);
	sp -= 2;
	ss->*sp = v14;
	sp -= 2;
	ss->*sp = dx;
	v15 = ss->*((word16) bp - 18);
	sp -= 2;
	ss->*sp = v15;
	fn2017_035B();
	sp = (word16) sp + 8;
	SCZO = cond(sp);
	ss->*((word16) bp - 2) = ax;
	while (true)
	{
		ax = ss->*((word16) bp - 40);
		SCZO = cond(ss->*((word16) bp - 2) - ax);
		if (Test(UGE,C))
			break;
		v17 = (word32) (ss->*((word16) bp - 2)) + 1;
		ss->*((word16) bp - 2) = v17;
		ax = ss->*((word16) bp - 40);
		SCZO = cond(ss->*((word16) bp - 2) - ax);
		if (Test(ULT,C))
		{
			bx = ss->*((word16) bp - 2);
			es_si = ss->*((word16) bp - 18);
			al = Mem0[es:bx + si:byte];
			ss->*((word16) bp - 42) = al;
			ah -= ah;
			SCZO = cond(ah);
			sp -= 2;
			ss->*sp = ax;
			fn38AD_0040();
			sp = (word16) sp + 2;
			SZP = cond(al & 0x01);
			O = false;
			C = false;
			if (Test(EQ,Z))
			{
				SCZO = cond(ss->*((word16) bp - 42) - 0x5F);
				if (Test(NE,Z))
					goto l31FF_1998;
			}
			ax = bp - 36;
			sp -= 2;
			ss->*sp = ss;
			sp -= 2;
			ss->*sp = ax;
			ax = ss->*((word16) bp - 40);
			ax -= ss->*((word16) bp - 2);
			sp -= 2;
			ss->*sp = ax;
			ax = ss->*((word16) bp - 2);
			ax += Mem0[ss:bp + -18:word16];
			SCZO = cond(ax);
			dx = ss->*((word16) bp - 16);
			sp -= 2;
			ss->*sp = dx;
			sp -= 2;
			ss->*sp = ax;
			fn31FF_0106();
			sp = (word16) sp + 0x0A;
			SCZO = cond(sp);
			ss->*((word16) bp - 24) = ax;
			ax = bp - 36;
			sp -= 2;
			ss->*sp = ss;
			sp -= 2;
			ss->*sp = ax;
			fn2BC7_0494();
			sp = (word16) sp + 4;
			ss->*((word16) bp - 0x0C) = ax;
			ss->*((word16) bp - 0x0A) = dx;
			ax |= dx;
			SZ = cond(ax);
			O = false;
			C = false;
			if (Test(EQ,Z))
			{
l31FF_1992:
				ax = ss->*((word16) bp - 24);
				v27 = Mem0[ss:bp + -2:word16] + ax;
				ss->*((word16) bp - 2) = v27;
				SCZO = cond(v27);
				goto l31FF_1998;
			}
			es_bx = ss->*((word16) bp - 0x0C);
			ax = es->*((word16) bx + 4);
			ax |= es->*((word16) bx + 6);
			SZ = cond(ax);
			O = false;
			C = false;
			if (Test(EQ,Z))
				goto l31FF_1992;
			es_bx = es->*((word16) bx + 4);
			SZP = cond(es->*bx & 0x0100);
			O = false;
			C = false;
			if (Test(EQ,Z))
				goto l31FF_1992;
			si = ss->*((word16) bp - 2);
			si += Mem0[ss:bp + -24:word16];
			SCZO = cond(ss->*((word16) bp - 40) - si);
			if (Test(UGT,CZ))
			{
				es_bx = ss->*((word16) bp - 18);
				SCZO = cond(Mem0[es:bx + si:byte] - 0x2E);
				if (Test(EQ,Z))
				{
					v29 = (word32) (ss->*((word16) bp - 24)) + 1;
					ss->*((word16) bp - 24) = v29;
					SZO = cond(v29);
				}
			}
			es_bx = ss->*((word16) bp - 0x0C);
			es_bx = es->*((word16) bx + 4);
			ax = es->*((word16) bx + 2);
			ss->*((word16) bp - 22) = ax;
			ax = ss->*((word16) bp - 40);
			ax -= ss->*((word16) bp - 24);
			ax += Mem0[ss:bp + -22:word16];
			--ax;
			ss->*((word16) bp - 0x0E) = ax;
			ax = ss->*((word16) bp - 2);
			ax += Mem0[ss:bp + -24:word16];
			SCZO = cond(ax);
			ss->*((word16) bp - 38) = ax;
			ax = ss->*((word16) bp - 0x0E);
			ax = (word32) ax.u0 + 1;
			SZO = cond(ax);
			ss->*((word16) bp - 8) = ax;
			sp -= 2;
			ss->*sp = ax;
			fn21DC_0718();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
			ss->*((word16) bp - 6) = ax;
			ss->*((word16) bp - 4) = dx;
			bx = ss->*((word16) bp - 0x0E);
			es_si = ss->*((word16) bp - 6);
			Mem0[es:bx + si:byte] = 0x00;
			v30 = ss->*((word16) bp - 2) - 0x01;
			ss->*((word16) bp - 2) = v30;
			SZO = cond(v30);
			v31 = ss->*((word16) bp - 2);
			sp -= 2;
			ss->*sp = v31;
			v32 = ss->*((word16) bp - 16);
			sp -= 2;
			ss->*sp = v32;
			v33 = ss->*((word16) bp - 18);
			sp -= 2;
			ss->*sp = v33;
			sp -= 2;
			ss->*sp = dx;
			sp -= 2;
			ss->*sp = ax;
			fn2017_02EC();
			sp = (word16) sp + 0x0A;
			v34 = ss->*((word16) bp - 22);
			sp -= 2;
			ss->*sp = v34;
			es_bx = ss->*((word16) bp - 0x0C);
			es_bx = es->*((word16) bx + 4);
			v35 = es->*((word16) bx + 8);
			sp -= 2;
			ss->*sp = v35;
			v36 = es->*((word16) bx + 6);
			sp -= 2;
			ss->*sp = v36;
			ax = ss->*((word16) bp - 2);
			ax += si;
			SCZO = cond(ax);
			dx = ss->*((word16) bp - 4);
			sp -= 2;
			ss->*sp = dx;
			sp -= 2;
			ss->*sp = ax;
			fn2017_02EC();
			sp = (word16) sp + 0x0A;
			ax = ss->*((word16) bp - 40);
			ax -= ss->*((word16) bp - 38);
			sp -= 2;
			ss->*sp = ax;
			ax = ss->*((word16) bp - 38);
			ax += Mem0[ss:bp + -18:word16];
			dx = ss->*((word16) bp - 16);
			sp -= 2;
			ss->*sp = dx;
			sp -= 2;
			ss->*sp = ax;
			ax = ss->*((word16) bp - 2);
			ax += Mem0[ss:bp + -22:word16];
			ax += si;
			SCZO = cond(ax);
			dx = ss->*((word16) bp - 4);
			sp -= 2;
			ss->*sp = dx;
			sp -= 2;
			ss->*sp = ax;
			fn2017_02EC();
			sp = (word16) sp + 0x0A;
			SCZO = cond(ss->*((word16) bp - 20) - 0x00);
			if (Test(NE,Z))
			{
				v37 = ss->*((word16) bp - 20);
				sp -= 2;
				ss->*sp = v37;
				v38 = ss->*((word16) bp - 16);
				sp -= 2;
				ss->*sp = v38;
				v39 = ss->*((word16) bp - 18);
				sp -= 2;
				ss->*sp = v39;
				fn21DC_074E();
				sp = (word16) sp + 6;
				SCZO = cond(sp);
			}
			ax = ss->*((word16) bp - 6);
			dx = ss->*((word16) bp - 4);
			ss->*((word16) bp - 18) = ax;
			ss->*((word16) bp - 16) = dx;
			ax = ss->*((word16) bp - 8);
			ss->*((word16) bp - 20) = ax;
			ax = ss->*((word16) bp - 0x0E);
			ss->*((word16) bp - 40) = ax;
		}
l31FF_1998:
		ax.u0 = 0x26;
		sp -= 2;
		ss->*sp = ax;
		ax = ss->*((word16) bp - 40);
		ax -= ss->*((word16) bp - 2);
		sp -= 2;
		ss->*sp = ax;
		ax = ss->*((word16) bp - 2);
		ax += Mem0[ss:bp + -18:word16];
		SCZO = cond(ax);
		dx = ss->*((word16) bp - 16);
		sp -= 2;
		ss->*sp = dx;
		sp -= 2;
		ss->*sp = ax;
		fn2017_035B();
		sp = (word16) sp + 8;
		v25 = Mem0[ss:bp + -2:word16] + ax;
		ss->*((word16) bp - 2) = v25;
		SCZO = cond(v25);
	}
	es_bx = ds->t1296;
	ax = ss->*((word16) bp - 18);
	dx = ss->*((word16) bp - 16);
	es->*((word16) bx + 8) = ax;
	es->*((word16) bx + 0x0A) = dx;
	ax = ss->*((word16) bp - 20);
	es->*((word16) bx + 0x0C) = ax;
	ax = ss->*((word16) bp - 40);
	es->*((word16) bx + 2) = ax;
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 31FF:19EA: define fn31FF_19EA
// Called from:
//      fn31FF_1B0A
define fn31FF_19EA
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x14;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	(ss->*((word16) bp - 2)).u0 = 0x01;
	while (true)
	{
		ax = ds->t1A4A;
		SCZO = cond(ss->*((word16) bp - 2) - ax);
		if (Test(UGE,C))
			break;
		si = ss->*((word16) bp - 2);
		cl = 0x03;
		si <<= cl;
		es_bx = ds->t1A46;
		SCZO = cond(Mem0[es:bx + 6 + si:word16] - 0x00);
		if (Test(EQ,Z))
			break;
		v18 = (word32) (ss->*((word16) bp - 2)) + 1;
		ss->*((word16) bp - 2) = v18;
		SZO = cond(v18);
	}
	ax = ds->t1A4A;
	SCZO = cond(ss->*((word16) bp - 2) - ax);
	if (Test(EQ,Z))
	{
		ax = (word16) ax + 64;
		ss->*((word16) bp - 8) = ax;
		cl = 0x03;
		ax <<= cl;
		SCZO = cond(ax);
		ss->*((word16) bp - 0x0A) = ax;
		sp -= 2;
		ss->*sp = ax;
		ax = bp - 6;
		sp -= 2;
		ss->*sp = ss;
		sp -= 2;
		ss->*sp = ax;
		fn21DC_0696();
		sp = (word16) sp + 6;
		ax |= ax;
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
l31FF_1B02:
			ax -= ax;
			SCZO = cond(ax);
			si = ss->*sp;
			sp = bp;
			bp = ss->*sp;
			sp = (word16) sp + 2;
			return;
		}
		v20 = ss->*((word16) bp - 0x0A);
		sp -= 2;
		ss->*sp = v20;
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		v21 = ss->*((word16) bp - 4);
		sp -= 2;
		ss->*sp = v21;
		v22 = ss->*((word16) bp - 6);
		sp -= 2;
		ss->*sp = v22;
		fn2017_0228();
		sp = (word16) sp + 8;
		SCZO = cond(sp);
		v23 = ds->t1A4C;
		sp -= 2;
		ss->*sp = v23;
		v24 = ds->t1A48;
		sp -= 2;
		ss->*sp = v24;
		v25 = ds->t1A46;
		sp -= 2;
		ss->*sp = v25;
		v26 = ss->*((word16) bp - 4);
		sp -= 2;
		ss->*sp = v26;
		v27 = ss->*((word16) bp - 6);
		sp -= 2;
		ss->*sp = v27;
		fn2017_02EC();
		sp = (word16) sp + 0x0A;
		SCZO = cond(sp);
		v28 = ds->t1A4C;
		sp -= 2;
		ss->*sp = v28;
		v29 = ds->t1A48;
		sp -= 2;
		ss->*sp = v29;
		v30 = ds->t1A46;
		sp -= 2;
		ss->*sp = v30;
		fn21DC_0702();
		sp = (word16) sp + 6;
		SCZO = cond(sp);
		ax = ss->*((word16) bp - 6);
		dx = ss->*((word16) bp - 4);
		ds->t1A46 = ax;
		ds->t1A48 = dx;
		ax = ss->*((word16) bp - 8);
		ds->t1A4A = ax;
		ax = ss->*((word16) bp - 0x0A);
		ds->t1A4C = ax;
	}
	v32 = ds->t1A28;
	sp -= 2;
	ss->*sp = v32;
	ax = bp - 16;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	fn21DC_0696();
	sp = (word16) sp + 6;
	ax |= ax;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		v33 = ds->t1A28;
		sp -= 2;
		ss->*sp = v33;
		v34 = ds->t1A24;
		sp -= 2;
		ss->*sp = v34;
		v35 = ds->t1A22;
		sp -= 2;
		ss->*sp = v35;
		v36 = ss->*((word16) bp - 0x0E);
		sp -= 2;
		ss->*sp = v36;
		v37 = ss->*((word16) bp - 16);
		sp -= 2;
		ss->*sp = v37;
		fn2017_02EC();
		sp = (word16) sp + 0x0A;
		ax = ss->*((word16) bp - 2);
		cl = 0x03;
		ax <<= cl;
		ax += Mem0[ds:6726:word16];
		SCZO = cond(ax);
		dx = ds->t1A48;
		ss->*((word16) bp - 20) = ax;
		ss->*((word16) bp - 18) = dx;
		es_bx = ss->*((word16) bp - 20);
		ax = ss->*((word16) bp - 16);
		dx = ss->*((word16) bp - 0x0E);
		(es->*bx).t0000.u2 = (struct Eq_238122 *) ax;
		(es->*bx).t0002.u2 = (struct Eq_238122 *) dx;
		ax = ds->t1A28;
		(es->*bx).t0004.u2 = (struct Eq_238122 *) ax;
		(es->*bx).a0006[0].u2 = (struct Eq_238122 *) ax;
		ax = ss->*((word16) bp - 2);
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
		return;
	}
	goto l31FF_1B02;
}

// 31FF:1B0A: define fn31FF_1B0A
// Called from:
//      fn31FF_1CE2
define fn31FF_1B0A
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_107308 Eq_107315::*) bp;
	bp = sp;
	sp -= 0x04;
	SCZO = cond(sp);
	v7 = (struct Eq_107308 Eq_107315::*) (ss->*bp).ptr000A;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_107308 Eq_107315::*) v7;
	v8 = (struct Eq_107308 Eq_107315::*) (ss->*bp).ptr0008;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_107308 Eq_107315::*) v8;
	v9 = (struct Eq_107308 Eq_107315::*) (ss->*bp).ptr0006;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_107308 Eq_107315::*) v9;
	fn38AD_0118();
	sp = (struct Eq_107308 Eq_107315::*) &sp->ptr0006;
	SCZO = cond(ax - (ss->*bp).ptr000A);
	if (Test(NE,Z))
	{
		v13 = (struct Eq_107308 Eq_107315::*) (ss->*bp).ptr000C;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_107308 Eq_107315::*) v13;
		v14 = (struct Eq_107308 Eq_107315::*) (ss->*bp).ptr000A;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_107308 Eq_107315::*) v14;
		v15 = (struct Eq_107308 Eq_107315::*) (ss->*bp).ptr0008;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_107308 Eq_107315::*) v15;
		v16 = (struct Eq_107308 Eq_107315::*) (ss->*bp).ptr0006;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_107308 Eq_107315::*) v16;
		fn31FF_0F20();
		sp = (struct Eq_107308 Eq_107315::*) &sp->ptr0008;
		(ss->*bp).wFFFFFFFC = ax;
		ax |= ax;
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
			fn31FF_19EA();
			(ss->*bp).wFFFFFFFE = ax;
			sp = bp;
			bp = (struct Eq_107308 Eq_107315::*) (ss->*sp).ptr0000;
			sp = (struct Eq_107308 Eq_107315::*) &sp->ptr0000;
			return;
		}
		SCZO = cond(ax - 0x02);
		if (Test(EQ,Z))
		{
			ds->w10D2 = 0x02;
l31FF_1B2C:
			ax -= ax;
			SCZO = cond(ax);
			sp = bp;
			bp = (struct Eq_107308 Eq_107315::*) (ss->*sp).ptr0000;
			sp = (struct Eq_107308 Eq_107315::*) &sp->ptr0000;
			return;
		}
	}
	ds->w10D2 = 0x09;
	goto l31FF_1B2C;
}

// 31FF:1B66: define fn31FF_1B66
// Called from:
//      fn31FF_1BE6
define fn31FF_1B66
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x40;
	sp -= 2;
	ss->*sp = si;
	SCZO = cond(ss->*((word16) bp + 6) - 0x00);
	if (Test(EQ,Z))
	{
		v17 = Mem0[ds:0x1296:word16] + 0x10;
		Mem0[ds:0x1296:word16] = v17;
		SCZO = cond(v17);
		es_bx = Mem0[ds:0x1296:segptr32];
		es->*bx = 0x00;
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
	else
	{
		ax.u0 = 0x40;
		sp -= 2;
		ss->*sp = ax;
		ax.u0 = 0x129A;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		ax = bp - 64;
		sp -= 2;
		ss->*sp = ss;
		sp -= 2;
		ss->*sp = ax;
		fn2017_02EC();
		sp = (word16) sp + 0x0A;
		ax.u0 = 0x40;
		sp -= 2;
		ss->*sp = ax;
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		ax.u0 = 0x129A;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		fn2017_0228();
		sp = (word16) sp + 8;
		bx = ss->*((word16) bp + 6);
		cl = 0x03;
		bx <<= cl;
		SCZO = cond(bx);
		es_si = Mem0[ds:6726:segptr32];
		v15 = es->*((word16) si + ((word16) bx + 2));
		sp -= 2;
		ss->*sp = v15;
		v16 = Mem0[es:bx + si:word16];
		sp -= 2;
		ss->*sp = v16;
		fn3BC2_009D();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		ax.u0 = 0x40;
		sp -= 2;
		ss->*sp = ax;
		ax = bp - 64;
		sp -= 2;
		ss->*sp = ss;
		sp -= 2;
		ss->*sp = ax;
		ax.u0 = 0x129A;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		fn2017_02EC();
		sp = (word16) sp + 0x0A;
		SCZO = cond(sp);
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 31FF:1BE6: define fn31FF_1BE6
// Called from:
//      fn2644_2384
//      fn2644_24C0
//      fn2EB3_2340
//      fn31FF_1CE2
define fn31FF_1BE6
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_107680 Eq_107687::*) bp;
	bp = sp;
	sp -= 0x02;
	ax = ds->w10D4;
	(ss->*bp).wFFFFFFFE = ax;
	ax = (ss->*bp).w0008;
	v9 = ds->w10D4 | ax;
	ds->w10D4 = v9;
	SZ = cond(ds->w10D4);
	O = false;
	C = false;
	v13 = (struct Eq_107680 Eq_107687::*) (ss->*bp).ptr0006;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_107680 Eq_107687::*) v13;
	fn31FF_1B66();
	ax = (ss->*bp).wFFFFFFFE;
	ds->w10D4 = ax;
	sp = bp;
	bp = (struct Eq_107680 Eq_107687::*) (ss->*sp).ptr0000;
	sp = (struct Eq_107680 Eq_107687::*) &sp->ptr0000;
}

// 31FF:1C0A: define fn31FF_1C0A
// Called from:
//      fn2644_45CA
//      fn2EB3_0002
//      fn31FF_1CE2
define fn31FF_1C0A
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_107748 Eq_107755::*) bp;
	bp = sp;
	sp -= 0x04;
	SCZO = cond((ss->*bp).t0006.u0 - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = (ss->*bp).t0006.u0;
		cl = 0x03;
		ax <<= cl;
		ax = (word16) ax.u0 + ds->w1A46;
		dx = ds->w1A48;
		(ss->*bp).tFFFFFFFC.u0 = (ui16) ax;
		(ss->*bp).wFFFFFFFE = dx;
		es_bx.u2 = (ss->*bp).tFFFFFFFC.u2;
		SCZO = cond((es->*bx).ptr0004 - 0x00);
		if (Test(NE,Z))
		{
			v15 = (es->*bx).ptr0004;
			sp -= 2;
			(ss->*sp).ptr0000 = (struct Eq_107748 Eq_107755::*) v15;
			v16 = (es->*bx).ptr0002;
			sp -= 2;
			(ss->*sp).ptr0000 = (struct Eq_107748 Eq_107755::*) v16;
			v17 = (es->*bx).ptr0000;
			sp -= 2;
			(ss->*sp).ptr0000 = (struct Eq_107748 Eq_107755::*) v17;
			fn21DC_0702();
			sp = (struct Eq_107748 Eq_107755::*) &sp->t0006.u0;
			SCZO = cond(sp);
		}
		ax.u0 = (ss->*bp).t0006.u0;
		cl = 0x03;
		ax <<= cl;
		ax = (word16) ax.u0 + ds->w1A46;
		SCZO = cond(ax);
		dx = ds->w1A48;
		(ss->*bp).tFFFFFFFC.u0 = (ui16) ax;
		(ss->*bp).wFFFFFFFE = dx;
		es_bx.u2 = (ss->*bp).tFFFFFFFC.u2;
		(es->*bx).w0006 = 0x00;
		(es->*bx).ptr0004 = &Eq_107755::t0000;
	}
	sp = bp;
	bp = (struct Eq_107748 Eq_107755::*) (ss->*sp).ptr0000;
	sp = (struct Eq_107748 Eq_107755::*) &sp->ptr0000;
}

// 31FF:1CE2: define fn31FF_1CE2
// Called from:
//      fn31FF_1D44
define fn31FF_1CE2
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x0C;
	SCZO = cond(sp);
	es_bx = ds->t1296;
	ax.u0 = (es->*bx).t0008.u0;
	dx.u0 = (es->*bx).t000A.u0;
	ss->*((word16) bp - 6) = ax;
	ss->*((word16) bp - 4) = dx;
	ax.u0 = (es->*bx).t0002.u0;
	ss->*((word16) bp - 0x0C) = ax;
	v13 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v13;
	sp -= 2;
	ss->*sp = ax;
	sp -= 2;
	ss->*sp = dx;
	v14 = ss->*((word16) bp - 6);
	sp -= 2;
	ss->*sp = v14;
	fn31FF_1B0A();
	sp = (word16) sp + 8;
	ss->*((word16) bp - 2) = ax;
	ax |= ax;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		fn2368_033C();
		ax.u0 = 0x01;
		sp -= 2;
		ss->*sp = ax;
		v19 = ss->*((word16) bp - 2);
		sp -= 2;
		ss->*sp = v19;
		fn31FF_1BE6();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		v20 = ss->*((word16) bp - 2);
		sp -= 2;
		ss->*sp = v20;
		fn31FF_1C0A();
		sp = (word16) sp + 2;
		SCZO = cond(sp);
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
	else
	{
		ds->w10D6 = 0x01;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 31FF:1D44: define fn31FF_1D44
// Called from:
//      fn1825_4DA6
//      fn1825_5FCA
//      fn1825_6078
//      fn3CEE_4490
//      fn3CEE_5556
define fn31FF_1D44
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_108045 Eq_108052::*) bp;
	bp = sp;
	sp -= 0x02;
	es_bx = ds->t1296;
	SZP = cond(es->*bx & 0x0100);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
		ds->w10D2 = 0x01;
		sp = bp;
		bp = (struct Eq_108045 Eq_108052::*) (ss->*sp).ptr0000;
		sp = (struct Eq_108045 Eq_108052::*) &sp->ptr0000;
	}
	else
	{
		fn31FF_17DA();
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_108045 Eq_108052::*) ax;
		fn31FF_1CE2();
		sp = (struct Eq_108045 Eq_108052::*) &sp->ptr0000;
		SCZO = cond(sp);
		sp = bp;
		bp = (struct Eq_108045 Eq_108052::*) (ss->*sp).ptr0000;
		sp = (struct Eq_108045 Eq_108052::*) &sp->ptr0000;
	}
}

// 31FF:207C: define fn31FF_207C
// Called from:
//      fn1825_6042
define fn31FF_207C
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x54;
	v7 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v7;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	v9 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v9;
	v10 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v10;
	fn2368_0272();
	sp = (word16) sp + 8;
	SCZO = cond(sp);
	fn31FF_17DA();
	Mem0[ds:6696:word16] = 0x00;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	es_bx = Mem0[ds:0x1296:segptr32];
	v15 = es->*((word16) bx + 2);
	sp -= 2;
	ss->*sp = v15;
	v16 = es->*((word16) bx + 0x0A);
	sp -= 2;
	ss->*sp = v16;
	v17 = es->*((word16) bx + 8);
	sp -= 2;
	ss->*sp = v17;
	fn31FF_0F20();
	sp = (word16) sp + 8;
	SCZO = cond(sp);
	ss->*((word16) bp - 0x0C) = ax;
	fn2368_033C();
	SCZO = cond(ss->*((word16) bp - 0x0C) - 0x00);
	if (Test(NE,Z))
	{
l31FF_20CF:
		SCZO = cond(ss->*((word16) bp - 0x0C) - 0x02);
		if (Test(EQ,Z))
			(ss->*((word16) bp - 0x0C)).u0 = ~0x00;
		else
			(ss->*((word16) bp - 0x0C)).u0 = ~0x02;
		goto l31FF_2240;
	}
	SCZO = cond(Mem0[ds:6696:word16] - 0x00);
	if (Test(EQ,Z))
		goto l31FF_20CF;
	ax = Mem0[ds:0x1296:word16];
	dx = Mem0[ds:0x1298:word16];
	ss->*((word16) bp - 6) = ax;
	ss->*((word16) bp - 4) = dx;
	ax.u0 = 0x40;
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x129A;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	ax = bp - 84;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	fn2017_02EC();
	sp = (word16) sp + 0x0A;
	ax.u0 = 0x40;
	sp -= 2;
	ss->*sp = ax;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x129A;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2017_0228();
	sp = (word16) sp + 8;
	SCZO = cond(sp);
	ax = Mem0[ds:0x1A22:word16];
	dx = Mem0[ds:6692:word16];
	ss->*((word16) bp - 20) = ax;
	ss->*((word16) bp - 18) = dx;
	ax = Mem0[ds:6696:word16];
	ss->*((word16) bp - 16) = ax;
	while (true)
	{
		SCZO = cond(ss->*((word16) bp - 16) - 0x00);
		if (Test(EQ,Z))
			break;
		SCZO = cond(ss->*((word16) bp - 0x0C) - 0x00);
		if (Test(NE,Z))
			break;
		es_bx = ss->*((word16) bp - 20);
		al = es->*bx;
		ah -= ah;
		SCZO = cond(ax - 0x34);
		if (Test(NE,Z))
		{
			SCZO = cond(ax - 0x46);
			if (Test(EQ,Z))
			{
				ax = ss->*((word16) bp - 20);
				dx = (cui16) (ss->*((word16) bp - 18));
				ax.u0 = (byte) ax.u0 + 1;
				ss->*((word16) bp - 0x0A) = ax;
				ss->*((word16) bp - 8) = dx;
				ax |= dx;
				SZ = cond(ax);
				O = false;
				C = false;
				if (Test(NE,Z))
				{
					es_bx = ss->*((word16) bp - 0x0A);
					ax = es->*((word16) bx + 0x0E);
					ax |= es->*((word16) bx + 16);
					SZ = cond(ax);
					O = false;
					C = false;
					if (Test(NE,Z))
					{
l31FF_21A8:
						(ss->*((word16) bp - 0x0C)).u0 = ~0x01;
						continue;
					}
				}
				(ss->*((word16) bp - 0x0C)).u0 = ~0x00;
				continue;
			}
			SCZO = cond(ax - 0x51);
			if (Test(UGE,C))
			{
				SCZO = cond(ax - 0x52);
				if (Test(UGT,CZ))
					goto l31FF_2159;
				goto l31FF_21A8;
			}
l31FF_2159:
			sp -= 2;
			ss->*sp = es;
			sp -= 2;
			ss->*sp = bx;
			fn3BC2_013E();
			sp = (word16) sp + 4;
			ss->*((word16) bp - 0x0E) = ax;
			SCZO = cond(Mem0[ds:0x10D2:word16] - 0x00);
			if (Test(EQ,Z))
			{
				ax = ss->*((word16) bp - 0x0E);
				v28 = ss->*((word16) bp - 16) - ax;
				ss->*((word16) bp - 16) = v28;
				v29 = Mem0[ss:bp + -20:word16] + ax;
				ss->*((word16) bp - 20) = v29;
				SCZO = cond(v29);
				continue;
			}
			SCZO = cond(Mem0[ds:0x10D2:word16] - 0x02);
			if (Test(NE,Z))
			{
				SCZO = cond(Mem0[ds:0x10D2:word16] - 0x07);
				if (Test(EQ,Z))
					goto l31FF_217B;
				(ss->*((word16) bp - 0x0C)).u0 = ~0x02;
			}
			else
			{
l31FF_217B:
				(ss->*((word16) bp - 0x0C)).u0 = ~0x00;
			}
			Mem0[ds:0x10D2:word16] = 0x00;
			continue;
		}
		(ss->*((word16) bp - 16)).u0 = 0x00;
	}
	SCZO = cond(ss->*((word16) bp - 0x0C) - 0x00);
	if (Test(EQ,Z))
	{
		ax = ss->*((word16) bp - 6);
		dx = (cui16) (ss->*((word16) bp - 4));
		ax.u0 = (byte) ax.u0 + 16;
		SCZO = cond(ax - Mem0[ds:0x1296:word16]);
		if (Test(NE,Z))
		{
l31FF_21F3:
			(ss->*((word16) bp - 0x0C)).u0 = ~0x02;
			goto l31FF_2216;
		}
		SCZO = cond(dx - Mem0[ds:0x1298:word16]);
		if (Test(NE,Z))
			goto l31FF_21F3;
		es_bx = Mem0[ds:0x1296:segptr32];
		SZP = cond(es->*bx & 0x0800);
		O = false;
		C = false;
		if (Test(NE,Z))
			es_bx = es->*((word16) bx + 8);
		else
			es_bx = Mem0[ds:0x1296:segptr32];
		ax = es->*bx;
		ss->*((word16) bp - 2) = ax;
	}
l31FF_2216:
	while (true)
	{
		ax = Mem0[ds:0x1296:word16];
		dx = Mem0[ds:0x1298:word16];
		SCZO = cond(ss->*((word16) bp - 6) - ax);
		if (Test(UGE,C))
			break;
		fn2368_033C();
	}
	ax.u0 = 0x40;
	sp -= 2;
	ss->*sp = ax;
	ax = bp - 84;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 0x129A;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn2017_02EC();
	sp = (word16) sp + 0x0A;
	SCZO = cond(sp);
l31FF_2240:
	SCZO = cond(ss->*((word16) bp - 0x0C) - 0x00);
	if (Test(NE,Z))
	{
		ax = ss->*((word16) bp - 0x0C);
		ss->*((word16) bp - 2) = ax;
	}
	ax = ss->*((word16) bp - 2);
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

