// 1999_SOFT_LOAN__2368.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 2368:0002: define fn2368_0002
// Called from:
//      fn21DC_0EC2
define fn2368_0002
{
	sp = fp;
	Top = 0;
	ax = (struct Eq_60165 *) seg0800;
	sp -= 2;
	ss->*sp = (struct Eq_60165 * Eq_60169::*) ax;
	ax = 0x1292;
	sp -= 2;
	ss->*sp = (struct Eq_60165 * Eq_60169::*) ds;
	sp -= 2;
	ss->*sp = (struct Eq_60165 * Eq_60169::*) ax;
	fn21DC_06DC();
	sp = (struct Eq_60165 * Eq_60169::*) ((char *) sp + 6);
	ax |= ax;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
		ax -= ax;
		SCZO = cond(ax);
	}
	else
	{
		ax = (struct Eq_60165 *) seg0800;
		sp -= 2;
		ss->*sp = (struct Eq_60165 * Eq_60169::*) ax;
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = (struct Eq_60165 * Eq_60169::*) ax;
		v12 = ds->ptr1294;
		sp -= 2;
		ss->*sp = (struct Eq_60165 * Eq_60169::*) v12;
		v13 = ds->ptr1292;
		sp -= 2;
		ss->*sp = (struct Eq_60165 * Eq_60169::*) v13;
		fn2017_0228();
		sp = (struct Eq_60165 * Eq_60169::*) ((char *) sp + 8);
		SCZO = cond(sp);
		ax = ds->ptr1292;
		dx = ds->ptr1294;
		ds->ptr1296 = ax;
		ds->ptr1298 = dx;
		ax = 0x01;
	}
}

// 2368:00D4: define fn2368_00D4
// Called from:
//      fn1825_48D2
//      fn1825_496A
define fn2368_00D4
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x04;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = di;
	sp -= 2;
	ss->*sp = si;
	es_bx = ss->*((word16) bp + 6);
	es->*bx = 0x0100;
	ax = ss->*((word16) bp + 0x0A);
	es->*((word16) bx + 2) = ax;
	si = ax;
	si = (word16) si + 1;
	SZO = cond(si);
	sp -= 2;
	ss->*sp = si;
	fn21DC_0718();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	ss->*((word16) bp - 4) = ax;
	ss->*((word16) bp - 2) = dx;
	bx = ss->*((word16) bp + 0x0A);
	es_di = ss->*((word16) bp - 4);
	Mem0[es:bx + di:byte] = 0x00;
	es_bx = ss->*((word16) bp + 6);
	es->*((word16) bx + 8) = ax;
	es->*((word16) bx + 0x0A) = dx;
	es->*((word16) bx + 0x0C) = si;
	si = ss->*sp;
	sp = (word16) sp + 2;
	di = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2368:01B0: define fn2368_01B0
// Called from:
//      fn3CEE_8634
define fn2368_01B0
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_60376 Eq_60383::*) bp;
	bp = sp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_60376 Eq_60383::*) di;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_60376 Eq_60383::*) si;
	v9 = (word32) ds->t1296 + 16;
	ds->t1296 = v9;
	SCZO = cond(v9);
	es_bx = ds->t1296;
	(es->*bx).ptr0000 = &Eq_60383::t0008;
	ax = (ss->*bp).w000E;
	(es->*bx).w0002 = ax;
	ax = (ss->*bp).w0010;
	(es->*bx).w0004 = ax;
	di = (struct Eq_60376 Eq_60383::*) (&bx->w0004 + 2);
	si = &bp->w0004 + 1;
	v15 = (struct Eq_60376 Eq_60383::*) (ds->*si).ptr0000;
	(es->*di).ptr0000 = (struct Eq_60376 Eq_60383::*) v15;
	si = (struct Eq_60376 Eq_60383::*) &si->w0002;
	di = (struct Eq_60376 Eq_60383::*) &di->w0002;
	v16 = (struct Eq_60376 Eq_60383::*) (ds->*si).ptr0000;
	(es->*di).ptr0000 = (struct Eq_60376 Eq_60383::*) v16;
	si = (struct Eq_60376 Eq_60383::*) &si->w0002;
	di = (struct Eq_60376 Eq_60383::*) &di->w0002;
	v17 = (struct Eq_60376 Eq_60383::*) (ds->*si).ptr0000;
	(es->*di).ptr0000 = (struct Eq_60376 Eq_60383::*) v17;
	si = (struct Eq_60376 Eq_60383::*) &si->w0002;
	di = (struct Eq_60376 Eq_60383::*) &di->w0002;
	v18 = (struct Eq_60376 Eq_60383::*) (ds->*si).ptr0000;
	(es->*di).ptr0000 = (struct Eq_60376 Eq_60383::*) v18;
	si = (struct Eq_60376 Eq_60383::*) (ss->*sp).ptr0000;
	sp = (struct Eq_60376 Eq_60383::*) &sp->w0002;
	di = (struct Eq_60376 Eq_60383::*) (ss->*sp).ptr0000;
	sp = (struct Eq_60376 Eq_60383::*) &sp->w0002;
	bp = (struct Eq_60376 Eq_60383::*) (ss->*sp).ptr0000;
	sp = (struct Eq_60376 Eq_60383::*) &sp->w0002;
}

// 2368:01E0: define fn2368_01E0
// Called from:
//      fn20B2_0474
//      fn20B2_0612
//      fn20B2_0776
//      fn20B2_0898
//      fn20B2_099A
//      fn20B2_0AC6
//      fn20B2_0BDC
//      fn20B2_0EF6
//      fn21DC_0856
//      fn3CEE_4EAC
//      fn3CEE_858E
define fn2368_01E0
{
	selector ds;
	word16 wArg04;
	Top_3 = 0;
	v7_10 = &ds->ptr1296->w000A + 3;
	ds->ptr1296 = v7_10;
	SCZO_12 = cond(v7_10);
	C_25 = SLICE(SCZO_12, bool, 1);
	O_26 = SLICE(SCZO_12, bool, 4);
	S_27 = (bool) SCZO_12;
	Z_28 = SLICE(SCZO_12, bool, 2);
	es_bx_13 = ds->ptr1296;
	es_14 = SLICE(es_bx_13, selector, 16);
	bx_15 = (word16) es_bx_13;
	es_bx_13->w0000 = 0x02;
	es_bx_13->w0002 = 0x0A;
	ax_18 = wArg04;
	es_bx_13->w0008 = wArg04;
	es_bx_13->w000A = 0x00;
}

// 2368:0206: define fn2368_0206
// Called from:
//      fn3B5D_057A
//      fn3B5D_0592
//      fn3CEE_4EAC
define fn2368_0206
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_60557 Eq_60564::*) bp;
	bp = sp;
	v7 = (word32) ds->t1296 + 16;
	ds->t1296 = v7;
	SCZO = cond(v7);
	es_bx = ds->t1296;
	(es->*bx).w0000 = 0x02;
	(es->*bx).w0002 = 0x0A;
	ax = (ss->*bp).w0006;
	dx = (ss->*bp).w0008;
	(es->*bx).w0008 = ax;
	(es->*bx).w000A = dx;
	bp = (struct Eq_60557 Eq_60564::*) (ss->*sp).ptr0000;
	sp = (struct Eq_60557 Eq_60564::*) &sp->ptr0000;
}

// 2368:022E: define fn2368_022E
// Called from:
//      fn1825_4DA6
//      fn1825_5FCA
//      fn1825_6078
//      fn20B2_0474
//      fn20B2_0612
//      fn20B2_0776
//      fn20B2_0898
//      fn20B2_099A
//      fn20B2_0AC6
//      fn20B2_0EF6
//      fn21DC_0856
//      main
//      fn3B5D_04C8
//      fn3CEE_4490
//      fn3CEE_5556
//      fn3CEE_8634
define fn2368_022E
{
	word32 dwArg04;
	mp16 fp;
	selector ds;
	wArg06 = SLICE(dwArg04, word16, 16);
	wArg04 = (word16) dwArg04;
	word16 wArg08;
	Top_3 = 0;
	v7_10 = &ds->ptr1296->w000C + 2;
	ds->ptr1296 = v7_10;
	es_bx_13 = ds->ptr1296;
	es_bx_13->w0000 = 0x0100;
	ptrLoc06_51 = dwArg04;
	fn2017_03F5();
	SCZO_32 = cond(fp - 0x02);
	C_53 = SLICE(SCZO_32, bool, 1);
	O_54 = SLICE(SCZO_32, bool, 4);
	S_55 = (bool) SCZO_32;
	Z_56 = SLICE(SCZO_32, bool, 2);
	es_bx_33 = ds->ptr1296;
	es_34 = SLICE(es_bx_33, selector, 16);
	bx_35 = (word16) es_bx_33;
	es_bx_33->w0002 = ax_23;
	es_bx_33->w0004 = 0x00;
	dx_39 = wArg06;
	es_bx_33->w0008 = wArg04;
	es_bx_33->w000A = wArg06;
	ax_42 = wArg08;
	es_bx_33->w000C = wArg08;
}

// 2368:0272: define fn2368_0272
// Called from:
//      fn1825_48D2
//      fn1825_496A
//      fn2EB3_2340
//      fn31FF_207C
//      fn3431_3E9E
//      fn3CEE_4EAC
define fn2368_0272
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_60689 Eq_60696::*) bp;
	bp = sp;
	v7 = (word32) ds->t1296 + 16;
	ds->t1296 = v7;
	SCZO = cond(v7);
	es_bx = ds->t1296;
	(es->*bx).w0000 = 0x0100;
	ax = (ss->*bp).w000C;
	(es->*bx).w0002 = ax;
	(es->*bx).w0004 = 0x00;
	ax = (ss->*bp).w0006;
	dx = (ss->*bp).w0008;
	(es->*bx).w0008 = ax;
	(es->*bx).w000A = dx;
	ax = (ss->*bp).w000A;
	(es->*bx).w000C = ax;
	bp = (struct Eq_60689 Eq_60696::*) (ss->*sp).ptr0000;
	sp = (struct Eq_60689 Eq_60696::*) &sp->ptr0000;
}

// 2368:02D2: define fn2368_02D2
// Called from:
//      fn3CEE_8634
define fn2368_02D2
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_60768 Eq_60775::*) bp;
	bp = sp;
	v7 = (word32) ds->t1296 + 16;
	ds->t1296 = v7;
	SCZO = cond(v7);
	es_bx = ds->t1296;
	(es->*bx).w0000 = 0x20;
	ax = (ss->*bp).w0006;
	dx = (ss->*bp).w0008;
	(es->*bx).w0008 = ax;
	(es->*bx).w000A = dx;
	bp = (struct Eq_60768 Eq_60775::*) (ss->*sp).ptr0000;
	sp = (struct Eq_60768 Eq_60775::*) &sp->ptr0000;
}

// 2368:02F4: define fn2368_02F4
// Called from:
//      fn3B5D_05D0
define fn2368_02F4
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_60826 Eq_60833::*) bp;
	bp = sp;
	v7 = (word32) ds->t1296 + 16;
	ds->t1296 = v7;
	SCZO = cond(v7);
	es_bx = ds->t1296;
	(es->*bx).w0000 = 0x80;
	ax = (ss->*bp).w0006;
	(es->*bx).w0008 = ax;
	bp = (struct Eq_60826 Eq_60833::*) (ss->*sp).ptr0000;
	sp = (struct Eq_60826 Eq_60833::*) &sp->ptr0000;
}

// 2368:030E: define fn2368_030E
// Called from:
//      fn1825_4DA6
//      fn20B2_0474
//      fn20B2_0612
//      fn20B2_0776
//      fn20B2_0898
//      fn20B2_099A
//      fn20B2_0AC6
//      fn20B2_0BDC
//      fn20B2_0EF6
//      fn21DC_0856
//      main
//      fn3CEE_4EAC
//      fn3CEE_858E
//      fn3CEE_8634
define fn2368_030E
{
	selector ds;
	word16 wArg04;
	word16 wArg06;
	Top_3 = 0;
	v7_10 = &ds->ptr1296->w000E + 1;
	ds->ptr1296 = v7_10;
	SCZO_12 = cond(v7_10);
	C_28 = SLICE(SCZO_12, bool, 1);
	O_29 = SLICE(SCZO_12, bool, 4);
	S_30 = (bool) SCZO_12;
	Z_31 = SLICE(SCZO_12, bool, 2);
	es_bx_13 = ds->ptr1296;
	es_14 = SLICE(es_bx_13, selector, 16);
	bx_15 = (word16) es_bx_13;
	es_bx_13->w0000 = 0x1000;
	ax_17 = wArg04;
	dx_18 = wArg06;
	es_bx_13->w0008 = wArg04;
	es_bx_13->w000A = wArg06;
	es_bx_13->w000C = 0x00;
	es_bx_13->w000E = 0x00;
}

// 2368:033C: define fn2368_033C
// Called from:
//      fn1825_4814
//      fn1825_4DA6
//      fn1825_5E5C
//      fn1825_5FCA
//      fn1825_6078
//      fn20B2_0474
//      fn20B2_0612
//      fn20B2_0776
//      fn20B2_0898
//      fn20B2_099A
//      fn20B2_0AC6
//      fn20B2_0BDC
//      fn20B2_0EF6
//      fn20B2_1192
//      fn21DC_01C4
//      fn2644_2384
//      fn2644_24C0
//      fn2EB3_2340
//      fn2EB3_240A
//      fn2EB3_24C6
//      fn31FF_1CE2
//      fn31FF_207C
//      fn3431_3E9E
//      fn3CEE_4490
//      fn3CEE_4EAC
//      fn3CEE_5556
//      fn3CEE_858E
define fn2368_033C
{
	selector ds;
	<unknown> Mem0;
	word16 ax;
	Top_3 = 0;
	es_bx_6 = ds->t1296;
	es_7 = SLICE(es_bx_6, selector, 16);
	bx_8 = (word16) es_bx_6;
	SZP_9 = cond(es_bx_6.u1->w0000 & 0x0100);
	P_50 = SLICE(SZP_9, bool, 5);
	if ((es_bx_6.u1->w0000 & 0x0100) != 0x00 && (es_bx_6.u1)->w000C != 0x00)
	{
		v15_19 = es_bx_6.u1->w000A;
		v16_22 = es_bx_6.u1->w0008;
		dwLoc06_42 = SEQ(v15_19, v16_22);
		fn21DC_074E();
	}
	es_47 = ϕ(es_7, es_7, es_27);
	bx_45 = ϕ(bx_8, bx_8, bx_26);
	ax_43 = ϕ(ax, ax, ax_25);
	Mem35 = ϕ(Mem0, Mem0, Mem24);
	v17_36 = ds->t1296 - 0x10;
	ds->t1296 = v17_36;
	SCZO_38 = cond(v17_36);
	C_46 = SLICE(SCZO_38, bool, 1);
	O_48 = SLICE(SCZO_38, bool, 4);
	S_51 = (bool) SCZO_38;
	Z_54 = SLICE(SCZO_38, bool, 2);
}

// 2368:042A: define fn2368_042A
// Called from:
//      fn21DC_01C4
//      fn2368_059E
define fn2368_042A
{
	mp16 fp;
	segptr32 ptrArg04;
	word16 ax;
	word16 cx;
	word16 dx;
	Top_3 = 0;
	if (ptrArg04->w0000 == 0x0100)
	{
		SCZO_100 = cond(ptrArg04->w000A - 0x00);
		Z_101 = SLICE(SCZO_100, bool, 2);
		C_174 = SLICE(SCZO_100, bool, 1);
		O_186 = SLICE(SCZO_100, bool, 4);
		S_190 = (bool) SCZO_100;
		if (ptrArg04->w000A == 0x00)
			goto l2368_04E8;
		v14_105 = ptrArg04->w0008;
		v15_108 = ptrArg04->w0006;
		dwLoc12_160 = SEQ(v14_105, v15_108);
		fn21DC_074E();
	}
	else
	{
		SCZO_18 = cond(ptrArg04->w0000 - 0x2000);
		Z_19 = SLICE(SCZO_18, bool, 2);
		C_175 = SLICE(SCZO_18, bool, 1);
		O_187 = SLICE(SCZO_18, bool, 4);
		S_191 = (bool) SCZO_18;
		if (ptrArg04->w0000 != 0x2000)
			goto l2368_04E8;
		ax_20 = ptrArg04->w0006;
		dx_21 = ptrArg04->w0008;
		wLoc04_139 = 0x00;
		while (true)
		{
			dx_183 = dx_21;
			wLoc04_141 = ϕ(wLoc04_139, wLoc04_152);
			Mem27 = ϕ(Mem24, Mem75);
			if (ptrArg04->w0002 <= wLoc04_141)
				break;
			ax_41 = wLoc04_141 * 0x0E + ax_20;
			ptrLoc0C_146 = SEQ(dx_21, ax_41);
			if (ptrLoc0C_146->w0000 == 0x0100 && ptrLoc0C_146->w000A != 0x00)
			{
				v21_56 = ptrLoc0C_146->w0008;
				v22_59 = ptrLoc0C_146->w0006;
				dwLoc12_150 = SEQ(v21_56, v22_59);
				fn21DC_0702();
			}
			v23_74 = wLoc04_141 + 0x01;
			wLoc04_152 = v23_74;
		}
		ax_77 = ptrArg04->w0002;
		cx_78 = ax_77;
		dwLoc12_156 = SEQ(dx_21, ax_20);
		fn21DC_0702();
	}
	dx_182 = ϕ(dx, dx_183);
	cx_179 = ϕ(cx, cx_78);
	ax_172 = ϕ(ax_111, ax_93);
	SCZO_120 = cond(fp - 0x0C);
	C_176 = SLICE(SCZO_120, bool, 1);
	O_188 = SLICE(SCZO_120, bool, 4);
	S_192 = (bool) SCZO_120;
	Z_198 = SLICE(SCZO_120, bool, 2);
l2368_04E8:
	Z_197 = ϕ(Z_101, Z_19, Z_198);
	S_189 = ϕ(S_190, S_191, S_192);
	O_185 = ϕ(O_186, O_187, O_188);
	dx_180 = ϕ(dx, dx, dx_182);
	cx_177 = ϕ(cx, cx, cx_179);
	C_173 = ϕ(C_174, C_175, C_176);
	ax_170 = ϕ(ax, ax, ax_172);
	es_128 = SLICE(ptrArg04, selector, 16);
	bx_129 = (word16) ptrArg04;
	ptrArg04->w0000 = 0x00;
}

// 2368:04F4: define fn2368_04F4
// Called from:
//      fn1825_4DA6
//      fn1825_5E5C
define fn2368_04F4
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x06;
	sp -= 2;
	ss->*sp = di;
	sp -= 2;
	ss->*sp = si;
	v10 = Mem0[ds:0x1296:word16] + 0x10;
	Mem0[ds:0x1296:word16] = v10;
	es_bx = ss->*((word16) bp + 6);
	si.u2 = (es->*bx).t0000.u2;
	es_bx = Mem0[ds:0x1296:segptr32];
	(es->*bx).t0000.u2 = (struct Eq_236305 *) si;
	es_bx = ss->*((word16) bp + 6);
	ax.u2 = (es->*bx).t0002.u2;
	es_bx = Mem0[ds:0x1296:segptr32];
	(es->*bx).t0002.u2 = (struct Eq_236305 *) ax;
	es_bx = ss->*((word16) bp + 6);
	ax.u2 = (es->*bx).t0004.u2;
	es_bx = Mem0[ds:0x1296:segptr32];
	(es->*bx).t0004.u2 = (struct Eq_236305 *) ax;
	SZP = cond(si & 0x0100);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
		es_bx = ss->*((word16) bp + 6);
		SZP = cond((es->*bx).t0000.u2 & 0x2000);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
			es_bx = Mem0[ds:0x1296:segptr32];
			ax = ss->*((word16) bp + 6);
			dx = ss->*((word16) bp + 8);
			ax = (char *) ax.u2 + 6;
			SCZO = cond(ax);
			di = &bx->t0008.u0;
			si = ax;
			sp -= 2;
			ss->*sp = ds;
			ds = dx;
			v20 = ds->*si.u2;
			es->*di = v20;
			si = (char *) si.u2 + 2;
			di = (word16) di + 2;
			v21 = ds->*si;
			es->*di = v21;
			si = (word16) si + 2;
			di = (word16) di + 2;
			v22 = ds->*si;
			es->*di = v22;
			si = (word16) si + 2;
			di = (word16) di + 2;
			v23 = ds->*si;
			es->*di = v23;
			ds = ss->*sp;
			sp = (word16) sp + 2;
			si = ss->*sp;
			sp = (word16) sp + 2;
			di = ss->*sp;
			sp = bp;
			bp = ss->*sp;
			sp = (word16) sp + 2;
		}
		else
		{
			es_bx = Mem0[ds:0x1296:segptr32];
			(es->*bx).t0000.u2 = (struct Eq_236305 *) 0x0800;
			ax = ss->*((word16) bp + 6);
			dx = ss->*((word16) bp + 8);
			(es->*bx).t0008.u2 = (struct Eq_236305 *) ax;
			(es->*bx).t000A.u2 = (struct Eq_236305 *) dx;
			si = ss->*sp;
			sp = (word16) sp + 2;
			di = ss->*sp;
			sp = bp;
			bp = ss->*sp;
			sp = (word16) sp + 2;
		}
	}
	else
	{
		es_bx = ss->*((word16) bp + 6);
		ax.u2 = (es->*bx).t0006.u2;
		dx.u2 = (es->*bx).t0008.u2;
		es_bx = Mem0[ds:0x1296:segptr32];
		(es->*bx).t0008.u2 = (struct Eq_236305 *) ax;
		(es->*bx).t000A.u2 = (struct Eq_236305 *) dx;
		(es->*bx).w000C = 0x00;
		si = ss->*sp;
		sp = (word16) sp + 2;
		di = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 2368:059E: define fn2368_059E
// Called from:
//      fn2368_0A7A
define fn2368_059E
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x06;
	sp -= 2;
	ss->*sp = di;
	sp -= 2;
	ss->*sp = si;
	es_bx = Mem0[ds:0x1296:segptr32];
	SCZO = cond((es->*bx).t0000.u3 - 0x00);
	if (Test(EQ,Z))
	{
l2368_0678:
		SCZO = cond(ss->*((word16) bp + 0x0A) - 0x00);
		if (Test(NE,Z))
		{
			v20 = Mem0[ds:0x1296:word16] - 0x10;
			Mem0[ds:0x1296:word16] = v20;
			SCZO = cond(v20);
		}
		si = ss->*sp;
		sp = (word16) sp + 2;
		di = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
		return;
	}
	v14 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v14;
	v15 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v15;
	fn2368_042A();
	sp = (word16) sp + 4;
	es_bx = Mem0[ds:0x1296:segptr32];
	SZP = cond((es->*bx).t0000.u0 & 0x08);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		SCZO = cond(Mem0[ds:5100:word16] - 0x00);
		if (Test(NE,Z))
		{
			ax = Mem0[ds:5112:word16];
			(es->*bx).t0004.u3 = (struct Eq_236308 *) ax;
		}
	}
	ax.u3 = (es->*bx).t0002.u3;
	ss->*((word16) bp - 6) = ax;
	si.u3 = (es->*bx).t0000.u3;
	es_bx = ss->*((word16) bp + 6);
	ax = si;
	ah &= ~0x02;
	(es->*bx).t0000.u3 = (struct Eq_236308 *) ax;
	ax = ss->*((word16) bp - 6);
	(es->*bx).t0002.u3 = (struct Eq_236308 *) ax;
	es_bx = Mem0[ds:0x1296:segptr32];
	ax.u3 = (es->*bx).t0004.u3;
	es_bx = ss->*((word16) bp + 6);
	(es->*bx).t0004.u3 = (struct Eq_236308 *) ax;
	SZP = cond(si & 0x0100);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		es_bx = Mem0[ds:0x1296:segptr32];
		SCZO = cond((es->*bx).w000C - 0x00);
		if (Test(EQ,Z))
		{
l2368_061A:
			es_bx = ss->*((word16) bp + 6);
			ax = ss->*((word16) bp - 6);
			ax = (word16) ax + 1;
			SZO = cond(ax);
			(es->*bx).t000A.u3 = (struct Eq_236308 *) ax;
			sp -= 2;
			ss->*sp = ax;
			fn21DC_0718();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
			es_bx = ss->*((word16) bp + 6);
			(es->*bx).t0006.u3 = (struct Eq_236308 *) ax;
			(es->*bx).t0008.u3 = (struct Eq_236308 *) dx;
			v25.u3 = (es->*bx).t000A.u3;
			sp -= 2;
			ss->*sp = v25;
			es_bx = Mem0[ds:0x1296:segptr32];
			v26.u3 = (es->*bx).t000A.u3;
			sp -= 2;
			ss->*sp = v26;
			v27.u3 = (es->*bx).t0008.u3;
			sp -= 2;
			ss->*sp = v27;
			es_bx = ss->*((word16) bp + 6);
			v28.u3 = (es->*bx).t0008.u3;
			sp -= 2;
			ss->*sp = v28;
			v29.u3 = (es->*bx).t0006.u3;
			sp -= 2;
			ss->*sp = v29;
			fn2017_02EC();
			sp = (word16) sp + 0x0A;
			SCZO = cond(sp);
			goto l2368_0678;
		}
		SCZO = cond(ss->*((word16) bp + 0x0A) - 0x00);
		if (Test(EQ,Z))
			goto l2368_061A;
	}
	es_bx = ss->*((word16) bp + 6);
	ax = Mem0[ds:0x1296:word16];
	dx = Mem0[ds:0x1298:word16];
	ax = (char *) ax.u3 + 8;
	SCZO = cond(ax);
	di = &bx->t0006.u0;
	si = ax;
	sp -= 2;
	ss->*sp = ds;
	ds = dx;
	v30 = ds->*si.u3;
	es->*di = v30;
	si = (char *) si.u3 + 2;
	di = (word16) di + 2;
	v31 = ds->*si;
	es->*di = v31;
	si = (word16) si + 2;
	di = (word16) di + 2;
	v32 = ds->*si;
	es->*di = v32;
	si = (word16) si + 2;
	di = (word16) di + 2;
	v33 = ds->*si;
	es->*di = v33;
	si = (word16) si + 2;
	di = (word16) di + 2;
	ds = ss->*sp;
	sp = (word16) sp + 2;
	goto l2368_0678;
}

// 2368:0A7A: define fn2368_0A7A
// Called from:
//      fn1825_4DA6
//      fn3CEE_8634
define fn2368_0A7A
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x0E;
	es_bx = ds->t1296;
	ax.u0 = (es->*bx).t0008.u0;
	dx.u0 = (es->*bx).t000A.u0;
	ss->*((word16) bp - 0x0A) = ax;
	ss->*((word16) bp - 8) = dx;
	ax.u0 = (es->*bx).t000E.u0;
	ss->*((word16) bp - 6) = ax;
	v13 = ds->t1296 - 0x10;
	ds->t1296 = v13;
	es_bx = ss->*((word16) bp - 0x0A);
	ax.u0 = (es->*bx).t0004.u0;
	ax |= (es->*bx).t0006.u0;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
		ax.u0 = 0x01;
		sp -= 2;
		ss->*sp = ax;
		fn21DC_0588();
		sp = (word16) sp + 2;
		ss->*((word16) bp - 4) = ax;
		ss->*((word16) bp - 2) = dx;
		es_bx = ss->*((word16) bp - 4);
		ax = ss->*((word16) bp - 0x0A);
		dx = ss->*((word16) bp - 8);
		(es->*bx).t0012.u0 = (ui16) ax;
		(es->*bx).t0014.u0 = (ui16) dx;
		ax -= ax;
		SCZO = cond(ax);
		(es->*bx).t0010.u0 = (ui16) ax;
		(es->*bx).t000E.u0 = (ui16) ax;
		es_bx = ss->*((word16) bp - 0x0A);
		ax = ss->*((word16) bp - 4);
		dx = ss->*((word16) bp - 2);
		(es->*bx).t0004.u0 = (ui16) ax;
		(es->*bx).t0006.u0 = (ui16) dx;
		(ss->*((word16) bp - 6)).u0 = 0x00;
	}
	SCZO = cond(ss->*((word16) bp - 6) - 0x00);
	if (Test(NE,Z))
	{
		es_bx.u2 = (es->*bx).t0004.u2;
		ax.u0 = (es->*bx).t0006.u0;
		dx.u0 = (es->*bx).t0008.u0;
		ss->*((word16) bp - 0x0E) = ax;
		ss->*((word16) bp - 0x0C) = dx;
		ax.u0 = 0x01;
		sp -= 2;
		ss->*sp = ax;
		ax = ss->*((word16) bp - 6);
		cx = ax;
		ax <<= 0x01;
		ax += cx;
		ax <<= 0x01;
		ax += cx;
		ax <<= 0x01;
		ax += Mem0[ss:bp + -0x0E:word16];
		ax -= 0x0E;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = dx;
		sp -= 2;
		ss->*sp = ax;
	}
	else
	{
		ax.u0 = 0x01;
		sp -= 2;
		ss->*sp = ax;
		es_bx = ss->*((word16) bp - 0x0A);
		v19.u0 = (es->*bx).t0006.u0;
		sp -= 2;
		ss->*sp = v19;
		v20.u0 = (es->*bx).t0004.u0;
		sp -= 2;
		ss->*sp = v20;
	}
	fn2368_059E();
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2368:0C7E: define fn2368_0C7E
// Called from:
//      fn1825_4DA6
define fn2368_0C7E
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x08;
	es_bx = ds->t1296;
	ax.u0 = (es->*bx).t0008.u0;
	dx = (es->*bx).w000A;
	ss->*((word16) bp - 8) = ax;
	ss->*((word16) bp - 6) = dx;
	v13 = ds->t1296 - 0x10;
	ds->t1296 = v13;
	es_bx = ss->*((word16) bp - 8);
	ax.u0 = (es->*bx).t0004.u0;
	ax |= (es->*bx).w0006;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		ax.u0 = 22;
		dx_ax = ds->w128A *32 ax;
		ax = (word16) ax.u0 + ds->w1282;
		dx = ds->w1284;
		SCZO = cond(ax - ((es->*bx).t0004).u0);
		if (Test(ULT,C))
		{
			ax.u0 = 22;
			dx_ax = ds->w1288 *32 ax;
			ax = (word16) ax.u0 + ds->w1282;
			dx = ds->w1284;
			SCZO = cond(ax - ((es->*bx).t0004).u0);
			if (Test(UGE,C))
			{
l2368_0D1C:
				sp = bp;
				bp = ss->*sp;
				sp = (word16) sp + 2;
				return;
			}
		}
	}
	ax.u0 = 0x01;
	sp -= 2;
	ss->*sp = ax;
	fn21DC_0588();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	ss->*((word16) bp - 4) = ax;
	ss->*((word16) bp - 2) = dx;
	es_bx = ss->*((word16) bp - 4);
	ax = ss->*((word16) bp - 8);
	dx = (cui16) (ss->*((word16) bp - 6));
	(es->*bx).t0012.u0 = (uint16) ax;
	(es->*bx).w0014 = dx;
	es_bx = ss->*((word16) bp - 8);
	ax.u0 = (es->*bx).t0004.u0;
	dx = (es->*bx).w0006;
	es_bx = ss->*((word16) bp - 4);
	(es->*bx).t000E.u0 = (uint16) ax;
	(es->*bx).w0010 = dx;
	es_bx = ss->*((word16) bp - 8);
	ax = ss->*((word16) bp - 4);
	dx = (cui16) (ss->*((word16) bp - 2));
	(es->*bx).t0004.u0 = (uint16) ax;
	(es->*bx).w0006 = dx;
	goto l2368_0D1C;
}

// 2368:0D20: define fn2368_0D20
// Called from:
//      fn1825_4DA6
define fn2368_0D20
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x08;
	es_bx = Mem0[ds:0x1296:segptr32];
	ax.u2 = (es->*bx).t0008.u2;
	dx.u2 = (es->*bx).t000A.u2;
	ss->*((word16) bp - 8) = ax;
	ss->*((word16) bp - 6) = dx;
	v13 = Mem0[ds:0x1296:word16] - 0x10;
	Mem0[ds:0x1296:word16] = v13;
	es_bx = ss->*((word16) bp - 8);
	ax.u2 = (es->*bx).t0004.u2;
	dx.u2 = (es->*bx).t0006.u2;
	ss->*((word16) bp - 4) = ax;
	ss->*((word16) bp - 2) = dx;
	ax |= dx;
	SZ = cond(ax);
	O = false;
	C.u0 = false;
	if (Test(EQ,Z))
	{
		ax.u0 = 0x01;
		sp -= 2;
		ss->*sp = ax;
		fn21DC_05EA();
		sp = (word16) sp + 2;
		SCZO = cond(sp);
		ss->*((word16) bp - 4) = ax;
		ss->*((word16) bp - 2) = dx;
		es_bx = ss->*((word16) bp - 4);
		(es->*bx).w0000 = 0x80;
		(es->*bx).w0002 = 0x00;
		(es->*bx).t0004.u2 = (struct Eq_236313 *) 0x00;
		ax.u0 = 0x08;
		sp -= 2;
		ss->*sp = ax;
		ax.u0 = 24102;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		v18 = ss->*((word16) bp - 6);
		sp -= 2;
		ss->*sp = v18;
		v19 = ss->*((word16) bp - 8);
		sp -= 2;
		ss->*sp = v19;
		fn2BC7_050A();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		sp -= 2;
		ss->*sp = dx;
		sp -= 2;
		ss->*sp = ax;
		fn38AD_00F2();
		sp = (word16) sp + 0x0A;
		SCZO = cond(ax - 0x01);
		cx = cx - cx - C;
		cx = -cx;
		es_bx = ss->*((word16) bp - 4);
		(es->*bx).t0006.u2 = (struct Eq_236313 *) cx;
		ax -= ax;
		SCZO = cond(ax);
		(es->*bx).t0010.u2 = (struct Eq_236313 *) ax;
		(es->*bx).t000E.u2 = (struct Eq_236313 *) ax;
		ax = ss->*((word16) bp - 8);
		dx = ss->*((word16) bp - 6);
		(es->*bx).t0012.u2 = (struct Eq_236313 *) ax;
		(es->*bx).t0014.u2 = (struct Eq_236313 *) dx;
		es_bx = ss->*((word16) bp - 8);
		ax = ss->*((word16) bp - 4);
		dx = ss->*((word16) bp - 2);
		(es->*bx).t0004.u2 = (struct Eq_236313 *) ax;
		(es->*bx).t0006.u2 = (struct Eq_236313 *) dx;
	}
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

