// 1999_SOFT_LOAN__2E37.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 2E37:0008: define fn2E37_0008
// Called from:
//      fn2E37_0022
//      fn2E37_0152
//      fn2E37_0212
define fn2E37_0008
{
	word16 wArg06;
	word16 wArg08;
	byte bArg04;
	Top_3 = 0;
	ax_9 = wArg06;
	dx_10 = wArg08;
	cl_11 = 0x08;
	dx_ax_47 = SEQ(dx_10, ax_9);
	do
	{
		dx_ax_48 = ϕ(dx_ax_47, v19_34);
		cl_20 = ϕ(cl_11, cl_21);
		v19_34 = dx_ax_48 >> 0x01;
		dx_13 = SLICE(v19_34, word16, 16);
		ax_18 = (word16) v19_34;
		al_24 = (byte) ax_18;
		cl_21 = cl_20 - 0x01;
	} while (cl_21 != 0x00);
	al_28 = al_24 + bArg04;
	SCZO_30 = cond(0x00);
	C_42 = SLICE(SCZO_30, bool, 1);
	O_43 = SLICE(SCZO_30, bool, 4);
	S_44 = (bool) SCZO_30;
	Z_46 = SLICE(SCZO_30, bool, 2);
	ax_41 = (uint16) al_28;
}

// 2E37:0022: define fn2E37_0022
// Called from:
//      fn2E37_04CE
//      fn2E37_05C0
//      fn2E37_06C4
define fn2E37_0022
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x06;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	v8 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v8;
	v9 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v9;
	v10 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v10;
	fn2E37_0008();
	sp = (word16) sp + 6;
	bx = ax;
	bx <<= 0x01;
	SCZO = cond(bx);
	es_si = ds->t1492;
	ax = Mem0[es:bx + si:word16];
	while (true)
	{
		ss->*((word16) bp - 2) = ax;
		SCZO = cond(ax - ~0x00);
		if (Test(EQ,Z))
			break;
		cl = 0x04;
		ax <<= cl;
		ax += Mem0[ds:5254:word16];
		dx = ds->t1488;
		ss->*((word16) bp - 6) = ax;
		ss->*((word16) bp - 4) = dx;
		es_bx = ss->*((word16) bp - 6);
		ax = ss->*((word16) bp + 6);
		SCZO = cond(es->*((word16) bx + 4) - ax);
		if (Test(EQ,Z))
		{
			ax = ss->*((word16) bp + 8);
			dx = ss->*((word16) bp + 0x0A);
			SCZO = cond(es->*bx - ax);
			if (Test(EQ,Z))
			{
				SCZO = cond(es->*((word16) bx + 2) - dx);
				if (Test(EQ,Z))
					break;
			}
		}
		si = ss->*((word16) bp - 2);
		cl = 0x04;
		si <<= cl;
		SCZO = cond(si);
		es_bx = ds->t1486;
		ax = es->*((word16) si + ((word16) bx + 8));
	}
	ax = ss->*((word16) bp - 2);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2E37:0096: define fn2E37_0096
// Called from:
//      fn2E37_0212
//      fn2E37_0382
//      fn2E37_0446
//      fn2E37_06F4
define fn2E37_0096
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x0E;
	sp -= 2;
	ss->*sp = si;
	ax = ss->*((word16) bp + 6);
	cl = 0x04;
	ax <<= cl;
	ax += Mem0[ds:5254:word16];
	dx = ds->t1488;
	ss->*((word16) bp - 0x0E) = ax;
	ss->*((word16) bp - 0x0C) = dx;
	es_bx = ss->*((word16) bp - 0x0E);
	SCZO = cond((es->*bx).a0006[0].u0 - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = (es->*bx).t0004.u0;
		ss->*((word16) bp - 0x0A) = ax;
		ax.u0 = (es->*bx).t0000.u0;
		dx.u0 = (es->*bx).t0002.u0;
		ss->*((word16) bp - 8) = ax;
		ss->*((word16) bp - 6) = dx;
		SCZO = cond(ds->w149A - 0x00);
		if (Test(NE,Z))
		{
			v16.u0 = (es->*bx).t000A.u0;
			sp -= 2;
			ss->*sp = v16;
			fn2C27_0440();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
		}
		else
		{
			si = ss->*((word16) bp + 6);
			cl = 0x04;
			si <<= cl;
			SCZO = cond(si);
			es_bx = ds->t1486;
			ax = Mem0[es:bx + 0x0C + si:word16];
			dx = Mem0[es:bx + 0x0E + si:word16];
		}
		ss->*((word16) bp - 4) = ax;
		ss->*((word16) bp - 2) = dx;
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		v17 = ss->*((word16) bp - 6);
		sp -= 2;
		ss->*sp = v17;
		v18 = ss->*((word16) bp - 8);
		sp -= 2;
		ss->*sp = v18;
		v19 = ss->*((word16) bp - 0x0A);
		sp -= 2;
		ss->*sp = v19;
		fn208F_0115();
		sp = (word16) sp + 8;
		SCZO = cond(sp);
		v20 = ds->t149C;
		sp -= 2;
		ss->*sp = v20;
		v21 = ss->*((word16) bp - 2);
		sp -= 2;
		ss->*sp = v21;
		v22 = ss->*((word16) bp - 4);
		sp -= 2;
		ss->*sp = v22;
		v23 = ss->*((word16) bp - 0x0A);
		sp -= 2;
		ss->*sp = v23;
		fn208F_00EF();
		sp = (word16) sp + 8;
		SCZO = cond(ax - ds->t149C);
		if (Test(NE,Z))
		{
			ds->w1484 = 0x01;
			si = ss->*sp;
			sp = bp;
			bp = ss->*sp;
			sp = (word16) sp + 2;
			return;
		}
		si = ss->*((word16) bp + 6);
		cl = 0x04;
		si <<= cl;
		SCZO = cond(si);
		es_bx = ds->t1486;
		Mem0[es:bx + 6 + si:word16] = 0x00;
	}
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2E37:0152: define fn2E37_0152
// Called from:
//      fn2E37_0212
//      fn2E37_0382
//      fn2E37_04CE
//      fn2E37_05C0
//      fn2E37_06F4
define fn2E37_0152
{
	selector ds;
	word16 wArg04;
	word16 ax;
	word16 dx;
	Top_3 = 0;
	es_bx_20 = ds->t1486;
	es_21 = SLICE(es_bx_20, selector, 16);
	bx_22 = (word16) es_bx_20;
	SCZO_23 = cond(((word16) bx_22 + 4)[wArg04].w0000 - 0x00);
	Z_24 = SLICE(SCZO_23, bool, 2);
	C_150 = SLICE(SCZO_23, bool, 1);
	O_157 = SLICE(SCZO_23, bool, 4);
	S_160 = (bool) SCZO_23;
	if (((word16) bx_22 + 4)[wArg04].w0000 != 0x00)
	{
		v15_25 = ((word16) bx_22 + 2)[wArg04].w0000;
		v16_28 = (word16) *((word32) es_bx_20 + wArg04 * 0x10);
		v17_31 = ((word16) bx_22 + 4)[wArg04].w0000;
		bLoc14_124 = (byte) v17_31;
		fn2E37_0008();
		ax_44 = (ax_34 << 0x01) + ds->w1492;
		dx_45 = ds->w1494;
		ptrLoc0A_128 = SEQ(dx_45, ax_44);
		ax_51 = *ptrLoc0A_128;
		wLoc06_129 = ax_51;
		if (ax_51 == wArg04)
		{
			es_bx_77 = ds->t1486;
			es_78 = SLICE(es_bx_77, selector, 16);
			bx_79 = (word16) es_bx_77;
			ax_80 = (&(es_78->*((char *) bx_79 + 8)))[wArg04].w0000;
			*ptrLoc0A_128 = ax_80;
		}
		else
		{
			while (true)
			{
				wLoc06_130 = ϕ(wLoc06_129, wLoc06_132);
				Mem58 = ϕ(Mem52, Mem69);
				es_bx_63 = ds->t1486;
				es_64 = SLICE(es_bx_63, selector, 16);
				bx_65 = (word16) es_bx_63;
				si_66 = (&(es_64->*((char *) bx_65 + 8)))[wLoc06_130].w0000;
				if (wArg04 == si_66)
					break;
				wLoc06_132 = si_66;
			}
			ax_72 = (&(es_64->*((char *) bx_65 + 8)))[wArg04].w0000;
			(&(es_64->*((char *) bx_65 + 8)))[wLoc06_130].w0000 = ax_72;
		}
		Mem87 = ϕ(Mem84, Mem76);
		ax_92 = &(ds->t1486.u1 + (wArg04 << 0x04) /16 16)->w0000;
		dx_93 = ds->ptr1488;
		ptrLoc0A_136 = (struct Eq_84477 *) ax_92;
		es_97 = dx_93;
		bx_98 = ax_92;
		ptrLoc0A_136->w0004 = 0x00;
		ax_100 = 0x00;
		SCZO_101 = cond(0x00);
		C_151 = SLICE(SCZO_101, bool, 1);
		O_158 = SLICE(SCZO_101, bool, 4);
		S_161 = (bool) SCZO_101;
		Z_166 = SLICE(SCZO_101, bool, 2);
		ptrLoc0A_136->w0002 = 0x00;
		ptrLoc0A_136->w0000 = 0x00;
		ptrLoc0A_136->w0008 = ~0x00;
	}
	Z_165 = ϕ(Z_24, Z_166);
	S_159 = ϕ(S_160, S_161);
	O_156 = ϕ(O_157, O_158);
	es_155 = ϕ(es_21, es_97);
	dx_153 = ϕ(dx, dx_93);
	cl_152 = 0x04;
	C_149 = ϕ(C_150, C_151);
	bx_148 = ϕ(bx_22, bx_98);
	ax_146 = ϕ(ax, ax_100);
}

// 2E37:0212: define fn2E37_0212
// Called from:
//      fn2E37_04CE
//      fn2E37_05C0
//      fn2E37_0740
define fn2E37_0212
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x08;
	sp -= 2;
	ss->*sp = si;
	ax = ds->t1490;
	ss->*((word16) bp - 4) = ax;
	v10 = (word32) ds->t1490 + 1;
	ds->t1490 = v10;
	ax = ds->t148C;
	SCZO = cond(ds->t1490 - ax);
	if (Test(EQ,Z))
		ds->t1490.u0 = 0x00;
	v13 = ss->*((word16) bp - 4);
	sp -= 2;
	ss->*sp = v13;
	fn2E37_0096();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	v14 = ss->*((word16) bp - 4);
	sp -= 2;
	ss->*sp = v14;
	fn2E37_0152();
	sp = (word16) sp + 2;
	si = ss->*((word16) bp - 4);
	cl = 0x04;
	si <<= cl;
	SCZO = cond(si);
	es_bx = ds->t1486;
	ax = ss->*((word16) bp + 6);
	Mem0[es:bx + 4 + si:word16] = ax;
	ax = ss->*((word16) bp + 8);
	dx = ss->*((word16) bp + 0x0A);
	Mem0[es:bx + si:word16] = ax;
	Mem0[es:bx + 2 + si:word16] = dx;
	sp -= 2;
	ss->*sp = dx;
	sp -= 2;
	ss->*sp = ax;
	v20 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v20;
	fn2E37_0008();
	sp = (word16) sp + 6;
	ss->*((word16) bp - 2) = ax;
	ax <<= 0x01;
	ax = (word16) ax + ds->w1492;
	SCZO = cond(ax);
	dx = ds->t1494;
	ss->*((word16) bp - 8) = ax;
	ss->*((word16) bp - 6) = dx;
	es_bx = ss->*((word16) bp - 8);
	ax.u0 = (es->*bx).a0000[0].u0;
	es_bx = ds->t1486;
	Mem0[es:bx + 8 + si:word16] = ax;
	es_bx = ss->*((word16) bp - 8);
	ax = ss->*((word16) bp - 4);
	(es->*bx).a0000[0].u0 = (int16) ax;
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2E37:02A0: define fn2E37_02A0
// Called from:
//      fn2D1A_0BD2
//      fn2D1A_0D38
//      fn2D1A_0FA6
define fn2E37_02A0
{
	selector ds;
	<unknown> Mem0;
	Top_3 = 0;
	ax_6 = ds->w148C;
}

// 2E37:02A4: define fn2E37_02A4
// Called from:
//      fn2E37_0432
define fn2E37_02A4
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x04;
	sp -= 2;
	ss->*sp = si;
	ax = ss->*((word16) bp + 6);
	ds->t148E = ax;
	ds->t148C = ax;
	cl = 0x04;
	ax <<= cl;
	SCZO = cond(ax);
	ds->t148A = ax;
	sp -= 2;
	ss->*sp = ax;
	fn21DC_097E();
	sp = (word16) sp + 2;
	ds->t1486 = ax;
	ds->t1488 = dx;
	ax = ds->t13B4;
	ds->t149A = ax;
	ds->w1490 = 0x00;
	v12 = ds->t148A;
	sp -= 2;
	ss->*sp = v12;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	sp -= 2;
	ss->*sp = dx;
	v13 = ds->t1486;
	sp -= 2;
	ss->*sp = v13;
	fn2017_0228();
	sp = (word16) sp + 8;
	SCZO = cond(sp);
	(ss->*((word16) bp - 4)).u0 = 0x00;
	while (true)
	{
		ax = ds->t148E;
		SCZO = cond(ss->*((word16) bp - 4) - ax);
		if (Test(UGE,C))
			break;
		si = ss->*((word16) bp - 4);
		cl = 0x04;
		si <<= cl;
		SCZO = cond(si);
		es_bx = ds->t1486;
		es->*((word16) si + ((word16) bx + 8)) = ~0x00;
		ax.u0 = 0x01;
		sp -= 2;
		ss->*sp = ax;
		fn2C27_0292();
		sp = (word16) sp + 2;
		es_bx = ds->t1486;
		es->*((word16) si + ((word16) bx + 0x0A)) = ax;
		SCZO = cond(ds->t149A - 0x00);
		if (Test(EQ,Z))
		{
			sp -= 2;
			ss->*sp = ax;
			fn2C27_0440();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
			es_bx = ds->t1486;
			es->*((word16) si + ((word16) bx + 0x0C)) = ax;
			es->*((word16) si + ((word16) bx + 0x0E)) = dx;
		}
		v20 = (word32) (ss->*((word16) bp - 4)) + 1;
		ss->*((word16) bp - 4) = v20;
		SZO = cond(v20);
	}
	ds->t1498.u0 = 0x0100;
	ds->t1496.u0 = 0x0200;
	v15 = ds->t1496;
	sp -= 2;
	ss->*sp = v15;
	fn21DC_097E();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	ds->t1492 = ax;
	ds->t1494 = dx;
	ss->*((word16) bp - 2) = 0x00;
	while (true)
	{
		ax = ds->t1498;
		SCZO = cond(ss->*((word16) bp - 2) - ax);
		if (Test(UGE,C))
			break;
		bx = ss->*((word16) bp - 2);
		bx <<= 0x01;
		SCZO = cond(bx);
		es_si = ds->t1492;
		Mem0[es:bx + si:word16] = ~0x00;
		v23 = (word32) (ss->*((word16) bp - 2)) + 1;
		ss->*((word16) bp - 2) = v23;
		SZO = cond(v23);
	}
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2E37:0382: define fn2E37_0382
// Called from:
//      fn2E37_04AE
//      fn2E37_04BE
define fn2E37_0382
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x02;
	sp -= 2;
	ss->*sp = si;
	ax = ds->t148C;
	SCZO = cond(ss->*((word16) bp + 6) - ax);
	if (Test(NE,Z))
	{
		SCZO = cond(ss->*((word16) bp + 6) - ax);
		if (Test(UGT,CZ))
		{
			ss->*((word16) bp - 2) = ax;
			while (true)
			{
				ax = ss->*((word16) bp + 6);
				SCZO = cond(ss->*((word16) bp - 2) - ax);
				if (Test(UGE,C))
					break;
				si = ss->*((word16) bp - 2);
				cl = 0x04;
				si <<= cl;
				SCZO = cond(si);
				ax.u0 = 0x01;
				sp -= 2;
				ss->*sp = ax;
				fn2C27_0292();
				sp = (word16) sp + 2;
				es_bx = ds->t1486;
				Mem0[es:bx + 0x0A + si:word16] = ax;
				SCZO = cond(ds->w149A - 0x00);
				if (Test(EQ,Z))
				{
					sp -= 2;
					ss->*sp = ax;
					fn2C27_0440();
					sp = (word16) sp + 2;
					SCZO = cond(sp);
					es_bx = ds->t1486;
					Mem0[es:bx + 0x0C + si:word16] = ax;
					Mem0[es:bx + 0x0E + si:word16] = dx;
				}
				v18 = (word16) (ss->*((word16) bp - 2)) + 1;
				ss->*((word16) bp - 2) = v18;
				SZO = cond(v18);
			}
		}
		else
		{
			ax = ss->*((word16) bp + 6);
			ss->*((word16) bp - 2) = ax;
			while (true)
			{
				ax = ds->t148C;
				SCZO = cond(ss->*((word16) bp - 2) - ax);
				if (Test(UGE,C))
					break;
				v20 = ss->*((word16) bp - 2);
				sp -= 2;
				ss->*sp = v20;
				fn2E37_0096();
				sp = (word16) sp + 2;
				SCZO = cond(sp);
				v21 = ss->*((word16) bp - 2);
				sp -= 2;
				ss->*sp = v21;
				fn2E37_0152();
				sp = (word16) sp + 2;
				si = ss->*((word16) bp - 2);
				cl = 0x04;
				si <<= cl;
				SCZO = cond(si);
				es_bx = ds->t1486;
				v22 = Mem0[es:bx + 0x0A + si:word16];
				sp -= 2;
				ss->*sp = v22;
				fn2C27_03B4();
				sp = (word16) sp + 2;
				SCZO = cond(sp);
				v23 = (word16) (ss->*((word16) bp - 2)) + 1;
				ss->*((word16) bp - 2) = v23;
				SZO = cond(v23);
			}
		}
		ax = ss->*((word16) bp + 6);
		ds->t148C = ax;
		ds->w1490 = 0x00;
	}
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2E37:0432: define fn2E37_0432
// Called from:
//      fn1825_0CD2
//      fn21DC_0EC2
define fn2E37_0432
{
	sp = fp;
	Top = 0;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	fn2C27_01F0();
	++sp;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = ax;
	fn2E37_02A4();
	++sp;
	SCZO = cond(sp);
}

// 2E37:0446: define fn2E37_0446
// Called from:
//      fn1825_0CD2
//      fn21DC_04BA
define fn2E37_0446
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x02;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	(ss->*((word16) bp - 2)).u0 = 0x00;
	while (true)
	{
		ax = ds->w148C;
		SCZO = cond(ss->*((word16) bp - 2) - ax);
		if (Test(UGE,C))
			break;
		v17 = ss->*((word16) bp - 2);
		sp -= 2;
		ss->*sp = v17;
		fn2E37_0096();
		sp = (word16) sp + 2;
		si = ss->*((word16) bp - 2);
		cl = 0x04;
		si <<= cl;
		SCZO = cond(si);
		es_bx = ds->t1486;
		v22 = Mem0[es:bx + 0x0A + si:word16];
		sp -= 2;
		ss->*sp = v22;
		fn2C27_03B4();
		sp = (word16) sp + 2;
		SCZO = cond(sp);
		v23 = (word32) (ss->*((word16) bp - 2)) + 1;
		ss->*((word16) bp - 2) = v23;
		SZO = cond(v23);
	}
	v11 = ds->t148A;
	sp -= 2;
	ss->*sp = v11;
	v12 = ds->t1488;
	sp -= 2;
	ss->*sp = v12;
	v13 = ds->t1486;
	sp -= 2;
	ss->*sp = v13;
	fn21DC_09B4();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	v14 = ds->t1496;
	sp -= 2;
	ss->*sp = v14;
	v15 = ds->t1494;
	sp -= 2;
	ss->*sp = v15;
	v16 = ds->t1492;
	sp -= 2;
	ss->*sp = v16;
	fn21DC_09B4();
	sp = (word16) sp + 6;
	SCZO = cond(sp);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2E37:04AE: define fn2E37_04AE
// Called from:
//      fn2D1A_0BD2
define fn2E37_04AE
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_85459 Eq_85466::*) bp;
	bp = sp;
	v6 = (struct Eq_85459 Eq_85466::*) (ss->*bp).ptr0006;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_85459 Eq_85466::*) v6;
	fn2E37_0382();
	sp = (struct Eq_85459 Eq_85466::*) &sp->ptr0000;
	SCZO = cond(sp);
	bp = (struct Eq_85459 Eq_85466::*) (ss->*sp).ptr0000;
	sp = (struct Eq_85459 Eq_85466::*) &sp->ptr0000;
}

// 2E37:04BE: define fn2E37_04BE
// Called from:
//      fn2D1A_0FA6
define fn2E37_04BE
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_85494 Eq_85501::*) bp;
	bp = sp;
	v6 = (struct Eq_85494 Eq_85501::*) (ss->*bp).ptr0006;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_85494 Eq_85501::*) v6;
	fn2E37_0382();
	sp = (struct Eq_85494 Eq_85501::*) &sp->ptr0000;
	SCZO = cond(sp);
	bp = (struct Eq_85494 Eq_85501::*) (ss->*sp).ptr0000;
	sp = (struct Eq_85494 Eq_85501::*) &sp->ptr0000;
}

// 2E37:04CE: define fn2E37_04CE
// Called from:
//      fn1825_48D2
//      fn1825_496A
//      fn2EB3_0BF0
//      fn2EB3_1526
//      fn2EB3_17FE
//      fn2EB3_20FE
define fn2E37_04CE
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x06;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	v8 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v8;
	v9 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v9;
	v10 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v10;
	fn2E37_0022();
	sp = (word16) sp + 6;
	ss->*((word16) bp - 6) = ax;
	SCZO = cond(ax - ~0x00);
	if (Test(NE,Z))
	{
		SCZO = cond(ds->w149A - 0x00);
		if (Test(NE,Z))
		{
			si = ss->*((word16) bp - 6);
			cl = 0x04;
			si <<= cl;
			SCZO = cond(si);
			es_bx = ds->t1486;
			v22 = Mem0[es:bx + 0x0A + si:word16];
			sp -= 2;
			ss->*sp = v22;
			fn2C27_0440();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
		}
		else
		{
			si = ss->*((word16) bp - 6);
			cl = 0x04;
			si <<= cl;
			SCZO = cond(si);
			es_bx = ds->t1486;
			ax = Mem0[es:bx + 0x0C + si:word16];
			dx = Mem0[es:bx + 0x0E + si:word16];
		}
		ss->*((word16) bp - 4) = ax;
		ss->*((word16) bp - 2) = dx;
	}
	else
	{
		v13 = ss->*((word16) bp + 0x0A);
		sp -= 2;
		ss->*sp = v13;
		v14 = ss->*((word16) bp + 8);
		sp -= 2;
		ss->*sp = v14;
		v15 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v15;
		fn2E37_0212();
		sp = (word16) sp + 6;
		ss->*((word16) bp - 6) = ax;
		SCZO = cond(ds->w149A - 0x00);
		if (Test(NE,Z))
		{
			si = ax;
			cl = 0x04;
			si <<= cl;
			SCZO = cond(si);
			es_bx = ds->t1486;
			v21 = Mem0[es:bx + 0x0A + si:word16];
			sp -= 2;
			ss->*sp = v21;
			fn2C27_0440();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
		}
		else
		{
			si = ss->*((word16) bp - 6);
			cl = 0x04;
			si <<= cl;
			SCZO = cond(si);
			es_bx = ds->t1486;
			ax = Mem0[es:bx + 0x0C + si:word16];
			dx = Mem0[es:bx + 0x0E + si:word16];
		}
		ss->*((word16) bp - 4) = ax;
		ss->*((word16) bp - 2) = dx;
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		v24 = ss->*((word16) bp + 0x0A);
		sp -= 2;
		ss->*sp = v24;
		v25 = ss->*((word16) bp + 8);
		sp -= 2;
		ss->*sp = v25;
		v26 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v26;
		fn208F_0115();
		sp = (word16) sp + 8;
		SCZO = cond(sp);
		v27 = ds->t149C;
		sp -= 2;
		ss->*sp = v27;
		v28 = ss->*((word16) bp - 2);
		sp -= 2;
		ss->*sp = v28;
		v29 = ss->*((word16) bp - 4);
		sp -= 2;
		ss->*sp = v29;
		v30 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v30;
		fn208F_00C9();
		sp = (word16) sp + 8;
		SCZO = cond(ax - ds->t149C);
		if (Test(NE,Z))
		{
			v31 = ss->*((word16) bp - 6);
			sp -= 2;
			ss->*sp = v31;
			fn2E37_0152();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
			ds->w1484 = 0x01;
		}
	}
	ax = ss->*((word16) bp - 4);
	dx = ss->*((word16) bp - 2);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2E37:05C0: define fn2E37_05C0
// Called from:
//      fn2EB3_0064
//      fn2EB3_1206
//      fn2EB3_17FE
//      fn2EB3_20FE
define fn2E37_05C0
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x06;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	v8 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v8;
	v9 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v9;
	v10 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v10;
	fn2E37_0022();
	sp = (word16) sp + 6;
	ss->*((word16) bp - 6) = ax;
	SCZO = cond(ax - ~0x00);
	if (Test(NE,Z))
	{
		SCZO = cond(ds->w149A - 0x00);
		if (Test(NE,Z))
		{
			si = ss->*((word16) bp - 6);
			cl = 0x04;
			si <<= cl;
			SCZO = cond(si);
			es_bx = ds->t1486;
			v22 = Mem0[es:bx + 0x0A + si:word16];
			sp -= 2;
			ss->*sp = v22;
			fn2C27_0440();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
		}
		else
		{
			si = ss->*((word16) bp - 6);
			cl = 0x04;
			si <<= cl;
			SCZO = cond(si);
			es_bx = ds->t1486;
			ax = Mem0[es:bx + 0x0C + si:word16];
			dx = Mem0[es:bx + 0x0E + si:word16];
		}
		ss->*((word16) bp - 4) = ax;
		ss->*((word16) bp - 2) = dx;
	}
	else
	{
		v13 = ss->*((word16) bp + 0x0A);
		sp -= 2;
		ss->*sp = v13;
		v14 = ss->*((word16) bp + 8);
		sp -= 2;
		ss->*sp = v14;
		v15 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v15;
		fn2E37_0212();
		sp = (word16) sp + 6;
		ss->*((word16) bp - 6) = ax;
		SCZO = cond(ds->w149A - 0x00);
		if (Test(NE,Z))
		{
			si = ax;
			cl = 0x04;
			si <<= cl;
			SCZO = cond(si);
			es_bx = ds->t1486;
			v21 = Mem0[es:bx + 0x0A + si:word16];
			sp -= 2;
			ss->*sp = v21;
			fn2C27_0440();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
		}
		else
		{
			si = ss->*((word16) bp - 6);
			cl = 0x04;
			si <<= cl;
			SCZO = cond(si);
			es_bx = ds->t1486;
			ax = Mem0[es:bx + 0x0C + si:word16];
			dx = Mem0[es:bx + 0x0E + si:word16];
		}
		ss->*((word16) bp - 4) = ax;
		ss->*((word16) bp - 2) = dx;
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		v24 = ss->*((word16) bp + 0x0A);
		sp -= 2;
		ss->*sp = v24;
		v25 = ss->*((word16) bp + 8);
		sp -= 2;
		ss->*sp = v25;
		v26 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v26;
		fn208F_0115();
		sp = (word16) sp + 8;
		SCZO = cond(sp);
		v27 = ds->t149C;
		sp -= 2;
		ss->*sp = v27;
		v28 = ss->*((word16) bp - 2);
		sp -= 2;
		ss->*sp = v28;
		v29 = ss->*((word16) bp - 4);
		sp -= 2;
		ss->*sp = v29;
		v30 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v30;
		fn208F_00C9();
		sp = (word16) sp + 8;
		SCZO = cond(ax - ds->t149C);
		if (Test(NE,Z))
		{
			v31 = ss->*((word16) bp - 6);
			sp -= 2;
			ss->*sp = v31;
			fn2E37_0152();
			sp = (word16) sp + 2;
			SCZO = cond(sp);
			ds->w1484 = 0x01;
		}
	}
	si = ss->*((word16) bp - 6);
	cl = 0x04;
	si <<= cl;
	SCZO = cond(si);
	es_bx = ds->t1486;
	Mem0[es:bx + 6 + si:word16] = 0x01;
	ax = ss->*((word16) bp - 4);
	dx = ss->*((word16) bp - 2);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2E37:06C4: define fn2E37_06C4
// Called from:
//      fn2EB3_17FE
//      fn2EB3_20FE
define fn2E37_06C4
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x02;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	v8 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v8;
	v9 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v9;
	v10 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v10;
	fn2E37_0022();
	sp = (word16) sp + 6;
	ss->*((word16) bp - 2) = ax;
	si = ax;
	cl = 0x04;
	si <<= cl;
	SCZO = cond(si);
	es_bx = ds->t1486;
	Mem0[es:bx + 6 + si:word16] = 0x01;
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2E37:06F4: define fn2E37_06F4
// Called from:
//      fn2EB3_0064
//      fn2EB3_0B54
//      fn2EB3_0BB4
define fn2E37_06F4
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x02;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	(ss->*((word16) bp - 2)).u0 = 0x00;
	while (true)
	{
		ax = ds->w148C;
		SCZO = cond(ss->*((word16) bp - 2) - ax);
		if (Test(UGE,C))
			break;
		si = ss->*((word16) bp - 2);
		cl = 0x04;
		si <<= cl;
		es_bx = ds->t1486;
		ax = (word16) (ss->*((word16) bp + 6));
		SCZO = cond(Mem0[es:bx + 4 + si:word16] - ax);
		if (Test(EQ,Z))
		{
			v16 = ss->*((word16) bp - 2);
			sp -= 2;
			ss->*sp = v16;
			fn2E37_0096();
			sp = (word16) sp + 2;
			SCZO = cond(ss->*((word16) bp + 8) - 0x00);
			if (Test(EQ,Z))
			{
				v17 = ss->*((word16) bp - 2);
				sp -= 2;
				ss->*sp = v17;
				fn2E37_0152();
				sp = (word16) sp + 2;
				SCZO = cond(sp);
			}
		}
		v18 = (word16) (ss->*((word16) bp - 2)) + 1;
		ss->*((word16) bp - 2) = v18;
		SZO = cond(v18);
	}
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2E37:0740: define fn2E37_0740
// Called from:
//      fn2EB3_1206
define fn2E37_0740
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x06;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	v8 = ss->*((word16) bp + 0x0A);
	sp -= 2;
	ss->*sp = v8;
	v9 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v9;
	v10 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v10;
	fn2E37_0212();
	sp = (word16) sp + 6;
	ss->*((word16) bp - 6) = ax;
	SCZO = cond(ds->w149A - 0x00);
	if (Test(NE,Z))
	{
		si = ax;
		cl = 0x04;
		si <<= cl;
		SCZO = cond(si);
		es_bx = ds->t1486;
		v18 = Mem0[es:bx + 0x0A + si:word16];
		sp -= 2;
		ss->*sp = v18;
		fn2C27_0440();
		sp = (word16) sp + 2;
		SCZO = cond(sp);
	}
	else
	{
		si = ss->*((word16) bp - 6);
		cl = 0x04;
		si <<= cl;
		SCZO = cond(si);
		es_bx = ds->t1486;
		ax = Mem0[es:bx + 0x0C + si:word16];
		dx = Mem0[es:bx + 0x0E + si:word16];
	}
	ss->*((word16) bp - 4) = ax;
	ss->*((word16) bp - 2) = dx;
	v20 = ds->t149C;
	sp -= 2;
	ss->*sp = v20;
	ax -= ax;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	sp -= 2;
	ss->*sp = dx;
	v21 = ss->*((word16) bp - 4);
	sp -= 2;
	ss->*sp = v21;
	fn2017_0228();
	sp = (word16) sp + 8;
	si = ss->*((word16) bp - 6);
	cl = 0x04;
	si <<= cl;
	SCZO = cond(si);
	es_bx = ds->t1486;
	Mem0[es:bx + 6 + si:word16] = 0x01;
	ax = ss->*((word16) bp - 4);
	dx = ss->*((word16) bp - 2);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

