// 1999_SOFT_LOAN__2C27.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 2C27:0002: define fn2C27_0002
// Called from:
//      fn2C27_0032
//      fn2C27_0140
define fn2C27_0002
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x02;
	SCZO = cond(sp);
	fn2017_01A8();
	cl = 0x06;
	ax >>= cl;
	ss->*((word16) bp - 2) = ax;
	ax = ss->*((word16) bp + 6);
	ax -= ss->*((word16) bp - 2);
	SCZO = cond(ax);
	cx = cx - cx - C;
	ax &= cx;
	ax += Mem0[ss:bp + -2:word16];
	ds->t13B6 = ax;
	cl = 0x06;
	ax <<= cl;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	fn2017_000F();
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2C27:0032: define fn2C27_0032
// Called from:
//      fn21DC_0EC2
define fn2C27_0032
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x04;
	sp -= 2;
	ss->*sp = si;
	SCZO = cond(ss->*((word16) bp + 8) - 0x00);
	if (Test(NE,Z))
	{
		ax.u0 = 5050;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		fn2017_007A();
		sp = (word16) sp + 4;
		ss->*((word16) bp - 4) = ax;
		ax |= ax;
		SZ = cond(ax);
		O = false;
		C.u0 = false;
		if (Test(EQ,Z))
		{
			ax = ss->*((word16) bp + 6);
			ax = (char *) ax.u0 + 0x0F;
			cl = 0x04;
			ax >>= cl;
			SCZO = cond(ax);
			Mem0[ds:5066:word16] = ax;
			ax.u0 = 0x13B2;
			sp -= 2;
			ss->*sp = ds;
			sp -= 2;
			ss->*sp = ax;
			v15 = Mem0[ds:5066:word16];
			sp -= 2;
			ss->*sp = v15;
			fn2017_0097();
			sp = (word16) sp + 6;
			ss->*((word16) bp - 4) = ax;
			ax |= ax;
			SZ = cond(ax);
			O = false;
			C.u0 = false;
			if (Test(EQ,Z))
			{
				ax = ss->*((word16) bp + 6);
				Mem0[ds:0x13B6:word16] = ax;
				Mem0[ds:5044:word16] = 0x01;
				Mem0[ds:0x13CC:word16] = 0x00;
			}
		}
		goto l2C27_00B9;
	}
	Mem0[ds:5044:word16] = 0x00;
	v16 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v16;
	fn2C27_0002();
	sp = (word16) sp + 2;
	Mem0[ds:5050:word16] = ax;
	Mem0[ds:5052:word16] = dx;
	ax |= dx;
	SZ = cond(ax);
	O = false;
	C.u0 = false;
	if (Test(NE,Z))
	{
		SCZO = cond(Mem0[ds:0x13B6:word16] - 0x10);
		if (Test(UGE,C))
		{
			ax -= ax;
			SCZO = cond(ax);
l2C27_00B6:
			ss->*((word16) bp - 4) = ax;
l2C27_00B9:
			SCZO = cond(ss->*((word16) bp - 4) - 0x00);
			if (Test(EQ,Z))
			{
				ax = Mem0[ds:0x13B6:word16];
				ax = (char *) ax.u0 + 1;
				SZO = cond(ax);
				sp -= 2;
				ss->*sp = ax;
				ax.u0 = 5054;
				sp -= 2;
				ss->*sp = ds;
				sp -= 2;
				ss->*sp = ax;
				fn21DC_06DC();
				sp = (word16) sp + 6;
				ax |= ax;
				SZ = cond(ax);
				O = false;
				C.u0 = false;
				if (Test(NE,Z))
				{
					ss->*((word16) bp - 2) = &Eq_76192::t0001;
					while (true)
					{
						ax = Mem0[ds:0x13B6:word16];
						SCZO = cond(ss->*((word16) bp - 2) - ax);
						if (Test(UGT,CZ))
							break;
						bx = (<unknown> Eq_76192::*) (ss->*((word16) bp - 2));
						es_si = Mem0[ds:5054:segptr32];
						Mem0[es:bx + si:byte] = 0x00;
						v23 = (word16) (ss->*((word16) bp - 2)) + 1;
						ss->*((word16) bp - 2) = v23;
						SZO = cond(v23);
					}
l2C27_00F9:
					Mem0[ds:5058:word16] = 0x01;
					ax = Mem0[ds:0x13B6:word16];
					Mem0[ds:0x13B8:word16] = ax;
					SCZO = cond(ss->*((word16) bp - 4) - 0x01);
					ax = ax - ax - C;
					C = ax != 0x00;
					ax = -ax;
					SZO = cond(ax);
					si = ss->*sp;
					sp = bp;
					bp = ss->*sp;
					sp = (word16) sp + 2;
					return;
				}
			}
			(ss->*((word16) bp - 4)).u0 = 0x01;
			goto l2C27_00F9;
		}
	}
	ax.u0 = 0x01;
	goto l2C27_00B6;
}

// 2C27:0112: define fn2C27_0112
// Called from:
//      fn1825_0CD2
//      fn2C27_01AC
define fn2C27_0112
{
	sp = fp;
	Top = 0;
	SCZO = cond(ds->w13B4 - 0x00);
	if (Test(EQ,Z))
	{
		v7 = ds->w13BC;
		sp -= 2;
		ss->*sp = v7;
		v9 = ds->w13BA;
		sp -= 2;
		ss->*sp = v9;
		fn2017_0033();
		sp += 2;
		ax |= ax;
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
			ax = 0x02;
			sp -= 2;
			ss->*sp = ax;
			fn20B2_0176();
			++sp;
			SCZO = cond(sp);
		}
		ds->w13B6 = 0x00;
	}
}

// 2C27:0140: define fn2C27_0140
// Called from:
//      fn1825_0CD2
define fn2C27_0140
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x02;
	sp -= 2;
	ss->*sp = si;
	SCZO = cond(ds->w13B4 - 0x00);
	if (Test(EQ,Z))
	{
		v10 = ds->t13B8;
		sp -= 2;
		ss->*sp = v10;
		fn2C27_0002();
		sp = (word16) sp + 2;
		ds->t13BA = ax;
		ds->w13BC = dx;
		ax |= dx;
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			SCZO = cond(ds->t13B6 - 0x10);
			if (Test(UGE,C))
			{
				ss->*((word16) bp - 2) = &Eq_76388::t0001;
				while (true)
				{
					ax = ds->t13B6;
					SCZO = cond(ss->*((word16) bp - 2) - ax);
					if (Test(UGT,CZ))
						break;
					bx = (<unknown> Eq_76388::*) (ss->*((word16) bp - 2));
					es_si = ds->t13BE;
					Mem0[es:bx + si:byte] = 0x00;
					v20 = (word16) (ss->*((word16) bp - 2)) + 1;
					ss->*((word16) bp - 2) = v20;
					SZO = cond(v20);
				}
				ds->w13C2 = 0x01;
				si = ss->*sp;
				sp = bp;
				bp = ss->*sp;
				sp = (word16) sp + 2;
				return;
			}
		}
		ax.u0 = 0x03;
		sp -= 2;
		ss->*sp = ax;
		fn20B2_0176();
		sp = (word16) sp + 2;
		SCZO = cond(sp);
		ds->t13B6.u0 = 0x00;
	}
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2C27:01AC: define fn2C27_01AC
// Called from:
//      fn21DC_04BA
define fn2C27_01AC
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_76419 Eq_76426::*) bp;
	bp = sp;
	sp -= 0x02;
	SCZO = cond(sp);
	ax = ds->ptr13B6;
	(ss->*bp).ptrFFFFFFFE = (struct Eq_76419 Eq_76426::*) ax;
	fn2C27_0112();
	SCZO = cond(ds->w13B4 - 0x00);
	if (Test(NE,Z))
	{
		v10 = ds->ptr13B2;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_76419 Eq_76426::*) v10;
		fn2017_00CB();
		sp = (struct Eq_76419 Eq_76426::*) &sp->ptr0000;
		SCZO = cond(sp);
	}
	SCZO = cond(ds->ptr13B8 - 0x00);
	if (Test(NE,Z))
	{
		ax = ds->ptr13B8;
		ax = (struct Eq_76419 Eq_76426::*) &ax->ptr0000;
		SZO = cond(ax);
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_76419 Eq_76426::*) ax;
		v12 = ds->ptr13C0;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_76419 Eq_76426::*) v12;
		v13 = ds->ptr13BE;
		sp -= 2;
		(ss->*sp).ptr0000 = (struct Eq_76419 Eq_76426::*) v13;
		fn21DC_09B4();
		sp = (struct Eq_76419 Eq_76426::*) &sp->ptr0000;
		SCZO = cond(sp);
	}
	sp = bp;
	bp = (struct Eq_76419 Eq_76426::*) (ss->*sp).ptr0000;
	sp = (struct Eq_76419 Eq_76426::*) &sp->ptr0000;
}

// 2C27:01F0: define fn2C27_01F0
// Called from:
//      fn2D1A_0BD2
//      fn2D1A_0D38
//      fn2D1A_0FA6
//      fn2E37_0432
define fn2C27_01F0
{
	selector ds;
	word16 wArg04;
	word16 bx;
	word16 cx;
	selector es;
	Top_3 = 0;
	if (wArg04 != 0x00)
	{
		wLoc08_112.u0 = 0x01;
		wLoc06_113 = 0x00;
		while (true)
		{
			es_166 = ϕ(es, es_167);
			cx_161 = ϕ(cx, cx_59);
			bx_151 = ϕ(bx, bx_152);
			wLoc06_122 = ϕ(wLoc06_113, wLoc06_124);
			wLoc08_114 = ϕ(wLoc08_112, wLoc08_126);
			Mem18 = ϕ(Mem16, Mem65);
			ax_19 = ds->t13B6;
			SCZO_22 = cond(wLoc08_114 - ax_19);
			C_156 = SLICE(SCZO_22, bool, 1);
			O_171 = SLICE(SCZO_22, bool, 4);
			S_174 = (bool) SCZO_22;
			Z_185 = SLICE(SCZO_22, bool, 2);
			if (wLoc08_114 > ax_19)
				break;
			bx_24 = wLoc08_114;
			es_si_25 = ds->ptr13BE;
			es_26 = SLICE(es_si_25, selector, 16);
			al_28 = es_si_25[(uipr32) wLoc08_114];
			ax_30 = (uint16) al_28;
			v20_31 = (word16) wLoc08_114.u0 + ax_30;
			wLoc04_116 = 0x00;
			while (true)
			{
				es_168 = ϕ(es_26, es_44);
				bx_153 = ϕ(bx_24, bx_45);
				wLoc04_118 = ϕ(wLoc04_116, wLoc04_119);
				Mem37 = ϕ(Mem34, Mem49);
				si_39 = v20_31 + wLoc04_118;
				if (ds->t13B6 < si_39)
					break;
				es_bx_43 = ds->ptr13BE;
				es_44 = SLICE(es_bx_43, selector, 16);
				bx_45 = (word16) es_bx_43;
				if (Mem37[es_bx_43 + si_39:byte] != 0x00)
					break;
				v27_48 = wLoc04_118 + 0x01;
				wLoc04_119 = v27_48;
			}
			es_167 = ϕ(es_168, es_44);
			bx_152 = ϕ(bx_153, bx_45);
			ax_55 = wLoc06_122 - wLoc04_118;
			cx_58 = 0x00 - (word16) (ax_55 < 0x00);
			cx_59 = ~cx_58;
			ax_60 = ax_55 & cx_59;
			ax_61 = ax_60 + wLoc04_118;
			wLoc06_124 = ax_61;
			v25_64 = v20_31 + wLoc04_118;
			wLoc08_126 = v25_64;
		}
		ax_67 = wLoc06_122;
	}
	else
	{
		wLoc08_133.u0 = 0x01;
		wLoc04_134 = 0x00;
		while (true)
		{
			es_163 = ϕ(es, es_86);
			bx_148 = ϕ(bx, bx_84);
			wLoc04_136 = ϕ(wLoc04_134, wLoc04_144);
			wLoc08_135 = ϕ(wLoc08_133, wLoc08_139);
			Mem78 = ϕ(Mem76, Mem97);
			ax_79 = ds->t13B6;
			SCZO_82 = cond(wLoc08_135 - ax_79);
			C_155 = SLICE(SCZO_82, bool, 1);
			O_170 = SLICE(SCZO_82, bool, 4);
			S_173 = (bool) SCZO_82;
			Z_184 = SLICE(SCZO_82, bool, 2);
			if (wLoc08_135 > ax_79)
				break;
			bx_84 = wLoc08_135;
			es_si_85 = ds->ptr13BE;
			es_86 = SLICE(es_si_85, selector, 16);
			if (es_si_85[(uipr32) wLoc08_135] == 0x00)
			{
				v15_90 = wLoc04_136 + 0x01;
				wLoc04_137 = v15_90;
			}
			wLoc04_144 = ϕ(wLoc04_136, wLoc04_137);
			v17_96.u1 = (word16) wLoc08_135.u0 + 1;
			wLoc08_139 = v17_96;
		}
		ax_99 = wLoc04_136;
	}
}

// 2C27:0292: define fn2C27_0292
// Called from:
//      fn2D1A_0BD2
//      fn2E37_02A4
//      fn2E37_0382
define fn2C27_0292
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x08;
	sp -= 2;
	ss->*sp = si;
	SCZO = cond(ss->*((word16) bp + 6) - 0x00);
	if (Test(NE,Z))
	{
		ax = Mem0[ds:0x13B6:word16];
		SCZO = cond(ss->*((word16) bp + 6) - ax);
		if (Test(ULE,CZ))
		{
			SCZO = cond(ss->*((word16) bp + 6) - 0x40);
			if (Test(ULE,CZ))
			{
				ax = Mem0[ds:5058:word16];
				ss->*((word16) bp - 8) = ax;
				ss->*((word16) bp - 2) = 0x00;
				ss->*((word16) bp - 6) = 0x00;
				while (true)
				{
					ax = ss->*((word16) bp + 6);
					SCZO = cond(ss->*((word16) bp - 2) - ax);
					if (Test(UGE,C))
						break;
					ax = Mem0[ds:0x13B6:word16];
					SCZO = cond(ss->*((word16) bp - 6) - ax);
					if (Test(UGE,C))
						break;
					bx = ss->*((word16) bp - 8);
					es_si = Mem0[ds:5054:segptr32];
					al = Mem0[es:bx + si:byte];
					ah -= ah;
					ax += Mem0[ss:bp + -2:word16];
					ss->*((word16) bp - 4) = ax;
					v19 = Mem0[ss:bp + -8:word16] + ax;
					ss->*((word16) bp - 8) = v19;
					v20 = Mem0[ss:bp + -6:word16] + ax;
					ss->*((word16) bp - 6) = v20;
					ax = ss->*((word16) bp - 8);
					ax += Mem0[ss:bp + 6:word16];
					--ax;
					SCZO = cond(ax - Mem0[ds:0x13B6:word16]);
					if (Test(UGT,CZ))
					{
						ax = Mem0[ds:0x13B6:word16];
						ax -= ss->*((word16) bp - 8);
						ax.u0 = (byte) ax.u0 + 1;
						v22 = Mem0[ss:bp + -6:word16] + ax;
						ss->*((word16) bp - 6) = v22;
						SCZO = cond(v22);
						(ss->*((word16) bp - 8)).u0 = 0x01;
					}
					else
					{
						SCZO = cond(Mem0[ds:5044:word16] - 0x00);
						if (Test(NE,Z))
						{
							SCZO = cond(ss->*((word16) bp + 6) - 0x30);
							if (Test(UGT,CZ))
							{
								si = ss->*((word16) bp - 8);
								--si;
								SZP = cond(si & 0x0F);
								O = false;
								C = false;
								if (Test(NE,Z))
								{
									ax = si;
									ax &= 0x0F;
									ax -= 0x10;
									ax = -ax;
									ss->*((word16) bp - 4) = ax;
									v26 = Mem0[ss:bp + -8:word16] + ax;
									ss->*((word16) bp - 8) = v26;
									v27 = Mem0[ss:bp + -6:word16] + ax;
									ss->*((word16) bp - 6) = v27;
									SCZO = cond(v27);
								}
							}
						}
					}
					ss->*((word16) bp - 2) = 0x00;
					while (true)
					{
						ax = ss->*((word16) bp + 6);
						SCZO = cond(ss->*((word16) bp - 2) - ax);
						if (Test(UGE,C))
							break;
						bx = ss->*((word16) bp - 8);
						bx += Mem0[ss:bp + -2:word16];
						es_si = Mem0[ds:5054:segptr32];
						SCZO = cond(Mem0[es:bx + si:byte] - 0x00);
						if (Test(NE,Z))
							break;
						v29 = (word16) (ss->*((word16) bp - 2)) + 1;
						ss->*((word16) bp - 2) = v29;
						SZO = cond(v29);
					}
				}
			}
		}
	}
	ax = ss->*((word16) bp + 6);
	SCZO = cond(ss->*((word16) bp - 2) - ax);
	if (Test(NE,Z))
	{
		ax.u0 = 24240;
		sp -= 2;
		ss->*sp = ds;
		sp -= 2;
		ss->*sp = ax;
		ax = ss->*((word16) bp + 6);
		cl = 0x0A;
		ax <<= cl;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		fn20B2_0E9E();
		sp = (word16) sp + 6;
		SCZO = cond(sp);
		(ss->*((word16) bp - 8)).u0 = 0x00;
	}
	else
	{
		ss->*((word16) bp - 2) = 0x00;
		while (true)
		{
			ax = ss->*((word16) bp + 6);
			SCZO = cond(ss->*((word16) bp - 2) - ax);
			if (Test(UGE,C))
				break;
			bx = ss->*((word16) bp - 8);
			bx += Mem0[ss:bp + -2:word16];
			es_si = Mem0[ds:5054:segptr32];
			al = ss->*((word16) bp + 6);
			al -= ss->*((word16) bp - 2);
			SCZO = cond(al);
			Mem0[es:bx + si:byte] = al;
			v28 = (word16) (ss->*((word16) bp - 2)) + 1;
			ss->*((word16) bp - 2) = v28;
			SZO = cond(v28);
		}
		ax = ss->*((word16) bp - 8);
		ax += Mem0[ss:bp + -2:word16];
		SCZO = cond(ax);
		Mem0[ds:5058:word16] = ax;
	}
	ax = ss->*((word16) bp - 8);
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2C27:03B4: define fn2C27_03B4
// Called from:
//      fn2D1A_0B04
//      fn2E37_0382
//      fn2E37_0446
define fn2C27_03B4
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x04;
	sp -= 2;
	ss->*sp = si;
	ax = ds->t13B6;
	SCZO = cond(ss->*((word16) bp + 6) - ax);
	if (Test(ULE,CZ))
	{
		bx = (byte Eq_77171::*) (ss->*((word16) bp + 6));
		es_si = ds->t13BE;
		SCZO = cond(Mem0[es:bx + si:byte] - 0x00);
		if (Test(NE,Z))
		{
			bx = (byte Eq_77171::*) (ss->*((word16) bp + 6));
			es_si = ds->t13BE;
			al = Mem0[es:bx + si:byte];
			ah -= ah;
			SCZO = cond(ah);
			ss->*((word16) bp - 4) = ax;
			do
			{
				v17 = ss->*((word16) bp - 4) - 0x01;
				ss->*((word16) bp - 4) = v17;
				bx = (byte Eq_77171::*) (ss->*((word16) bp + 6));
				bx += Mem0[ss:bp + -4:word16];
				si = ds->t13BE;
				Mem0[es:bx + si:byte] = 0x00;
				SCZO = cond(ss->*((word16) bp - 4) - 0x00);
			} while (Test(NE,Z));
l2C27_0404:
			ax = ds->t13C4;
			SCZO = cond(ss->*((word16) bp + 6) - ax);
			if (Test(EQ,Z))
				ds->t13C4.u0 = 0x00;
			(ss->*((word16) bp - 2)).u0 = 0x00;
			do
			{
				si = ss->*((word16) bp - 2);
				si <<= 0x01;
				si = (word16) si + 5070;
				ax = ds->*si;
				SCZO = cond(ss->*((word16) bp + 6) - ax);
				if (Test(EQ,Z))
					(ds->*si).u0 = 0x00;
				v19 = (word32) (ss->*((word16) bp - 2)) + 1;
				ss->*((word16) bp - 2) = v19;
				SCZO = cond(ss->*((word16) bp - 2) - 0x04);
			} while (Test(ULT,C));
			ds->w13C2 = 0x01;
			si = ss->*sp;
			sp = bp;
			bp = ss->*sp;
			sp = (word16) sp + 2;
			return;
		}
	}
	ax.u0 = 0x04;
	sp -= 2;
	ss->*sp = ax;
	fn20B2_0176();
	sp = (word16) sp + 2;
	SCZO = cond(sp);
	goto l2C27_0404;
}

// 2C27:0440: define fn2C27_0440
// Called from:
//      fn2D1A_003C
//      fn2D1A_0186
//      fn2D1A_02FC
//      fn2D1A_03E4
//      fn2D1A_0598
//      fn2D1A_064E
//      fn2E37_0096
//      fn2E37_02A4
//      fn2E37_0382
//      fn2E37_04CE
//      fn2E37_05C0
//      fn2E37_0740
define fn2C27_0440
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x10;
	sp -= 2;
	ss->*sp = si;
	ax = ds->t13C4;
	SCZO = cond(ss->*((word16) bp + 6) - ax);
	if (Test(NE,Z))
	{
		SCZO = cond(ds->w13B4 - 0x00);
		if (Test(EQ,Z))
		{
			ax = ss->*((word16) bp + 6);
			--ax;
			ss->*((word16) bp - 8) = ax;
			dx -= dx;
			SCZO = cond(dx);
			cl = 0x0A;
			do
			{
				ax <<= 0x01;
				SCZO = cond(ax);
				v14 = (dx & 0x01 << 0x10 - 0x01) != 0x00;
				dx = __rcl<word16,byte>(dx, 0x01, C);
				C = v14;
				--cl;
				SZO = cond(cl);
			} while (Test(NE,Z));
			sp -= 2;
			ss->*sp = dx;
			sp -= 2;
			ss->*sp = ax;
			v16 = ds->t13BC;
			sp -= 2;
			ss->*sp = v16;
			v17 = ds->t13BA;
			sp -= 2;
			ss->*sp = v17;
			fn2017_00DF();
			sp = (word16) sp + 8;
			SCZO = cond(sp);
			ss->*((word16) bp - 0x0C) = ax;
			ss->*((word16) bp - 0x0A) = dx;
		}
		else
		{
			(ss->*((word16) bp - 0x0E)).u0 = 0x00;
			while (true)
			{
				SCZO = cond(ss->*((word16) bp - 0x0E) - 0x04);
				if (Test(UGE,C))
					break;
				bx = ss->*((word16) bp - 0x0E);
				bx <<= 0x01;
				ax = ss->*((word16) bp + 6);
				SCZO = cond(ds->*((word16) bx + 5070) - ax);
				if (Test(EQ,Z))
				{
					bx = ss->*((word16) bp - 0x0E);
					bx <<= 0x01;
					bx <<= 0x01;
					SCZO = cond(bx);
					ax = ds->*((word16) bx + 5078);
					dx = ds->*((word16) bx + 5080);
					si = ss->*sp;
					sp = bp;
					bp = ss->*sp;
					sp = &sp.u7->u1.t0002.u0;
					return;
				}
				v19 = (word80) (ss->*((word16) bp - 0x0E)) + 1;
				ss->*((word16) bp - 0x0E) = v19;
				SZO = cond(v19);
			}
			ax = ss->*((word16) bp + 6);
			--ax;
			ss->*((word16) bp - 8) = ax;
			bx = ss->*((word16) bp + 6);
			es_si = ds->t13BE;
			al = Mem0[es:bx + si:byte];
			ah -= ah;
			ss->*((word16) bp - 2) = ax;
			ax = ss->*((word16) bp - 8);
			ax &= 0x0F;
			ss->*((word16) bp - 4) = ax;
			ax = ss->*((word16) bp - 8);
			cl = 0x04;
			ax >>= cl;
			ss->*((word16) bp - 16) = ax;
			ax = ss->*((word16) bp - 4);
			ax += Mem0[ss:bp + -2:word16];
			--ax;
			ax >>= cl;
			ax = (word16) ax + 1;
			ss->*((word16) bp - 6) = ax;
			ax = ds->t13CC;
			ss->*((word16) bp - 0x0E) = ax;
			ax = ss->*((word16) bp - 6);
			v26 = Mem0[ds:0x13CC:word16] + ax;
			ds->t13CC = v26;
			SCZO = cond(ds->t13CC - 0x04);
			if (Test(UGT,CZ))
			{
				(ss->*((word16) bp - 0x0E)).u0 = 0x00;
				ds->t13CC = ax;
			}
			ax = ss->*((word16) bp - 0x0E);
			cl = 0x0E;
			ax <<= cl;
			dx = ss->*((word16) bp - 4);
			cl = 0x0A;
			dx <<= cl;
			ax += dx;
			ax += Mem0[ds:5050:word16];
			dx = ds->t13BC;
			ss->*((word16) bp - 0x0C) = ax;
			ss->*((word16) bp - 0x0A) = dx;
			bx = ss->*((word16) bp - 0x0E);
			bx <<= 0x01;
			bx <<= 0x01;
			SCZO = cond(bx);
			ds->*((word16) bx + 5078) = ax;
			ds->*((word16) bx + 5080) = dx;
			while (true)
			{
				ax = ss->*((word16) bp - 6);
				v28 = ss->*((word16) bp - 6) - 0x01;
				ss->*((word16) bp - 6) = v28;
				ax |= ax;
				SZ = cond(ax);
				O = false;
				C.u0 = false;
				if (Test(EQ,Z))
					break;
				v29 = ss->*((word16) bp - 0x0E);
				sp -= 2;
				ss->*sp = v29;
				v30 = ss->*((word16) bp - 16);
				sp -= 2;
				ss->*sp = v30;
				v31 = ds->t13B2;
				sp -= 2;
				ss->*sp = v31;
				fn2017_00B1();
				sp = (word16) sp + 6;
				ax |= ax;
				SZ = cond(ax);
				O = false;
				C.u0 = false;
				if (Test(NE,Z))
				{
					ax.u0 = 0x05;
					sp -= 2;
					ss->*sp = ax;
					fn20B2_0176();
					sp = &sp.u7->u1.t0002.u0;
					SCZO = cond(sp);
				}
				bx = ss->*((word16) bp - 0x0E);
				bx <<= 0x01;
				SCZO = cond(bx);
				ax = ss->*((word16) bp + 6);
				ds->*((word16) bx + 5070) = ax;
				(ss->*((word16) bp + 6)).u0 = 0x00;
				v32 = (word80) (ss->*((word16) bp - 0x0E)) + 1;
				ss->*((word16) bp - 0x0E) = v32;
				v33 = (word80) (ss->*((word16) bp - 16)) + 1;
				ss->*((word16) bp - 16) = v33;
				SZO = cond(v33);
			}
		}
		ax = ss->*((word16) bp + 6);
		ds->t13C4 = ax;
		ax = ss->*((word16) bp - 0x0C);
		dx = ss->*((word16) bp - 0x0A);
		ds->t13C6 = ax;
		ds->t13C8 = dx;
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = &sp.u7->u1.t0002.u0;
	}
	else
	{
		ax = ds->t13C6;
		dx = ds->t13C8;
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = &sp.u7->u1.t0002.u0;
	}
}

