// 1999_SOFT_LOAN__436F.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 3CEE:681D: define fn3CEE_681D
// Called from:
//      fn3CEE_1472
define fn3CEE_681D
{
	sp = fp;
	Top = 0;
	__halt();
}

