// 1999_SOFT_LOAN__1F38.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 1F38:0000: define fn1F38_0000
// Called from:
//      fn1F38_029A
//      fn1F38_042D
//      fn1F38_049F
//      fn1F38_05DB
define fn1F38_0000
{
	selector ds;
	byte al;
	Top_3 = 0;
	es_di_9 = ds->t0F0C;
	di_52 = (word16) es_di_9;
	ah_10 = ds->b0F14;
	D_11 = false;
	SZP_12 = cond(ds->w0EE8);
	Z_15 = SLICE(SZP_12, bool, 2);
	P_82 = SLICE(SZP_12, bool, 5);
	S_85 = (bool) SZP_12;
	ax_18 = SEQ(ah_10, al);
	if (ds->w0EE8 != 0x00)
	{
		do
			al_25 = __in<byte>(0x03DA);
		while ((al_25 & 0x01) != 0x00);
		__cli();
		do
		{
			al_31 = __in<byte>(0x03DA);
			SZP_32 = cond(al_31 & 0x01);
			Z_35 = SLICE(SZP_32, bool, 2);
			P_83 = SLICE(SZP_32, bool, 5);
			S_86 = (bool) SZP_32;
		} while ((al_31 & 0x01) == 0x00);
	}
	Z_90 = ϕ(Z_15, Z_35);
	S_84 = ϕ(S_85, S_86);
	P_81 = ϕ(P_82, P_83);
	O_80 = false;
	C_75 = false;
	ax_46 = ax_18;
	*es_di_9.u1 = ax_18;
	di_56 = di_52 + 2;
	__sti();
	ds->t0F0C = di_52 + 2;
}

// 1F38:002E: define fn1F38_002E
// Called from:
//      fn1F38_003F
//      fn1F38_0104
//      fn1F38_017F
//      fn1F38_01FA
//      fn1F38_032B
//      fn1F38_04E7
//      fn1F38_096A
//      fn1F38_09C6
define fn1F38_002E
{
	word16 ax;
	word16 bx;
	selector ds;
	<unknown> Mem0;
	Top_3 = 0;
	cx_4 = 0xA0;
	dx_17 = SLICE(ax *32 0xA0, word16, 16);
	bx_8 = bx << 0x01;
	ax_10 = ax * 0xA0 + (bx << 0x01);
	ax_13 = ax_10 + ds->w0F10;
	SCZO_14 = cond(ax_13);
	C_16 = SLICE(SCZO_14, bool, 1);
	O_18 = SLICE(SCZO_14, bool, 4);
	S_19 = (bool) SCZO_14;
	Z_20 = SLICE(SCZO_14, bool, 2);
	ds->w0F0C = ax_13;
}

// 1F38:003F: define fn1F38_003F
// Called from:
//      fn1F38_00B6
//      fn1F38_029A
//      fn1F38_042D
//      fn1F38_05DB
//      fn1F38_094C
define fn1F38_003F
{
	selector ds;
	Top_3 = 0;
	ax_18 = ds->w0F06;
	bx_19 = ds->w0F08;
	ax_20 = ax_18 + ds->w0EEA;
	bx_21 = bx_19 + ds->w0EEC;
	fn1F38_002E();
}

// 1F38:0069: define fn1F38_0069
// Called from:
//      fn1F38_042D
//      fn1F38_049F
//      fn1F38_04E7
//      fn1F38_094C
define fn1F38_0069
{
	selector ds;
	<unknown> Mem0;
	Top_3 = 0;
	dh_6 = ds->b0F06;
	dl_7 = ds->b0F08;
	dh_8 = dh_6 + ds->b0EEA;
	dl_9 = dl_7 + ds->b0EEC;
	SCZO_10 = cond(dl_9);
	C_13 = SLICE(SCZO_10, bool, 1);
	O_14 = SLICE(SCZO_10, bool, 4);
	S_15 = (bool) SCZO_10;
	Z_16 = SLICE(SCZO_10, bool, 2);
	ah_11 = 0x02;
	bh_12 = 0x00;
	bios_video_set_cursor_position(0x00, dh_8, dl_9);
}

// 1F38:0080: define fn1F38_0080
// Called from:
//      fn1F38_042D
//      fn1F38_049F
define fn1F38_0080
{
	selector ds;
	<unknown> Mem0;
	Top_3 = 0;
	ax_6 = ds->w0F08;
	ax_7 = ax_6 * 0x02;
	v7_8 = ds->w0F0C - ax_6 * 0x02;
	ds->w0F0C = v7_8;
	SCZO_10 = cond(v7_8);
	C_12 = SLICE(SCZO_10, bool, 1);
	O_13 = SLICE(SCZO_10, bool, 4);
	S_14 = (bool) SCZO_10;
	Z_15 = SLICE(SCZO_10, bool, 2);
	ds->w0F08 = 0x00;
}

// 1F38:0090: define fn1F38_0090
// Called from:
//      fn1F38_042D
//      fn1F38_049F
define fn1F38_0090
{
	selector ds;
	<unknown> Mem0;
	bool D;
	word16 di;
	bool P;
	Top_3 = 0;
	ax_6 = ds->w0F06;
	if (ax_6 < ds->w0EEE)
	{
		v8_16 = ds->w0F0C + 0xA0;
		ds->w0F0C = v8_16;
		SCZO_18 = cond(v8_16);
		C_24 = SLICE(SCZO_18, bool, 1);
		v9_19 = ds->w0F06 + 0x01;
		ds->w0F06 = v9_19;
		SZO_21 = cond(v9_19);
		O_30 = SLICE(SZO_21, bool, 4);
		S_34 = (bool) SZO_21;
		Z_38 = SLICE(SZO_21, bool, 2);
	}
	else
		fn1F38_0279();
	Z_37 = ϕ(Z_38, Z_12);
	S_33 = ϕ(S_34, S_10);
	P_31 = ϕ(P, P_15);
	O_29 = ϕ(O_30, O_14);
	di_27 = ϕ(di, di_9);
	D_25 = ϕ(D, D_13);
	C_23 = ϕ(C_24, C_11);
}

// 1F38:00A9: define fn1F38_00A9
// Called from:
//      fn1F38_042D
define fn1F38_00A9
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = (struct Eq_41372 * Eq_41373::*) es;
	sp -= 2;
	ss->*sp = (struct Eq_41372 * Eq_41373::*) si;
	sp -= 2;
	ss->*sp = (struct Eq_41372 * Eq_41373::*) cx;
	ah = 0x0E;
	al = 0x07;
	bios_video_teletype_output(al, bh, bl);
	cx = (struct Eq_41372 *) (ss->*sp);
	sp = (struct Eq_41372 * Eq_41373::*) ((char *) sp + 2);
	si = (struct Eq_41372 *) (ss->*sp);
	sp = (struct Eq_41372 * Eq_41373::*) ((char *) sp + 2);
	es = (struct Eq_41372 *) (ss->*sp);
	sp = (struct Eq_41372 * Eq_41373::*) ((char *) sp + 2);
}

// 1F38:00B6: define fn1F38_00B6
// Called from:
//      fn1F38_042D
define fn1F38_00B6
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = (struct Eq_41428 * Eq_41429::*) es;
	sp -= 2;
	ss->*sp = (struct Eq_41428 * Eq_41429::*) si;
	sp -= 2;
	ss->*sp = (struct Eq_41428 * Eq_41429::*) cx;
	ax = ds->w0F06;
	bx = ds->w0F08;
	ax |= bx;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		ax = ds->w0F06;
		--bx;
		SZO = cond(bx);
		if (Test(SG,S))
		{
			bx = ds->w0EF0;
			--ax;
			SZO = cond(ax);
		}
		ds->w0F06 = ax;
		ds->w0F08 = bx;
		fn1F38_003F();
		es_di = ds->t0F0C;
		ah = ds->b0F14;
		al = 0x20;
		es->*di = ax;
		++di;
	}
	cx = (struct Eq_41428 *) (ss->*sp);
	sp = (struct Eq_41428 * Eq_41429::*) ((char *) sp + 2);
	si = (struct Eq_41428 *) (ss->*sp);
	sp = (struct Eq_41428 * Eq_41429::*) ((char *) sp + 2);
	es = (struct Eq_41428 *) (ss->*sp);
	sp = (struct Eq_41428 * Eq_41429::*) ((char *) sp + 2);
}

// 1F38:00E8: define fn1F38_00E8
// Called from:
//      fn1F38_0104
//      fn1F38_017F
//      fn1F38_01FA
//      fn1F38_096A
//      fn1F38_09C6
define fn1F38_00E8
{
	byte ch;
	byte cl;
	byte dh;
	byte dl;
	Top_3 = 0;
	SCZO_5 = cond(ch - 0x19);
	C_6 = SLICE(SCZO_5, bool, 1);
	O_23 = SLICE(SCZO_5, bool, 4);
	S_30 = (bool) SCZO_5;
	Z_39 = SLICE(SCZO_5, bool, 2);
	if (ch < 0x19)
	{
		SCZO_8 = cond(cl - 0x50);
		C_9 = SLICE(SCZO_8, bool, 1);
		O_24 = SLICE(SCZO_8, bool, 4);
		S_31 = (bool) SCZO_8;
		Z_40 = SLICE(SCZO_8, bool, 2);
		if (cl < 0x50)
		{
			SCZO_11 = cond(dh - 0x19);
			C_12 = SLICE(SCZO_11, bool, 1);
			O_25 = SLICE(SCZO_11, bool, 4);
			S_32 = (bool) SCZO_11;
			Z_41 = SLICE(SCZO_11, bool, 2);
			if (dh < 0x19)
			{
				SCZO_14 = cond(dl - 0x50);
				C_15 = SLICE(SCZO_14, bool, 1);
				O_26 = SLICE(SCZO_14, bool, 4);
				S_33 = (bool) SCZO_14;
				Z_42 = SLICE(SCZO_14, bool, 2);
				if (dl < 0x50)
				{
					SCZO_16 = cond(ch - dh);
					C_17 = SLICE(SCZO_16, bool, 1);
					O_27 = SLICE(SCZO_16, bool, 4);
					S_34 = (bool) SCZO_16;
					Z_43 = SLICE(SCZO_16, bool, 2);
					if (ch < dh)
					{
						SCZO_18 = cond(cl - dl);
						C_20 = SLICE(SCZO_18, bool, 1);
						O_28 = SLICE(SCZO_18, bool, 4);
						S_35 = (bool) SCZO_18;
						Z_44 = SLICE(SCZO_18, bool, 2);
					}
				}
			}
		}
	}
	Z_38 = ϕ(Z_39, Z_40, Z_41, Z_42, Z_43, Z_44);
	S_29 = ϕ(S_30, S_31, S_32, S_33, S_34, S_35);
	O_22 = ϕ(O_23, O_24, O_25, O_26, O_27, O_28);
	C_19 = ϕ(C_6, C_9, C_12, C_15, C_17, C_20);
	C_21 = !C_19;
}

// 1F38:0104: define fn1F38_0104
// Called from:
//      fn1F38_0279
//      fn1F38_055E
define fn1F38_0104
{
	word16 cx;
	ch_27 = SLICE(cx, byte, 8);
	cl_28 = (byte) cx;
	word16 dx;
	dh_29 = SLICE(dx, byte, 8);
	dl_30 = (byte) dx;
	selector ds;
	bool D;
	word16 di;
	bool P;
	Top_3 = 0;
	v12_24 = ds->t0F0C;
	fn1F38_00E8();
	if (!C_32)
	{
		D_35 = false;
		ax_48 = (uint16) ch_27;
		bx_50 = (uint16) cl_28;
		fn1F38_002E();
		dl_63 = (byte) dx;
		dh_66 = SLICE(dx, byte, 8);
		cl_64 = (byte) cx;
		ch_67 = SLICE(cx, byte, 8);
		dl_65 = dl_63 - cl_64;
		dh_68 = dh_66 - ch_67;
		cx_71 = (uint16) dl_65;
		es_di_75 = ds->t0F0C;
		di_76 = (word16) es_di_75;
		es_154 = SLICE(es_di_75, selector, 16);
		si_78 = di_76 + 80;
		ds_85 = ds->ptr0F0E;
		bx_155 = (uint16) dh_68;
		if (ds->w0EE8 != 0x00)
			__out<byte>(0x03D8, 33);
		do
		{
			bx_111 = ϕ(bx_155, bx_155, bx_112);
			si_97 = ϕ(si_78, si_78, si_109);
			di_94 = ϕ(di_76, di_76, di_108);
			size_99 = (cx_71 + 0x01) *32 0x02;
			memcpy(&(es_154->*di_94), si_97, size_99);
			cx_106 = cx_71 + 0x01;
			di_108 = di_94 + 80;
			si_109 = (word16) ((char *) si_97 + 0x00A0);
			bx_112 = bx_111 - 0x01;
		} while (bx_112 != 0x00);
		ah_117 = ds->b0F14;
		ax_157 = SEQ(ah_117, 0x20);
		while (true)
		{
			di_150 = ϕ(di_108, di_152);
			Mem121 = ϕ(Mem98, Mem151);
			cx_119 = ϕ(cx_106, cx_153);
			if (cx_119 == 0x00)
				break;
			es_154->*di_150 = ax_157;
			di_152 = di_150 + 1;
			cx_153 = cx_119 - 0x01;
		}
		SZP_122 = cond(ds->w0EE8);
		Z_125 = SLICE(SZP_122, bool, 2);
		P_203 = SLICE(SZP_122, bool, 5);
		S_205 = (bool) SZP_122;
		O_123 = false;
		C_124 = false;
		if (ds->w0EE8 != 0x00)
			__out<byte>(0x03D8, 0x29);
	}
	Z_209 = ϕ(Z_33, Z_125, Z_125);
	S_204 = ϕ(S_31, S_205, S_205);
	P_201 = ϕ(P, P_203, P_203);
	O_200 = ϕ(O_34, O_123, O_123);
	di_198 = ϕ(di, di_150, di_150);
	D_194 = ϕ(D, D_35, D_35);
	C_193 = ϕ(C_32, C_124, C_124);
	ds->t0F0C = v12_24;
}

// 1F38:017F: define fn1F38_017F
// Called from:
//      fn1F38_055E
define fn1F38_017F
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) es;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) si;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) ax;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) bx;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) cx;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) dx;
	v12 = Mem0[ds:0x0F0C:word16];
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) v12;
	fn1F38_00E8();
	if (Test(UGE,C))
	{
		D = false;
		ax = ax ^ ax;
		SZ = cond(ax);
		O = false;
		C = false;
		bx = ax;
		al = dh;
		bl = cl;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) cx;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) dx;
		fn1F38_002E();
		dx.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
		cx.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
		dl -= cl;
		dh -= ch;
		cl = dl;
		ch = ch ^ ch;
		cx = (char *) cx.u7 + 1;
		bl = dh;
		bh = bh ^ bh;
		es_di = Mem0[ds:0x0F0C:segptr32];
		si = di;
		si -= 0xA0;
		dx.u0 = 0x03D8;
		SZP = cond(Mem0[ds:0x0EE8:word16] & ~0x00);
		O = false;
		C = false;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) ds;
		ds = Mem0[ds:0x0F0E:selector];
		if (Test(NE,Z))
		{
			al.u0 = 33;
			__out<byte>(dx, al);
		}
		do
		{
			sp -= 2;
			(ss->*sp).u7 = (union Eq_234980 *) cx;
			sp -= 2;
			(ss->*sp).u7 = (union Eq_234980 *) di;
			sp -= 2;
			(ss->*sp).u7 = (union Eq_234980 *) si;
			size = cx *32 0x02;
			memcpy(di, si.u7, size);
			si.u7 = (ss->*sp).u7;
			sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
			di = (<unknown>*) (ss->*sp).u7;
			sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
			cx.u7 = (ss->*sp).u7;
			sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
			di = (<unknown>*) (di - 0xA0);
			si -= 0xA0;
			SCZO = cond(si);
			--bx;
			SZO = cond(bx);
		} while (Test(NE,Z));
		ds.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
		ah = Mem0[ds:0x0F14:byte];
		al.u0 = 0x20;
		for (; cx != 0x00; --cx)
		{
			es->*di = (<unknown>*) ax;
			di = (<unknown>*) ((char *) di + 2);
		}
		SZP = cond(Mem0[ds:0x0EE8:word16] & ~0x00);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			al.u0 = 0x29;
			__out<byte>(dx, al);
		}
	}
	Mem0[ds:0x0F0C:word16] = Mem0[ss:sp + 0x00:word16];
	sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
	dx.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
	cx.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
	bx.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
	ax.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
	si.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
	es.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_41797::*) ((char *) sp + 2);
}

// 1F38:01FA: define fn1F38_01FA
// Called from:
//      fn1F38_028F
//      fn1F38_055E
define fn1F38_01FA
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) es;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) si;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) ax;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) bx;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) cx;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) dx;
	v12 = ds->t0F0C;
	sp -= 2;
	(ss->*sp).u7 = (union Eq_234980 *) v12;
	fn1F38_00E8();
	if (Test(UGE,C))
	{
		D = false;
		ax = ax ^ ax;
		SZ = cond(ax);
		O = false;
		C = false;
		bx = ax;
		al = ch;
		bl = cl;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) cx;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) dx;
		fn1F38_002E();
		dx.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
		cx.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
		dl -= cl;
		dh -= ch;
		cl = dl;
		ch = ch ^ ch;
		cx = (char *) cx.u7 + 1;
		bl = dh;
		bh = bh ^ bh;
		bx = (char *) bx.u7 + 1;
		ah = ds->b0F14;
		al.u0 = 0x20;
		es_di = ds->t0F0C;
		dx.u0 = 0x03D8;
		SZP = cond(ds->w0EE8 & ~0x00);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			sp -= 2;
			(ss->*sp).u7 = (union Eq_234980 *) ax;
			al.u0 = 33;
			__out<byte>(dx, al);
			ax.u7 = (ss->*sp).u7;
			sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
		}
		do
		{
			sp -= 2;
			(ss->*sp).u7 = (union Eq_234980 *) cx;
			sp -= 2;
			(ss->*sp).u7 = (union Eq_234980 *) di;
			for (; cx != 0x00; --cx)
			{
				es->*di = ax;
				di = &di.u7->u1.t0002.u0;
			}
			di.u7 = (ss->*sp).u7;
			sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
			cx.u7 = (ss->*sp).u7;
			sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
			di = (char *) di.u7 + 0x00A0;
			SCZO = cond(di);
			--bx;
			SZO = cond(bx);
		} while (Test(NE,Z));
		SZP = cond(ds->w0EE8 & ~0x00);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			al.u0 = 0x29;
			__out<byte>(dx, al);
		}
	}
	ds->t0F0C.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
	dx.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
	cx.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
	bx.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
	ax.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
	si.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
	es.u7 = (ss->*sp).u7;
	sp = (union Eq_226 Eq_42071::*) ((char *) sp + 2);
}

// 1F38:0264: define fn1F38_0264
// Called from:
//      fn1F38_0279
//      fn1F38_028F
define fn1F38_0264
{
	selector ds;
	<unknown> Mem0;
	Top_3 = 0;
	ch_6 = ds->b0EEA;
	cl_7 = ds->b0EEC;
	dh_8 = ds->b0EEE;
	dl_9 = ds->b0EF0;
	dh_10 = dh_8 + ch_6;
	dl_11 = dl_9 + cl_7;
	SCZO_12 = cond(dl_11);
	C_13 = SLICE(SCZO_12, bool, 1);
	O_14 = SLICE(SCZO_12, bool, 4);
	S_15 = (bool) SCZO_12;
	Z_16 = SLICE(SCZO_12, bool, 2);
}

// 1F38:0279: define fn1F38_0279
// Called from:
//      fn1F38_0090
define fn1F38_0279
{
	selector ds;
	Top_3 = 0;
	fn1F38_0264();
	cx_20 = cx_35;
	dx_21 = dx_36;
	fn1F38_0104();
}

// 1F38:028F: define fn1F38_028F
// Called from:
//      fn1F38_094C
define fn1F38_028F
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = cx;
	sp -= 2;
	ss->*sp = dx;
	fn1F38_0264();
	fn1F38_01FA();
	dx = ss->*sp;
	++sp;
	cx = ss->*sp;
	++sp;
}

// 1F38:029A: define fn1F38_029A
// Called from:
//      fn1F38_05DB
//      fn1F38_08CB
define fn1F38_029A
{
	word16 ax;
	selector ds;
	word16 cx;
	al = (byte) ax;
	Top_3 = 0;
	D_17 = false;
	bx_19 = ds->w0EF0;
	si_20 = ds->w0EEE;
	SZP_21 = cond(ds->w0EE8);
	P_211 = SLICE(SZP_21, bool, 5);
	if (ds->w0EE8 == 0x00)
	{
		ah_56 = ds->b0F14;
		dx_58 = cx;
		es_59 = ds->ptr0F0E;
		ax_156 = SEQ(ah_56, al);
		while (true)
		{
			dx_67 = ϕ(dx_58, dx_93);
			Mem63 = ϕ(Mem16, Mem133);
			cx_64 = bx_19 - ds->w0F08;
			cx_65 = cx_64 + 0x01;
			di_66 = ds->ptr0F0C;
			if (cx_64 + 0x01 >= dx_67)
				break;
			dx_93 = dx_67 - (cx_64 + 0x01);
			while (true)
			{
				di_141 = ϕ(di_66, di_143);
				cx_95 = ϕ(cx_65, cx_144);
				if (cx_95 == 0x00)
					break;
				es_59->*di_141 = ax_156;
				di_143 = di_141 + 1;
				cx_144 = cx_95 - 0x01;
			}
			ds->w0F08 = 0x00;
			if (ds->w0F06 >= si_20)
				goto l1F38_02FF;
			v24_132 = ds->w0F06 + 0x01;
			ds->w0F06 = v24_132;
			fn1F38_003F();
		}
		cx_70 = dx_67;
		v25_71 = ds->w0F08 + dx_67;
		ds->w0F08 = v25_71;
		while (true)
		{
			di_89 = ϕ(di_66, di_91);
			Mem76 = ϕ(Mem72, Mem90);
			cx_74 = ϕ(cx_70, cx_92);
			if (cx_74 == 0x00)
				break;
			es_59->*di_89 = ax_156;
			di_91 = di_89 + 1;
			cx_92 = cx_74 - 0x01;
		}
		if (ds->w0F08 > bx_19)
		{
			ds->w0F08 = 0x00;
			if (ds->w0F06 < si_20)
			{
				v26_84 = ds->w0F06 + 0x01;
				ds->w0F06 = v26_84;
			}
		}
	}
	else
	{
		do
		{
			cx_53 = ϕ(cx, cx_55);
			Mem34 = ϕ(Mem16, Mem122);
			fn1F38_0000();
			v21_35 = ds->w0F08 + 0x01;
			ds->w0F08 = v21_35;
			if (ds->w0F08 > bx_19)
			{
				ds->w0F08 = 0x00;
				if (ds->w0F06 < si_20)
				{
					v23_44 = ds->w0F06 + 0x01;
					ds->w0F06 = v23_44;
				}
				Mem123 = ϕ(Mem40, Mem45);
				fn1F38_003F();
			}
			Mem122 = ϕ(Mem36, Mem123);
			cx_55 = cx_53 - 0x01;
			ax_195 = ax;
		} while (cx_55 != 0x00);
	}
l1F38_02FF:
	P_206 = ϕ(P_33, P_211, P_211, P_211, P_211);
	di_203 = ϕ(di_27, di_141, di_89, di_89, di_89);
	D_197 = ϕ(D_31, D_17, D_17, D_17, D_17);
	cx_196 = ϕ(cx_55, cx_95, cx_74, cx_74, cx_74);
	ax_190 = ϕ(ax_195, ax_156, ax_156, ax_156, ax_156);
	fn1F38_003F();
}

// 1F38:032B: define fn1F38_032B
// Called from:
//      fn21DC_0EC2
define fn1F38_032B
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_42603 Eq_42610::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_42603 Eq_42610::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_42603 Eq_42610::*) di;
	bp = sp;
	__syscall<byte>(0x11);
	bx = 0xB000;
	ax &= 0x30;
	SCZO = cond(ax - 0x30);
	if (Test(NE,Z))
	{
		bx = 0xB800;
		ds->w0EE6 = 0x01;
	}
	ds->w0F0E = bx;
	ds->w0F12 = bx;
	ah = 0x03;
	bh = 0x00;
	ch = bios_video_get_cursor_position_size(bh, out cl, out dh, out dl);
	ax = ax ^ ax;
	SZ = cond(ax);
	O = false;
	C = false;
	bx = ax;
	al = dh;
	bl = dl;
	ds->w0F06 = ax;
	ds->w0F08 = bx;
	fn1F38_002E();
	fn1F38_07E7();
	di = (struct Eq_42603 Eq_42610::*) (ss->*sp).ptr0000;
	sp = (struct Eq_42603 Eq_42610::*) &sp->ptr0000;
	si = (struct Eq_42603 Eq_42610::*) (ss->*sp).ptr0000;
	sp = (struct Eq_42603 Eq_42610::*) &sp->ptr0000;
	bp = (struct Eq_42603 Eq_42610::*) (ss->*sp).ptr0000;
	sp = (struct Eq_42603 Eq_42610::*) &sp->ptr0000;
}

// 1F38:036F: define fn1F38_036F
// Called from:
//      fn21DC_04BA
//      main
define fn1F38_036F
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	di = ss->*sp;
	++sp;
	si = ss->*sp;
	++sp;
	bp = ss->*sp;
	++sp;
}

// 1F38:042D: define fn1F38_042D
// Called from:
//      fn1825_4DA6
//      main
//      fn3CEE_74B8
define fn1F38_042D
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	D = false;
	cx = ss->*((word16) bp + 0x0E);
	if (cx != 0x00)
	{
		es_si = ss->*((word16) bp + 0x0A);
		do
		{
			sp -= 2;
			ss->*sp = cx;
			al = es->*si;
			si = (word16) si + 1;
			SCZO = cond(al - 0x20);
			if (Test(UGE,C))
			{
l1F38_0442:
				fn1F38_0000();
				v16 = ds->w0F08 + 0x01;
				ds->w0F08 = v16;
				cx = ds->t0EF0;
				SCZO = cond(ds->w0F08 - cx);
				if (Test(UGT,CZ))
				{
					fn1F38_0080();
					cx = ds->t0EEE;
					SCZO = cond(ds->w0F06 - cx);
					if (Test(ULT,C))
					{
						v19 = ds->w0F06 + 0x01;
						ds->w0F06 = v19;
						SZO = cond(v19);
						fn1F38_003F();
					}
					else
						fn1F38_0090();
				}
				goto l1F38_0467;
			}
			SCZO = cond(al - 0x08);
			if (Test(NE,Z))
			{
				SCZO = cond(al - 0x0D);
				if (Test(NE,Z))
				{
					SCZO = cond(al - 0x0A);
					if (Test(NE,Z))
					{
						SCZO = cond(al - 0x07);
						if (Test(NE,Z))
							goto l1F38_0442;
						fn1F38_00A9();
					}
					else
						fn1F38_0090();
				}
				else
					fn1F38_0080();
			}
			else
				fn1F38_00B6();
l1F38_0467:
			cx = ss->*sp;
			sp = (word16) sp + 2;
			--cx;
		} while (cx != 0x00);
	}
	fn1F38_0069();
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 1F38:049F: define fn1F38_049F
// Called from:
//      fn1825_02F0
//      fn1825_037E
//      fn1825_05F2
//      fn1825_06E0
//      fn1825_0C7E
//      fn1825_0E72
//      fn1825_139A
//      fn1825_18A6
//      fn1825_1D40
//      fn1825_2020
//      fn1825_2696
//      fn1825_26D6
//      fn1825_2880
//      fn1825_2C52
//      fn1825_3436
//      fn1825_3766
//      fn1825_39DE
//      fn1825_3BCE
//      fn1825_3EE6
//      fn1825_45B2
//      fn1825_4658
//      fn1825_4770
//      fn1825_4814
//      fn1825_4A02
//      fn1825_4BFA
//      fn1825_4DA6
//      fn1825_5154
//      fn1825_54D4
//      fn1825_5730
//      fn1825_5850
//      fn1825_59CC
//      fn1825_5BD8
//      fn1825_5E5C
//      fn1825_63F8
//      fn1825_648A
//      fn1825_675E
//      fn1825_6EA4
//      fn20B2_000E
//      fn20B2_005C
//      fn20B2_0140
//      fn20B2_1014
//      fn20B2_107C
//      fn20B2_10AC
//      fn3CEE_47CC
//      fn3CEE_4882
//      fn3CEE_6DBC
//      fn3CEE_6F82
//      fn3CEE_8634
define fn1F38_049F
{
	selector ds;
	word16 wArg08;
	segptr32 ptrArg04;
	byte al;
	byte bl;
	selector es;
	bool P;
	Top_3 = 0;
	D_15 = false;
	cx_16 = wArg08;
	if (wArg08 != 0x00)
	{
		es_85 = SLICE(ptrArg04, selector, 16);
		si_87 = (word16) ptrArg04;
		bx_19 = ds->w0EF0;
		bl_112 = (byte) bx_19;
		dx_20 = ds->w0EEE;
		do
		{
			cx_59 = ϕ(cx_16, cx_60);
			Mem23 = ϕ(Mem13, Mem78);
			si_22 = ϕ(si_87, si_25);
			al_24 = es_85->*si_22;
			si_25 = si_22 + 1;
			fn1F38_0000();
			if (ds->w0F08 < bx_19)
			{
				v18_55 = ds->w0F08 + 0x01;
				ds->w0F08 = v18_55;
			}
			else
			{
				v20_37 = ds->w0F0C - 0x01;
				ds->w0F0C = v20_37;
				v21_39 = ds->w0F0C - 0x01;
				ds->w0F0C = v21_39;
				if (ds->w0F06 >= dx_20)
					break;
				fn1F38_0080();
				fn1F38_0090();
				al_108 = (byte) ax_49;
			}
			al_107 = ϕ(al_24, al_108);
			Mem78 = ϕ(Mem56, Mem40);
			cx_60 = cx_59 - 0x01;
		} while (cx_60 != 0x00);
	}
	P_120 = ϕ(P, P_33, P_33);
	es_118 = ϕ(es, es_85, es_85);
	D_115 = ϕ(D_15, D_31, D_31);
	cx_114 = ϕ(cx_16, cx_60, cx_59);
	bl_110 = ϕ(bl, bl_112, bl_112);
	al_105 = ϕ(al, al_107, al_24);
	fn1F38_0069();
	ax_109 = SEQ(ah_63, al_105);
	bx_113 = SEQ(bh_64, bl_110);
	dx_117 = dx_126;
}

// 1F38:04E7: define fn1F38_04E7
// Called from:
//      fn1825_000A
//      fn1825_017A
//      fn1825_02F0
//      fn1825_037E
//      fn1825_05F2
//      fn1825_06E0
//      fn1825_0C7E
//      fn1825_0D5E
//      fn1825_0E72
//      fn1825_139A
//      fn1825_18A6
//      fn1825_1D40
//      fn1825_2020
//      fn1825_22BC
//      fn1825_25AE
//      fn1825_26D6
//      fn1825_2880
//      fn1825_2B6E
//      fn1825_2C52
//      fn1825_3436
//      fn1825_3766
//      fn1825_39DE
//      fn1825_3BCE
//      fn1825_3EE6
//      fn1825_45B2
//      fn1825_4658
//      fn1825_4770
//      fn1825_4814
//      fn1825_4A02
//      fn1825_4B48
//      fn1825_4BFA
//      fn1825_4DA6
//      fn1825_5154
//      fn1825_54D4
//      fn1825_5730
//      fn1825_5850
//      fn1825_59CC
//      fn1825_5B30
//      fn1825_5BD8
//      fn1825_5DB0
//      fn1825_5E5C
//      fn1825_6078
//      fn1825_63F8
//      fn1825_648A
//      fn1825_675E
//      fn1825_6EA4
//      fn1F38_05A1
//      fn20B2_005C
//      fn20B2_0118
//      fn20B2_1014
//      fn3CEE_47CC
//      fn3CEE_4882
//      fn3CEE_6DBC
//      fn3CEE_6F82
//      fn3CEE_8634
//      fn3CEE_8A23
define fn1F38_04E7
{
	selector ds;
	word16 wArg04;
	word16 wArg06;
	word16 bx;
	word16 cx;
	word16 dx;
	Top_3 = 0;
	ax_15 = wArg04;
	SCZO_17 = cond(wArg04 - ds->w0EEE);
	C_68 = SLICE(SCZO_17, bool, 1);
	O_76 = SLICE(SCZO_17, bool, 4);
	S_79 = (bool) SCZO_17;
	Z_83 = SLICE(SCZO_17, bool, 2);
	if (wArg04 <= ds->w0EEE)
	{
		bx_19 = wArg06;
		SCZO_20 = cond(wArg06 - ds->w0EF0);
		C_69 = SLICE(SCZO_20, bool, 1);
		O_77 = SLICE(SCZO_20, bool, 4);
		S_80 = (bool) SCZO_20;
		Z_84 = SLICE(SCZO_20, bool, 2);
		if (wArg06 <= ds->w0EF0)
		{
			ds->w0F06 = wArg04;
			ds->w0F08 = wArg06;
			ax_24 = wArg04 + ds->w0EEA;
			bx_25 = wArg06 + ds->w0EEC;
			fn1F38_002E();
			al_61 = (byte) ax_27;
			bl_65 = (byte) bx_28;
			fn1F38_0069();
			ax_62 = SEQ(ah_35, al_61);
			bx_66 = SEQ(bh_36, bl_65);
			dx_74 = dx_85;
		}
	}
	Z_82 = ϕ(Z_83, Z_84, Z_41);
	S_78 = ϕ(S_79, S_80, S_39);
	O_75 = ϕ(O_76, O_77, O_42);
	dx_72 = ϕ(dx, dx, dx_74);
	cx_70 = ϕ(cx, cx, cx_29);
	C_67 = ϕ(C_68, C_69, C_40);
	bx_63 = ϕ(bx, bx_19, bx_66);
	ax_60 = ϕ(ax_15, ax_15, ax_62);
}

// 1F38:0517: define fn1F38_0517
// Called from:
//      fn1825_000A
//      fn1825_22BC
//      fn1825_2C52
//      fn1825_3EE6
//      fn1825_4658
//      fn1825_4814
//      fn1825_4BFA
//      fn1825_5E5C
//      fn1825_6078
//      fn1825_63F8
//      fn1825_648A
//      fn1825_675E
//      fn1825_6EA4
//      fn20B2_005C
define fn1F38_0517
{
	selector ds;
	Top_3 = 0;
	ah_15 = ds->b0F06;
	al_16 = ds->b0F08;
}

// 1F38:0527: define fn1F38_0527
// Called from:
//      fn1825_000A
//      fn1825_037E
//      fn1825_06E0
//      fn1825_0E72
//      fn1825_18A6
//      fn1825_2450
//      fn1825_2880
//      fn1825_2A26
//      fn1825_3436
//      fn1825_5154
//      fn1825_5BD8
//      fn1825_648A
//      fn3CEE_661D
//      fn3CEE_6620
define fn1F38_0527
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_43138 Eq_43145::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_43138 Eq_43145::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_43138 Eq_43145::*) di;
	bp = sp;
	ax = (ss->*bp).w000A;
	ds->w0F0A = ax;
	cx = 0x2000;
	SZP = cond((ss->*bp).w000A & ~0x00);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		cx = 2828;
		SZP = cond(ds->w0EE6 & ~0x00);
		O = false;
		C = false;
		if (Test(NE,Z))
			cx = 0x0607;
	}
	ah = 0x01;
	bios_video_set_text_mode_cursor_shape(ch, cl);
	di = (struct Eq_43138 Eq_43145::*) (ss->*sp).ptr0000;
	sp = (struct Eq_43138 Eq_43145::*) &sp->ptr0000;
	si = (struct Eq_43138 Eq_43145::*) (ss->*sp).ptr0000;
	sp = (struct Eq_43138 Eq_43145::*) &sp->ptr0000;
	bp = (struct Eq_43138 Eq_43145::*) (ss->*sp).ptr0000;
	sp = (struct Eq_43138 Eq_43145::*) &sp->ptr0000;
}

// 1F38:0552: define fn1F38_0552
// Called from:
//      fn3CEE_661D
//      fn3CEE_6620
define fn1F38_0552
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	ax = ds->w0F0A;
	di = ss->*sp;
	++sp;
	si = ss->*sp;
	++sp;
	bp = ss->*sp;
	++sp;
}

// 1F38:055E: define fn1F38_055E
// Called from:
//      fn3CEE_3E50
//      fn3CEE_3E8B
//      fn3CEE_3F4C
//      fn3CEE_70B0
define fn1F38_055E
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_43276 Eq_43283::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_43276 Eq_43283::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_43276 Eq_43283::*) di;
	bp = sp;
	ch = (ss->*bp).b000A;
	cl = (ss->*bp).b000C;
	dh = (ss->*bp).b000E;
	dl = (ss->*bp).b0010;
	ch += ds->b0EEA;
	dh += ds->b0EEA;
	cl += ds->b0EEC;
	dl += ds->b0EEC;
	ax = (ss->*bp).w0012;
	SZP = cond(ax & ax);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		if (Test(SG,S))
		{
			C = ax != 0x00;
			ax = -ax;
			SZO = cond(ax);
			do
			{
				fn1F38_017F();
				--ax;
				SZO = cond(ax);
			} while (Test(NE,Z));
		}
		else
		{
			do
			{
				fn1F38_0104();
				--ax;
				SZO = cond(ax);
			} while (Test(NE,Z));
		}
	}
	else
		fn1F38_01FA();
	di = (struct Eq_43276 Eq_43283::*) (ss->*sp).ptr0000;
	sp = (struct Eq_43276 Eq_43283::*) &sp->ptr0000;
	si = (struct Eq_43276 Eq_43283::*) (ss->*sp).ptr0000;
	sp = (struct Eq_43276 Eq_43283::*) &sp->ptr0000;
	bp = (struct Eq_43276 Eq_43283::*) (ss->*sp).ptr0000;
	sp = (struct Eq_43276 Eq_43283::*) &sp->ptr0000;
}

// 1F38:05A1: define fn1F38_05A1
// Called from:
//      fn1F38_05DB
//      fn1F38_08CB
define fn1F38_05A1
{
	mp16 fp;
	word16 dx;
	dh_24 = SLICE(dx, byte, 8);
	dl_31 = (byte) dx;
	selector ds;
	Top_3 = 0;
	dx_32 = (uint16) dl_31;
	ax_36 = (uint16) dh_24;
	fn1F38_04E7();
	SCZO_48 = cond(fp - 0x0C);
	C_69 = SLICE(SCZO_48, bool, 1);
	O_70 = SLICE(SCZO_48, bool, 4);
	S_71 = (bool) SCZO_48;
	Z_72 = SLICE(SCZO_48, bool, 2);
}

// 1F38:05BE: define fn1F38_05BE
// Called from:
//      fn1F38_05DB
define fn1F38_05BE
{
	sp = fp;
	Top = 0;
	al = (es->*si).b0000;
	si = &si->b0000 + 1;
	al |= al;
	SZ = cond(al);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
		--si;
		bl |= bl;
		SZ = cond(bl);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			SCZO = cond(bh - 0x08);
			if (Test(ULT,C))
				al = (es->*si).bFFFFFFFF;
		}
		else
			al = 0x20;
	}
	++bh;
	SZO = cond(bh);
}

// 1F38:05DB: define fn1F38_05DB
// Called from:
//      fn1825_05F2
//      fn1825_0E72
//      fn1825_18A6
//      fn1825_2020
//      fn1825_2450
//      fn1825_25AE
//      fn1825_26D6
//      fn1825_2880
//      fn1825_2A26
//      fn1825_2B6E
//      fn1825_3436
//      fn1825_39DE
//      fn1825_3CDC
//      fn1825_3EE6
//      fn1825_45B2
//      fn1825_4770
//      fn1825_4A02
//      fn1825_4DA6
//      fn1825_5154
//      fn1825_5730
//      fn1825_5850
//      fn1825_59CC
//      fn1825_5BD8
//      fn1825_6EA4
define fn1F38_05DB
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	D = false;
	ax = ss->*((word16) bp + 0x0E);
	SCZO = cond(ax - ds->w0EEE);
	if (Test(ULE,CZ))
	{
		ax = ss->*((word16) bp + 16);
		SCZO = cond(ax - ds->w0EF0);
		if (Test(UGT,CZ))
			goto l1F38_0603;
		ax = ss->*((word16) bp + 0x0A);
		SCZO = cond(ax - ss->*((word16) bp + 0x0E));
		if (Test(ULE,CZ))
		{
			ax = ss->*((word16) bp + 0x0C);
			SCZO = cond(ax - ss->*((word16) bp + 16));
			if (Test(UGT,CZ))
				goto l1F38_0603;
			es_si = ss->*((word16) bp + 18);
			bx = bx ^ bx;
			SZ = cond(bx);
			O = false;
			C = false;
			while (true)
			{
				SCZO = cond(Mem0[es:bx + si:byte] - 0x00);
				if (Test(EQ,Z))
					break;
				++bl;
				SZO = cond(bl);
			}
			ax = ss->*((word16) bp + 0x0A);
			ds->t0F06 = ax;
			ax = ss->*((word16) bp + 0x0C);
			ds->t0F08 = ax;
			fn1F38_003F();
			cx = ss->*((word16) bp + 16);
			cx -= ds->t0F08;
			SCZO = cond(cx);
			--cx;
			SZO = cond(cx);
			fn1F38_05BE();
			sp -= 2;
			ss->*sp = ax;
			ax = ss->*((word16) bp + 0x0A);
			SCZO = cond(ax - ss->*((word16) bp + 0x0E));
			ax = ss->*sp;
			sp = (word16) sp + 2;
			if (Test(EQ,Z))
			{
				cx = (word16) cx + 1;
				cx = (word16) cx + 1;
				SZO = cond(cx);
			}
			else
			{
				sp -= 2;
				ss->*sp = ax;
				ax = ss->*((word16) bp + 16);
				SCZO = cond(ax - ss->*((word16) bp + 0x0C));
				ax = ss->*sp;
				sp = (word16) sp + 2;
				if (Test(NE,Z))
				{
					fn1F38_0000();
					v23 = (word16) ds->t0F08 + 1;
					ds->t0F08 = v23;
					SZO = cond(v23);
				}
			}
			fn1F38_05BE();
			cx |= cx;
			SZ = cond(cx);
			O = false;
			C = false;
			if (Test(GT,SZO))
				fn1F38_029A();
			fn1F38_05BE();
			cx |= cx;
			SZ = cond(cx);
			O = false;
			C = false;
			cx = ss->*((word16) bp + 0x0E);
			if (Test(GE,SO))
			{
				SCZO = cond(cx - ss->*((word16) bp + 0x0A));
				if (Test(EQ,Z))
					goto l1F38_074A;
				fn1F38_0000();
				v27 = (word16) ds->t0F08 + 1;
				ds->t0F08 = v27;
				SZO = cond(v27);
			}
			cx -= ss->*((word16) bp + 0x0A);
			SCZO = cond(cx);
			--cx;
			SZO = cond(cx);
			fn1F38_05BE();
			sp -= 2;
			ss->*sp = ax;
			ax = ss->*((word16) bp + 16);
			SCZO = cond(ax - ss->*((word16) bp + 0x0C));
			ax = ss->*sp;
			sp = (word16) sp + 2;
			if (Test(EQ,Z))
			{
				cx = (word16) cx + 1;
				SZO = cond(cx);
				fn1F38_0000();
				v28 = (word16) ds->t0F08 + 1;
				ds->t0F08 = v28;
				SZO = cond(v28);
			}
			dx = 0x9E;
			for (; cx != 0x00; --cx)
			{
				v30 = (word16) ds->t0F0C + dx;
				ds->t0F0C = v30;
				SCZO = cond(v30);
				v31 = (word16) ds->t0F06 + 1;
				ds->t0F06 = v31;
				SZO = cond(v31);
				fn1F38_0000();
			}
			v32 = (word16) ds->t0F0C + dx;
			ds->t0F0C = v32;
			SCZO = cond(v32);
			v33 = (word16) ds->t0F06 + 1;
			ds->t0F06 = v33;
			SZO = cond(v33);
			fn1F38_05BE();
			sp -= 2;
			ss->*sp = ax;
			ax = ss->*((word16) bp + 16);
			SCZO = cond(ax - ss->*((word16) bp + 0x0C));
			ax = ss->*sp;
			sp = (word16) sp + 2;
			if (Test(UGT,CZ))
			{
				fn1F38_0000();
				fn1F38_05BE();
				cx = ss->*((word16) bp + 16);
				cx -= ss->*((word16) bp + 0x0C);
				v34 = ds->t0F0C - cx;
				ds->t0F0C = v34;
				v35 = ds->t0F0C - cx;
				ds->t0F0C = v35;
				v36 = ds->t0F08 - cx;
				ds->t0F08 = v36;
				SCZO = cond(v36);
				v37 = ds->t0F0C;
				sp -= 2;
				ss->*sp = v37;
				v38 = ds->t0F08;
				sp -= 2;
				ss->*sp = v38;
				--cx;
				SZO = cond(cx);
				if (cx != 0x00)
					fn1F38_029A();
				fn1F38_05BE();
				ds->t0F08 = ss->*sp;
				sp = (word16) sp + 2;
				ds->t0F0C = ss->*sp;
				sp = (word16) sp + 2;
				v39 = ds->t0F0C - 0x01;
				ds->t0F0C = v39;
				v40 = ds->t0F0C - 0x01;
				ds->t0F0C = v40;
				SZO = cond(v40);
				fn1F38_0000();
				fn1F38_05BE();
				cx = ss->*((word16) bp + 0x0E);
				cx -= ss->*((word16) bp + 0x0A);
				SCZO = cond(cx);
				--cx;
				SZO = cond(cx);
				if (cx != 0x00)
				{
					dx = 0xA2;
					do
					{
						v41 = ds->t0F0C - dx;
						ds->t0F0C = v41;
						SCZO = cond(v41);
						v42 = ds->t0F06 - 0x01;
						ds->t0F06 = v42;
						SZO = cond(v42);
						fn1F38_0000();
						--cx;
					} while (cx != 0x00);
				}
				fn1F38_05BE();
				al |= al;
				SZ = cond(al);
				O = false;
				C = false;
				if (Test(NE,Z))
				{
					bx = ss->*((word16) bp + 0x0E);
					bx -= ss->*((word16) bp + 0x0A);
					--bx;
					bx |= bx;
					SZ = cond(bx);
					O = false;
					C = false;
					if (Test(NE,Z))
					{
						cx = ss->*((word16) bp + 16);
						cx -= ss->*((word16) bp + 0x0C);
						SCZO = cond(cx);
						--cx;
						SZO = cond(cx);
						if (cx != 0x00)
						{
							dx = 0xA0;
							do
							{
								sp -= 2;
								ss->*sp = cx;
								v44 = ds->t0F0C;
								sp -= 2;
								ss->*sp = v44;
								v45 = ds->t0F08;
								sp -= 2;
								ss->*sp = v45;
								fn1F38_029A();
								ds->t0F08 = ss->*sp;
								sp = (word16) sp + 2;
								ds->t0F0C = ss->*sp;
								sp = (word16) sp + 2;
								v46 = (word16) ds->t0F0C + dx;
								ds->t0F0C = v46;
								SCZO = cond(v46);
								v47 = (word16) ds->t0F06 + 1;
								ds->t0F06 = v47;
								cx = ss->*sp;
								sp = (word16) sp + 2;
								--bx;
								SZO = cond(bx);
							} while (Test(NE,Z));
						}
					}
				}
			}
l1F38_074A:
			dh = ss->*((word16) bp + 0x0A);
			dh.u1 = (byte) dh.u1 + 1;
			ds->t0F06 = dh;
			dl = ss->*((word16) bp + 0x0C);
			dl.u1 = (byte) dl.u1 + 1;
			SZO = cond(dl);
			ds->t0F08 = dl;
			fn1F38_05A1();
l1F38_075F:
			di = ss->*sp;
			sp = (word16) sp + 2;
			si = ss->*sp;
			sp = (word16) sp + 2;
			bp = ss->*sp;
			sp = (word16) sp + 2;
			return;
		}
	}
l1F38_0603:
	goto l1F38_075F;
}

// 1F38:0763: define fn1F38_0763
// Called from:
//      fn1F38_07E7
//      fn1F38_07FA
define fn1F38_0763
{
	sp = fp;
	Top = 0;
	dl = dl ^ dl;
	cx = ax;
	cx |= bx;
	SZP = cond(cx & 0x8000);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
		SZP = cond(cx & 0x10);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			dl |= 0x80;
			SZ = cond(dl);
			O = false;
			C = false;
		}
		SZP = cond(cx & 0x08);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			dl |= 0x08;
			SZ = cond(dl);
			O = false;
			C = false;
		}
		SZP = cond(ds->w0EE6 & ~0x00);
		O = false;
		C = false;
		if (Test(EQ,Z))
		{
			SZP = cond(cx & 0x20);
			O = false;
			C = false;
			if (Test(NE,Z))
			{
				dl |= 0x01;
				SZ = cond(dl);
				O = false;
				C = false;
			}
		}
		SZP = cond(ax & 0x80);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			ax |= 0x07;
			SZ = cond(ax);
			O = false;
			C = false;
		}
		SZP = cond(bx & 0x80);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			bx |= 0x07;
			SZ = cond(bx);
			O = false;
			C = false;
		}
		SZP = cond(cx & 0x0100);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			SZP = cond(bx & 0x07);
			O = false;
			C = false;
			if (Test(EQ,Z))
			{
				bx |= 0x07;
				SZ = cond(bx);
				O = false;
				C = false;
			}
		}
		SZP = cond(cx & 0x0200);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			ax = ax ^ ax;
			SZ = cond(ax);
			O = false;
			C = false;
			bx = ax;
			dl = al;
		}
	}
	cl = 0x04;
	bl <<= cl;
	dl |= bl;
	al &= 0x0F;
	dl |= al;
	ds->t0F14 = dl;
	SZP = cond(ds->w0EE6 & ~0x00);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		ax = ds->w0EFE;
		SZP = cond(ax & 0x80);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			ax |= 0x07;
			SZ = cond(ax);
			O = false;
			C = false;
		}
		ax &= 0x0F;
		SZ = cond(ax);
		O = false;
		C = false;
		dx.u0 = 0x03D9;
		__out<byte>(dx, al);
	}
}

// 1F38:07E7: define fn1F38_07E7
// Called from:
//      fn1825_037E
//      fn1825_06E0
//      fn1825_0E72
//      fn1825_18A6
//      fn1825_2880
//      fn1825_3436
//      fn1825_3766
//      fn1825_3BCE
//      fn1825_5154
//      fn1825_54D4
//      fn1825_5BD8
//      fn1825_7078
//      fn1825_7106
//      fn1F38_032B
define fn1F38_07E7
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44244 Eq_44251::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44244 Eq_44251::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44244 Eq_44251::*) di;
	bp = sp;
	ax = ds->w0EF2;
	bx = ds->w0EF4;
	fn1F38_0763();
	di = (struct Eq_44244 Eq_44251::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44244 Eq_44251::*) &sp->ptr0000;
	si = (struct Eq_44244 Eq_44251::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44244 Eq_44251::*) &sp->ptr0000;
	bp = (struct Eq_44244 Eq_44251::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44244 Eq_44251::*) &sp->ptr0000;
}

// 1F38:07FA: define fn1F38_07FA
// Called from:
//      fn1825_037E
//      fn1825_06E0
//      fn1825_0E72
//      fn1825_18A6
//      fn1825_2880
//      fn1825_3436
//      fn1825_3766
//      fn1825_3BCE
//      fn1825_5154
//      fn1825_54D4
//      fn1825_5BD8
define fn1F38_07FA
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44299 Eq_44306::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44299 Eq_44306::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44299 Eq_44306::*) di;
	bp = sp;
	ax = ds->w0EF6;
	bx = ds->w0EF8;
	fn1F38_0763();
	di = (struct Eq_44299 Eq_44306::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44299 Eq_44306::*) &sp->ptr0000;
	si = (struct Eq_44299 Eq_44306::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44299 Eq_44306::*) &sp->ptr0000;
	bp = (struct Eq_44299 Eq_44306::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44299 Eq_44306::*) &sp->ptr0000;
}

// 1F38:08CB: define fn1F38_08CB
// Called from:
//      fn20B2_005C
//      fn20B2_0118
//      fn3CEE_8634
define fn1F38_08CB
{
	selector ds;
	byte ah;
	Top_3 = 0;
	v10_19 = ds->w0F0C;
	v11_22 = ds->t0F08;
	v12_25 = ds->t0F06;
	cx_28 = ds->w0EF0;
	cx_29 = cx_28 - ds->t0F08;
	ax_35 = SEQ(ah, 0x20);
	fn1F38_029A();
	ds->t0F06 = v12_25;
	ds->t0F08 = v11_22;
	ds->w0F0C = v10_19;
	dl_51 = ds->t0F08;
	dh_52 = ds->t0F06;
	dx_53 = SEQ(dh_52, dl_51);
	fn1F38_05A1();
}

// 1F38:094C: define fn1F38_094C
// Called from:
//      fn1825_017A
//      fn1825_0CD2
define fn1F38_094C
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44409 Eq_44416::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44409 Eq_44416::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44409 Eq_44416::*) di;
	bp = sp;
	fn1F38_028F();
	ds->w0F06 = 0x00;
	ds->w0F08 = 0x00;
	fn1F38_003F();
	fn1F38_0069();
	di = (struct Eq_44409 Eq_44416::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44409 Eq_44416::*) &sp->ptr0000;
	si = (struct Eq_44409 Eq_44416::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44409 Eq_44416::*) &sp->ptr0000;
	bp = (struct Eq_44409 Eq_44416::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44409 Eq_44416::*) &sp->ptr0000;
}

// 1F38:096A: define fn1F38_096A
// Called from:
//      fn1F38_0A29
//      fn1F38_0A6F
define fn1F38_096A
{
	sp = fp;
	Top = 0;
	fn1F38_00E8();
	if (Test(UGE,C))
	{
		v6 = Mem0[ds:0x0F0C:word16];
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) v6;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) ds;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) cx;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) dx;
		ax = ax ^ ax;
		SZ = cond(ax);
		O = false;
		C = false;
		bx = ax;
		al = ch;
		bl = cl;
		fn1F38_002E();
		ax.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_44480::*) ((char *) sp + 2);
		cx.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_44480::*) ((char *) sp + 2);
		ah -= ch;
		ah = (byte) ah + 1;
		al -= cl;
		al = (byte) al + 1;
		cl = al;
		ch = ch ^ ch;
		al = ah;
		ah = ah ^ ah;
		dx.u0 = 0x03D8;
		SZP = cond(Mem0[ds:0x0EE8:word16] & ~0x00);
		O = false;
		C = false;
		ds_bx = Mem0[ds:0x0F0C:segptr32];
		D = false;
		if (Test(NE,Z))
		{
			sp -= 2;
			(ss->*sp).u7 = (union Eq_234980 *) ax;
			al.u0 = 33;
			__out<byte>(dx, al);
			ax.u7 = (ss->*sp).u7;
			sp = (union Eq_226 Eq_44480::*) ((char *) sp + 2);
		}
		do
		{
			si = bx;
			bx = (word16) bx + 0x00A0;
			SCZO = cond(bx);
			sp -= 2;
			(ss->*sp).u7 = (union Eq_234980 *) cx;
			size = cx *32 0x02;
			memcpy(di, si, size);
			si = (<unknown>*) ((char *) si + (word16) size);
			di = (<unknown>*) ((char *) di + (word16) size);
			cx.u7 = (ss->*sp).u7;
			sp = (union Eq_226 Eq_44480::*) ((char *) sp + 2);
			--ax;
			SZO = cond(ax);
		} while (Test(NE,Z));
		ds.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_44480::*) ((char *) sp + 2);
		Mem0[ds:0x0F0C:word16] = Mem0[ss:sp + 0x00:word16];
		sp = (union Eq_226 Eq_44480::*) ((char *) sp + 2);
		SZP = cond(Mem0[ds:0x0EE8:word16] & ~0x00);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			al.u0 = 0x29;
			__out<byte>(dx, al);
		}
	}
}

// 1F38:09C6: define fn1F38_09C6
// Called from:
//      fn1F38_0A4C
//      fn1F38_0A9A
define fn1F38_09C6
{
	sp = fp;
	Top = 0;
	fn1F38_00E8();
	if (Test(UGE,C))
	{
		v6 = Mem0[ds:0x0F0C:word16];
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) v6;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) ds;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) cx;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) dx;
		ax = ax ^ ax;
		SZ = cond(ax);
		O = false;
		C = false;
		bx = ax;
		al = ch;
		bl = cl;
		fn1F38_002E();
		ax.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_44652::*) ((char *) sp + 2);
		cx.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_44652::*) ((char *) sp + 2);
		ah -= ch;
		ah = (byte) ah + 1;
		al -= cl;
		al = (byte) al + 1;
		cl = al;
		ch = ch ^ ch;
		al = ah;
		ah = ah ^ ah;
		dx.u0 = 0x03D8;
		SZP = cond(Mem0[ds:0x0EE8:word16] & ~0x00);
		O = false;
		C = false;
		sp -= 2;
		(ss->*sp).u7 = (union Eq_234980 *) es;
		es_bx = Mem0[ds:0x0F0C:segptr32];
		ds.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_44652::*) ((char *) sp + 2);
		si = di;
		D = false;
		if (Test(NE,Z))
		{
			sp -= 2;
			(ss->*sp).u7 = (union Eq_234980 *) ax;
			al.u0 = 33;
			__out<byte>(dx, al);
			ax.u7 = (ss->*sp).u7;
			sp = (union Eq_226 Eq_44652::*) ((char *) sp + 2);
		}
		do
		{
			di = bx;
			bx = (word16) bx + 0x00A0;
			SCZO = cond(bx);
			sp -= 2;
			(ss->*sp).u7 = (union Eq_234980 *) cx;
			size = cx *32 0x02;
			memcpy(di, si, size);
			si = (<unknown>*) ((char *) si + (word16) size);
			di = (<unknown>*) ((char *) di + (word16) size);
			cx.u7 = (ss->*sp).u7;
			sp = (union Eq_226 Eq_44652::*) ((char *) sp + 2);
			--ax;
			SZO = cond(ax);
		} while (Test(NE,Z));
		ds.u7 = (ss->*sp).u7;
		sp = (union Eq_226 Eq_44652::*) ((char *) sp + 2);
		Mem0[ds:0x0F0C:word16] = Mem0[ss:sp + 0x00:word16];
		sp = (union Eq_226 Eq_44652::*) ((char *) sp + 2);
		SZP = cond(Mem0[ds:0x0EE8:word16] & ~0x00);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			al.u0 = 0x29;
			__out<byte>(dx, al);
		}
	}
}

// 1F38:0A29: define fn1F38_0A29
// Called from:
//      fn1825_000A
define fn1F38_0A29
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44822 Eq_44829::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44822 Eq_44829::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44822 Eq_44829::*) di;
	bp = sp;
	ch = ds->b0EEA;
	cl = ds->b0EEC;
	dh = ds->b0EEE;
	dl = ds->b0EF0;
	dh += ch;
	dl += cl;
	SCZO = cond(dl);
	es_di.u1 = (ss->*bp).t000A.u1;
	fn1F38_096A();
	di = (struct Eq_44822 Eq_44829::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44822 Eq_44829::*) &sp->ptr0000;
	si = (struct Eq_44822 Eq_44829::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44822 Eq_44829::*) &sp->ptr0000;
	bp = (struct Eq_44822 Eq_44829::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44822 Eq_44829::*) &sp->ptr0000;
}

// 1F38:0A4C: define fn1F38_0A4C
// Called from:
//      fn1825_000A
//      fn1825_017A
//      fn1825_0CD2
//      fn1825_0D5E
define fn1F38_0A4C
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44894 Eq_44901::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44894 Eq_44901::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44894 Eq_44901::*) di;
	bp = sp;
	ch = ds->b0EEA;
	cl = ds->b0EEC;
	dh = ds->b0EEE;
	dl = ds->b0EF0;
	dh += ch;
	dl += cl;
	SCZO = cond(dl);
	es_di.u1 = (ss->*bp).t000A.u1;
	fn1F38_09C6();
	di = (struct Eq_44894 Eq_44901::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44894 Eq_44901::*) &sp->ptr0000;
	si = (struct Eq_44894 Eq_44901::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44894 Eq_44901::*) &sp->ptr0000;
	bp = (struct Eq_44894 Eq_44901::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44894 Eq_44901::*) &sp->ptr0000;
}

// 1F38:0A6F: define fn1F38_0A6F
// Called from:
//      fn1825_4CFE
define fn1F38_0A6F
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44966 Eq_44973::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44966 Eq_44973::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_44966 Eq_44973::*) di;
	bp = sp;
	ch = (ss->*bp).b000A;
	cl = (ss->*bp).b000C;
	dh = (ss->*bp).b000E;
	dl = (ss->*bp).b0010;
	ch += ds->b0EEA;
	cl += ds->b0EEC;
	dh += ds->b0EEA;
	dl += ds->b0EEC;
	SCZO = cond(dl);
	es_di.u1 = (ss->*bp).t0012.u1;
	fn1F38_096A();
	di = (struct Eq_44966 Eq_44973::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44966 Eq_44973::*) &sp->ptr0000;
	si = (struct Eq_44966 Eq_44973::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44966 Eq_44973::*) &sp->ptr0000;
	bp = (struct Eq_44966 Eq_44973::*) (ss->*sp).ptr0000;
	sp = (struct Eq_44966 Eq_44973::*) &sp->ptr0000;
}

// 1F38:0A9A: define fn1F38_0A9A
// Called from:
//      fn1825_4D78
define fn1F38_0A9A
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_45055 Eq_45062::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_45055 Eq_45062::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_45055 Eq_45062::*) di;
	bp = sp;
	ch = (ss->*bp).b000A;
	cl = (ss->*bp).b000C;
	dh = (ss->*bp).b000E;
	dl = (ss->*bp).b0010;
	ch += ds->b0EEA;
	cl += ds->b0EEC;
	dh += ds->b0EEA;
	dl += ds->b0EEC;
	SCZO = cond(dl);
	es_di.u1 = (ss->*bp).t0012.u1;
	fn1F38_09C6();
	di = (struct Eq_45055 Eq_45062::*) (ss->*sp).ptr0000;
	sp = (struct Eq_45055 Eq_45062::*) &sp->ptr0000;
	si = (struct Eq_45055 Eq_45062::*) (ss->*sp).ptr0000;
	sp = (struct Eq_45055 Eq_45062::*) &sp->ptr0000;
	bp = (struct Eq_45055 Eq_45062::*) (ss->*sp).ptr0000;
	sp = (struct Eq_45055 Eq_45062::*) &sp->ptr0000;
}

// 1F38:0AC5: define fn1F38_0AC5
// Called from:
//      fn1F38_0B2D
define fn1F38_0AC5
{
	word16 ax;
	selector ds;
	word16 si;
	<unknown> Mem0;
	Top_3 = 0;
	D_4 = false;
	cx_6 = ax;
	dx_7 = ax;
l1F38_0ACA:
	while (true)
	{
		dx_73 = ϕ(dx_7, dx_17, dx_73);
		si_9 = ϕ(si, si_16, si_65);
		al_11.u1 = (ds->*si_9).u1;
		si_12 = (struct Eq_45153 Eq_45159::*) ((char *) si_9 + 1);
		if (al_11 != 0x01)
			break;
		ax_15.u0 = (ds->*si_12).t0000.u0;
		si_16 = (union Eq_45146 Eq_45159::*) &si_12->t0002.u0;
		dx_17 = ax_15;
	}
	if (al_11 != 0x02)
	{
		if (al_11 != 0x03)
		{
			if (al_11 != 0x04)
			{
				SCZO_53 = cond(al_11 - 0x05);
				Z_54 = SLICE(SCZO_53, bool, 2);
				C_88 = SLICE(SCZO_53, bool, 1);
				O_100 = SLICE(SCZO_53, bool, 4);
				S_106 = (bool) SCZO_53;
				if (al_11 != 0x05)
				{
					ax_76 = dx_73;
					goto l1F38_0B2C;
				}
				ax_55.u0 = (ds->*si_12).t0000.u0;
				if (ax >= ax_55 && ax <= ((ds->*si_12).t0002).u0)
				{
					cx_67 = ax - ax_55;
					ax_69.u0 = (ds->*si_12).t0004.u0;
					si_70 = (struct Eq_45153 Eq_45159::*) ((char *) &si_12->t0004 + 2);
					ax_71 = ax_69 - cx_67;
					SCZO_72 = cond(ax_71);
					C_89 = SLICE(SCZO_72, bool, 1);
					O_101 = SLICE(SCZO_72, bool, 4);
					S_107 = (bool) SCZO_72;
					Z_121 = SLICE(SCZO_72, bool, 2);
					goto l1F38_0B2C;
				}
l1F38_0B24:
				si_61 = (union Eq_45146 Eq_45159::*) ((char *) si_9 + 3);
				si_62 = (struct Eq_45179 Eq_45159::*) ((char *) si_61 + 2);
				goto l1F38_0B27;
			}
			ax_41.u0 = (ds->*si_12).t0000.u0;
			if (ax < ax_41)
				goto l1F38_0B24;
			ax_45.u0 = (ds->*si_12).t0002.u0;
			si_46 = (struct Eq_45179 Eq_45159::*) &si_12->t0004.u0;
			if (ax <= ax_45)
			{
				ax_49.u0 = (ds->*si_12).t0004.u0;
				si_50 = (struct Eq_45153 Eq_45159::*) ((char *) &si_12->t0004 + 2);
				ax_51 = ax_49 + ax;
				SCZO_52 = cond(ax_51);
				C_90 = SLICE(SCZO_52, bool, 1);
				O_102 = SLICE(SCZO_52, bool, 4);
				S_108 = (bool) SCZO_52;
				Z_122 = SLICE(SCZO_52, bool, 2);
				goto l1F38_0B2C;
			}
l1F38_0B27:
			si_64 = ϕ(si_46, si_34, si_62, si_21);
			si_65 = (union Eq_45146 Eq_45159::*) &si_64->t0002.u0;
			goto l1F38_0ACA;
		}
		ax_29.u0 = (ds->*si_12).t0000.u0;
		if (ax < ax_29)
			goto l1F38_0B24;
		ax_33.u0 = (ds->*si_12).t0002.u0;
		si_34 = (struct Eq_45179 Eq_45159::*) &si_12->t0004.u0;
		SCZO_35 = cond(ax - ax_33);
		C_91 = SLICE(SCZO_35, bool, 1);
		O_103 = SLICE(SCZO_35, bool, 4);
		S_109 = (bool) SCZO_35;
		Z_123 = SLICE(SCZO_35, bool, 2);
		if (ax > ax_33)
			goto l1F38_0B27;
		ax_37.u0 = (ds->*si_12).t0004.u0;
		si_38 = (struct Eq_45153 Eq_45159::*) ((char *) &si_12->t0004 + 2);
	}
	else
	{
		ax_20.u0 = (ds->*si_12).t0000.u0;
		si_21 = (struct Eq_45179 Eq_45159::*) &si_12->t0002.u0;
		SCZO_23 = cond(ax - ax_20);
		Z_24 = SLICE(SCZO_23, bool, 2);
		C_92 = SLICE(SCZO_23, bool, 1);
		O_104 = SLICE(SCZO_23, bool, 4);
		S_110 = (bool) SCZO_23;
		if (ax != ax_20)
			goto l1F38_0B27;
		ax_25.u0 = (ds->*si_12).t0002.u0;
		si_26 = (struct Eq_45153 Eq_45159::*) &si_12->t0004.u0;
	}
l1F38_0B2C:
	Z_120 = ϕ(Z_54, Z_121, Z_122, Z_123, Z_24);
	si_111 = ϕ(si_12, si_70, si_50, si_38, si_26);
	S_105 = ϕ(S_106, S_107, S_108, S_109, S_110);
	O_99 = ϕ(O_100, O_101, O_102, O_103, O_104);
	cx_93 = ϕ(cx_6, cx_67, cx_6, cx_6, cx_6);
	C_87 = ϕ(C_88, C_89, C_90, C_91, C_92);
	ax_86 = ϕ(ax_76, ax_71, ax_51, ax_37, ax_25);
}

// 1F38:0B2D: define fn1F38_0B2D
// Called from:
//      fn1F38_0B4E
//      fn1F38_0B88
//      fn1F38_0C24
//      fn1F38_0C41
//      fn1F38_0C67
//      fn1F38_0C81
define fn1F38_0B2D
{
	selector ds;
	<unknown> Mem0;
	word16 ax;
	Top_3 = 0;
	si_6 = ds->w0F1B;
	si_15 = (si_6 << 0x02) + 0x02;
	si_17 = (word16) (ds->*((word16) si_15 + 0x0F2F));
	fn1F38_0AC5();
	ds->w0F17 = ax_18;
	si_32 = ds->a0F2F[0].w0000[si_6].w0000;
	fn1F38_0AC5();
}

// 1F38:0B4E: define fn1F38_0B4E
// Called from:
//      fn1F38_0D06
define fn1F38_0B4E
{
	selector ds;
	Top_3 = 0;
	do
		Z_6 = msdos_direct_console_input(out al_5);
	while (Z_6);
	ax_18 = (uint16) al_5;
	if (al_5 == 0x00)
	{
		msdos_direct_console_output(~0x00);
		ax_11 = (uint16) al_5;
		ax_12 = ax_11 + 0x0100;
	}
	ax_17 = ϕ(ax_18, ax_12);
	fn1F38_0B2D();
}

// 1F38:0B69: define fn1F38_0B69
// Called from:
//      fn1F38_0CDC
define fn1F38_0B69
{
	byte al;
	selector ds;
	Top_3 = 0;
	msdos_get_stdin_status();
	ax_6 = (uint16) al;
	SZP_7 = cond(ax_6);
	Z_10 = SLICE(SZP_7, bool, 2);
	P_18 = SLICE(SZP_7, bool, 5);
	S_20 = (bool) SZP_7;
	O_8 = false;
	C_9 = false;
	if (ax_6 != 0x00)
	{
		ax_11 = 0x02;
		ds->w0F17 = 0x00;
	}
	ax_14 = ϕ(ax_6, ax_11);
}

// 1F38:0B7D: define fn1F38_0B7D
// Called from:
//      fn1F38_0B88
//      fn1F38_0C81
define fn1F38_0B7D
{
	word16 bx;
	selector ds;
	<unknown> Mem0;
	Top_3 = 0;
	bx_6 = bx + 0x02;
	SCZO_9 = cond(bx + 0x02 - ds->w0F25);
	C_10 = SLICE(SCZO_9, bool, 1);
	O_18 = SLICE(SCZO_9, bool, 4);
	S_20 = (bool) SCZO_9;
	Z_25 = SLICE(SCZO_9, bool, 2);
	if (bx + 0x02 >= ds->w0F25)
	{
		bx_11 = 0x00;
		SZ_12 = cond(0x00);
		S_21 = (bool) SZ_12;
		Z_26 = SLICE(SZ_12, bool, 2);
		O_13 = false;
		C_14 = false;
	}
	Z_24 = ϕ(Z_25, Z_26);
	S_19 = ϕ(S_20, S_21);
	O_17 = ϕ(O_18, O_13);
	C_16 = ϕ(C_10, C_14);
	bx_15 = ϕ(bx_6, bx_11);
}

// 1F38:0B88: define fn1F38_0B88
// Called from:
//      fn1F38_0CC5
//      fn1F38_0CDC
//      fn1F38_0D06
define fn1F38_0B88
{
	selector ds;
	bool C;
	bool D;
	byte dh;
	bool O;
	bool S;
	Top_3 = 0;
	while (true)
	{
		S_91 = ϕ(S, S_93, S_93);
		O_88 = ϕ(O, O_90, O_90);
		dh_83 = ϕ(dh, dh_86, dh_86);
		D_80 = ϕ(D, D_31, D_31);
		C_74 = ϕ(C, C_76, C_76);
		Z_6 = msdos_direct_console_input(out al_5);
		ax_71 = (uint16) al_5;
		dx_87 = SEQ(dh_83, ~0x00);
		if (Z_6)
			break;
		ax_18 = (uint16) al_5;
		if (al_5 == 0x00)
		{
			msdos_direct_console_output(~0x00);
			ax_11 = (uint16) al_5;
			ax_12 = ax_11 + 0x0100;
		}
		ax_17 = ϕ(ax_18, ax_12);
		fn1F38_0B2D();
		dh_86 = SLICE(dx_26, byte, 8);
		if (ax_24 <= 0x87 && ax_24 >= 0x80)
		{
			ds->t0F2B.u0 = 0x00;
			ds->t0F2D.u0 = 0x00;
		}
		Mem41 = ϕ(Mem21, Mem39);
		bx_42 = ds->t0F2D;
		fn1F38_0B7D();
		SCZO_49 = cond(bx_44 - ds->t0F2B);
		C_76 = SLICE(SCZO_49, bool, 1);
		O_90 = SLICE(SCZO_49, bool, 4);
		S_93 = (bool) SCZO_49;
		if (bx_44 != ds->t0F2B)
		{
			ds->t0F2D = bx_44;
			es_bx_59 = ds->ptr0F27;
			Mem63[es_bx_59 + bx_42:word16] = ax_17;
		}
	}
}

// 1F38:0BD9: define fn1F38_0BD9
// Called from:
//      fn21DC_0EC2
define fn1F38_0BD9
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = (struct Eq_45609 * Eq_45610::*) bp;
	sp -= 2;
	ss->*sp = (struct Eq_45609 * Eq_45610::*) si;
	sp -= 2;
	ss->*sp = (struct Eq_45609 * Eq_45610::*) di;
	sp -= 2;
	ss->*sp = (struct Eq_45609 * Eq_45610::*) ds;
	dx = cs;
	ds = dx;
	dx = 0x0D4E;
	al = 0x23;
	ah = 0x25;
	msdos_set_interrupt_vector(al, ds_dx);
	ds = (struct Eq_45609 *) (ss->*sp);
	sp = (struct Eq_45609 * Eq_45610::*) ((char *) sp + 2);
	di = (struct Eq_45609 *) (ss->*sp);
	sp = (struct Eq_45609 * Eq_45610::*) ((char *) sp + 2);
	si = (struct Eq_45609 *) (ss->*sp);
	sp = (struct Eq_45609 * Eq_45610::*) ((char *) sp + 2);
	bp = (struct Eq_45609 *) (ss->*sp);
	sp = (struct Eq_45609 * Eq_45610::*) ((char *) sp + 2);
}

// 1F38:0BF1: define fn1F38_0BF1
// Called from:
//      fn21DC_04BA
//      main
define fn1F38_0BF1
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	di = ss->*sp;
	++sp;
	si = ss->*sp;
	++sp;
	bp = ss->*sp;
	++sp;
}

// 1F38:0C09: define fn1F38_0C09
// Called from:
//      fn3431_06CC
define fn1F38_0C09
{
	selector ds;
	segptr32 ptrArg04;
	word16 wArg08;
	Top_3 = 0;
	es_16 = SLICE(ptrArg04, selector, 16);
	si_19 = (word16) ptrArg04;
	ds->ptr0F23 = es_16;
	ds->w0F21 = si_19;
	ds->w0F1F = wArg08;
}

// 1F38:0C24: define fn1F38_0C24
// Called from:
//      fn1F38_0CDC
define fn1F38_0C24
{
	selector ds;
	<unknown> Mem0;
	word16 bx;
	word16 ax;
	word16 cx;
	bool D;
	word16 dx;
	selector es;
	word16 si;
	Top_3 = 0;
	SZP_6 = cond(ds->w0F1F);
	Z_9 = SLICE(SZP_6, bool, 2);
	P_53 = SLICE(SZP_6, bool, 5);
	S_56 = (bool) SZP_6;
	if (ds->w0F1F != 0x00)
	{
		es_si_10 = ds->ptr0F21;
		es_12 = SLICE(es_si_10, selector, 16);
		al_14 = *es_si_10;
		ax_21 = (uint16) al_14;
		if (al_14 == 0x3B)
			ax_22 = 0x0D;
		ax_20 = ϕ(ax_21, ax_22);
		fn1F38_0B2D();
		bx_34 = bx | 0x01;
		SZ_35 = cond(bx | 0x01);
		S_57 = (bool) SZ_35;
		Z_65 = SLICE(SZ_35, bool, 2);
	}
	Z_64 = ϕ(Z_9, Z_65);
	si_58 = ϕ(si, si_26);
	S_55 = ϕ(S_56, S_57);
	O_51 = false;
	es_48 = ϕ(es, es_12);
	dx_46 = ϕ(dx, dx_25);
	D_44 = ϕ(D, D_30);
	cx_42 = ϕ(cx, cx_24);
	C_41 = false;
	bx_40 = ϕ(bx, bx_34);
	ax_38 = ϕ(ax, ax_23);
}

// 1F38:0C41: define fn1F38_0C41
// Called from:
//      fn1F38_0D06
define fn1F38_0C41
{
	selector ds;
	<unknown> Mem0;
	word16 bx;
	word16 ax;
	word16 cx;
	bool D;
	word16 dx;
	selector es;
	word16 si;
	Top_3 = 0;
	SZP_6 = cond(ds->w0F1F);
	Z_9 = SLICE(SZP_6, bool, 2);
	P_57 = SLICE(SZP_6, bool, 5);
	S_60 = (bool) SZP_6;
	if (ds->w0F1F != 0x00)
	{
		es_si_11 = ds->t0F21;
		es_13 = SLICE(es_si_11, selector, 16);
		si_14 = (word16) es_si_11;
		al_15 = *es_si_11.u1;
		ds->t0F21 = si_14 + 1;
		v16_18 = ds->w0F1F - 0x01;
		ds->w0F1F = v16_18;
		ax_25 = (uint16) al_15;
		if (al_15 == 0x3B)
			ax_26 = 0x0D;
		ax_24 = ϕ(ax_25, ax_26);
		fn1F38_0B2D();
		bx_38 = bx | 0x01;
		SZ_39 = cond(bx | 0x01);
		S_61 = (bool) SZ_39;
		Z_69 = SLICE(SZ_39, bool, 2);
	}
	Z_68 = ϕ(Z_9, Z_69);
	si_62 = ϕ(si, si_30);
	S_59 = ϕ(S_60, S_61);
	O_55 = false;
	es_52 = ϕ(es, es_13);
	dx_50 = ϕ(dx, dx_29);
	D_48 = ϕ(D, D_34);
	cx_46 = ϕ(cx, cx_28);
	C_45 = false;
	bx_44 = ϕ(bx, bx_38);
	ax_42 = ϕ(ax, ax_27);
}

// 1F38:0C67: define fn1F38_0C67
// Called from:
//      fn1F38_0CDC
define fn1F38_0C67
{
	selector ds;
	<unknown> Mem0;
	word16 ax;
	word16 cx;
	bool D;
	word16 dx;
	word16 si;
	Top_3 = 0;
	bx_6 = ds->w0F2B;
	SCZO_7 = cond(bx_6 - ds->w0F2D);
	Z_8 = SLICE(SCZO_7, bool, 2);
	C_37 = SLICE(SCZO_7, bool, 1);
	O_46 = SLICE(SCZO_7, bool, 4);
	S_48 = (bool) SCZO_7;
	if (bx_6 != ds->w0F2D)
	{
		es_si_13 = ds->t0F27;
		ax_16 = (word16) *((word32) es_si_13 + (uipr32) bx_6);
		fn1F38_0B2D();
		bx_28 = bx_6 | 0x01;
		SZ_29 = cond(bx_6 | 0x01);
		S_49 = (bool) SZ_29;
		Z_55 = SLICE(SZ_29, bool, 2);
		O_30 = false;
		C_31 = false;
	}
	Z_54 = ϕ(Z_8, Z_55);
	si_50 = ϕ(si, si_22);
	S_47 = ϕ(S_48, S_49);
	O_45 = ϕ(O_46, O_30);
	dx_42 = ϕ(dx, dx_21);
	D_40 = ϕ(D, D_26);
	cx_38 = ϕ(cx, cx_20);
	C_36 = ϕ(C_37, C_31);
	bx_35 = ϕ(bx_6, bx_28);
	ax_33 = ϕ(ax, ax_19);
}

// 1F38:0C81: define fn1F38_0C81
// Called from:
//      fn1F38_0D06
define fn1F38_0C81
{
	selector ds;
	<unknown> Mem0;
	word16 ax;
	word16 cx;
	bool D;
	word16 dx;
	word16 si;
	Top_3 = 0;
	bx_6 = ds->w0F2B;
	SCZO_7 = cond(bx_6 - ds->w0F2D);
	Z_8 = SLICE(SCZO_7, bool, 2);
	C_43 = SLICE(SCZO_7, bool, 1);
	O_52 = SLICE(SCZO_7, bool, 4);
	S_54 = (bool) SCZO_7;
	if (bx_6 != ds->w0F2D)
	{
		es_si_13 = ds->t0F27;
		ax_16 = (word16) *((word32) es_si_13 + (uipr32) bx_6);
		fn1F38_0B7D();
		ds->w0F2B = bx_19;
		fn1F38_0B2D();
		bx_34 = bx_19 | 0x01;
		SZ_35 = cond(bx_19 | 0x01);
		S_55 = (bool) SZ_35;
		Z_61 = SLICE(SZ_35, bool, 2);
		O_36 = false;
		C_37 = false;
	}
	Z_60 = ϕ(Z_8, Z_61);
	si_56 = ϕ(si, si_28);
	S_53 = ϕ(S_54, S_55);
	O_51 = ϕ(O_52, O_36);
	dx_48 = ϕ(dx, dx_27);
	D_46 = ϕ(D, D_32);
	cx_44 = ϕ(cx, cx_26);
	C_42 = ϕ(C_43, C_37);
	bx_41 = ϕ(bx_6, bx_34);
	ax_39 = ϕ(ax, ax_25);
}

// 1F38:0CA2: define fn1F38_0CA2
// Called from:
//      fn3431_000A
//      fn3431_013E
define fn1F38_0CA2
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46071 Eq_46078::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46071 Eq_46078::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46071 Eq_46078::*) di;
	bp = sp;
	ax = (ss->*bp).w000A;
	ds->w0F27 = ax;
	ax = (ss->*bp).w000C;
	ds->w0F29 = ax;
	ax = (ss->*bp).w000E;
	ds->w0F25 = ax;
	ax = ax ^ ax;
	SZ = cond(ax);
	O = false;
	C = false;
	ds->w0F2B = ax;
	ds->w0F2D = ax;
	di = (struct Eq_46071 Eq_46078::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46071 Eq_46078::*) &sp->ptr0000;
	si = (struct Eq_46071 Eq_46078::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46071 Eq_46078::*) &sp->ptr0000;
	bp = (struct Eq_46071 Eq_46078::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46071 Eq_46078::*) &sp->ptr0000;
}

// 1F38:0CC5: define fn1F38_0CC5
// Called from:
//      fn1825_037E
//      fn1825_06E0
//      fn20B2_1014
//      fn21DC_0006
define fn1F38_0CC5
{
	selector ds;
	Top_3 = 0;
	fn1F38_0B88();
	ax_19 = 0x00;
	SZ_20 = cond(0x00);
	S_35 = (bool) SZ_20;
	Z_36 = SLICE(SZ_20, bool, 2);
	O_21 = false;
	C_22 = false;
	ds->w0F2B = 0x00;
	ds->w0F2D = 0x00;
	ds->w0F1F = 0x00;
}

// 1F38:0CDC: define fn1F38_0CDC
// Called from:
//      fn1825_0C7E
//      fn1F38_0D37
//      fn3431_06CC
define fn1F38_0CDC
{
	selector ds;
	word16 bx;
	Top_3 = 0;
	if (ds->w0F25 != 0x00)
	{
		fn1F38_0B88();
		fn1F38_0C24();
		if (!Z_50)
		{
			fn1F38_0C67();
			if (!Z_60)
			{
				ax_62 = 0x00;
				SZ_63 = cond(0x00);
				S_105 = (bool) SZ_63;
				Z_110 = SLICE(SZ_63, bool, 2);
				O_64 = false;
				C_65 = false;
			}
		}
	}
	else
	{
		fn1F38_0C24();
		al_32 = (byte) ax_21;
		if (!Z_29)
		{
			fn1F38_0B69();
l1F38_0D02:
			Z_108 = ϕ(Z_36, Z_109);
			S_103 = ϕ(S_34, S_104);
			P_101 = ϕ(P_38, P_102);
			O_99 = ϕ(O_37, O_100);
			es_97 = ϕ(es_25, es_98);
			dx_95 = ϕ(dx_24, dx_96);
			cx_93 = ϕ(cx_23, cx_94);
			C_91 = ϕ(C_35, C_92);
			bx_89 = ϕ(bx_22, bx_90);
			ax_87 = ϕ(ax_33, ax_88);
			return;
		}
	}
	Z_109 = ϕ(Z_50, Z_60, Z_110, Z_29);
	S_104 = ϕ(S_48, S_58, S_105, S_27);
	P_102 = ϕ(P_52, P_52, P_52, P_31);
	O_100 = ϕ(O_51, O_61, O_64, O_30);
	es_98 = ϕ(es_46, es_46, es_46, es_25);
	dx_96 = ϕ(dx_45, dx_56, dx_56, dx_24);
	cx_94 = ϕ(cx_44, cx_55, cx_55, cx_23);
	C_92 = ϕ(C_49, C_59, C_65, C_28);
	bx_90 = ϕ(bx_43, bx_53, bx_53, bx_22);
	ax_88 = ϕ(ax_42, ax_54, ax_62, ax_21);
	goto l1F38_0D02;
}

// 1F38:0D06: define fn1F38_0D06
// Called from:
//      fn21DC_0D60
//      fn3431_06CC
define fn1F38_0D06
{
	selector ds;
	word16 bx;
	bool D;
	Top_3 = 0;
	if (ds->w0F25 != 0x00)
	{
		do
		{
			bx_45 = ϕ(bx, bx_57);
			fn1F38_0B88();
			fn1F38_0C41();
			if (Z_54)
				break;
			fn1F38_0C81();
		} while (Z_64);
	}
	else
	{
		fn1F38_0C41();
		if (!Z_29)
		{
			fn1F38_0B4E();
l1F38_0D33:
			Z_120 = ϕ(Z_121, Z_38);
			S_115 = ϕ(S_116, S_36);
			P_113 = ϕ(P_114, P_31);
			O_111 = ϕ(O_112, O_40);
			es_109 = ϕ(es_110, es_25);
			dx_107 = ϕ(dx_108, dx_34);
			D_103 = ϕ(D, D_39);
			cx_101 = ϕ(cx_102, cx_33);
			C_99 = ϕ(C_100, C_37);
			bx_98 = ϕ(bx_69, bx_22);
			ax_96 = ϕ(ax_97, ax_32);
			return;
		}
	}
	Z_121 = ϕ(Z_54, Z_64, Z_29);
	S_116 = ϕ(S_52, S_62, S_27);
	P_114 = ϕ(P_56, P_56, P_31);
	O_112 = ϕ(O_55, O_65, O_30);
	es_110 = ϕ(es_50, es_50, es_25);
	dx_108 = ϕ(dx_49, dx_60, dx_24);
	cx_102 = ϕ(cx_48, cx_59, cx_23);
	C_100 = ϕ(C_53, C_63, C_28);
	ax_97 = ϕ(ax_46, ax_58, ax_21);
	bx_69 = ds->w0F17;
	ds->w0F19 = bx_69;
	goto l1F38_0D33;
}

// 1F38:0D37: define fn1F38_0D37
// Called from:
//      fn21DC_0D60
define fn1F38_0D37
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46389 Eq_46396::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46389 Eq_46396::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46389 Eq_46396::*) di;
	bp = sp;
	ah = 0x01;
	Z = bios_kbd_check_keystroke(out al, out ah);
	ax = 0x00;
	if (Test(NE,Z))
		fn1F38_0CDC();
	di = (struct Eq_46389 Eq_46396::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46389 Eq_46396::*) &sp->ptr0000;
	si = (struct Eq_46389 Eq_46396::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46389 Eq_46396::*) &sp->ptr0000;
	bp = (struct Eq_46389 Eq_46396::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46389 Eq_46396::*) &sp->ptr0000;
}

// 1F38:0D68: define fn1F38_0D68
// Called from:
//      fn21DC_0EC2
define fn1F38_0D68
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46448 Eq_46455::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46448 Eq_46455::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46448 Eq_46455::*) di;
	bp = sp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46448 Eq_46455::*) ax;
	ax = &Eq_46455::t0004;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46448 Eq_46455::*) bp;
	bp = sp;
	v9 = (struct Eq_46448 Eq_46455::*) (ss->*bp).ptr0002;
	(ss->*bp).ptr0002 = (struct Eq_46448 Eq_46455::*) ax;
	ax = v9;
	bp = (struct Eq_46448 Eq_46455::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46448 Eq_46455::*) &sp->ptr0002;
	fn1F38_0D8D();
	sp = (struct Eq_46448 Eq_46455::*) &sp->ptr0002;
	SCZO = cond(sp);
	di = (struct Eq_46448 Eq_46455::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46448 Eq_46455::*) &sp->ptr0002;
	si = (struct Eq_46448 Eq_46455::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46448 Eq_46455::*) &sp->ptr0002;
	bp = (struct Eq_46448 Eq_46455::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46448 Eq_46455::*) &sp->ptr0002;
}

// 1F38:0D84: define fn1F38_0D84
// Called from:
//      fn21DC_04BA
//      main
define fn1F38_0D84
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	di = ss->*sp;
	++sp;
	si = ss->*sp;
	++sp;
	bp = ss->*sp;
	++sp;
}

// 1F38:0D8D: define fn1F38_0D8D
// Called from:
//      fn1F38_0D68
//      fn21DC_04BA
define fn1F38_0D8D
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46571 Eq_46578::*) bp;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46571 Eq_46578::*) si;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_46571 Eq_46578::*) di;
	bp = sp;
	bx = (ss->*bp).w000A;
	ds->w10A3 = bx;
	al = 0x00;
	ah = 0x44;
	C = msdos_ioctl_get_device_info(bx, out dx);
	dx &= 0x80;
	SZ = cond(dx);
	O = false;
	C = false;
	ds->w10A5 = dx;
	di = (struct Eq_46571 Eq_46578::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46571 Eq_46578::*) &sp->ptr0000;
	si = (struct Eq_46571 Eq_46578::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46571 Eq_46578::*) &sp->ptr0000;
	bp = (struct Eq_46571 Eq_46578::*) (ss->*sp).ptr0000;
	sp = (struct Eq_46571 Eq_46578::*) &sp->ptr0000;
}

// 1F38:0DAB: define fn1F38_0DAB
// Called from:
//      fn3431_0214
define fn1F38_0DAB
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	sp -= 2;
	ss->*sp = si;
	sp -= 2;
	ss->*sp = di;
	bp = sp;
	Mem0[ds:0x10A1:word16] = 0x00;
	cx = ss->*((word16) bp + 0x0E);
	if (cx != 0x00)
	{
		bx = Mem0[ds:0x10A3:word16];
		SZP = cond(Mem0[ds:0x10A5:word16] & ~0x00);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			do
			{
				sp -= 2;
				ss->*sp = cx;
				sp -= 2;
				ss->*sp = ds;
				cx.u0 = 0x01;
				ds_dx.u1 = ss->*((word16) bp + 0x0A);
				ah = 0x40;
				C = msdos_write_file(bx, cx, ds_dx, out ax);
				ds = ss->*sp;
				sp = (word16) sp + 2;
				cx = ss->*sp;
				sp = (word16) sp + 2;
				if (Test(ULT,C))
					goto l1F38_0DDF;
				v19.u0 = (word16) (ss->*((word16) bp + 0x0A)) + 1;
				ss->*((word16) bp + 0x0A) = v19;
				SZO = cond(v19);
				--cx;
			} while (cx != 0x00);
			ax.u0 = 0x00;
l1F38_0DDF:
			Mem0[ds:0x10A1:word16] = ax;
			ax = ss->*((word16) bp + 0x0E);
			ax -= cx;
			SCZO = cond(ax);
		}
		else
		{
			sp -= 2;
			ss->*sp = ds;
			ds_dx.u1 = ss->*((word16) bp + 0x0A);
			ah = 0x40;
			C = msdos_write_file(bx, cx, ds_dx, out ax);
			ds = ss->*sp;
			sp = (word16) sp + 2;
			if (Test(ULT,C))
			{
				Mem0[ds:0x10A1:word16] = ax;
				ax.u0 = 0x00;
			}
		}
	}
	di = ss->*sp;
	sp = (word16) sp + 2;
	si = ss->*sp;
	sp = (word16) sp + 2;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

