// 1999_SOFT_LOAN__2BC7.c
// Generated by decompiling 1999_SOFT_LOAN_.exe
// using Reko decompiler version 0.11.4.0.

#include "1999_SOFT_LOAN_.h"

// 2BC7:0000: define fn2BC7_0000
// Called from:
//      fn2BC7_01EA
define fn2BC7_0000
{
	sp = fp;
	Top = 0;
	SCZO = cond(ds->w13AA - 0x00);
	if (Test(EQ,Z))
	{
		ax = 0x01C2;
		sp -= 2;
		ss->*sp = ax;
		fn21DC_097E();
		++sp;
		SCZO = cond(sp);
		ds->w13A6 = ax;
		ds->w13A8 = dx;
		ds->w13AA = 0x19;
	}
	v10 = ds->w13AA - 0x01;
	ds->w13AA = v10;
	ax = 0x12;
	dx_ax = ds->w13AA *32 ax;
	ax += ds->w13A6;
	SCZO = cond(ax);
	dx = ds->w13A8;
}

// 2BC7:0034: define fn2BC7_0034
// Called from:
//      fn2BC7_03C2
define fn2BC7_0034
{
	sp = fp;
	Top = 0;
	SCZO = cond(ds->w13B0 - 0x00);
	if (Test(EQ,Z))
	{
		ax = 0x01E0;
		sp -= 2;
		ss->*sp = ax;
		fn21DC_097E();
		++sp;
		SCZO = cond(sp);
		ds->w13AC = ax;
		ds->w13AE = dx;
		ds->w13B0 = 0x1E;
	}
	v10 = ds->w13B0 - 0x01;
	ds->w13B0 = v10;
	ax = ds->w13B0;
	cl = 0x04;
	ax <<= cl;
	ax += ds->w13AC;
	SCZO = cond(ax);
	dx = ds->w13AE;
}

// 2BC7:0068: define fn2BC7_0068
// Called from:
//      fn2BC7_0312
//      fn2BC7_03C2
//      fn2BC7_0494
define fn2BC7_0068
{
	word32 dwArg04;
	selector ds;
	segptr32 ptrArg0A;
	word16 wArg08;
	word16 cx;
	bool D;
	Top_3 = 0;
	wLoc08_147 = 0x00;
	ax_16 = ds->w1392;
l2BC7_00BB:
	D_201 = ϕ(D, D_62);
	cx_196 = ϕ(cx, cx_57);
	wLoc08_179 = ϕ(wLoc08_147, wLoc08_150);
	ax_17 = ϕ(ax_16, ax_70);
	while (true)
	{
		D_200 = ϕ(D_201, D_62);
		cx_195 = ϕ(cx_196, cx_57);
		wLoc08_150 = ϕ(wLoc08_179, wLoc08_162);
		if (wLoc08_150 >= ax_17)
			break;
		ax_28 = wLoc08_150 + ax_17;
		es_si_41 = ds->ptr138E;
		es_42 = SLICE(es_si_41, selector, 16);
		si_43 = (word16) es_si_41;
		v25_44 = (Eq_74210) (es_42->*((word16) si_43 + ((word16) ((ax_28 >> 0x01) << 0x02) + 2)));
		v26_47 = si_43[ax_28 >> 0x01].w0000;
		ptrLoc10_160 = SEQ(v25_44, v26_47);
		ptrLoc14_161 = dwArg04;
		fn38AD_00F2();
		if (ax_56 <= 0x00)
		{
			ax_70 = ax_28 >> 0x01;
			goto l2BC7_00BB;
		}
		wLoc08_162 = (ax_28 >> 0x01) + 0x01;
	}
	es_77 = SLICE(ptrArg0A, selector, 16);
	bx_78 = (word16) ptrArg0A;
	*ptrArg0A = wLoc08_150;
	ax_80 = ds->w1392;
	if (wLoc08_150 < ax_80)
	{
		es_bx_92 = ds->ptr138E;
		es_93 = SLICE(es_bx_92, selector, 16);
		bx_94 = (word16) es_bx_92;
		v16_95 = (&(es_93->*((char *) bx_94 + 2)))[wLoc08_150].w0000;
		v17_98 = es_bx_92[wLoc08_150].w0000;
		ptrLoc10_171 = SEQ(v16_95, v17_98);
		ptrLoc14_172 = dwArg04;
		fn38AD_00F2();
		SZ_117 = cond(ax_107);
		Z_120 = SLICE(SZ_117, bool, 2);
		S_210 = (bool) SZ_117;
		O_118 = false;
		C_119 = false;
		if (ax_107 == 0x00)
		{
			es_bx_132 = ds->ptr138E;
			bx_133 = (word16) es_bx_132;
			es_bx_134 = bx_133[wLoc08_150];
			es_135 = SLICE(es_bx_134, selector, 16);
			bx_136 = (word16) es_bx_134;
			ax_137 = es_bx_134->w000C;
			dx_138 = es_bx_134->w000E;
			return;
		}
	}
	es_206 = ϕ(es_77, es_109);
	D_199 = ϕ(D_200, D_113);
	cx_194 = ϕ(cx_195, cx_108);
	bx_190 = ϕ(bx_78, bx_94);
	SCZO_122 = cond(0x00);
	C_192 = SLICE(SCZO_122, bool, 1);
	O_208 = SLICE(SCZO_122, bool, 4);
	S_211 = (bool) SCZO_122;
	Z_219 = SLICE(SCZO_122, bool, 2);
	ax_187 = 0x00;
	dx_204 = 0x00;
}

// 2BC7:011C: define fn2BC7_011C
// Called from:
//      fn2BC7_0312
//      fn2BC7_03C2
define fn2BC7_011C
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x0A;
	sp -= 2;
	ss->*sp = si;
	ax = ds->t1394;
	SCZO = cond(ds->t1392 - ax);
	if (Test(UGE,C))
	{
		++ah;
		ss->*((word16) bp - 6) = ax;
		ax <<= 0x01;
		ax <<= 0x01;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		fn21DC_097E();
		sp = (word16) sp + 2;
		ss->*((word16) bp - 4) = ax;
		ss->*((word16) bp - 2) = dx;
		ax = ds->t1394;
		ax <<= 0x01;
		ax <<= 0x01;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		v13 = ds->t1390;
		sp -= 2;
		ss->*sp = v13;
		v14 = ds->t138E;
		sp -= 2;
		ss->*sp = v14;
		sp -= 2;
		ss->*sp = dx;
		v15 = ss->*((word16) bp - 4);
		sp -= 2;
		ss->*sp = v15;
		fn2017_0258();
		sp = (word16) sp + 0x0A;
		ax = ds->t1394;
		ax <<= 0x01;
		ax <<= 0x01;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		v16 = ds->t1390;
		sp -= 2;
		ss->*sp = v16;
		v17 = ds->t138E;
		sp -= 2;
		ss->*sp = v17;
		fn21DC_09B4();
		sp = (word16) sp + 6;
		SCZO = cond(sp);
		ax = ss->*((word16) bp - 6);
		ds->t1394 = ax;
		ax = ss->*((word16) bp - 4);
		dx = ss->*((word16) bp - 2);
		ds->t138E = ax;
		ds->t1390 = dx;
	}
	ax = ds->t1392;
	SCZO = cond(ss->*((word16) bp + 0x0A) - ax);
	if (Test(ULT,C))
	{
		ax = ss->*((word16) bp + 0x0A);
		ax <<= 0x01;
		ax <<= 0x01;
		ax += Mem0[ds:5006:word16];
		dx = ds->t1390;
		ss->*((word16) bp - 0x0A) = ax;
		ss->*((word16) bp - 8) = dx;
		ax = ds->t1392;
		ax -= ss->*((word16) bp + 0x0A);
		ax <<= 0x01;
		ax <<= 0x01;
		sp -= 2;
		ss->*sp = ax;
		sp -= 2;
		ss->*sp = dx;
		v18 = ss->*((word16) bp - 0x0A);
		sp -= 2;
		ss->*sp = v18;
		ax = ss->*((word16) bp - 0x0A);
		ax = (word16) ax + 4;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = dx;
		sp -= 2;
		ss->*sp = ax;
		fn2017_0258();
		sp = (word16) sp + 0x0A;
		SCZO = cond(sp);
	}
	v19 = (word32) ds->t1392 + 1;
	ds->t1392 = v19;
	bx = ss->*((word16) bp + 0x0A);
	bx <<= 0x01;
	bx <<= 0x01;
	SCZO = cond(bx);
	es_si = ds->t138E;
	ax = ss->*((word16) bp + 6);
	dx = ss->*((word16) bp + 8);
	Mem0[es:bx + si:word16] = ax;
	es->*((word16) si + ((word16) bx + 2)) = dx;
	si = ss->*sp;
	sp = bp;
	bp = ss->*sp;
	sp = (word16) sp + 2;
}

// 2BC7:01EA: define fn2BC7_01EA
// Called from:
//      fn2BC7_0312
//      fn2BC7_03C2
define fn2BC7_01EA
{
	sp = fp;
	Top = 0;
	sp -= 2;
	(ss->*sp).ptr0000 = (struct Eq_74632 Eq_74639::*) bp;
	bp = sp;
	sp -= 0x04;
	SCZO = cond(sp);
	fn2BC7_0000();
	(ss->*bp).tFFFFFFFC.u2 = (struct Eq_236605 Eq_74655::*) ax;
	(ss->*bp).ptrFFFFFFFE = dx;
	es_bx.u1 = (ss->*bp).tFFFFFFFC.u1;
	ax -= ax;
	SCZO = cond(ax);
	es->*((word16) bx + 2) = ax;
	es->*bx = ax;
	es->*((word16) bx + 6) = ax;
	es->*((word16) bx + 4) = ax;
	es->*((word16) bx + 8) = ax;
	&ax.u2->t0000.u0 = (ss->*bp).t000A.u2;
	dx = (ss->*bp).ptr000C;
	es->*((word16) bx + 0x0E) = ax;
	es->*((word16) bx + 16) = dx;
	&ax.u2->t0000.u0 = (ss->*bp).t0006.u2;
	dx = (ss->*bp).ptr0008;
	es->*((word16) bx + 0x0A) = ax;
	es->*((word16) bx + 0x0C) = dx;
	ax = bx;
	dx = es;
	sp = bp;
	bp = (struct Eq_74632 Eq_74639::*) (ss->*sp).ptr0000;
	sp = (struct Eq_74632 Eq_74639::*) &sp->ptr0000;
}

// 2BC7:0236: define fn2BC7_0236
// Called from:
//      fn21DC_0EC2
define fn2BC7_0236
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x0A;
	SCZO = cond(sp);
	ax = bp - 6;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	fn3CB4_0008();
	sp = (word16) sp + 4;
	ss->*((word16) bp - 2) = ax;
	++ah;
	Mem0[ds:0x1394:word16] = ax;
	ax <<= 0x01;
	ax <<= 0x01;
	SCZO = cond(ax);
	sp -= 2;
	ss->*sp = ax;
	ax.u0 = 5006;
	sp -= 2;
	ss->*sp = ds;
	sp -= 2;
	ss->*sp = ax;
	fn21DC_06DC();
	sp = (word16) sp + 6;
	ax |= ax;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		(ss->*((word16) bp - 0x0A)).u0 = 0x01;
		while (true)
		{
			ax = ss->*((word16) bp - 2);
			SCZO = cond(ss->*((word16) bp - 0x0A) - ax);
			if (Test(UGE,C))
				break;
			ax.u0 = 0x10;
			dx_ax = (int32) ax;
			sp -= 2;
			ss->*sp = dx;
			sp -= 2;
			ss->*sp = ax;
			v22 = ss->*((word16) bp - 4);
			sp -= 2;
			ss->*sp = v22;
			v23 = ss->*((word16) bp - 6);
			sp -= 2;
			ss->*sp = v23;
			fn2017_00DF();
			sp = (word16) sp + 8;
			ss->*((word16) bp - 6) = ax;
			ss->*((word16) bp - 4) = dx;
			es_bx = ss->*((word16) bp - 6);
			SCZO = cond(es->*bx - 0x00);
			if (Test(NE,Z))
			{
				v25 = es->*((word16) bx + 0x0E);
				sp -= 2;
				ss->*sp = v25;
				v26 = es->*((word16) bx + 0x0C);
				sp -= 2;
				ss->*sp = v26;
				sp -= 2;
				ss->*sp = dx;
				sp -= 2;
				ss->*sp = ax;
				fn2BC7_0312();
				sp = (word16) sp + 8;
				SCZO = cond(sp);
				es_bx = ss->*((word16) bp - 6);
				es->*((word16) bx + 0x0C) = ax;
				es->*((word16) bx + 0x0E) = dx;
			}
			v27 = (word32) (ss->*((word16) bp - 0x0A)) + 1;
			ss->*((word16) bp - 0x0A) = v27;
			SZO = cond(v27);
		}
		(ss->*((word16) bp - 7)).u0 = 0x00;
		(ss->*((word16) bp - 0x0A)).u0 = 0x01;
		do
		{
			al = ss->*((word16) bp - 0x0A);
			al.u0 = (byte) al.u0 + 64;
			SCZO = cond(al);
			ss->*((word16) bp - 8) = al;
			ax = bp - 8;
			sp -= 2;
			ss->*sp = ss;
			sp -= 2;
			ss->*sp = ax;
			fn2BC7_03C2();
			sp = (word16) sp + 4;
			bx = ax;
			es = dx;
			ax = ss->*((word16) bp - 0x0A);
			es->*((word16) bx + 8) = ax;
			v18 = (word32) (ss->*((word16) bp - 0x0A)) + 1;
			ss->*((word16) bp - 0x0A) = v18;
			SCZO = cond(ss->*((word16) bp - 0x0A) - 0x0A);
		} while (Test(ULE,CZ));
		(ss->*((word16) bp - 8)).u0 = 77;
		ax = bp - 8;
		sp -= 2;
		ss->*sp = ss;
		sp -= 2;
		ss->*sp = ax;
		fn2BC7_03C2();
		sp = (word16) sp + 4;
		SCZO = cond(sp);
		bx = ax;
		es = dx;
		(es->*((word16) bx + 8)).u0 = ~0x00;
		ax.u0 = 0x01;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
	else
	{
		ax -= ax;
		SCZO = cond(ax);
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 2BC7:0312: define fn2BC7_0312
// Called from:
//      fn2BC7_0236
define fn2BC7_0312
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x06;
	es_bx = ss->*((word16) bp + 6);
	SCZO = cond(es->*bx - 0x24);
	if (Test(EQ,Z))
	{
l2BC7_039E:
		v21 = ss->*((word16) bp + 0x0C);
		sp -= 2;
		ss->*sp = v21;
		v22 = ss->*((word16) bp + 0x0A);
		sp -= 2;
		ss->*sp = v22;
		v23 = ss->*((word16) bp + 8);
		sp -= 2;
		ss->*sp = v23;
		v24 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v24;
		fn2BC7_01EA();
		sp = (word16) sp + 8;
		SCZO = cond(sp);
		ss->*((word16) bp - 6) = ax;
		ss->*((word16) bp - 4) = dx;
		goto l2BC7_03B7;
	}
	ax = bp - 2;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	sp -= 2;
	ss->*sp = es;
	sp -= 2;
	ss->*sp = bx;
	fn2017_03F5();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = ax;
	v12 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v12;
	v13 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v13;
	fn2BC7_0068();
	sp = (word16) sp + 0x0A;
	ss->*((word16) bp - 6) = ax;
	ss->*((word16) bp - 4) = dx;
	ax |= dx;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
		v18 = ss->*((word16) bp - 2);
		sp -= 2;
		ss->*sp = v18;
		v19 = ss->*((word16) bp + 8);
		sp -= 2;
		ss->*sp = v19;
		v20 = ss->*((word16) bp + 6);
		sp -= 2;
		ss->*sp = v20;
		fn2BC7_011C();
		sp = (word16) sp + 6;
		SCZO = cond(sp);
		goto l2BC7_039E;
	}
	es_bx = ss->*((word16) bp - 6);
	ax = es->*((word16) bx + 0x0E);
	ax |= es->*((word16) bx + 16);
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(EQ,Z))
	{
l2BC7_038B:
		es_bx = ss->*((word16) bp - 6);
		ax = ss->*((word16) bp + 0x0A);
		dx = ss->*((word16) bp + 0x0C);
		es->*((word16) bx + 0x0E) = ax;
		es->*((word16) bx + 16) = dx;
		goto l2BC7_03B7;
	}
	else
	{
		ax = ss->*((word16) bp + 0x0A);
		ax |= ss->*((word16) bp + 0x0C);
		SZ = cond(ax);
		O = false;
		C = false;
		if (Test(NE,Z))
		{
			v25 = es->*((word16) bx + 16);
			sp -= 2;
			ss->*sp = v25;
			v26 = es->*((word16) bx + 0x0E);
			sp -= 2;
			ss->*sp = v26;
			v27 = ss->*((word16) bp + 0x0C);
			sp -= 2;
			ss->*sp = v27;
			v28 = ss->*((word16) bp + 0x0A);
			sp -= 2;
			ss->*sp = v28;
			fn2017_0132();
			sp = (word16) sp + 8;
			ax |= ax;
			SZ = cond(ax);
			O = false;
			C = false;
			if (Test(LT,SO))
				goto l2BC7_038B;
		}
l2BC7_03B7:
		ax = ss->*((word16) bp - 6);
		dx = ss->*((word16) bp - 4);
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 2BC7:03C2: define fn2BC7_03C2
// Called from:
//      fn1825_4DA6
//      main
//      fn2BC7_0236
//      fn31FF_0F20
//      fn3431_000A
define fn2BC7_03C2
{
	sp = fp;
	Top = 0;
	sp -= 2;
	ss->*sp = bp;
	bp = sp;
	sp -= 0x1A;
	SCZO = cond(sp);
	sp -= 2;
	ss->*sp = si;
	v8 = ss->*((word16) bp + 8);
	sp -= 2;
	ss->*sp = v8;
	v9 = ss->*((word16) bp + 6);
	sp -= 2;
	ss->*sp = v9;
	fn2017_03D0();
	sp = (word16) sp + 4;
	SCZO = cond(sp);
	ss->*((word16) bp + 6) = ax;
	ss->*((word16) bp + 8) = dx;
	(ss->*((word16) bp - 24)).u0 = 0x00;
	while (true)
	{
		bx = ss->*((word16) bp - 24);
		es_si = ss->*((word16) bp + 6);
		al = Mem0[es:bx + si:byte];
		ss->*((word16) bp - 26) = al;
		al |= al;
		SZ = cond(al);
		O = false;
		C = false;
		if (Test(EQ,Z))
			break;
		SCZO = cond(ss->*((word16) bp - 26) - 0x20);
		if (Test(EQ,Z))
			break;
		SCZO = cond(ss->*((word16) bp - 24) - 0x0A);
		if (Test(UGE,C))
			break;
		al = ss->*((word16) bp - 26);
		ah -= ah;
		SCZO = cond(ah);
		sp -= 2;
		ss->*sp = ax;
		fn38AD_001E();
		sp = (word16) sp + 2;
		SCZO = cond(sp);
		si = ss->*((word16) bp - 24);
		Mem0[ss:bp - 18 + si:byte] = al;
		v29 = (word32) (ss->*((word16) bp - 24)) + 1;
		ss->*((word16) bp - 24) = v29;
		SZO = cond(v29);
	}
	si = ss->*((word16) bp - 24);
	Mem0[ss:bp - 18 + si:byte] = 0x00;
	ax = bp - 2;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	v20 = ss->*((word16) bp - 24);
	sp -= 2;
	ss->*sp = v20;
	ax = bp - 18;
	sp -= 2;
	ss->*sp = ss;
	sp -= 2;
	ss->*sp = ax;
	fn2BC7_0068();
	sp = (word16) sp + 0x0A;
	ss->*((word16) bp - 22) = ax;
	ss->*((word16) bp - 20) = dx;
	ax |= dx;
	SZ = cond(ax);
	O = false;
	C = false;
	if (Test(NE,Z))
	{
		ax = ss->*((word16) bp - 22);
		dx = ss->*((word16) bp - 20);
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
	else
	{
		fn2BC7_0034();
		ss->*((word16) bp - 6) = ax;
		ss->*((word16) bp - 4) = dx;
		ax = bp - 18;
		sp -= 2;
		ss->*sp = ss;
		sp -= 2;
		ss->*sp = ax;
		sp -= 2;
		ss->*sp = dx;
		v21 = ss->*((word16) bp - 6);
		sp -= 2;
		ss->*sp = v21;
		fn2017_01BA();
		sp = (word16) sp + 8;
		SCZO = cond(sp);
		v22 = ss->*((word16) bp - 2);
		sp -= 2;
		ss->*sp = v22;
		v23 = ss->*((word16) bp - 4);
		sp -= 2;
		ss->*sp = v23;
		v24 = ss->*((word16) bp - 6);
		sp -= 2;
		ss->*sp = v24;
		fn2BC7_011C();
		sp = (word16) sp + 6;
		ax -= ax;
		SCZO = cond(ax);
		sp -= 2;
		ss->*sp = ax;
		sp -= 2;
		ss->*sp = ax;
		v25 = ss->*((word16) bp - 4);
		sp -= 2;
		ss->*sp = v25;
		v26 = ss->*((word16) bp - 6);
		sp -= 2;
		ss->*sp = v26;
		fn2BC7_01EA();
		sp = (word16) sp + 8;
		SCZO = cond(sp);
		es_bx = ss->*((word16) bp - 6);
		es->*((word16) bx + 0x0C) = ax;
		es->*((word16) bx + 0x0E) = dx;
		si = ss->*sp;
		sp = bp;
		bp = ss->*sp;
		sp = (word16) sp + 2;
	}
}

// 2BC7:0494: define fn2BC7_0494
// Called from:
//      fn1825_5F7C
//      fn20B2_01BA
//      fn31FF_0F20
//      fn31FF_17DA
//      fn3CEE_4EAC
define fn2BC7_0494
{
	segptr32 ptrArg04;
	mp16 fp;
	selector ss;
	selector ds;
	Top_3 = 0;
	ptrLoc1A_114 = ptrArg04;
	fn2017_03D0();
	wLoc10_117.u0 = 0x00;
	while (true)
	{
		wLoc10_118 = ϕ(wLoc10_117, wLoc10_123);
		Mem35 = ϕ(Mem32, Mem69);
		al_40 = (byte) *((word32) (uipr32) wLoc10_118 + dx_ax_146);
		if (al_40 == 0x00 || (al_40 == 0x20 || wLoc10_118 >= 0x0A))
			break;
		ax_56 = (uint16) al_40;
		bLoc18_122 = (byte) ax_56;
		fn38AD_001E();
		Mem67[ss:fp - 0x0E + wLoc10_118:byte] = al_59;
		v22_68 = (word16) wLoc10_118 + 1;
		wLoc10_123 = v22_68;
	}
	Mem75[ss:fp - 0x0E + wLoc10_118:byte] = 0x00;
	dwLoc20_130 = (word32) (fp - 0x0E);
	ptrLoc1A_131 = (segptr32) (fp - 18);
	fn2BC7_0068();
	SCZO_103 = cond(fp - 22);
	C_137 = SLICE(SCZO_103, bool, 1);
	O_140 = SLICE(SCZO_103, bool, 4);
	S_141 = (bool) SCZO_103;
	Z_144 = SLICE(SCZO_103, bool, 2);
}

// 2BC7:050A: define fn2BC7_050A
// Called from:
//      fn1825_139A
//      fn1825_2020
//      fn1825_4BFA
//      fn1825_54D4
//      fn1825_5730
//      fn1825_5850
//      fn1825_5E5C
//      fn20B2_005C
//      fn20B2_01FC
//      fn20B2_0474
//      fn20B2_0612
//      fn20B2_0776
//      fn20B2_0898
//      fn20B2_099A
//      fn20B2_0AC6
//      fn20B2_0EF6
//      fn21DC_0856
//      fn2368_0D20
define fn2BC7_050A
{
	segptr32 ptrArg04;
	Top_3 = 0;
	es_10 = SLICE(ptrArg04, selector, 16);
	bx_11 = (word16) ptrArg04;
	ax_12 = ptrArg04->w000A;
	dx_13 = ptrArg04->w000C;
}

